### ISSUE TITLE
Strange bug with Program-O

### ISSUE THREAD

**Issue by wofty** [Program-O/Program-O#100]
Hi, I find a strange bug. I tested this code with Program-e, Pandorabots and Program-AB and it works, but not with Program-O. I must repeat two time the name. Thank
Example: 
Seeker: HELLO
victor: Hello, but i don't know your name, what is it?
Seeker: MY NAME IS FRANCK
victor: Hello FRANCK. I do not know that name, but it looks nice.
FRANCK: MY NAME IS FRANCK
victor: Hello FRANCK.This is a nice male first name.
FRANCK: MY NAME IS MAEVA
victor: Hello MAEVA.This is a nice male first name.
MAEVA: MY NAME IS MAEVA
victor: Hello MAEVA.It is a lovely feminine first name.

code : 
https://www.dropbox.com/s/uwfcokbrx661vbg/hello.aiml?dl=0

**Comment by Program-O** [comment]
Hi there
There was two issues...
the first was in conversation_start.php
the $convoArr was initialising each  time regardless of whether it had been previous set or not
this has been revert back to:

```
  $convoArr = array();
  //$convoArr = intialise_convoArray($convoArr);
```
And the parseTemplateRecursive() function needed to pass the $convoArr by reference.

It has been fixed now and released 
:)

**Comment by Dave-Morton** [comment]
I thought we had made the same changes that you just put in ages ago. I wonder when they got broken...
