### ISSUE TITLE
How to use math and php tags

### ISSUE THREAD

**Issue by wofty** [Program-O/Program-O#101]
Hello,
 I would like to use the full potential of Program-O. In the file custom_tags.php I noticed the math and php tags. Do you have examples to use them? Thank you

**Comment by wofty** [comment]
Ok, I find for math. But now I search for php tags.

**Comment by Dave-Morton** [comment]
The PHP tags in Program O serve essentially the same function as the old AIML 1.0 <system> tags did, but with a kick. This allows certain PHP code to be executed as part of the response. For example, let's say that you have a PHP script in your chatbot's root folder named fpp.php, and it contains the function foo(), which looks like this:

```PHP
function foo() {
  $out = date('m/d/Y i:h:sP);
  return "The date and time is now $out";
}
```

... and you have the following AIML category:

```XML
<category>
  <pattern>WHAT TIME IS IT</pattern>
  <template><php>include_once 'foo.php'; foo();</php></template>
</category>
```
(now bear in mind that this is **NOT** a "real world" example, and that this is just here to serve as a **NON_WORKING** example. It's up to you to write both proper **PHP ~AND~ AIML** that will work together to generate the output that you desire)

when the user asks what time it is, your bot can give a response based on the PHP code within the function foo(). Be warned, however, that using evaluated PHP code can be **DANGEROUS**, and should be used only sparingly, and with great care.
