### ISSUE TITLE
the bot does not follow a topic when I teach, how I correct this problem 

### ISSUE THREAD

**Issue by Amjed1991** [Program-O/Program-O#102]
the bot does not follow a topic when I teach, how I correct this problem

**Comment by Dave-Morton** [comment]
This is often (but not always) a problem with how the AIML is written. If you can provide us a sample of the AIML categories that are displaying the unwanted behavior, we can take a look at it and see if that's the cause.

**Comment by Amjed1991** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="1.0.1" encoding="UTF-8"?>
   <category>
      <pattern>LET DISCUSS music</pattern>
      <template>Yes <set name="topic">movies</set></template>  
   </category>
   <topic name="movies">
      <category>
         <pattern> * </pattern>
         <template>Watching good movies refreshes our minds.</template>
      </category>
      <category>
         <pattern> I LIKE WATCHING COMEDY! </pattern>
         <template>I like comedy movies too.</template>
      </category>
   </topic>
</aiml>

**Comment by Amjed1991** [comment]
``<?xml version="1.0" encoding="UTF-8"?>
<aiml version="1.0.1" encoding="UTF-8"?>
   <category>
      <pattern>LET DISCUSS music</pattern>
      <template>Yes <set name="topic">movies</set></template>  
   </category>
   <topic name="movies">
      <category>
         <pattern> * </pattern>
         <template>Watching good movies refreshes our minds.</template>
      </category>
      <category>
         <pattern> I LIKE WATCHING COMEDY! </pattern>
         <template>I like comedy movies too.</template>
      </category>
   </topic>
</aiml>

**Comment by Amjed1991** [comment]
2016-03-24 1:37 GMT+01:00 Dave Morton <notifications@github.com>:

**Comment by Amjed1991** [comment]
[test.txt](https://github.com/Program-O/Program-O/files/187567/test.txt)

**Comment by Amjed1991** [comment]
[test.txt](https://github.com/Program-O/Program-O/files/187579/test.txt)

**Comment by Dave-Morton** [comment]
Ok, part of your problem lies in the fact that the pattern within your movie topic is surrounded by spaces. With Program O, EVERYTHING within the pattern is considered, even spaces, so this will cause unexpected results. Instead of this:

    <pattern> * </pattern>

You should try this:

    <pattern>*</pattern>

and see if that fixes the problem. Also, the AIML tag at the beginning, while not contributing to your problem, isn't helping, either. Here's your AIML using "well formed", valid AIML code:

```XML
<?xml version="1.0" encoding="UTF-8"?>
  <aiml version="1.0">
   <category>
      <pattern>LET S DISCUSS music</pattern>
      <template>Yes <set name="topic">movies</set></template>
   </category>
   <topic name="movies">
      <category>
         <pattern>*</pattern>
         <template>Watching good movies refreshes our minds.</template>
      </category>
      <category>
         <pattern>I LIKE WATCHING COMEDY!</pattern>
         <template>I like comedy movies too.</template>
      </category>
   </topic>
</aiml>
```

Please note that I've changed the opening pattern from **LET DISCUSS**  to **LET S DISCUSS**, as this covers "let's discuss", which is how most people say it. You may also want to add a category for **LET US DISCUSS" that SRAI's to that same category, as well as a few others to catch other variations of what folks might say.

**Comment by Amjed1991** [comment]
It makes me the same answer even if I did get a new pattern

**Comment by Amjed1991** [comment]
![dialog](https://cloud.githubusercontent.com/assets/14986763/14018405/e89a56ac-f1cd-11e5-9f6a-1676d41f155c.PNG)

**Comment by Dave-Morton** [comment]
Oops! I missed it the first time. You have an exclamation point in the I LIKE COMEDY pattern. Punctuation is not allowed in the pattern, that or thatpattern elements. Remove that exclamation point and it should correct the issue. Sorry about that. that's what I get for trying to do support before I've had my coffee. :)

**Comment by Dave-Morton** [comment]
Additionally, you have no provision within the MOVIES topic to "break out" of that topic. This is usually taken care of within the topic's "catchall" (the category with just a * for the pattern), or a category that indicates that the user is tired of talking about movies. you can handle breaking out of the topic by doing something like this:

```xml
<topic name="movies">
  <category>
    <pattern>*</pattern>
    <template>
      Watching good movies refreshes our minds.
      <think><set name="topic">*</set></think>
    </template>
  </category>
  <category>
    <pattern>LET S TALK ABOUT SOMETHING ELSE</pattern>
    <template>
      <think><set name="topic>*</set></think>
      Okay, what do you want to talk about?
    </template>
  </category>
</topic>
```
Either one of these categories will remove the current topic, replacing it with the default value (*). If you do not do this, you'll never leave the topic of movies. Just to be clear here, you can do one, or the other, or both. You don't NEED both of them.

**Comment by Amjed1991** [comment]
Ok , thank you

**Comment by Dave-Morton** [comment]
Please let us know if that fixed the issue, at your convenience. :)

**Comment by Amjed1991** [comment]
With the AIML file works well, but thank you for the admin section, the foncionalite teach << >> I know how it works, I'm not convinced of result , how i can test it by teach

**Comment by Amjed1991** [comment]
![teach](https://cloud.githubusercontent.com/assets/14986763/14022027/36125ec4-f1de-11e5-9d41-6b3700bc1130.PNG)

**Comment by Dave-Morton** [comment]
That's just a method for adding AIML to the chatbot without having to create an AIML file and uploading it. the topic and previous bot response fields are optional. If you click on that blue cube at the top of the page (the one labeled "help") it will give you more detailed instructions on how to use this feature.
