### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by BeZazz** [Program-O/Program-O#103]
Hi,
I was wondering if there was any documentation to read?
(I tried reading over the forum but it is down)

Thanks

EDIT: Forum back up :)

**Comment by Dave-Morton** [comment]
Liz is working on a wiki for Program O, which will include the documentation. Not sure how far along she is with it, though.

**Comment by Program-O** [comment]
There was a certain amount of documentation on the blog
i took it down as i didnt know how useful it was

what sort of things do you feel would help you?
As i am in the process of writing more relevant and useful documentation on the github wiki

**Comment by BeZazz** [comment]
4am here so maybe I will have a better answer later but I was after anything.

Normally when I start messing around with something like this, I read as much as I can.
Saves asking silly questions and wasting peoples time.

**Comment by Program-O** [comment]
i can try to pull out an old copy of the documentation but it was really like a list of functions and what they expect as parameters and their purpose.
I am not sure how useful it was
i will see if i can find it

**Comment by BeZazz** [comment]
That would be good and appreciated :)

**Comment by Program-O** [comment]
I have run PHPdocumentor across the code and created a first version of the documentation for the latest release here : [http://documentation.program-o.com/latest/](http://documentation.program-o.com/latest/)

I will go though and update the phpdoc blocks as and when i get time and hopefully anyone else reading this and feels compelled will contribute to that massive task and make my life slightly easier :D
