### ISSUE TITLE
Program-O chatbot not working

### ISSUE THREAD

**Issue by dp33** [Program-O/Program-O#104]
Not sure what happened, but it's not working anymore. The bot returns "error" to every input. Also looks like Progam-O isn't working on website, either.

**Comment by Dave-Morton** [comment]
Have you checked the error logs, to see if there might be a problem? Also, if debugging is turned on, take a look at the debug files frm the most recent conversation. There may be a clue or several that could point you in the correct direction. If you don't know how to access either the logs or the debug files, let me know, and I'll walk you through it.

**Comment by AidanLumina** [comment]
I can confirm this issue. It could be that the deprecation of the original MySQL extension in PHP is causing this issue. If you have recently updated the PHP version of the server, then it's clear. See http://php.net/manual/de/migration55.deprecated.php for details.
Porting the Program O to PDO_MySQL would be the best way to solve this issue, and it would effectively protect Program O from SQL injections, too.

**Comment by Dave-Morton** [comment]
Program O has used PDO for several years now, ever since version 2.3, at least, and possibly 2.1, so I highly doubt that this is the issue, unless an older version of Program O is being used. So my first question is which version of Program O are you using?

**Comment by dp33** [comment]
I was using the Wordpress plugin version for a blog post, and it stopped working sometime yesterday afternoon. At that point I went to www.program-0.com <http://www.program-0.com/> and noticed that it wasn’t working there either — every response was "Request failed: parser error"

**Comment by Program-O** [comment]
i have checked the api and it's up so i am not sure why you have the error.
i am guessing it was maybe a period of high useage which prevented the mysql from connecting
i will look into this further can u confirm your plugin is working now?

**Comment by dp33** [comment]
Yes, it’s working again now! Thanks so much!

**Comment by Program-O** [comment]
i will look into the server loads and see what i can do to stop it in the future
thanks
:)
