### ISSUE TITLE
Change the text located at footer

### ISSUE THREAD

**Issue by Amjed1991** [Program-O/Program-O#106]
I changed the text located at footer .It was modified in the "admin / index.php? Page = login", but remains unchangeable in "admin / index.php", after the administration login page

**Comment by Dave-Morton** [comment]
The Program O admin pages use an HTML templating system for it's output. All of the HTML code within those admin pages are contained in the template file default.page.html - Any changes that you want to make to the admin pages should be made within that file. What, specifically, did you want to change?

**Comment by Amjed1991** [comment]
I change the information in footer "© 2016-O My Program
You are logged in as: Admin from :: 1 since: Wednesday 30th of March 2016 5:26:12 PM
You last logged in from :: 1 on Wednesday 30th of March 2016 12:42:18 PM ", and I have not understood or he takes the information from loggin" You are logged in as: Admin from :: 1 since : Wednesday 30th of March 2016 5:26:12 PM
You last logged in from :: 1 on Wednesday 30th of March 2016 12:42:18 PM "
I change the page index.php, admin level "$ Footer Info = '<p> & copy; 2016 My bot <br /> </ p>', but the change was at page" admin / index .php? page = login "c all .when I authenticates I find © 2016-O My Program
You are logged in as: Admin from :: 1 since: Wednesday 30th of March 2016 5:26:12 PM
You last logged in from :: 1 on Wednesday 30th of March 2016 12:42:18 PM "

**Comment by Dave-Morton** [comment]
That's handled within the script itself, and is generated dynamically, each time you access the page. To change is will require changing the code that generates it. Tell me please, why do you want to change it? the only people that should be able to see the admin pages are people with admin level access (e.g. you). Just curious.

**Comment by Dave-Morton** [comment]
By the way, the footer is generated in the file misc_functions.php, in the function getFooter()

**Comment by Amjed1991** [comment]
I will not change but I just want to see how because I tried and I could not, and as you said the last pratie admin to limit the access for the admin, you are right.
thanks for the advice

**Comment by Dave-Morton** [comment]
No problem.
