### ISSUE TITLE
Empty responses

### ISSUE THREAD

**Issue by egrish** [Program-O/Program-O#109]
After installation I try to teach it saying "Hello" to "Hi". I have an empty response.

"Found an error trying to identify the chatbot. "

e

Seeker: HI
TP Client:
06-04-2016 12:26:26.32028[0][3] - Elapsed time: 0.058 milliseconds
[conversation_start.php][Called outside of function][25]
Conversation Starting. Program O version 2.4.8
PHP  version 5.5.9-1ubuntu4.14
OS: Linux version #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:15 UTC 2016 
-----------------------
06-04-2016 12:26:26.32503[0][3] - Elapsed time: 4.744 milliseconds
[conversation_start.php][Called outside of function][84]
Debug level: 3
session ID = t3u9vtqonblc6j5ssvjn3kms23 
-----------------------
06-04-2016 12:26:26.3251[2][3] - Elapsed time: 0.076 milliseconds
[spell_checker.php][run_spell_checker_say][36]
Starting function and setting timestamp. 
-----------------------
06-04-2016 12:26:26.32514[2][3] - Elapsed time: 0.037 milliseconds
[spell_checker.php][spell_check][57]
Preforming a spel chek on hi. 
-----------------------
06-04-2016 12:26:26.32523[2][3] - Elapsed time: 0.096 milliseconds
[spell_checker.php][load_spelling_list][120]
Loading the spellcheck list from the DB. 
-----------------------
06-04-2016 12:26:26.32739[2][3] - Elapsed time: 2.152 milliseconds
[conversation_start.php][Called outside of function][146]
Details:
User say: HI
Convo id: t3u9vtqonblc6j5ssvjn3kms23
Bot id: 1
Format: html 
-----------------------
06-04-2016 12:26:26.32745[3][3] - Elapsed time: 0.060 milliseconds
[intialise_conversation.php][load_default_bot_values][109]
load db bot personality values SQL: SELECT * FROM `programo`.`botpersonality` WHERE `bot_id` = '1' 
-----------------------
06-04-2016 12:26:26.32862[2][3] - Elapsed time: 1.173 milliseconds
[intialise_conversation.php][check_set_bot][473]
Checking and/or setting the current bot. 
-----------------------
06-04-2016 12:26:26.32868[3][3] - Elapsed time: 0.059 milliseconds
[intialise_conversation.php][check_set_bot][491]
Making sure the bot exists. SQL = SELECT * FROM `programo`.`bots` WHERE bot_id = '1' and `bot_active`='1' 
-----------------------
06-04-2016 12:26:26.3302[2][3] - Elapsed time: 1.519 milliseconds
[intialise_conversation.php][check_set_bot][502]
BOT ID: 1 
-----------------------
06-04-2016 12:26:26.33026[2][3] - Elapsed time: 0.059 milliseconds
[intialise_conversation.php][check_set_user][556]
Checking and setting the user info, as needed. 
-----------------------
06-04-2016 12:26:26.33154[2][3] - Elapsed time: 1.282 milliseconds
[handle_user.php][intisaliseUser][77]
Initializing user. 
-----------------------
06-04-2016 12:26:26.33261[3][3] - Elapsed time: 1.076 milliseconds
[handle_user.php][intisaliseUser][106]
intisaliseUser #8 SQL: INSERT INTO `programo`.`users` (`id`, `user_name`, `session_id`, `bot_id`, `chatlines` ,`ip` ,`referer` ,`browser` ,`date_logged_on` ,`last_update`, `state`)
  VALUES ( NULL , 'Seeker', 't3u9vtqonblc6j5ssvjn3kms23', 1, '0', '195.210.6.5', 'http://devtoolstest.westeurope.cloudapp.azure.com/program-o/gui/plain/?bot_id=1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP, '') 
-----------------------
06-04-2016 12:26:26.33325[2][3] - Elapsed time: 0.631 milliseconds
[intialise_conversation.php][load_that][632]
Loading the THAT array. 
-----------------------
06-04-2016 12:26:26.33328[3][3] - Elapsed time: 0.035 milliseconds
[intialise_conversation.php][load_that][639]
Getting conversation log entries for the current user. SQL:
select `input`, `response` from `programo`.`conversation_log` where `user_id` = 8 and `bot_id` = 1 order by `id` desc limit 10; 
-----------------------
06-04-2016 12:26:26.33524[2][3] - Elapsed time: 1.964 milliseconds
[intialise_conversation.php][load_bot_config][315]
Loading config data for the current bot. 
-----------------------
06-04-2016 12:26:26.33528[3][3] - Elapsed time: 0.036 milliseconds
[intialise_conversation.php][load_bot_config][319]
load bot config SQL: SELECT * FROM `programo`.`bots` WHERE bot_id = '1' 
-----------------------
06-04-2016 12:26:26.33614[0][4] - Elapsed time: 0.857 milliseconds
[conversation_start.php][Called outside of function][167]
Debug level = 3 
-----------------------
06-04-2016 12:26:26.33617[0][4] - Elapsed time: 0.032 milliseconds
[conversation_start.php][Called outside of function][169]
Debug level = 4 
-----------------------
06-04-2016 12:26:26.33619[4][4] - Elapsed time: 0.016 milliseconds
[intialise_conversation.php][add_new_conversation_vars][165]
New conversation vars 
-----------------------
06-04-2016 12:26:26.3362[2][4] - Elapsed time: 0.018 milliseconds
[intialise_conversation.php][push_on_front_convoArr][204]
Pushing 'HI' to the front of the [user_say] array 
-----------------------
06-04-2016 12:26:26.33623[4][4] - Elapsed time: 0.027 milliseconds
[intialise_conversation.php][load_blank_array_element][59]
Loading blank user_say array 
-----------------------
06-04-2016 12:26:26.33627[2][4] - Elapsed time: 0.039 milliseconds
[intialise_conversation.php][push_on_front_convoArr][204]
Pushing 'HI' to the front of the [input] array 
-----------------------
06-04-2016 12:26:26.33629[4][4] - Elapsed time: 0.019 milliseconds
[intialise_conversation.php][load_blank_array_element][59]
Loading blank input array 
-----------------------
06-04-2016 12:26:26.33631[4][4] - Elapsed time: 0.026 milliseconds
[make_conversation.php][make_conversation][22]
Making conversation 
-----------------------
06-04-2016 12:26:26.33633[4][4] - Elapsed time: 0.014 milliseconds
[misc_functions.php][normalize_text][56]
Begin normalization - text = 'HI' 
-----------------------
06-04-2016 12:26:26.33636[4][4] - Elapsed time: 0.031 milliseconds
[misc_functions.php][normalize_text][71]
Normalization complete. Text = 'HI' 
-----------------------
06-04-2016 12:26:26.33638[4][4] - Elapsed time: 0.017 milliseconds
[find_aiml.php][get_aiml_to_parse][809]
Running all functions to get the correct aiml from the DB 
-----------------------
06-04-2016 12:26:26.3388[4][4] - Elapsed time: 2.422 milliseconds
[find_aiml.php][find_userdefined_aiml][768]
Looking for user defined responses 
-----------------------
06-04-2016 12:26:26.33884[3][4] - Elapsed time: 0.037 milliseconds
[find_aiml.php][find_userdefined_aiml][780]
User defined SQL: SELECT * FROM `programo`.`aiml_userdefined` WHERE
    `bot_id` = '1' AND
    (`user_id` = '8' OR `user_id` = '-1') AND
    `pattern` = 'HI' 
-----------------------
06-04-2016 12:26:26.33951[2][4] - Elapsed time: 0.672 milliseconds
[find_aiml.php][find_userdefined_aiml][796]
User defined rows found: '0' 
-----------------------
06-04-2016 12:26:26.33955[4][4] - Elapsed time: 0.038 milliseconds
[find_aiml.php][find_aiml_matches][883]
Finding the aiml matches from the DB 
-----------------------
06-04-2016 12:26:26.33957[4][4] - Elapsed time: 0.028 milliseconds
[find_aiml.php][get_last_word][22]
Sentence: HI. Last word:HI 
-----------------------
06-04-2016 12:26:26.33959[4][4] - Elapsed time: 0.018 milliseconds
[find_aiml.php][get_first_word][35]
Sentence: HI. First word:HI 
-----------------------
06-04-2016 12:26:26.34033[4][4] - Elapsed time: 0.739 milliseconds
[find_aiml.php][find_aiml_matches][897]
Stored topic = '' 
-----------------------
06-04-2016 12:26:26.34037[4][4] - Elapsed time: 0.040 milliseconds
[find_aiml.php][wordsCount_inSentence][120]
Sentence: HI numWords:1 
-----------------------
06-04-2016 12:26:26.34039[3][4] - Elapsed time: 0.023 milliseconds
[find_aiml.php][find_aiml_matches][954]
Match AIML sql: SELECT `id`, `pattern`, `thatpattern`, `topic` FROM `programo`.`aiml` WHERE
   bot_id = '1'  AND (
  `pattern` = '_' OR
  `pattern` = '*' OR
  `pattern` = 'HI' OR
  `pattern` = 'RANDOM PICKUP LINE'
  )  order by `topic` desc, `id` asc, `pattern` asc; 
-----------------------
06-04-2016 12:26:26.34101[2][4] - Elapsed time: 0.618 milliseconds
[find_aiml.php][find_aiml_matches][960]
FOUND: (1) potential AIML matches 
-----------------------
06-04-2016 12:26:26.342[4][4] - Elapsed time: 0.990 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][148]
NEW FUNC Searching through 1 rows to unset bad matches 
-----------------------
06-04-2016 12:26:26.34204[4][4] - Elapsed time: 0.035 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][157]
Blue 5 to Blue leader. Starting my run now! 
-----------------------
06-04-2016 12:26:26.34212[1][4] - Elapsed time: 0.083 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][250]
Error: FOUND NO AIML matches in DB 
-----------------------
06-04-2016 12:26:26.34215[4][4] - Elapsed time: 0.032 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][259]
Found 1 relevant rows 
-----------------------
06-04-2016 12:26:26.34217[4][4] - Elapsed time: 0.018 milliseconds
[find_aiml.php][score_matches][296]
Scoring the matches. 
-----------------------
06-04-2016 12:26:26.34309[1][4] - Elapsed time: 0.924 milliseconds
[find_aiml.php][score_matches][365]
Found an error trying to identify the chatbot. 
-----------------------
06-04-2016 12:26:26.34315[4][4] - Elapsed time: 0.056 milliseconds
[find_aiml.php][score_matches][539]
Sorted array $allrows:
Array
(
)
 
-----------------------
06-04-2016 12:26:26.34318[4][4] - Elapsed time: 0.028 milliseconds
[find_aiml.php][get_highest_scoring_row][632]
Best Responses: Array
(
)
 
-----------------------
06-04-2016 12:26:26.34319[2][4] - Elapsed time: 0.015 milliseconds
[find_aiml.php][get_highest_scoring_row][633]
Will use randomly picked best response chosen out of 0 responses with same score:  -  
-----------------------
06-04-2016 12:26:26.34321[4][4] - Elapsed time: 0.019 milliseconds
[find_aiml.php][get_aiml_to_parse][842]
Will be parsing id: () 
-----------------------
06-04-2016 12:26:26.34323[3][4] - Elapsed time: 0.016 milliseconds
[parse_aiml.php][parse_matched_aiml][190]
Run the aiml parse in normal mode (normal or srai) 
-----------------------
06-04-2016 12:26:26.34324[2][4] - Elapsed time: 0.013 milliseconds
[parse_aiml.php][set_wildcards][250]
Setting Wildcards 
-----------------------
06-04-2016 12:26:26.34327[2][4] - Elapsed time: 0.033 milliseconds
[parse_aiml_as_XML.php][parse_aiml_as_XML][22]
Parsing the AIML template as XML 
-----------------------
06-04-2016 12:26:26.34329[2][4] - Elapsed time: 0.017 milliseconds
[parse_aiml_as_XML.php][add_text_tags][53]
Adding some TEXT tags into the template, just because I can... 
-----------------------
06-04-2016 12:26:26.34333[4][4] - Elapsed time: 0.039 milliseconds
[parse_aiml_as_XML.php][add_text_tags][79]
Returning template:
 
-----------------------
06-04-2016 12:26:26.34339[2][4] - Elapsed time: 0.062 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][142]
Recursively parsing the AIML template. 
-----------------------
06-04-2016 12:26:26.34344[4][4] - Elapsed time: 0.047 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][149]
Processing element template at level 0. element XML =

**Comment by BeZazz** [comment]
Provided you set everything up in the admin panel, I would suggest checking over the config file and making sure that was correct.

**Comment by Dave-Morton** [comment]
Based on what I'm reading here, I think that you might be experiencing two separate problems here. The first is fairly straight-forward, and is indicated in the first line of the debug file you've posted:

>Found an error trying to identify the chatbot.

This usually only occurs when the chatbot isn't fully set up after installation. Tell me, please, did you just install, then try to chat with your bot right away? Or did you go into the admin page (as suggested by the last page of the install process) and complete the setup?

The install process only creates the config file and sets up the database with just the basic data necessary to allow the chatbot to work *after it's configured in the admin section*. Also, Program O does not include *any* AIML response categories, which are necessary for the chatbot to respond. these must be added in the admin pages before the chatbot will "work". If you've already completed these necessary steps, then I suggest that you look within the error logs and post what you find here.

**Comment by Program-O** [comment]
I was about to say the same thing
make sure you follow the instructions here:
https://github.com/Program-O/Program-O/wiki/Installation-Guide

**Comment by Program-O** [comment]
closing as no response for 30 days
