### ISSUE TITLE
git pull overwrites global_config.php

### ISSUE THREAD

**Issue by BeZazz** [Program-O/Program-O#112]
Just noticed that git pull overwrites global_config.php.

Maybe the connection settings should be in a file that does not get overwritten.

**Comment by Program-O** [comment]
oh crap it should have been gitignored
and that would prob explain your last issue

**Comment by Program-O** [comment]
except there is no global_config.php in the repo..
i just looked... 
hmmmmmmm
i also updated all the live servers to the new version and this didnt happen to me

**Comment by BeZazz** [comment]
Mmmm I'm getting confused lol

The global_config.php in config remains unchanged but
a new global_config.php was placed in the / of Program-O

**Comment by Program-O** [comment]
blinkin heck that was my fault when i was testing something .. i have removed that now
try another pull and see if anything changes

**Comment by BeZazz** [comment]
That is fixed :) but I still can no longer get my bot working via the web page (where you chat) the only bot to select is Unknown.

In admin it only answers with 
Yes or No
as a reply

**Comment by Program-O** [comment]
the changes were not that drastic to break the bot in that way... can you log in to the admin area and see the bot in the admin area.
also i had to do another push to remove that dam config file 
sorry :)

**Comment by BeZazz** [comment]
In admin everything looks fine.
No probs :)

I will have look into my side of things more.
Here is an eg, of a chat

Conversation#1 2016-04-09

Seeker: HI
Sbot: Yes or No?
Seeker: I DO NOT UNDERSTAND
Sbot: Yes or No?
Seeker: YES
Sbot: Yes or No?
Seeker: YES
Sbot: Yes or No?
Seeker: TELL ME A JOKE
Sbot: Yes or No?
