### ISSUE TITLE
Change header for admin

### ISSUE THREAD

**Issue by Amjed1991** [Program-O/Program-O#115]
![header](https://cloud.githubusercontent.com/assets/14986763/14548476/05949136-02af-11e6-8702-8625f7d8635e.PNG)
I'll change the header, but the image does not remove, I did not find its source

**Comment by Dave-Morton** [comment]
It's in the CSS for the page. I don't remember the element that "contains" it, but you'll find it in the stylesheet.

**Comment by Amjed1991** [comment]
But i remove the image for the folder images/images/repeated_header2.jpg , and i run , but exist also . i dont faind in the Css

**Comment by Program-O** [comment]
closing no response in 30 days
