### ISSUE TITLE
how to turn the topic tag

### ISSUE THREAD

**Issue by NASRAOUI** [Program-O/Program-O#117]
how to enable tag topic at IALM browse the file or entered automatically with the admin interface, because it is not functional

**Comment by Dave-Morton** [comment]
I'm not certain what you mean. Can you describe the problem in greater detail?

**Comment by NASRAOUI** [comment]
what is the use of topic and That a teacher interface, or the deus text boxes is not functional, there is a correction that defects?

**Comment by Dave-Morton** [comment]
I've just tested the eeaching interface, and I see no problems at all with it. I'll outline what I did to test it in a moment, but first, I need some information about your program O installation. Please proved te us the following:

1.) Program O version (it's in the upper-left corner of the admin pages)
2.) the server's operating system (linux, windows, etc.) and version
3.) the server's PHP version and database type (MySQL, PostGreSQL, etc.) and version.
4.) which browser(s) that you're using to access the chatbot.

Ok, here's how to test to see for sure if the teaching interface is working:

1.) Log into the admin page and go to Search/Edit AIML
2.) in the search box for TOPIC, type in something that you do not expect to find (I used TEST) and verify that the search returned no results. If it does, put in another search term until you find something that doesn't return any AIML categories. Remember what you put in there. You'll need it in the next steep.
3.) Go to the Teach interface, and enter in the word you couldn't find any results for into the Topic field of the interface.
4.) in the User Input field, type in the word "TEST". (no quotes)
5.) in the Bot Response field, put in "Test passed!" (don't put in the quotation marks)
6.) Hit the Teach button.
7.) Once again, in the Topic field, put in the word that you used for the topic.
8.) in the User Input field, just put in the * wildcard
9.) In the Bot response field, put in the following AIML code:

````xml
<think>
  <set name="lasttopic"><get name="topic></set>
  <set name="topic"></set>
</think>
Topic <get name="lasttopic" /> removed.
````
10.) Once again, hit the Teach button.
11.) This time, leave the Topic field blank.
12.) In the User Input field, put in the word "TEST" again. (still, no quotes)
13. In the Bot Response field, put in "Test FAILED!"
14.) Hit the Teach button.
{pause for short breath}
15.) Ok, now we're done teaching the bot. Go to the Search/Edit AIML page again, and in the Topic search box, type in the word that you used for the topic, before. You should see 2 new entries for that topic. If not, stop testing and report back here.
16.) If you see the two AIML categories, then it's time to test them. Fir that, go to the Test Your Bot page and enter the word "TEST" (no quotes). Note the response that you get (it should be "Test FAILED!", unless you already had an AIML category for the input TEST).
17.) Next, type in "Let's talk about " followed by the word you set for your topic, earlier (I shouldn't have to remind you not to use the quotes here, but I will anyway) and hit the Enter key. Again, note the response. I'll want to see it here in your next reply.
18.) Again, enter the word "TEST" and note the response.
19.) Put in anything you wish this time, and note the response.

If you followed these steps exactly, you should get a conversation that looks something like this:


>Human: LET US TALK ABOUT TEST
>Chatbot: Sure, TEST sounds like a good topic.
>Human: WHAT IS THE TOPIC
>Chatbot: The topic is TEST.
>Human: GO AWAY
>Chatbot: topic TEST removed.

If it does not, then we need to do some investigating.

**Comment by Program-O** [comment]
closing no response in 30 days

**Comment by NASRAOUI** [comment]
how the agent will extract led for data from a file and AIML What is the decision making for the reprondre intrnaute, what is the php class responsible for extracting data, is that there is an algorithm already responsible exsit

**Comment by Dave-Morton** [comment]
I got both of your emails (in French) that asked the same question. I just had not yet had the time to respond. 

There are several files involved in the process of first finding, then parsing the AIML that's stored in the database, so this isn't a "quick and easy" question to answer. The only time an actual AIML file is used is when you upload it to Program O via the Upload panel. Once the file is uploaded, it's stored in the database, where the script searches for the best potential matches to the input given by the user. The results of the database search are then sorted and scored, and the AIML category that ends up with the highest score is selected and parsed, which results in the response that's displayed to the user. There are a **lot** of algorithms involved in this process, and (of course) they all "exist". This section of the script doesn't yet use PHP classes, but future versions will, at some point. Object Oriented code is much easier to read and follow, but it takes time to convert procedural code into classes and objects, so if you're waiting for that to happen you;ll need a bit of patience.

**Comment by NASRAOUI** [comment]
or manifests intelligence to choose the answer to the question from database, how to choose a sql query or by another method! ??

**Comment by Dave-Morton** [comment]
I'm not sure of what you are asking this time. Can you explain further?

**Comment by NASRAOUI** [comment]
how to choose the answer of a question already asked if we avans a database filled with AIML files, the question is how to choose the answer dee issue raised is that there is an intelligence choice of the answer, reallement how come, I just want to have the intellligence reprondre of the question.

**Comment by Dave-Morton** [comment]
I've been dealing with this issue via email (in French), and since it does not actually involve a bug or other problem, I'm closing the issue.
