### ISSUE TITLE
Every even numbered answer blank

### ISSUE THREAD

**Issue by 3Wision** [Program-O/Program-O#118]
Seeker: 1
robochat: 2
Seeker: 2
robochat:
Seeker: 1
robochat: 2
Seeker: 2
robochat:
Seeker: 2
robochat: 3
Seeker: 1
robochat:
Seeker: 2
robochat: 3
Seeker: 1
robochat:
Seeker: 1
robochat: 2
Seeker: 2
robochat:
Seeker: 2
robochat: 3

**Comment by 3wision** [comment]
<category>
    <pattern>2</pattern>
    <that></that>
    <template>3</template>
  </category>
  <category>
    <pattern>1</pattern>
    <that></that>
    <template>2</template>
  </category>

**Comment by Dave-Morton** [comment]
Have you looked at the debug files and error logs to see if there is any indication as to what's going on? That's generally the first step toward fixing issues with Program O. Also, can you provide the AIML categories that are generating the responses?

**Comment by 3Wision** [comment]
Seeker: 1
3wision:
Seeker: 1
3wision: 1
Seeker: 1
3wision:
Seeker: 1
3wision: 1
Seeker: 1
3wision:
Seeker: 1
3wision: 1
Seeker: 2
3wision:
Seeker: 2
3wision: 22222222
Seeker: 2
3wision:
Seeker: 2
3wision: 22222222
Seeker: 3
3wision:
Seeker: 3
3wision: 3 3
Seeker: 3
3wision: 3 3
Seeker: 3
3wision: 3 3
Seeker: 3
3wision: 3 3
Seeker: 1
3wision: 1
Seeker: 2
3wision:
Seeker: 3
3wision: 3 3
Seeker: 4
3wision: 4.
Seeker: 4
3wision:
Seeker: 4
3wision: 4.
Seeker: 4
3wision:
Seeker: 4
3wision: 4.
Seeker: 5
3wision:
Seeker: 5
3wision: Five
Seeker: 5
3wision:
Seeker: 5
3wision: Five
Seeker: 5
3wision:
Seeker: 5
3wision: Five
Seeker: 6
3wision:
Seeker: 6
3wision: 6 |
Seeker: 6
3wision:
Seeker: 6
3wision: 6 |
Seeker: 6
3wision:
Seeker: 6
3wision: 6 |
Seeker: 7
3wision:
Seeker: 7
3wision: 7.
Seeker: 7
3wision:
Seeker: 7
3wision: 7.
Seeker: 7
3wision:
Seeker: 3
3wision: 3 3
Seeker: 3
3wision: 3 3
Seeker: 3
3wision: 3 3
Seeker: 1
3wision: 1
Seeker: 1
3wision:
Seeker: 2
3wision: 22222222
Seeker: 2
3wision:
Seeker: 3
3wision: 3 3
Seeker: 3
3wision: 3 3
Seeker: 3
3wision: 3 3
Seeker: 4
3wision: 4.
Seeker: 4
3wision:
Seeker: 5
3wision: Five
Seeker: 5
3wision:
Seeker: 6
3wision: 6 |
Seeker: 6
3wision:
Seeker: 7
3wision: 7.
Seeker: 7
3wision:
Seeker: 8
3wision: it is eight
Seeker: 8
3wision: it is eight
Seeker: 8
3wision: it is eight
Seeker: 8
3wision: it is eight
[3wision.AIML.zip](https://github.com/Program-O/Program-O/files/225112/3wision.AIML.zip)

**Comment by Dave-Morton** [comment]
Ok, I see the problem, but not yet the cause. I'll dig further, and let you know what I find.

**Comment by Dave-Morton** [comment]
It looks like there's a problem with the SQL query that's being generated. I'll put this on the priority list, but I don't have time right this second to dig into it.

**Comment by Dave-Morton** [comment]
Ok, I found out that single word user inputs (e.g. typing "1") weren't being properly handled when generating the SQL that searched for matching responses. I've corrected that, so it should work for you, once you update.

**Comment by 3Wision** [comment]
Hello Dave! Thank you for your participation. Please tell me what I need to do. Sorry for my English, it not native for me.

**Comment by Dave-Morton** [comment]
Just download the latest version of Program O and upload it to your server. You don't have to reinstall it. Once you have uploaded the new version, try your chatbot again, and let us know if the problem still exists.

**Comment by jonnyboy** [comment]
Did you forget to push the change?

**Comment by Dave-Morton** [comment]
Nope! Look up a few posts and you'll see that I added a [commit](https://github.com/Program-O/Program-O/commit/fa7ad47dfb03b950d6859db0b643f1195cc832b7) about 10 hours previous to this post.

**Comment by jonnyboy** [comment]
My mistake. I pulled, showed no changes. I must have been in master. Thanks

**Comment by Dave-Morton** [comment]
No worries. Happens all the time. :) Let me know if you have any more issues.

**Comment by 3Wision** [comment]
I applied the update kindly provided by you and it worked correctly. Thank you for your prompt support. With best regards, Dmitry.

**Comment by Dave-Morton** [comment]
Thanks for letting us know, Dmitri.

**Comment by 3Wision** [comment]
After the update the bot only responds to one-word requests. What's wrong?

Seeker: 1
3wision: 1
Seeker: 1
3wision: 1
Seeker: 1 1
3wision:
Seeker: 1 1
3wision:
Seeker: 1 1 1
3wision:
Seeker: 1 1 1
3wision:
Seeker: 1
3wision: 1
[3wision_1.AIML.zip](https://github.com/Program-O/Program-O/files/227814/3wision_1.AIML.zip)

**Comment by Dave-Morton** [comment]
You broke it! lol.

Seriously, that's a bit odd. It seems to work fine for me. Let me delve into this a bit further.

**Comment by Dave-Morton** [comment]
Tell me something. Is that AIML file the only one loaded for your chatbot?

**Comment by Dave-Morton** [comment]
Ok, found not one, but two bugs that affect this. Just pushed the bug fixes to the DEV branch.

**Comment by 3Wision** [comment]
I really broke it! lol. The human factor has not been canceled. ) I applied first At least a partial fix for issue #118 and panicked. Further fixes for issue #118 has solved all the problems. Patience is the mother of learning - Russian proverb.

**Comment by Dave-Morton** [comment]
Great! Don't be afraid to reopen this issue if the problem returns.
