### ISSUE TITLE
The usefulness of adding more than a bot 

### ISSUE THREAD

**Issue by Amjed1991** [Program-O/Program-O#119]
The usefulness of adding more than a bot

**Comment by Dave-Morton** [comment]
You can conceivably create multiple chatbots, each with their own personality, for users to enjoy. You could also (with a little bit of creative tweaking) create a web page that can allow two or more chatbots to have a conversation with each other, which can make for some rather humorous dialog. there is quite a lot of "usefulness" to adding more than one bot to Program O.
