### ISSUE TITLE
Troubles with Twitter

### ISSUE THREAD

**Issue by FullCustom** [Program-O/Program-O#121]
I'm having trouble porting my bot to twitter. I know I've made some simple mistake I just don't know what it is.

**Comment by Program-O** [comment]
do you think you can describe the problem in more detail?

**Comment by FullCustom** [comment]
If I understand this correctly there are three things I'm setting up for my bot. The twitter app, the parameters in tweet.php and the cron job. I've done all that and it doesn't work. I don't know how to test what the problem is. Under the twitter app settings it ask for a callback url. That was the one thing that I wasn't real sure about.

**Comment by Program-O** [comment]
You can leave the call back url empty.
and if you run it a few times directly you should be able to tweet your bot and get a response back

**Comment by FullCustom** [comment]
That's how I started with no callback url. I shortened the name from @JavierFullCustomMusic to @JavierFullCustom to see if just having a name that is too long could cause a problem. When I tweet to that name it doesn't highlight it. I also changed the cron job time to 15mins cause that is the lowest my server allows. I should get an email when the cron is called, I haven't seen one yet.

**Comment by Program-O** [comment]
you will get an email for your cron if you set it up like that.

You need to run the script directly and do not wait for cron 
to see if it is set up properly

**Comment by FullCustom** [comment]
Just ran it direct says no new tweets

**Comment by Program-O** [comment]
what is your bots twitter name

**Comment by Program-O** [comment]
cus when i try to tweet you i cant find your name
have you actually created the twitter account for your bot?

**Comment by FullCustom** [comment]
http://javier.fullcustommusic.com/gui/twitter/tweet.php there is the path to my script, bots name is Javier. app is @JavierFullCustom

**Comment by Program-O** [comment]
can you show me your twitter account on twitter
cus i cant find you on twitter using @JavierFullCustom

**Comment by FullCustom** [comment]
Okay, first I feels really dumb. I changed the app name to @8BitSeanConnery my personal twitter. now when I run the script I get - Could not tweet : Missing required parameter: status.

**Comment by Program-O** [comment]
when twitter says 'status' that actually means a tweet.
so basically twitter is responding saying you have no added a message to tweet.
so i suspect your bot is not set up properly to respond.
did you follow the wiki to ensure all your aiml files were loaded?

**Comment by FullCustom** [comment]
It bots directly from the main site. I think I'm stuck with a callback url that is wrong I may have to recreate the app to delete the callback url

**Comment by Program-O** [comment]
This message here.... Could not tweet : Missing required parameter: status.
tells me it is working
your bot could not generate a tweet because it is not set up properly
what is the url of your bot?

**Comment by FullCustom** [comment]
javier.fullcustommusic.com

**Comment by Program-O** [comment]
cool that seems to working well

**Comment by Program-O** [comment]
i still cant find you on twitter though to send you a test tweet

**Comment by FullCustom** [comment]
@8BitSeanConnery is the account its setup with

**Comment by Program-O** [comment]
is the path correct in your file?
e.g. have you replaced this   $path_to_bot = "http://www.yoursite.com/chatbot/conversation_start.php";

**Comment by FullCustom** [comment]
$path_to_bot = "http://www.javier.fullcustommusic.com/chatbot/conversation_start.php"; is the current setup

**Comment by Program-O** [comment]
can you post these lines of code on line 75?

echo "<pre>";
print_r(myMentionsArr);
print_r(myReplies);
echo "</pre>";

**Comment by Program-O** [comment]
`echo "<pre>";
print_r(myMentionsArr);
print_r(myReplies);
echo "</pre>";`

**Comment by Program-O** [comment]
tell me when it is done and i will hit your script

**Comment by FullCustom** [comment]
No new tweets myMentionsArrmyReplies
myMentionsArrmyReplies

**Comment by FullCustom** [comment]
This is new I got a message back from the Cron
subject
Cron <fullcdhk@cp-30> php /home/fullcdhk/javier.fullcustommusic.com/public_html/javier/gui/twitter/tweet.php
message:
Status: 404 Not Found
X-Powered-By: PHP/5.3.29
Content-type: text/html

No input file specified.

**Comment by Program-O** [comment]
well the 404 is annoying but you can fix that

you need to put dollar signs in from of mymentionsarr and my replies.... `echo "<pre>"; print_r($myMentionsArr); print_r($myReplies); echo "</pre>";`

**Comment by Dave-Morton** [comment]
oops? :D

**Comment by FullCustom** [comment]
With the $ added we have this when the script is run

No new tweets myMentionsArrmyReplies
Array
(
)
Array
(
)

**Comment by FullCustom** [comment]
with a new tweet
Could not tweet : Missing required parameter: status. myMentionsArrmyReplies
Array
(
    [0] => Array
        (
            [created] => Tue Apr 19 19:51:28 +0000 2016
            [tweetidstr] => 722512961789493249
            [tweet] => so lonely
            [userid] => 780825018
            [useridstr] => 780825018
            [userscreenname] => 8BitSeanConnery
        )

)
Array
(
    [0] => Array
        (
            [in_reply_to_status_id] => 722512961789493249
        )

)

**Comment by Dave-Morton** [comment]
I see nothing in there about "status", which is likely the problem. It should probably look like this:

```php
Array
(
[0] => Array
(
[created] => Tue Apr 19 19:51:28 +0000 2016
[tweetidstr] => 722512961789493249
[tweet] => so lonely
[userid] => 780825018
[useridstr] => 780825018
[userscreenname] => 8BitSeanConnery
[status] => "this would be the content of the tweet itself"
)

)

**Comment by Program-O** [comment]
this is the function to make the tweet message...

` function makeReplies($myMentionsArr){
      $rArr = array();
      foreach($myMentionsArr as $i=>$mention){
          $rArr[$i]['in_reply_to_status_id']=$mention['tweetidstr'];
          //build the reply to tweet
           $botresponse = getReply($mention['useridstr'],$mention['tweet']);
          if($botresponse!=''){
            $message = safeToTweet("@".$mention['userscreenname']." ".$botresponse);
            $rArr[$i]['message']=$message;
          }
      }
    return $rArr;
    }`

**Comment by FullCustom** [comment]
It looks just like that in my tweet.php

**Comment by Dave-Morton** [comment]
Is it possible that Twitter has made changes yet again to their API?

**Comment by FullCustom** [comment]
Got this back from the Cron
  <br/>Could not tweet : Missing required parameter: status.
myMentionsArrmyReplies

<pre>Array
(
    [0] => Array
        (
            [created] => Tue Apr 19 19:53:52 +0000 2016
            [tweetidstr] => 722513567866609665
            [tweet] => hi
            [userid] => 73351905
            [useridstr] => 73351905
            [userscreenname] => grrl_robot
        )

)
Array
(
    [0] => Array
        (
            [in_reply_to_status_id] => 722513567866609665
        )

)
</pre>

**Comment by Dave-Morton** [comment]
Liz, are we using REST or oAuth for the Twitter interface? I forget.

**Comment by Program-O** [comment]
oauth 
but it should work
program o generates the status
that is why it isnt posting
cus its not generating the tweet

**Comment by Dave-Morton** [comment]
Ok, that gives me enough info to do more research. I'm at school, though, so I can't code anything until late tonight. With that in mind, I'll leave this issue in your more-than-capable hands. :P

**Comment by Program-O** [comment]
:)

**Comment by Program-O** [comment]
just to let you both know,
chatmundo is still working
so it must be something in your set up
did you check your debug files to see what it there

**Comment by Program-O** [comment]
maybe you haven't sent the bot id correctly

**Comment by FullCustom** [comment]
I'm going to recreate the app with new keys and see what happens. I know my cron works and the script will find the tweets. That is farther than I was.

**Comment by Program-O** [comment]
it is not the twitter app that is at fault.
you have no message to tweet
you need to work out why the message is not being created
you can see that twitter works
if if didnt you wouldnt see this
 [in_reply_to_status_id] => 722513567866609665

**Comment by Program-O** [comment]
look in your logs and try to work out why program o isnt making a message

**Comment by FullCustom** [comment]
Fair enough

**Comment by FullCustom** [comment]
The logs show no messages from twitter

**Comment by Program-O** [comment]
does it show you what the response is from the bot
to a tweet?

**Comment by Program-O** [comment]
i mean does it even look like a request is triggered to the bot

**Comment by FullCustom** [comment]
There is nothing from twitter in the logs. The message doesn't seem to be getting to the bot.

**Comment by Program-O** [comment]
hmmm, check your normal logs now your nginx/apache logs to see what they say

**Comment by FullCustom** [comment]
Nothing new in the SQL DB log

**Comment by Program-O** [comment]
i think there will be an error in your apache logs

**Comment by FullCustom** [comment]
I can't find any tweets in the logs. If the bot doesn't get a message of course there would be no reply.

**Comment by Program-O** [comment]
but this.....

> `Array
(
    [0] => Array
        (
            [created] => Tue Apr 19 19:53:52 +0000 2016
            [tweetidstr] => 722513567866609665
            [tweet] => hi
            [userid] => 73351905
            [useridstr] => 73351905
            [userscreenname] => grrl_robot
        )

)
Array
(
    [0] => Array
        (
            [in_reply_to_status_id] => 722513567866609665
        )

)`

means there was a tweet

**Comment by FullCustom** [comment]
It looks to me like the tweet.php finds the tweets. I can call the script manually and the cron will call the script. But the tweets are not read by the bot, so there is no reply to post.

**Comment by Program-O** [comment]
i agree
but the tweet is availlable...
cus you can see it here
[tweet] => hi
so i think you are not passing it correctly , or the script path is wrong or something like that

**Comment by FullCustom** [comment]
it's something real dumb

**Comment by Program-O** [comment]
and hopefully easy to solve

**Comment by FullCustom** [comment]
I check the tweet error log in my host. It said I needed to add more $$ to your code. Now after I called the script with a new tweet
 Could not tweet : Missing required parameter: status. Array ( [0] => Array ( [created] => Tue Apr 19 21:26:29 +0000 2016 [tweetidstr] => 722536873743114240 [tweet] => error log test [userid] => 780825018 [useridstr] => 780825018 [userscreenname] => 8BitSeanConnery ) ) Array ( [0] => Array ( [in_reply_to_status_id] => 722536873743114240 ) )
Array
(
    [0] => Array
        (
            [created] => Tue Apr 19 21:26:29 +0000 2016
            [tweetidstr] => 722536873743114240
            [tweet] => error log test
            [userid] => 780825018
            [useridstr] => 780825018
            [userscreenname] => 8BitSeanConnery
        )

)
Array
(
    [0] => Array
        (
            [in_reply_to_status_id] => 722536873743114240
        )

)

**Comment by Program-O** [comment]
so you can see it can see your tweet
but it still doesnt have a response
is there any thing in your bot logs now?

**Comment by FullCustom** [comment]
not from twitter, just the main page.

**Comment by Program-O** [comment]
so there is still the issue that your tweet
which the script picked up wasnt passed to the bot

**Comment by FullCustom** [comment]
Could twitter be blocking my script because I didn't have a callback url?

**Comment by Program-O** [comment]
the problem is the file is not sending your tweet to your bot
but its not twitter its your script or the way it has been set up
i suspect the path is wrong or your bot id is wrong
if twitter didnt work you wouldnt get a twitter message

**Comment by FullCustom** [comment]
function(){
sigh
}

**Comment by Program-O** [comment]
lol we are going round in circles arent we
honeslty trust me if you want to investigate twitter callbacks go for it
but its the wrong place to look

**Comment by FullCustom** [comment]
I have three bots setup Javier is the main bot. How does the script know to call to Javier and not the other bots. I can see a call to Javier in the cron job and that works. But later in a process when the tweet is handed over I don't understand how Javier is called from the path javier.fullcustommusic.com/chatbot/conversation_ start.php

**Comment by Dave-Morton** [comment]
Well, Javier seems to work from the jQuery GUI. Let me have a look at the Twitter interface (I've never actually used it before, so some investigation is in order) and see what I can come up with.

**Comment by Dave-Morton** [comment]
One thing I can see here is that we need to update the internal documentation within tweet.php. I'll work on this once I get my test chatbot for Twitter working. the Twitter handle for the bot is @MortiProgramO and it should be up and running in about a half hour (I HOPE).

**Comment by Program-O** [comment]
you can test it by just running the script directly
so tweet your bot then just run /gui/tweet.php

**Comment by Dave-Morton** [comment]
Yes, but that script produces no real output. I was going to make something that calls the script via a jQuery AJAX call, and report back on success or failure.

**Comment by FullCustom** [comment]
This is exciting and I've learned a lot. I want to get this working. I'll help where I can.

**Comment by Dave-Morton** [comment]
This issue sort of "fell through the cracks", I'm afraid, but I'm in the last weeks of the semester at school, so I'll have to revisit this in June. That's the best I can do for now.

**Comment by FullCustom** [comment]
I still had a lot of work to do with Javier before he can really take other my twitter account. Also I need to build my own HTML interface.

**Comment by Dave-Morton** [comment]
@FullCustom where are we at with this? Anything new on your end? I'm taking this weekend to look into this, so if you have any additional details, please let me know here.

**Comment by FullCustom** [comment]
I haven't done a thing with it. I would like to get my bot working with
twitter.

Timothy Eisenacher
Full Custom Music Repair
400 Market Street Rear Entrance
PO Box 272
Lemoyne, PA 17043
717-761-0890
www.fullcustommusic.com

**Comment by Dave-Morton** [comment]
Ok, Liz and I will both be working on this over the weekend (I just confirmed with her). If you have Skype, and have the time/interest, feel free to join in. My Skype handle is GeekCaveCreations.

**Comment by FullCustom** [comment]
I won't have time for skype but I'll try to stay involved over the weekend.
Monday I'll have more time.

Timothy Eisenacher
Full Custom Music Repair
400 Market Street Rear Entrance
PO Box 272
Lemoyne, PA 17043
717-761-0890
www.fullcustommusic.com

**Comment by Dave-Morton** [comment]
No worries. I'm working Monday, though. I'm off on Saturday, Sunday and Tuesday this (well, next) week. but we can either communicate via email, or if need be, here.

**Comment by Program-O** [comment]
Hi FullCustom are you about at all?
I have some time to help to sort this out with you.
if you can drop me an email at admin@program-o.com we can have a private chat and get this sorted

**Comment by Dave-Morton** [comment]
@FullCustom - A change in my work schedule is preventing me from digging into this as much as I would like, but I'm still devoting off-work time to it.

@Program-O - Take a look at tweet.php. I noticed that the bot ID is hard coded to a value of 6 on line 99, which may be causing part of the issue, at least (if not all of it). For testing purposes, I've split out the Twitter config variables from lines 49 through 54 into a separate file (tweet_config.php), and added  the variable $bot_id to that, setting it to the value of the current bot (1), then changing the code on line 99 to remove the hard-coded value and replace it with $bot_id.

That's as far as I got, though, and was unable to test it, so I don't know if that's the only problem. I suspect that the reason we're getting back the 170 (missing required parameter - status) error is because the bot is returning a blank response, so what I want to do is add in some code to check for an empty response before it tries to post to Twitter. I'll look more into this this evening when I get home from work.

**Comment by Dave-Morton** [comment]
Ok, I've pushed a new commit to the DEV branch that should address this issue (forgot to reference it in the commit comments, though... OOPS?). @FullCustom please grab the lates version from DEV and try it. Liz has also updated the [wiki](*https://github.com/Program-O/Program-O/wiki/Twitterbot-Set-Up) with more complete and concise instructions for setting up the bot, so it would be to your advantage to check those out as well. Let me know please if this takes care of things, or if you still have trouble.

**Comment by FullCustom** [comment]
I'll have time to do that Monday morning.

Timothy Eisenacher
Full Custom Music Repair
400 Market Street Rear Entrance
PO Box 272
Lemoyne, PA 17043
717-761-0890
www.fullcustommusic.com

**Comment by Dave-Morton** [comment]
Depending on your idea of "morning", I may still be at my desk (I'm an early riser). I'll monitor this issue till it's time to head for work. If I miss you Monday morning, I'll take a look right after work, as well.

**Comment by FullCustom** [comment]
I think this right here is my problem. I don't understand these two steps and they weren't in the originak instructions. Looks really really important. 
$chatbot_endpoint - Enter the url to your chatbot conversation endpoint - this is normally http:///chatbot/conversation_start.php
$bot_id - Enter your chatbot bot_id - this is the bot_id from the bots table

**Comment by FullCustom** [comment]
These are the parameters in my tweet.php (keys and url omitted). I have my cron job setup for 15mins cause that is a low as I'm allowed to go without paying extra. But where is the $bot_id, $chatbot_endpoint and $age_of_tweets_in_minutes that is mentioned in the new directions? Is that new code that I don't have yet?
 //--------------------------------------------------------------------------------------------------------------------
  // EDIT PARAMS
  //--------------------------------------------------------------------------------------------------------------------
  $consumerkey="";
  $consumersecret="";
  $accesstoken="";
  $accesstokensecret="";
  $path_to_bot = "http://www.yoursite.com/chatbot/conversation_start.php";
  $cron_every_x_minutes = 5;

**Comment by Dave-Morton** [comment]
did you download the latest version from the DEV or MASTER branch? For now, we've got the latest changes in DEV, so that they can be tested more widely before merging. From the looks of things, you may have grabbed the latest MASTER version, which won't yet work for you.

**Comment by FullCustom** [comment]
I see what I need know. I couldn't fine it earlier. Sorry I'm new to github. Do I need to reload the whole bot  or can I just sneak in the new tweet.php?

**Comment by Dave-Morton** [comment]
Just replace tweet.php. I don't think much else has changed with that, though there have been some other bug fixes. If you upload all of the files to your server those other bug fixes will also be taken care of without having to reinstall, so that would probably be best. :)

**Comment by FullCustom** [comment]
With the new tweet.php setup this is what I get:
Could not tweet. Bot returned an empty response!

**Comment by Dave-Morton** [comment]
Well, that's progress, at least. :)

Most likely it's a problem with the interface between tweet.php and your chatbot. Within the function `getReply()` (starting at line 114) you should find the following code:

    $request_url = $path_to_bot . "?say=" . urlencode($usersay) . "&convo_id=" . $convo_id . "&bot_id=$bot_id&format=xml";

Below that line, insert the following code:

    echo $request_url;

and run the script again (make sure there's a new tweet for the script to reply to). This time, a URL should be printed on the screen. Copy that URL and insert it into a new browser tab, and see what the result is, then paste that result here, please.

**Comment by FullCustom** [comment]
Here is the result:
?say=hello+bacon&convo_id=203089363&bot_id=1&format=xml
Could not tweet. Bot returned an empty response!

**Comment by Dave-Morton** [comment]
I think I see what at least part of the problem is. during our `codefest` the other night, Liz and I were working on different parts of the script (she handled the beginning of the code, as well as improving the documentation, while I addressed the issue of adding sanity checks, and the hard-coded bot ID). From the looks of it, she changed a variable name without notifying me, and I failed to proofread before merging her code with mine. Additionally, I never tested the code after said merge (had to head out to work), so this renamed variable never got found, and made it into the repo. The easiest "fix" for this is to go to line 27 and change `$chatbot_endpoint` to read `$path_to_bot` for now. I'm in the middle of working on a different bug, and so my local repo is in a state of flux, so it's not simple for me to push the correction at this point. I've already fixed the code locally (though I replaced the variable name in the opposite order, turning path_to_bot into chatbot_endpoint), but can't really push those changes until I'm done working on the other issue.

**Comment by FullCustom** [comment]
So you tried to Neil Gaiman/Terry Pratchett some php and the result was nowhere near as good as the book Good Omens.

**Comment by Dave-Morton** [comment]
lol yes. Sorry, but I'm afraid I'm less than perfect. Huge Pratchett fan, BTW. Was saddened to learn of his demise.

I've decided to backup the changes I've made to Program O that addresses the other bug (issue #140 ), and push the changes to address this one. the new commit should be up in a few seconds.

**Comment by FullCustom** [comment]
I tweeted to Javier that I have a post about the Sovtek MIG100 coming soon, He replied "I'm Optimistic".

**Comment by Dave-Morton** [comment]
Sounds like it works, then. Awesome!
