### ISSUE TITLE
Not so much an issue, looking for a point in the right direction

### ISSUE THREAD

**Issue by AdamMiltonBarker** [Program-O/Program-O#125]
Hi, I have rewritten the entire admin area to integrate with my platform, restructured everything and have added some new features, one of these new features parses an extra tag from the AIML, `<command>`, into the database and I have been successful getting this command back in the response. What I am attempting to do now is parse the star tags in the same way as the template, for example if the template is:

`<template>TEST <star index="1"/> TEST <star index="2"/></template>`

Then the command could be for example:

`<command>function(<star index="1"/>,<star index="2"/>)</command>`

Can you point me to the exact location of the interpreter that parses the template stars so that I can adapt it to also parse the command stars at the same time before logging the conversation and returning the response, I have found all of the relevant functions but I keep following them round in a circle and cannot find exactly where to implement this. Thanks in advance.

**Comment by AdamMiltonBarker** [comment]
I have attempted the following which I believe should do what is needed:

`
  function parse_aiml_as_XML($convoArr)
  {
    global $botsay, $error_response;
    runDebug(__FILE__, __FUNCTION__, __LINE__, "Parsing the AIML template as XML", 2);
    $template = add_text_tags($convoArr['aiml']['template']);
    try
    {
      $aimlTemplate = new SimpleXMLElement($template, LIBXML_NOCDATA);
    }
    catch (exception $e)
    {
      trigger_error("There was a problem parsing the template as XML. Template value:\n$template", E_USER_WARNING);
      $aimlTemplate = new SimpleXMLElement("<text>$error_response</text>", LIBXML_NOCDATA);
    }
    $responseArray = parseTemplateRecursive($convoArr, $aimlTemplate);
    $botsay = trim(implode_recursive(' ', $responseArray, __FILE__, __FUNCTION__, __LINE__));
    $botsay = str_replace(' .', '.', $botsay);
    $botsay = str_replace('  ', ' ', $botsay);
    $botsay = str_replace(' ?', '?', $botsay);
    $botsay = str_replace(' ,', ',', $botsay);
    $botsay = str_replace(' s ', 's ', $botsay);
    $convoArr['aiml']['parsed_template'] = $botsay;
    runDebug(__FILE__, __FUNCTION__, __LINE__, "Completed parsing the template. The bot will say: $botsay", 4);
	
	
    $command = add_text_tags($convoArr['aiml']['command']);
    try
    {
      $aimlTemplate2 = new SimpleXMLElement($command, LIBXML_NOCDATA);
    }
    catch (exception $e)
    {
      trigger_error("There was a problem parsing the template as XML. Template value:\n$command", E_USER_WARNING);
      $aimlTemplate = new SimpleXMLElement("<text>$error_response</text>", LIBXML_NOCDATA);
    }
    $responseArray = parseTemplateRecursive($convoArr, $aimlTemplate2);
    $commadit = trim(implode_recursive(' ', $responseArray, __FILE__, __FUNCTION__, __LINE__));
    $commadit = str_replace(' .', '.', $commadit);
    $commadit = str_replace('  ', ' ', $commadit);
    $commadit = str_replace(' ?', '?', $commadit);
    $commadit = str_replace(' ,', ',', $commadit);
    $commadit = str_replace(' s ', 's ', $commadit);
    $convoArr['aiml']['parsed_command'] = $commadit;
    runDebug(__FILE__, __FUNCTION__, __LINE__, "Completed parsing the commad. The bot will say: $commadit", 4);
	
	
    return $convoArr;
  }`

but the command response ends up with the star tags missing not parsed like the template is

**Comment by Dave-Morton** [comment]
You should be able to just run the contents of the `<command>` tag through `parseTemplateRecursive()`, which will (or should) properly parse those `<star>` tags. Take a look at the other functions in chatbot/addons/custom_tags/custom_tags.php to see how those other functions deal with this issue.

If I could ask, what language is being used to execute these "commands"?

**Comment by AdamMiltonBarker** [comment]
Hi thank you I think the issue was that  I have just found that my new teach and upload script actually stripped the star tags out of the AIML command db entry. And thanks will check out those functions as well. The function I showed above is not the actual way the commands will be stored it was just an example of what I wanted to parse, there will be multiple command fields for different languages such as Python, Android, Objective C, Pure JS, Node JS, etc etc

**Comment by AdamMiltonBarker** [comment]
After fixing my upload code that works now thanks :)

**Comment by Dave-Morton** [comment]
Always happy to help. Your concept sounds interesting. Please let us know how you get on with it.

**Comment by AdamMiltonBarker** [comment]
I will do thanks, will email you the link to the info when it is done I am creating a couple of services for businesses and homes. It is already integrated with FB chatbots and also will be integrating it with my MQTT broker so that people can command devices by MQTT through my IoT platform. There are a lot more features really. Will drop you an email once it is all ready, should be a couple of weeks.
