### ISSUE TITLE
download bot file fails

### ISSUE THREAD

**Issue by jamieduk** [Program-O/Program-O#126]
I click all files and select download and then it attempt to push file.php file to download instead of the actual file itself!

**Comment by Program-O** [comment]
what os and browser are you using please?

**Comment by Dave-Morton** [comment]
I just tested this on my development server and it works fine, so two things:

1.) Are you using the most recent version? and
2.) are you accessing Program O from your local computer (e.g. http://localhost) or from a remote server?

**Comment by Dave-Morton** [comment]
Since this issue has been more than 30 days without any further feedback, I'm closing the issue. If you have more info for us, please feel free to reopen it.
