### ISSUE TITLE
install_programo.php returns Error 500

### ISSUE THREAD

**Issue by bladeism** [Program-O/Program-O#127]
I uploaded the files configure and when I try to submit the form I got error 500. 
I already tested the server if it support PDO and can query well.

I'm using PHP and mysql (maria DB) under centOS

Also it file managed to create a table in my DB 'srai_lookup'
I also cheked the code but I can't trace whats the problem. 

Thank you!

**Comment by BeZazz** [comment]
First thing would be to go over error logs.
error 500, is a very generic error.

Have a look at the logs that relate to your http server.

**Comment by bladeism** [comment]
Oh i forgot checking man

**Comment by bladeism** [comment]
Here what I saw in my logs
Sadly I didn't saw any in errorlogs

In access log yes it just show Error 500

**Comment by Dave-Morton** [comment]
Where are you looking for the logs? Are you looking at the server logs, or the Program O logs (located in the logs folder of the Program O install)?

**Comment by bladeism** [comment]
@Dave-Morton thank you I saw this in install.error.log

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'chatterbot.bots' doesn't exist' in /var/www/html/hellodolly/install/install_programo.php:229
Stack trace:
#0 /var/www/html/hellodolly/install/install_programo.php(229): PDOStatement->execute()
#1 /var/www/html/hellodolly/install/install_programo.php(75): Save('2')
#2 {main}
  thrown in /var/www/html/hellodolly/install/install_programo.php on line 229


Although I noticed that this is the line after the creation of table 'srai_lookup'

And I just saw that the code doesn't automatically create the table of 'bots'

Will try to recreate in the db and test again.

**Comment by bladeism** [comment]
@Dave-Morton  oh wait I don't know the data types of the fields.

**Comment by Dave-Morton** [comment]
there's a file, new.sql in the install folder. that SQL file contains all of the information necessary to create the tables in the database that the script needs. It's used during the install process by the installation script. It sounds to me at this point that this step got missed somehow. I suggest trying to make sure that the database is completely empty (usually with phpMyAdmin), then run the install script again, but before you do, remove or rename install.error.log so that you have a "clean slate" for any later troubleshooting that may be required.

**Comment by bladeism** [comment]
@Dave-Morton I followed the instructions

and when I'm trying to upload an AIML

which I downloaded here
https://github.com/fastcoding/aiml-en-us-foundation-alice.v1-6

I get error 500

Thanks alot!

**Comment by Dave-Morton** [comment]
Is it still in the file install.error.log? Or is it now somewhere else?

**Comment by bladeism** [comment]
@Dave-Morton no logs. It's kinda weird. Btw this is on the admin panel uploading of AIML.

Thanks!

**Comment by Dave-Morton** [comment]
Interesting. Are you trying to upload that file as is? If so, it might be choking on the HTML file that lives inside the Zip archive (custom.html), and if *that's* the case, it should be creating a log entry **somewhere**. I've downloaded the file from GitHub, and I'll try to upload it as downloaded, and see what I get. Then I'll report back.

**Comment by Dave-Morton** [comment]
As it's been more than a month with no further feedback, I'm closing this issue for now. Please feel free to reopen it if you still have trouble with this.
