### ISSUE TITLE
Not working at all!

### ISSUE THREAD

**Issue by DaliborVlaho** [Program-O/Program-O#131]
I have installed Program O on my server without any problems during installation. After it, I used AIML's found here on GitHub and try to upload them via admin panel but i got a blank page at upload process. There is no respons from server.

During test bot action there is no respond from bot. Return empty answer.
Any suggestions?

Regards,
Dalibor

**Comment by Dave-Morton** [comment]
Take a look in the logs folder to see if any log files are present, and if they are, attach them to your next post so we can see what's happening. Also, some background information would be helpful. Please answer these questions:

1.) which version of Program O did you install, and from which branch (MASTER or DEV)?
2.) What is the OS, server software (and version) and PHP version that Program O is installed on?
3.) What is the OS and web browser that you are using to access Program O?

Providing this information will allow us to try to recreate the problem.

**Comment by Dave-Morton** [comment]
It's been about a month with no response, so I'm closing this issue. If you have more information for me, please reopen it. Thanks.
