### ISSUE TITLE
How to implement this function   for Restaurant ChatBot.

### ISSUE THREAD

**Issue by beshoo** [Program-O/Program-O#134]
```
Dear all  
  thank you very much for this wonderful program
  I have an idea to implement this program as a chat boat for a restaurant  
 taking orders from the client.

How can I run some functions when user say some key words.
Like
If user say Ok send the order.
---------------------------
How can I make chatBot remember the Order user ask for after long chat?.
 I don't know how to explain my idea but  imagine yourself log into a website 
and you want to order some pizza, imagine the conversation with you  and the assistant.
How can bot respond to you and even more , when the   conversation go on with you and the bot.
how can boot remember your order.
and how can I send   the order to the Admin, as a new order without sending all conversation !
Dos Program-O able to do some thing SMART like that ?

Please see this Example of chat between me and  a bot I like to create , is that possible  :
---------------------------
Me : Hello , Nice day
Bot: Hello sir , how may I help you today ?
Me: Bot I am hungry , are you !.
Bot: Me ! No at all. (But since you are   hungry ) 
lets me make your day easy and show you our menu !

Bot : Item 1 , price : 5$
Bot: Item 2 , price 8$.
Bot Item 3 , Price 10$.

Me: BTW , what is the weather in your aria bot !.
Bot : it is suny today , you are welcome in our local restaurant , do you prefer a delivery?
Me: Of wonderful time to get out , but for now , please send the order to my home 
( See here I did not say any thing about "delivery" word )
Bot , Ok then delivery.
Me : Yes 
Bot: Please may you send your order .
Me: I like to order item 1, and 3 please.
Bot: Wonderful , the price will be $15, delivery on house . 
Bot: Please what is your Address , please may you gave me your GPS location ?
Me : lat:2332 , long:78987
bot: Is there any phone Number?
Me : sure here you go 45678909876
Bot: Ok after 20 Min you will got your order.
Me : wonderful. Have a nice day.
Bot : Thank you.

Here the chat is ended 
---------------------------

Restaurant owner will get a new record on his admin panel some thing like this :+1: 

New Order : 
item 1, and 3 
price $15
Address :lat:2332 , long:78987.
Phone Number : 45678909876
------------------------------------------------------
Lets say I login to the chat next time :+1: 

Me: Hello Bot, how are you today ?
Bot: My software is broken today , but never mind , I am just fine.
Me: How are you today ?
( Note I did repeat the question )
Bot: I already told you ! 
Me: How are you today ?
Bot: Ok , I am fine :) happy !
Me: How are you today ?
Bot : FINE ! 
Me: How are you today ?
Bot: It is bad game !
Me: I am just playing around.
Bot: How may help you to day , same as usual ?
 (Note here , bot is remember what Is my order last time)
Me : yes please as usual .
Bot: your order is : item 1, and 3 ,  price will be $15, delivery on house . 
Me : Yes .
Bot : Same address ?
Me: No the new location is lat: 234323 long: 5432432
Bot: I am sorry , this location is far a way , cost will be on you , which will cost $15+.
Me : please I don't want toe order
Bot. Ok , your order is Canceled.

Here in this point the chat is end and nothing sent to the owner of the restaurant.  
Please advice and thank you for your interest
```

**Comment by Dave-Morton** [comment]
That's a rather ambitious project, @beshoo , and while it's certainly possible to do something like that with Program O, I'm afraid than any assistance beyond simple advice is beyond the scope of a GitHub issue.

That said, however, I have some suggestions, bit I need to ask a question or two before I go any further:

1.) A project like this will require some in-depth PHP programming to pull off. How proficient is your team (or you, if it's just you) with coding in PHP?

2.) Given the content of your post, I have a feeling that English isn't your 'native' language. This is fine, but will have a profound effect on the way your restaurant bot will handle responses. Will you be able to obtain the services of a professional writer to assist? Or, at the very least, someone who is naturally fluent in English who can take care of any grammatical or semantics issues what would otherwise cause a problem? Even if English **is** your native language, you're going to need to enlist help in this area. This isn't an insult, mind you. Just an observation.

**Comment by beshoo** [comment]
First Of all , yes English isn't my 'native' language, Oh my god I tried my best in the school!
Any way , I need to travel to USA to get that empress you.
Well you may ask from ware I am , I am From Syria! I am sure you know syria if you watch TV.

Any Way, Regarding PHP, yes I am good in it. Not as you for sure.

>  will have a profound effect on the way your restaurant bot will handle responses

As I told you I am From Syria, which is Arabic country and arabic is a mother language,
I am targeting Arabic clients.

**Comment by Dave-Morton** [comment]
Please don't get me wrong here. You have nothing to apologize for. In fact, your command of the English language is far better than many people that I know that were *born* here. It's just that there are some grammatical and semantic errors that I've noticed that will likely cause trouble for you at some point. I think that your project is exciting, and I want it to succeed, so I'll give you advice that's intended to help you do just that: succeed.

Yes, I'm well aware of where Syria is, no worries. :) Will you then be writing the AIML categories in Arabic? One nice thing about Program O is that it can handle a large number of different language encodings, though we haven't tested Arabic yet.

Given that you're at least competent in PHP, you will have a good chance of succeeding in the area of integrating your chatbot with a product ordering system. There are a number of ways to accomplish this task, but all of them begin with creating custom AIML tags to handle collecting the customer's data, storing it for later use, and sending orders to the restaurant somehow (probably via email, an internet messaging system, or a "back-end" interface that can collect data from the same database that the bot uses to store it). This isn't extremely difficult, but it *does* require intermediate to advanced level skills in PHP and SQL to accomplish. I can provide a small amount of limited support for this portion of the project, but prefer to do so outside of GitHub. You're welcome to contact me via [my website](http://www.geekcavecreations.com/?contactMe) about this, if you like.

**Comment by beshoo** [comment]
I tried my best to contact you via website form

CAPTCHA did not match the image.Please try again

My email is
beshoo (a t)  gmail.com
Please drop me an email.
On May 29, 2016 5:26 AM, "Dave Morton" <notifications@github.com> wrote:

Please don't get me wrong here. You have nothing to apologize for. In fact,
your command of the English language is far better than many people that I
know that were *born* here. It's just that there are some grammatical and
semantic errors that I've noticed that will likely cause trouble for you at
some point. I think that your project is exciting, and I want it to
succeed, so I'll give you advice that's intended to help you do just that:
succeed.

Yes, I'm well aware of where Syria is, no worries. :) Will you then be
writing the AIML categories in Arabic? One nice thing about Program O is
that it can handle a large number of different language encodings, though
we haven't tested Arabic yet.

Given that you're at least competent in PHP, you will have a good chance of
succeeding in the area of integrating your chatbot with a product ordering
system. There are a number of ways to accomplish this task, but all of them
begin with creating custom AIML tags to handle collecting the customer's
data, storing it for later use, and sending orders to the restaurant
somehow (probably via email, an internet messaging system, or a "back-end"
interface that can collect data from the same database that the bot uses to
store it). This isn't extremely difficult, but it *does* require
intermediate to advanced level skills in PHP and SQL to accomplish. I can
provide a small amount of limited support for this portion of the project,
but prefer to do so outside of GitHub. You're welcome to contact me via my
website <http://www.geekcavecreations.com/?contactMe> about this, if you
like.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Program-O/Program-O/issues/134#issuecomment-222339099>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEa56-Jn2Z2tjcjoPQ3_gl0dJqnFXb7uks5qGPlKgaJpZM4IpLdA>
.

**Comment by Dave-Morton** [comment]
That's very odd. I get the same thing as well. I'll have to check the logs and figure out what's gone wrong. Meanwhile I'll send you an email.
