### ISSUE TITLE
always got error when i test it "Something went wrong! Error ="

### ISSUE THREAD

**Issue by satishverma143** [Program-O/Program-O#137]

**Comment by Dave-Morton** [comment]
Generally speaking, it's a really good idea to provide some details when you submit an issue. At the very least, I'll need the following:

+ Program O version
+ OS type & version (server)
+ OS type & version (client)
+ PHP/MySQL version
+ Web browser type & version

It's also very helpful if you can provide any relevant error log entries, and any debug files that may have been generated. the error logs can be found in the logs folder, and the debug files are in chatbot/debug. Without this information it's impossible to diagnose the problem.

**Comment by satishverma143** [comment]
Program O version : **2.5.4**
OS type & version (server) : **windows server**
OS type & version (client) : 
PHP/MySQL version : **PHP - 5.5.12, MySQL - 5.6.17**
Web browser type & version : in any browser same error but i am using **chrome** & **version : 51.0.2704.84 m**

Please help me asap.

**Comment by satishverma143** [comment]
i solved the issue.

**Comment by Dave-Morton** [comment]
That's great! but can you please tell us what you did to fix it, in case someone in the future has a similar problem?

**Comment by findborg** [comment]
I get the same issue,  I think that it has to do with testing on localhost and getting the path correct

**Comment by Dave-Morton** [comment]
@findborg Are you currently having this issue? If so, can you please provide some specifics, so that we can help you to correct the problem?

**Comment by findborg** [comment]
I fixed the problem,  it has to do with the paths in the example files.  For example:
  `// Experimental code
  $base_URL  = 'http://' . $_SERVER['HTTP_HOST']';'  
Needs to be changed to:
  `// Experimental code
  $base_URL  = 'http://' . $_SERVER['HTTP_HOST'] .'/';!

**Comment by jonnyboy** [comment]
While you are making changes there, you should really consider removing the 'http:' to allow for https also.

**Comment by findborg** [comment]
@jonnyboy This code is from the example gui's php.  When you build your page you can adjust the server paths as required.

**Comment by jonnyboy** [comment]
ok

**Comment by Dave-Morton** [comment]
@findborg I'd still be very interested in knowing the deails of your Program O installation, since that very same code that you've described changing works perfectly well on all of my various machines which use both Windows and various flavors of Linux operating systems. I've just tested the jQuery GUI for both my Windows 10 and CentOS 6 installs, and the original code is working perfectly. So if you would, please provide your Program O install information, so I can try to replicate this as you would find it on your server.

**Comment by findborg** [comment]
Server: Local Databases (127.0.0.1 via TCP/IP)
Server type: MySQL
Server version: 5.7.9 - MySQL Community Server (GPL)
Protocol version: 10
User: @localhost
Server charset: UTF-8 Unicode (utf8)
Web server

Apache/2.4.17 (Win64) PHP/5.6.16
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 4b7b5b787fe5555 $
PHP extension: mysqli Documentation
PHP version: 5.6.16

windows machine running wamp64

**Comment by Dave-Morton** [comment]
It appears that you're running a server nearly identical to mine (see the specs, below), so It's a bit odd that you've had to make the changes you did. but I've seen stranger, so if it works for you, then that's what matters. :)

*My (mostly complete) List of Servers That I Test With*

1. Main Server:
+OS: Windows 10 Pro 64bit
+Server Software: Apache 2.4.17
+PHP Version: 5.6.18
+MySQL Version: 5.7.9
+Program O Version: 2.6.2 (BETA)

2. CentOS Server:
+OS: CentOS 6.8 64bit
+Server Software: Apache 2.2.15
+PHP Version: 5.3.3
+MySQL Version: 5.7.9 on DMORTON (See 1., above)
+Program O Version: 2.6.2 (BETA)

3. Debian Server:
+OS: Debian GNU/Linux 6.0 64bit
+Server Software: Apache 2.2.16
+PHP Version: 5.3.3
+MySQL Version: 5.7.9 on DMORTON (See 1., above)
+Program O Version: 2.6.2 (BETA)

4. Windows 7 Server:
+OS: Windows 7 Ultimate 64bit
+Server Software:  Apache 2.2.25
+PHP Version: 5.5.12
+MySQL Version: 5.7.9 on DMORTON (See 1., above)
+Program O Version: 2.6.2 (BETA)

5. Ubuntu Server:
+OS: Ubuntu 14.04 LTS
+Server Software: Apache 2.4.7
+PHP Version: 5.5.9
+MySQL Version: 5.7.9 on DMORTON (See 1., above)
+Program O Version: 2.6.2 (BETA)

**Comment by findborg** [comment]
Do you think that it has to do with the fact that it is in a sub folder not a root install.  Or,  because the folder is renamed?  The only other thing that I could think of is maybe it is a matter of turning on or off a particular php setting.

**Comment by Dave-Morton** [comment]
I'd have to see the error logs to be able to determine what's going on. You can view them in the logs folder of your Program O install. The DEV branch version (2.6.2) actually now has links to the debug and logs folders to make it easier to find them, but that version hasn't been completely tested yet.

**Comment by rwaters71** [comment]
I ran into the same issue with a fresh installation on a https-only server. I had to change the chatbot/gui/jquery/index.php (line 25):

**Comment by Dave-Morton** [comment]
Actually, I've been working with some code to correct this, though I haven't yet had the time to implement it yet. Give me a couple of days and I'll get this handled.

**Comment by Dave-Morton** [comment]
Ok maybe not a couple of days. Please check out the latest version in the `DEV` branch.

**Comment by rwaters71** [comment]
Just tried the jquery gui protocol detection, seems to work fine with HTTPS on Apache 2.4 :)

**Comment by Dave-Morton** [comment]
Glad to hear it. Please let us know if you have any more issues, or if you have a question.

**Comment by ajosav** [comment]
Please help, I still encounter the same issue of 'something went wrong error ='. I have followed all the suggested solutions but still getting back to the same point. 

Tried with different servers (wamp and xampp) still not working... 

Solution urgently needed please

**Comment by patrickschur** [comment]
@ajosav To help you I need your log files. There should be a file called `error.log` in your `log` folder. :)

**Comment by ajosav** [comment]
X
![img-20170803-wa0028](https://user-images.githubusercontent.com/27934057/28923279-64c6d066-7855-11e7-8dae-3ecf274ac1ed.jpg)

**Comment by ajosav** [comment]
Will upload the log file soon

**Comment by patrickschur** [comment]
Ok I need you log files otherwise I can't help you.

**Comment by ajosav** [comment]
Please my laptop is currently down will upload as soon as I am able to
charge. Thanks

**Comment by ajosav** [comment]
Yes the html response type is working fine, it's only json format that is giving me the error. 
And when I checked the log folder, I only saw index

**Comment by patrickschur** [comment]
The first time you accessed the site with JSON enabled, did you received any message other than the error message? If there is no `error.log`, I need the full HTML of the error message. Because it looks like the error message contains HTML and was parsed by the browser. To do that you have to open your developer tools (inspector) on your browser and search for the error message in the HTML. Then copy and paste the HTML.

**Comment by ajosav** [comment]
inspecting the error message, this is the outer html  
<div id="urlwarning">Something went wrong! Error = </div>
![error](https://user-images.githubusercontent.com/27934057/28961994-280b7fbc-78fc-11e7-909a-dd8e9e48d445.png)

**Comment by patrickschur** [comment]
Could you test Program-O with the newest dev branch + can you check the console logs on your browser?
It looks like that the error comes from javascript. Did you modify something on the site? Just to be sure.

**Comment by ajosav** [comment]
Finn

**Comment by Dave-Morton** [comment]
The javascript console should provide a clue to what's happening. The methods for accessing the console vary from browser to browser, and I'm on the road, so can't go into detail on how to do it, so it's up to you to figure it out. Once you get the console open, try chatting with the bot and copy everything that gets generated in the console, then post it here.

**Comment by ajosav** [comment]
Program-o in the dev branch gives me same error but it's like a log file
has been generated now.

**Comment by patrickschur** [comment]
What does the log file say?

**Comment by ajosav** [comment]
Attached to this mail

**Comment by Dave-Morton** [comment]
Sadly, attached files don't seem to make the trip when you reply via email. I strongly suggest that you actually follow the link in this email entitled "view it on github" and dragging the log file onto the page itself. Then we'll be able to see the file, read it, and help further.
