### ISSUE TITLE
Response appears twice 

### ISSUE THREAD

**Issue by redamith** [Program-O/Program-O#138]
when "talking to the bot" the responses appear twice on the upper left corner of the browser and inside the "response" div

**Comment by Dave-Morton** [comment]
Ah, yes. So it does. I've found the problem, and will address it this weekend. I'll let you know when I've handled the problem.

**Comment by Dave-Morton** [comment]
This issue has been addressed in the DEV branch, and will be placed into MASTER during the next branch merge.
