### ISSUE TITLE
Help panels for some admin sections still need to be written

### ISSUE THREAD

**Issue by Dave-Morton** [Program-O/Program-O#14]
The help panels for both the AIML downloading and "Clear AIML Categories" sections have yet to be completed. The code for these sections is in the file admin/default.page.htm. I'll work this out after overall stability of the script has been verified.

**Comment by iUzairJan** [comment]
Hey, Dave Im web dev and Hacker I found many venrubilities on ur site i emailed u too, Anyways Program o needs scratch, Firstly Ui is not good I found Aiml bot named JXBot its Ui is too gud Also supports. Aiml 2.0 but lack features and community like Program O. I'll keep pentesting your website and Aiml bot and will report to you. Also if u need Guy for Managing Your servers Ping Me

YOU Fan

Uzair 1337

**Comment by Program-O** [comment]
@iUzairJan thanks for your input, please feel free to fork the dev branch and submit any fixes you feel would improve security or ux.
thanks again

**Comment by wofty** [comment]
Hello, I'm having trouble to installing Program-O and I have this error at the installation.
Parse error: syntax error, unexpected '{' in /mnt/100/sdb/c/0/wofty/install/install_programo.php on line 178

In the file install_programo.php I have this line 178:
  try {
      $dbConn = new PDO("mysql:host=$dbh;dbname=$dbn;charset=utf8", $dbu, $dbp);
      $dbConn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
      $dbConn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    }
I don't think it's really a Parse error.
Here are my versions: SQL, Apache and PHP :
MySQL
Server: wofty.sql.free.fr via TCP/IP
Server version: 5.0.83
 MySQL charset:  UTF-8 Unicode (utf8)  

Web server
Apache
MySQL client version: 5.1.61
PHP extension: mysql

phpMyAdmin
Version information: 3.1.5

Other question : 
Is it possible to used api.program-o.com with Program-O or it's an other program?

Thanks for your works

**Comment by Program-O** [comment]
can you please open this in a new issue?
thanks

**Comment by wofty** [comment]
Sorry, off course.

**Comment by Program-O** [comment]
completed!
