### ISSUE TITLE
A bug,when edit aiml in admin panel

### ISSUE THREAD

**Issue by longcnn** [Program-O/Program-O#140]
As the title,i could not save when edited the aiml in admin panel with chinese ,but english is good,please help fix the bug,thanks!
The file url is /admin/index.php?page=editAiml

**Comment by Dave-Morton** [comment]
I'm aware of the problem, though the solution has not yet been found. I'm still working on it, though.

**Comment by Dave-Morton** [comment]
No need to close this issue yet, as it's still unresolved. I've got the jQuery version working in all respects except for the editing of existing fields. I should have it completely working by this weekend, barring complications or interruptions.

**Comment by Dave-Morton** [comment]
Ok, I've uploaded the latest version that addresses this issue. Please download the zip file [here](https://github.com/Program-O/Program-O/archive/dev.zip) and give it a try, letting me know how it goes.

**Comment by longcnn** [comment]
Okay,that's a good news! I'll give it a try this night!

**Comment by longcnn** [comment]
well,how to upgrade?

**Comment by Dave-Morton** [comment]
If you click on the link in my earlier post, you will download the zip file for the project from the DEV branch. Simply check it for viruses (I advise that to everyone, even from "trusted" sources), unzip the file, then upload the files to your server. There is no need to reinstall, since there are no changes to the config or database. Once you've uploaded the files, log into the admin page to test it.

**Comment by longcnn** [comment]
Yes,it's working...
But,I couldn't found any  AIML data list when I click the **Search/Edit AIML**  menu left side , just 
![36020160709082812728](https://cloud.githubusercontent.com/assets/4423477/16704868/b332e282-45af-11e6-8d04-2dcc69792b32.jpg)

**Comment by longcnn** [comment]
En,It's good behavior, maybe the empty data before due to the page cache, and I tested the form,  edited the aiml in admin panel with chinese, it works perfectly!
Thanks very much Dave!

**Comment by Dave-Morton** [comment]
Great! Please let us know if you have any issues. For now I'll close this issue.
