### ISSUE TITLE
Does the Program-o support the logic AND and logic OR when use the condition tag?

### ISSUE THREAD

**Issue by longcnn** [Program-O/Program-O#141]
Does the Program-o support the **logic AND** and **logic OR** when use the condition tag?
I had some problem above when i want the robot response a  accurate answer for two or more premiss,just like the syntax **_if a =1 and b = 2_**  in php or orther language.
If not ,how to  solve it?
Thanks!!

**Comment by Dave-Morton** [comment]
That sort of logic lies outside of the capabilities of the AIML specification without jumping through a **LOT** of hoops I'm afraid, and isn't *directly* supported in Program O, but I'm sure that a workaround could be devised. The two methods that come to mind are:
1. create some rather complex AIML code to combine all possible permutations of the values of a and b into one variable, and then use the `<condition>` tag to choose among those permutations, or:
2. Create a custom AIML tag and function to handle them via PHP

There are advantages and disadvantages to each of these, but either could work well if done correctly.

**Comment by longcnn** [comment]
Thank you Dave，I'll try.
