### ISSUE TITLE
Not a real issue - about translations

### ISSUE THREAD

**Issue by andymnc** [Program-O/Program-O#143]
i can't find a real and good aiml in italian for program-o.
If you know about any of italian aiml knowledge library but "maria" that's not working at all.. please, can you give me your advice about them?
Thank you very much

**Comment by LorenzCK** [comment]
As far as I know, there is no “good” Italian AIML-based bot, unfortunately. The only public one available is [Maria](http://bsdgurl.net/pages/maria.html), but the [official AIML source](http://www.alicebot.org/downloads/aiml/maria.zip) contains many errors and does not work with Program O.

However, it can be fixed: for instance, in `Ciao.aiml` you can replace `<alice>` tags with the correct `<aiml>` tags and replace the strange `<getname/>` tags with the correct ones (i.e., `<get name="name" />`).
There is a _fixed_ version of Maria’s AIML code [on Github](https://github.com/moondroid/ChatBot/tree/master/app/src/main/assets/alice-it/aiml). I didn’t try, but it should work with Program O.

Assuming you can get Maria to work... it still doesn’t make it a great bot. But you might be able to use it as a starting point. Hope this helps. :)

**Comment by Program-O** [comment]
Hi,
When I made the turkish AIML set, 
I wrote a small script which used Google Translate to convert the english aiml into turkish
I put the 'turkish' aiml on to Github.
I did this for a Program O user who needed a turkish AIML set.
It was my hope that he and other turkish speaking users would correct any errors they found.
I havent actually had one pull request for the AIML set! but oh well.
Maybe you can do something similar for an Italian language set.

**Comment by Dave-Morton** [comment]
I was more or less thinking the same thing, Liz. But I think that since Google made some pretty major changes to how Translate works (I read a while back that they now limit the number of free translations that can be handled per day/hour), doing the entire ALICE AIML set may take a few weeks to convert. And knowing how inaccurate translations from English to French are from personal experience, there will be a significant number of corrections necessary. Still, that's far, far easier than re-writing the entire corpus from scratch. :)

**Comment by andymnc** [comment]
I agree with Dave. Goog translator from ita to eng and viceversa is a mess.
Anyway, thanks for the MARIA link and suggestions to Lorenz.
About the comment by Program-O.. if you can give me some help, i will be helping you back, of course.
As i wrote here and on an email that i sent to u today, i just saw what a huge work is there to have this working in italian in a realistic good way. I understood ur statement.

**Comment by Dave-Morton** [comment]
@LorenzCK  what about MARIA is not working with Program O? Is it that it simply contains XML errors, thus failing validation? Or is there something else at issue?

**Comment by andymnc** [comment]
Tomorrow morning i'm going to try that other version of Maria and i let you know if it works. 
But it seems that he think it's not too much evolved

**Comment by LorenzCK** [comment]
@Dave-Morton The original MARIA uses some strange AIML tags (`<getname/>` instead of `<get name="name" />`, for instance) and the root tag is `<alice>` instead of `<aiml>`. Perhaps it just uses some old-fashioned AIML syntax? Anyway, [the other MARIA version](https://github.com/moondroid/ChatBot/tree/master/app/src/main/assets/alice-it/aiml) _should_ work on Program O.
I agree with @Program-O, this could be a good opportunity to create a decent Italian bot on a public repository.

**Comment by Dave-Morton** [comment]
the `<getname> tag is AIML 0.9 syntax, and has been deprecated and unused for nearly 20 years now. But if that's all there is to the problem, a simple search/replace script to replace those tags (along with any other deprecated tags) wouldn't be hard to make and run. I'll download and validate the AIML set, then write a script to translate all of the deprecated tags, then validate the files again. I have most of the tools at hand to make it a fairly fast process.

**Comment by Dave-Morton** [comment]
I've written a script that can du the bulk of transformations from AIML 0.9 to AIML 1.0, and so far it seems to work well on the older MARIA files that I've been testing with. As soon as I get it all done I'll be adding it to my [**AIML Toolkit**](http://www.geekcavecreations.com/AIML/). This way, anyone with older (0.9) AIML files will be able to "upgrade" them without having to pore through dozens to thousands of lines of code. :)

**Comment by LorenzCK** [comment]
@Dave-Morton Excellent! :+1:

**Comment by andymnc** [comment]
@LorenzCK and @Program-O i'm starting to try that [Maria](https://github.com/moondroid/ChatBot/tree/master/app/src/main/assets/alice-it/aiml)

@Dave-Morton super! And thanks for your tools

**Comment by Dave-Morton** [comment]
@andymnc I've only looked at SioNo.aiml in that repo, but it looks like the conversion that @moondroid did was successful. So far, the conversion script that I've written is working just fine, but I'm sure that I'll have to tweak it as time goes on. I've converted all of the older MARIA files and placed them in the repository, and once I add the necessary code to process uploaded files, I'll be adding the conversion script to the toolkit. I think I'll also be adding the option of downloading entire repository "folders" as zip files, but that probably won't happen till this weekend.

**Comment by andymnc** [comment]
@Dave-Morton  super! Anyway there's some strange word in italian and i mean.. about italian! In any case, it's very helpful just like that. How could we download those files? if you "save as" it's not working, and if you click on the filenames you'll receive a "I can't do that. sorry. (web spamming?)". I'm on chrome 51.0.2704.106 (64-bit) on linux.
@Program-O if you want me to help translating program-O and, for example, the common.dat in italian, give me some int/rule on how/where to do it. I mean, I can translate the program-O admin gui and the common.dat in italian
I think that if you could extrapolate the english sentences from the code it could be better (in a lang file or in the DB in a new lang table), so i can translate the whole gui, both for admin and "frontend" gui...

**Comment by Dave-Morton** [comment]
Um... Oops? It seems that there is a bit of a bug in the download script. I'm looking into it. Sorry for the inconvenience.

**Comment by Dave-Morton** [comment]
@andymnc the file download bug has been corrected, and you should no longer be plagued by the warning about web spamming. It seems that the download script got corrupted somehow.

**Comment by andymnc** [comment]
let me know if you want me to help translating gui and stuff like that in italian for you.

**Comment by Dave-Morton** [comment]
I wasn't really planning on doing that, to be honest. That sort of thing is something that I leave up to the botmaster.

That said, however, if you wish to fork Program O and create an Italian version I'm with you 100%, and will provide whatever assistance I can to help you along. :)

**Comment by andymnc** [comment]
ok. so the request  was only about the aiml files, wasn't it? If you give me some time, i can check all the maria files and fix them (about italian i mean), or ... tell me what kind of help i can give to you guys.

**Comment by Dave-Morton** [comment]
The MARIA files aren't all that big, really, and I'm not quite sure how accurate they are, so far as the Italian portions go (I don't speak Italian at all, so... Also, there seems to be a small amount of English in the mix in some of the files, from what I could see. I admit I didn't look at the content much while I was converting them to AIML 1.0), so if you want to verify the Italian within them, that would be a great help. I haven't done so yet, but one of the things on the agenda for the AIML editor in the AIML Toolkit is to allow "one-click loading" of AIML files within the repository, as well as some other enhancements & improvements.

**Comment by andymnc** [comment]
ok, give me some time and i'll check and fix them

**Comment by Program-O** [comment]
closing over 30 days old without a response
