### ISSUE TITLE
The missing slash

### ISSUE THREAD

**Issue by Nerdcoat** [Program-O/Program-O#147]
Not the baddest error ever, but after a fresh installation,
there is a missing slash before the chatbot api link. 
Its on every gui as far as I can say.

**Comment by Dave-Morton** [comment]
Not exactly certain of what you mean. Can you paste the URL that's giving you trouble here?

**Comment by Nerdcoat** [comment]
In JSON, the index.php, line 21. 
It make out of http://google.com/chatbot/conversation_start.php a 
http://google.comchatbot/conversation_start.php
same with xml gui and plain gui.
have the same on master version.

**Comment by Dave-Morton** [comment]
That's a problem with the configuration of the GUI files themselves, I think. I have no problems of this sort on any of my systems. If you look in the file gui/xml/index.php you should see the following code, starting on line 21. Please note the first line:

```php

  // Experimental code
  $base_URL  = 'http://' . $_SERVER['HTTP_HOST'];                                   // set domain name for the script
  $this_path = str_replace(DIRECTORY_SEPARATOR, '/', realpath(dirname(__FILE__)));  // The current location of this file, normalized to use forward slashes
  $this_path = str_replace($_SERVER['DOCUMENT_ROOT'], $base_URL, $this_path);       // transform it from a file path to a URL
  $url = str_replace('gui/xml', 'chatbot/conversation_start.php', $this_path);      // and set it to the correct script location
/*
  Example URL's for use with the chatbot API
  $url = 'http://api.program-o.com/v2.3.1/chatbot/';
  $url = 'http://localhost/Program-O/Program-O/chatbot/conversation_start.php';
  $url = 'chat.php';
*/
```
Also, please note the comment that I've also included here. If you're having trouble with the "experimental" code here, you can simply hard-code the value of `$url` to suit your needs. I'll try to replicate the error here tomorrow (I'm getting ready for work in a couple of minutes), but as I said, I was just using all of the GUI pages to test the last issue, and saw nothing like this.

**Comment by Nerdcoat** [comment]
Yes, like I said, a missing slash isnt the hardest error ever, may its a hoster problem too, I dont know. 
I just tested the "normal" version before with the same error. 

No need to be in a rush! :)
Have a great day Dave!

**Comment by Dave-Morton** [comment]
I just updated my previous post, so it may not ba a bad idea to re-read it. :)

**Comment by Nerdcoat** [comment]
Yeah I do this little fix everytime before, its a very small but strange error. :)

**Comment by Dave-Morton** [comment]
If that's the case, I'm having to conclude that this is a "server thing". That kind of sucks, but at least you know about it.
