### ISSUE TITLE
session id issue

### ISSUE THREAD

**Issue by tbenjis** [Program-O/Program-O#148]
Hi, PHP 5.6 throws this error 

PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/20/2016 21:36:16 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/20/2016 21:40:22 -

**Comment by tbenjis** [comment]
is there a better way to retrieve all data than the fetch_all() function in PDO_functions.php line **93**

**Comment by Dave-Morton** [comment]
@tbenjis it sounds like you have an exceptionally large amount of data in the database that could be causing the memory issue. As far as the session ID problem, that could be any number of things causing that, so what I need is more information so that I can assist you better. Please read [**this wiki page**](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to get an idea of the sort of information that will be needed to help troubleshoot the issue.

**Comment by tbenjis** [comment]
Yes, I noticed it was due to multiphp support in WHM without suphp enabled, so the changes I made to php.ini didn't take effect. I have however fixed this now. Thanks. 

As for the session, I use PHP 5.6, MySQL 5.6 on CentOS7. I have also included the contents of  the error.log file for details.

`07/21/2016 00:31:03 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 00:31:03 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 00:55:10 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 00:55:10 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:09:58 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:09:58 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:01 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:01 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:16 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:16 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:29 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:29 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:32 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:32 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:34 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:34 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:37 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:37 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:42 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:42 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:10:47 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:10:47 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 01:51:20 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 01:51:20 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 02:38:03 - PHP ERROR [Notice] -Undefined variable: tmp_sentence in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 255
07/21/2016 02:38:03 - PHP ERROR [Warning] -array_reverse() expects parameter 1 to be array, null given in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 255
07/21/2016 02:38:03 - PHP ERROR [Warning] -array_unshift() expects parameter 1 to be array, null given in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 270
07/21/2016 02:43:26 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 02:43:26 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 02:48:09 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 02:48:09 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:06:36 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:06:36 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:06:41 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:06:41 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:06:52 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:06:52 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:08:58 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:08:58 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:09:07 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:09:07 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:09:25 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:09:25 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:09:45 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:09:45 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:09:54 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:09:54 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:09:58 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:09:58 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:11:02 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:11:02 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:11:22 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:11:22 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:11:43 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:11:43 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:12:17 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
07/21/2016 03:12:17 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct () in Unknown on Line 0
07/21/2016 03:12:41 - PHP ERROR [Notice] -Undefined variable: tmp_sentence in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 255
07/21/2016 03:12:41 - PHP ERROR [Warning] -array_reverse() expects parameter 1 to be array, null given in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 255
07/21/2016 03:12:41 - PHP ERROR [Warning] -array_unshift() expects parameter 1 to be array, null given in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 270
07/21/2016 03:12:45 - PHP ERROR [Notice] -Undefined variable: tmp_sentence in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 255
07/21/2016 03:12:45 - PHP ERROR [Warning] -array_reverse() expects parameter 1 to be array, null given in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 255
07/21/2016 03:12:45 - PHP ERROR [Warning] -array_unshift() expects parameter 1 to be array, null given in /home/tbenjis/bot/chatbot/core/conversation/intialise_conversation.php on Line 270
07/21/2016 03:13:23 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0`

**Comment by tbenjis** [comment]
Although everything seems to work fine and no error is shown to the user, but the log file is filled up with the contents above.

**Comment by Dave-Morton** [comment]
Is the log continuing to fill up, then, after you made the changes you did?

**Comment by tbenjis** [comment]
yes, even after the changes.

**Comment by Dave-Morton** [comment]
Ok, I'll need to fire up and upgrade my CentOS server (it's CentOS 6.8) to test it. I'll need at least an hour.

**Comment by tbenjis** [comment]
okay, thanks. It's 64

**Comment by Dave-Morton** [comment]
Awesome! That makes it easier, since I don't have to create an entirely new virtual machine.

**Comment by Dave-Morton** [comment]
After extensive testing I cannot reproduce the problem, so I think I'll  need a bit more information. First off, are you using the most recent version of Program O? The latest version is 2.5.4 on the MASTER branch, and 2.6.3 on the DEV branch. If you aren't using the most recent version, please update your Program O install, delete all error log files in the logs folder and try it again.

If you *are* using the most recent version, I'll need to know if you are using one of the pre-made interfaces (HTML, XML or jQuery), or if you're using a custom interface, and which output format it uses. All of the pre-made GUI pages display the conversation (session) id right on the page, so I'll need to see what that looks like, please.

**Comment by tbenjis** [comment]
I call the conversation_start.php directly. This is a sample request
`"GET /chatbot/conversation_start.php?convo_id=+clientid+&say=holaaaa&bot_id=1&format=json HTTP/1.1" 404 10260 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.2; GT-I9192 Build/KOT49H)"`

**Comment by tbenjis** [comment]
Oh I found the error. This occurs when the convo_id isn't provided and it happens when the first message is sent without a convo_id before it retrieves one from the server. so if i sent a request such as this `GET /chatbot/conversation_start.php?convo_id=&say=what%20for&bot_id=1&format=json HTTP/1.1" 200 120 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.2; Lenovo TAB 2 A7-30HC Build/KOT49H)`, the error shows up. So I guess with a custom interface, a convo_id is to be provided before initiating any conversation.

**Comment by Dave-Morton** [comment]
lol that will do it. :) Yes, a conversation id (which could literally be anything that doesn't contain "illegal" characters) is required to be provided.
