### ISSUE TITLE
how do we fix uppercase responses?

### ISSUE THREAD

**Issue by tbenjis** [Program-O/Program-O#149]

**Comment by Dave-Morton** [comment]
@tbenjis I really need more information that what you've provided. Can you give me an example of what you're seeing? That would be most helpful.

**Comment by Nerdcoat** [comment]
I think he means, that when you input "Hello!" the script convert it into "HELLO!"?
It was fixed in the dev version.

**Comment by Dave-Morton** [comment]
That's possible. I found a bug a while back where the returned input had been normalized prior to being returned, and this was not the desired action. We'll have to see, though, what sort of reply we get back. :)

**Comment by tbenjis** [comment]
I think its with parts of the reply that is saved to the clients_properties table. For example if I say `my name is tbenjis` the bot replies with `hello TBENJIS` or I say `I love books`, it replies with `what kind of BOOKS do you like?`. However, this isn't shown in all sentences but rather words or phrases in the `client_properties table are displayed in uppercase.

**Comment by Alexeggers** [comment]
I had this happen earlier. When I asked: "Why do your answers take so long?", the bot answered with: "I did not know YOUR ANSWERS TAKE SO LONG 3F does."

**Comment by Dave-Morton** [comment]
Hmmm... I'll have to look at how that part of the script normalizes the text. It sounds like it's converting it to uppercase for testing, but not returning it to normal once testing is done.

**Comment by tbenjis** [comment]
Yes, it seems it converts to upper case for comparison, but it may be challenging to return the exact case received if its not saved before conversion.

**Comment by Dave-Morton** [comment]
Frankly, I think I'll see about comparing a normalized *copy* of the text when doing the testing, rather than normalizing the text itself. That way there is no possibility of "contaminating" the text in question. However, my schedule has become rather full lately, between school, work and other family crises, so this may take a while to get to. But I'll take care of it as quickly as I can.

**Comment by d351gn** [comment]
+1 from my side! Of course family and health comes first!

**Comment by Program-O** [comment]
fixed in the next release
