### ISSUE TITLE
[feature req] Markdown

### ISSUE THREAD

**Issue by Maik-Thiele** [Program-O/Program-O#150]
I think it would be great to have a better way for links and making things bold or italic. 
For me, my bot have actually a lot of links to pictures and urls, so I can save a lot of space then.

**Comment by Dave-Morton** [comment]
Actually, there's already a plugin in place for just that, though it's BBCode rather than markdown. For links, you can use either [url=my.url/to/something]link title[/url], [url]my.url/to/something[/url] or [link=my.url/to/something]link title[/link]. Images are [img]link.to/my/image[/img], and you can use colors, font modifiers (e.g. bold, italic, underline, etc.) and (I think) a few others. In the chatbot/addons folder is a folder named parseBBCode. Have a look at both the INSTALL and README files for usage information.

**Comment by Nerdcoat** [comment]
Amazing. Just amazing!

**Comment by Dave-Morton** [comment]
That feature has been in place for a number of years now, as I was using Program within a chatroom script that I developed, and it was handy to have it in place by default.

**Comment by Dave-Morton** [comment]
there are other useful addons in there, as well, such as custom tags (~<google>` and`<wiki>` chief among them), spellchecking and word censoring, as well. Most are enabled by default, and the spellcheck and word censor addons have options in the admin.

**Comment by Nerdcoat** [comment]
I use the spellcheck for "cancelled/canceled", works great. May it would be nice to turn on/off the plugin via acp.

**Comment by Dave-Morton** [comment]
I'll add that to the ToDo list. I've thought about doing so several times over the years, but I always seem to get distracted by other things (bugs, motorcycle wrecks, etc.) snf forget. :)

**Comment by Nerdcoat** [comment]
Step 4 - add the following line to the function start_response_useraddon() (in load_addons.php)

//run the BBCode input parser before sending into the system
parseInput($convoArr);

there isnt this line in the file.

**Comment by Dave-Morton** [comment]
So it needs to be added. I'll add that to the list of things to put into the admin.

**Comment by Nerdcoat** [comment]
After all, the installation didnt work for me. Can I put the load_addons I have here?

**Comment by Dave-Morton** [comment]
Sure.

**Comment by Nerdcoat** [comment]
`<?php
/***************************************
* www.program-o.com
* PROGRAM O 
* Version: 2.6.3
* FILE: chatbot/addons/load_addons.php
* AUTHOR: Elizabeth Perreau and Dave Morton
* DATE: MAY 17TH 2014
* DETAILS: this file contains the calls to include addon functions
***************************************/

//load the word censor functions
include("custom_tags/custom_tags.php");
include("word_censor/word_censor.php");
include('spell_checker/spell_checker.php');
include("parseBBCode/parseBBCode.php");
//include("checkForBan/checkForBan.php"); // A new addon for verifying that a user has not been banned by IP address

runDebug( __FILE__, __FUNCTION__, __LINE__, "Loading addons",4);

  /**
   * Function run_pre_input_addons
   *
   * * @param $convoArr
   * @param $say
   * @return string
   */
  function run_pre_input_addons(&$convoArr, $say) {
  global $format;
  $say = (USE_SPELL_CHECKER) ? run_spell_checker_say($say) : $say;
  //$convoArr = checkIP($convoArr);
  #if ($format == 'html') $say =  parseInput($say);
  return $say;
}

  /**
   * Function run_mid_level_addons
   *
   * * @param $convoArr
   * @return mixed
   */
  function run_mid_level_addons($convoArr)
{
  return $convoArr;
}

parseInput($convoArr);

  /**
   * Function run_post_response_useraddons
   *
   * * @param $convoArr
   * @return mixed
   */
  function run_post_response_useraddons($convoArr) {
  $format = $convoArr['conversation']['format'];
  $response = (isset($convoArr['send_to_user'])) ? $convoArr['send_to_user'] : $convoArr['conversation']['error_response'];
  $curTime = date('H:i:s');
  $response = str_replace('[serverTime]',$curTime, $response);
  if ($convoArr['send_to_user'] != $response) $convoArr['send_to_user'] = $response;
  //$convoArr =  run_censor($convoArr);
  checkForParsing($convoArr);
  if ($format == 'html') $convoArr =  checkForParsing($convoArr);
  $ip = $convoArr['client_properties']['ip_address'];
  //if ($convoArr['client_properties']['banned'] === true) add_to_ban($ip);
  return $convoArr;
}










?>`

**Comment by Dave-Morton** [comment]
I probably should have mentioned that the BBCode addon only works when the chatbot's format is set to HTML. this line:

` #if ($format == 'html') $say =  parseInput($say);`

should be uncommented to enable the BBCode parser, but again, it only works for the HTML interface. that **can** be changed, but will require some modification to the other GUI pages to get them to work; especially the jQuery GUI.

**Comment by Nerdcoat** [comment]
Then I wish this to the todo list. :)

**Comment by Dave-Morton** [comment]
We decided a while ago that since the GUI pages were only supposed to be simple, quick examples (templates, as it were) of how to create your own bot pages, such things as parsing BBCode on the XML and jQuery pages wasn't really going to be planned for. If you want to handle that aspect yourself, I'm more than happy to assist, but I think that should probably be done via email, rather than on GitHub. the XML interface shouldn't be difficult to do, but the jQuery GUI will be very tricky.

**Comment by Dave-Morton** [comment]
BTW, the line of code that I referenced a few posts ago isn't the only one that would need to be altered. That one handles the user's input, and as mentioned in the INSTALL and README files, is experimental in nature, and may not work as intended. the other line is in the function run_post_response_useraddons(), and looks like this:

`if ($format == 'html') $convoArr =  checkForParsing($convoArr);`

that's the one that parses the bot's responses.

**Comment by Dave-Morton** [comment]
I was able to get the BBCode parsing to work in the XML GUI, but it required going a bit "off the reservation" to make it work. If you wish to send me an email, I'll send you the instructions to make it happen, along with some files to assist the process.

**Comment by Nerdcoat** [comment]
Thanks Dave, I will send you an email asap.

**Comment by Dave-Morton** [comment]
I've changed my mind, and decided to include the changes made to the XML GUI to the project, since they work well enough, and don't seem to negatively impact operation. No sense in wasting effort here. :)

**Comment by Program-O** [comment]
closed over 30 days without response
