### ISSUE TITLE
SRAI lookup didnt work anymore

### ISSUE THREAD

**Issue by Maik-Thiele** [Program-O/Program-O#151]
It contains in a blank white page. The rest works.

EDIT: The admin.error.log says

> [21-Jul-2016 13:34:05 Europe/Berlin] PHP Parse error:  syntax error, unexpected '[' in /admin/srai_lookup.php on line 64

which is this line:

`$starArray = ['~<star[ ]?/>~i', '~<star index="\d+"[ ]?\/>~'];`

I think I saw this error before?

**Comment by Dave-Morton** [comment]
You did. I'll look through the entire script for the code that produces that error and correct it all. Oops? :)

**Comment by Dave-Morton** [comment]
I've just pushed the changes to address this. Please let me know if you have anymore problems with this.

**Comment by Nerdcoat** [comment]
Oh damn ... I am very sorry, it was a hard night! :(
I think I will wait for the next dev update.

**Comment by Dave-Morton** [comment]
No need to apologize. And no need to wait, either. the "next" dev update is already in place, and deals with not only this issue, but the other issue you've mentioned.

**Comment by Dave-Morton** [comment]
@Nerdcoat have you had a chance to see if updating fixed the issue?

**Comment by Program-O** [comment]
closed over 30 days without response
