### ISSUE TITLE
[feature req] Dropdown menue in acp

### ISSUE THREAD

**Issue by Maik-Thiele** [Program-O/Program-O#154]
I thin the acp would be looking much better and more modern, 
if its using a dropdown, it also would needed less space. 

May better also in the header, not on the left site, 
it would give more space for the functions.

**Comment by Dave-Morton** [comment]
@Nerdcoat  My, you're a busy one. :P 

Are you referring to the navigation links down the lsft side of the screen? If so, that can certainly be done, but as this is not a bug, per se, it may be a while before I get to it, and before that, I'll have to talk it over with the rest of the development team. But I'll let youknow the results of that discussion.

**Comment by Nerdcoat** [comment]
Yes I mean the left menue. Sorry to give your team so much work.
Any way to donate for all your work?

**Comment by Dave-Morton** [comment]
@Nerdcoat there's no way at present to directly make donations to the team. I have a donate button on [my website](http://www.geekcavecreations.com), but that's just me. I think Liz may have one, too, but I'm not 100% certain about that, and I simply don't know if @LorenzCK has one at all. I know he has a website, though, so you could check that out to see. :)

**Comment by Nerdcoat** [comment]
So, how can user say thanks for all your work? It comsumes a lot of time...

**Comment by Dave-Morton** [comment]
Truthfully, just a smile and a "thank you" is good enough for me. I'm doing this for the love of the art, not for money. :)

**Comment by Nerdcoat** [comment]
Thank you! :)

**Comment by Program-O** [comment]
closing over 30 days without a response
