### ISSUE TITLE
srai and previous bot response

### ISSUE THREAD

**Issue by malmestig** [Program-O/Program-O#155]
Hi
I've been using Program-O 2.4.8 and found something in the srai lookup. I upgraded to 2.5.4 to see if it was still there and it is. I'm not sure if it's a bug or by design?

Here's how to reproduce:

Create 2 categories with values as below
1. Previous bot response= \* ANSWER
   User input= MY REPLY
   Bot reply= TOP SECRET
2. User input= MY *
   Bot reply= `<srai>MY REPLY</srai>`

Test it by typing in MY TEST and the result back will be TOP SECRET. 

Is this by design? I sort of expect TOP SECRET not to show up because the That field acts as a "safeguard"? That is, I don't expect a match.

Thanks, malmestig

**Comment by Dave-Morton** [comment]
The SRAI lookup table doesn't have a `that` field in irt because it doesn't need one. When you execute an AIML category with an `<srai>` tag, the bot's "previous response" (e.g. THAT) hasn't changed, so there's no need to store it in the database.

**Comment by malmestig** [comment]
No, sorry, I didn't mean the SRAI lookup table. I believe that works fine. 
What I'm having problems with is that the srai redirect seems to ignore the previous bot response.

Here are the categories I'm having problems with:
SQL:

`INSERT INTO aiml VALUES(1488, 1, '<category><pattern>MY *</pattern><that></that><template><srai>MY REPLY</srai></template></category>', 'MY *', '', '<srai>MY REPLY</srai>', '', 'admin_added.aiml');`

`INSERT INTO aiml VALUES(1489, 1, '<category><pattern>MY REPLY</pattern>[thatpattern]<template>TOP SECRET</template></category>', 'MY REPLY', '* ANSWER', 'TOP SECRET', '', 'admin_added.aiml');`

Screenshot:
![issue](https://cloud.githubusercontent.com/assets/4559865/17077351/e43ab174-50cd-11e6-8b1c-5ff4c0379a4a.png)

The issue I have is that I don't want the bot to give the answer "TOP SECRET" when I say
"MY TEST" if the bot hasn't previously said something ending with "ANSWER".
Currently it will say "TOP SECRET" whatever it has previously said.

Thanks, malmestig

**Comment by Dave-Morton** [comment]
but that's exactly what you have there, so that's the response the chatbot will give. Either that, or I'm missing something, so let's make sure we're on the same page here.

If your bot says something that ends in ANSWER (e.g. I have no answer), and you say "My test", you **DO NOT** want the bot to say "TOP SECRET", right? If this is the case what *do* you want the bot to say?

**Comment by malmestig** [comment]
Sorry for the confusion (English isn't my first language)
If my bot says something ending in "ANSWER" and I say "my test" then it should say "TOP SECRET". This is what I expect.
However right now if the bot previously has said for example "I AGREE" and I say "my test" then it will also say "TOP SECRET". This is what I don't want.

**Comment by Dave-Morton** [comment]
Ah. I understand now. Do you have an AIML category for "MY REPLY" that has no `<that>` tag? If not, please add one and put in a response that is *not* "TOP SECRET", and see if that works. Just make sure to re-run the SRAI lookup script to make sure that the new entry is added.

**Comment by Dave-Morton** [comment]
I may have to alter the lookup script to ignore categories that have `<that>` patterns. We'll see after you test my suggestion.

**Comment by malmestig** [comment]
I just tested it and found that
1. Just adding it and not immediately running the SRAI lookup script caused it to 100% choose the "NOT TOP SECRET" choice (without the that tag)
2. Running the SRAI lookup subsequently reversed it and caused it to 100% choose "TOP SECRET" again.

**Comment by Dave-Morton** [comment]
Ok, that's a problem. I'll do some testing to see specifically what's going on.

**Comment by Dave-Morton** [comment]
In the meantime, you can fix the issue by noting the ID if the new category that you've added and altering the entry in the SRAI lookup table to match that ID. that should put the desired action back in place.

**Comment by malmestig** [comment]
Thanks, I will have to check that!

**Comment by Dave-Morton** [comment]
I'm afraid that any more investigation on my part will have to wait until later. It's almost 4AM here, and that's well past my bed time! :O
