### ISSUE TITLE
Issue with: 'Navigate to http:///install/install_programo.php'

### ISSUE THREAD

**Issue by youmoosebejoking** [Program-O/Program-O#158]
I am following the instructions page and an having issues with the step:
-Navigate to http:///install/install_programo.php

When I open this file with the Mac OS Finder, it brings up the file in Dreamweaver.  Safari doesn't give me the option to open the file, but if I choose to Open With and select Safari then the file opens as a text file.

I have installed mysql and later MAMP just to see if that would make a difference, but it did not.  I would appreciate any advice anyone can offer.

Thank you

**Comment by BeZazz** [comment]
I am afraid from what you have written above that you to to start off at the basics of running a php file on your computer before attempting this.

**Comment by Dave-Morton** [comment]
Since you've installed MAMP, can you navigate to http://localhost and see at least some sort of web page? This is the first step; making sure that you have a working web server. Once you get the web server up and running, we can continue. :)

**Comment by youmoosebejoking** [comment]
I spent some time learning about php today.  I was able to get the form up and complete it, but was returned a page with the following error.  I'll keep trying to figure it out, but if there's anything simple I could be missing, please let me know.

string(87) "SQLSTATE[HY000] [1045] Access denied for user 'x'@'localhost' (using password: YES)

notes:
-real username replaced with x
-I did create a mysql database and an ID for x, which was granted all privileges on all databases
-I've tried connecting several times, so I do not believe I am typing the wrong password.  After a few more tries, I will delete/recreate the user to make sure that it is the right password.  (should be, just cant think of any other options at the moment)
-I set the web and mysql ports to 80 and 3306

Thanks

**Comment by Dave-Morton** [comment]
Since you have MAMP installed, it should come with phpMyAdmin, which is a database management tool. Can you log into phpMyAdmin? If so, you should be able to create a user account that can be used to access the database portion of Program O.

**Comment by youmoosebejoking** [comment]
I removed/reinstalled everything and am now up and running.

Thank you for your assistance!

**Comment by Dave-Morton** [comment]
Terrific! If you need anything else, or have questions, please let us know.
