### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by DaliborVlaho** [Program-O/Program-O#159]
Hello,

as title above means - 403 Forbidden after install process. You fill out fields and hit save but 403 says NO. Program-O Master, downloaded from Github. Tested on three OS with mulltiple browsers.

Regards!
Dalibor

**Comment by Dave-Morton** [comment]
HTTP status code 403 is a permissions issue. Please take a look at [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) and provide the information requested so that we can better advise you on how to address the issue. Thanks. :)

**Comment by Program-O** [comment]
closing over 30 days old without a response
