### ISSUE TITLE
How to add requests in base Korean characters ?

### ISSUE THREAD

**Issue by MorganBurn** [Program-O/Program-O#160]
No answer if add and to write korean characters

**Comment by Dave-Morton** [comment]
If you have copies of the dialog with the chatbot, and the AIML categories that you wrote to use that contain Korean, please post them here so that we can take a look, and see what's going on.

**Comment by MorganBurn** [comment]
Please look at the screenshots
1) Admin: http://prntscr.com/c849pg
2) Website: http://prntscr.com/c849vq

**Comment by Dave-Morton** [comment]
Thank you for the screenshots. Can you download admin_added.aiml from the "Download AIML" panel, and attach it here so that I can test that file?

**Comment by MorganBurn** [comment]
https://drive.google.com/file/d/0B2205DbYQOQjMVliY2sySHF1NjA/view?usp=sharing

**Comment by Dave-Morton** [comment]
Thank you. I'll examine this, and see what's going on.

**Comment by Dave-Morton** [comment]
Ok, I've added the AIML that was giving you trouble, and added some of my own (thanks to Google Translate, so don't shoot me if the Korean is bad). Here are the results:

>Seeker: 안녕
>Baseline: 안녕 bro
>Seeker: 내 이름은 데이비드이다
>Baseline: 안녕하세요 데이비드이다, 어떻게 당신은?

And here is the AIML code used:

```XML
<category>
  <pattern>안녕</pattern>
  <template>안녕 bro</template>
</category>
<category>
  <pattern>내 이름은 *</pattern>
  <template>안녕하세요 <star/>, 어떻게 당신은?</template>
</category>
```

the debug files generated all look fine, and no errors are created during the conversations, so I need to know some more information. Please read [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues), and collect the information requested. If you're using the most recent version of Program O, all of this information is in the very first entry of every debug file, so you can just open one of them, copy the information, and paste it here. Or you can post the file itself to save time, as that will give me even more information to work with.

**Comment by MorganBurn** [comment]
Thank you for your help. I use: Current GitHub Version: 2.6.3
If > "User Input: any language except english" then > "Bot Response: No AIML category found."
And if > "User Input: english language " then > "Bot Response: correct answer with any language"
What could be the problem ?

**Comment by Dave-Morton** [comment]
It could be a lot of things. That's why I need the information about your system. If your chatbot is visible to the public I can get the information myself. All I would need is a URL that I can access the bot with. Until I get the information I need, there isn't much I can do to help.

**Comment by MorganBurn** [comment]
http://morningbeats.ml/bot5/admin
admin
111318

**Comment by Dave-Morton** [comment]
While the Program O version you are using *is* 2.6.3, it's not the most recent version. As a result, the debug information that I was looking for isn't available in the debug file. Please locate and provide the following:

1. Operating system (including version)
2. PHP version
3. MySQL version
4. Which browser (including version) are you accessing the bot with

**Comment by MorganBurn** [comment]
PHP 5.4
MySQL 5.6.x
Browser: Opera 39.0

**Comment by Dave-Morton** [comment]
Oops? I forgot to add the server software version. Are you using IIS or Apache (there are others, but those "others" aren't easy to install on a Windows system)?

**Comment by MorganBurn** [comment]
If I will install an Apache that will show korean characters ?

**Comment by Program-O** [comment]
closing as over 30 days without a response please feel free to reopen if still an issue
