### ISSUE TITLE
conversation_start.php gives no result

### ISSUE THREAD

**Issue by nickzwart** [Program-O/Program-O#162]
Hi, thanks for the great program. 
I have a small issue. The program is working fine, so the JSON, HTML and XML respond to the input. But conversation_start.php not, which I use a lot. I looked in the chatbot/debug files and the respond is generated, the output is fine: **"[send_to_user] => div class="usersay" Seeker: hello peo /div - div class="botsay" Alice: Hi there!. When do you think artificial intelligence will replace lawyers? /div"**
(I removed the < and > from the 'div' here )

I have another instance running on the same server that works fine, the difference is that this other instance gives a **convo_id** in the string.

Any thoughts on this.

With kind regards,

Nick Zwart

**Comment by Dave-Morton** [comment]
Hi, Nick! Sorry for the delay in responding. Between work and school, I seem to have little time for much else, these days.

Are you seeing anything in the error logs that may relate to this? Also, how are you calling conversation_start.php? Knowing this might help to narrow down the problem.

**Comment by nickzwart** [comment]
Hi Dave, no problem, I am busy also.
No, there are no error logs.
I called the conversation_start.php from the link on JSON example page. http://chatbot.3dles.com/VWchat/gui/jquery/ 
The rest is fine, as I can see.

**Comment by Dave-Morton** [comment]
Interesting. I just tried the following URL and it works just fine:

http://chatbot.3dles.com/VWchat/chatbot/conversation_start.php?say=hello&convo_id=Dave&bot_id=1&format=json

the response I got back was as follows:

`{"convo_id":"Dave","usersay":"hello","botsay":"How are you?"}`

When tying 3rd party apps or programs into the Program O API, it's important to make sure that the following variables are passed into conversation_start.php:

+ **say:** This is what the user is inputting into the chatbot.
+ **convo_id:** This is the unique identifier that tells the chatbot who they are speaking to.
+ **bot_id:** This tels Program O which chatbot to interact with (defaults to 1).
+ **format:** This tells Program O how the response is to be formatted. With 3rd party API calls, this needs to be either JSON or XML. Leaving this blank may cause issues if your Program O install's default format is set to HTML.

**Comment by nickzwart** [comment]
Ahhh, that's why I got problems, the &format=json needed to be added.
Thanks for the reply. Great news.

Nick

**Comment by nickzwart** [comment]
I tested it with the scripts I have running in Second Life, it runs great. Thanks Dave.

**Comment by Dave-Morton** [comment]
Glad to hear it, Nick. Please let us know if you have any other problems.
