### ISSUE TITLE
<system>,<math>, and <wiki>  tags

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#164]
Are `<system>` and `<math>` tags supported in 2.6.x? I'm getting validation errors for these tags, that were worked fine in 2.4.x

**Comment by Dave-Morton** [comment]
The `<math>` tag is not part of the AIML 1.0.1 specification, so it's no surprise that an AIML file containing that tag fails validation. The `<system>` tag appears to have been left out of the DTD and XML Schema files that Program O references, so it will also cause validation errors. I'll put adding the `<system>` tag into those reference files on my ToDo list.

**Comment by AlekzNet** [comment]
I mean I cannot add an AIML file containing `<math>` or `<system>` using the admin GUI, because of the errors:

A total of 2 errors have been found in this document.
`
Error 1871: Element '{http://www.alicebot.org/TR/2001/WD-aiml}math': This element is not expected. in /home/alekz/public_html/ai/o/admin/
on line 172

Error 1871: Element '{http://www.alicebot.org/TR/2001/WD-aiml}math': This element is not expected. Expected is one of ( {http://www.alicebot.org/TR/2001/WD-aiml}set, {http://www.alicebot.org/TR/2001/WD-aiml}think, {http://www.alicebot.org/TR/2001/WD-aiml}br, {http://www.alicebot.org/TR/2001/WD-aiml}get, {http://www.alicebot.org/TR/2001/WD-aiml}random, {http://www.alicebot.org/TR/2001/WD-aiml}li, {http://www.alicebot.org/TR/2001/WD-aiml}srai, {http://www.alicebot.org/TR/2001/WD-aiml}star, {http://www.alicebot.org/TR/2001/WD-aiml}a, {http://www.alicebot.org/TR/2001/WD-aiml}person ). in /home/alekz/public_html/ai/o/admin/
on line 179
`

**Comment by Dave-Morton** [comment]
Well, you can't add them in *file* form, but they can certainly be added in the Teaching or Search/Edit interfaces. Both of those panels will allow you to add the desired AIML category without having to validate the AIML in the process. If you have only a couple of AIML categories that use the `<system>` tag then this could be a viable option. If you have several dozen or more of such categories, then manually entering each one could be a bit annoying and frustrating. I **will** be addressing this in the future, but my schedule is such at present that it's going to be several weeks before I can get to it. In the meantime, you're more than welcome to fiddle with the code if you're comfortable doing so, and disabling validation so that you can upload AIML files without validation. For now that's the best I can offer.

**Comment by AlekzNet** [comment]
That means that something was changed recently in the validation/uploading area. Because other elements (e.g. `<wiki>`) also stopped working.

**Comment by AlekzNet** [comment]
OK, managed to get the tags to work and to pass validation by tweaking admin/aiml.xsd. Learnt something ;)

**Comment by AlekzNet** [comment]
With some serious aiml.xsd tweaking (e.g. added table, font, styles, etc support from https://www.w3.org/TR/xhtml1-schema and tweaked existing elements) I even managed to run tic-tac-toe from the CallMom suite. So, indeed, Program-O is much more capable, than the admin GUI lets do ;) 

Two side notes:
- tic-tac-toe game is too buggy, so no use without proper rethinking and debugging.
- aiml.xsd needs serious redesigning

**Comment by Dave-Morton** [comment]
Just so you know, HTML tags aren't part of the AIML standard, so they aren't included in the XSD or DTD files. At some point I might be interested in adding your XSD file to the project, and provide an option to "Allow HTML tags" in both the validation and upload pages, as well as an option to skip validation when files are uploaded, but that's a while off. Right now I have far too many irons in the fire, and I'm spending homework time to address these new issues. :P :) But that's ok, I've gone without sleep before. ;)

**Comment by Dave-Morton** [comment]
@AlekzNet would you be willing to share your modified XSD file? I think that the changes you've mentioned would be beneficial to the project.

**Comment by AlekzNet** [comment]
Yes, but I need to comb it out a bit, for it's too messy. Also, I'm going to replace the repetitive blocks with links.

**Comment by silverark** [comment]
@AlekzNet I hope you don't mind me asking, but is the <math> tag something you are processing yourself? I couldn't find it specified anywhere. I'm looking for an AIML file that will help my bot do some maths for me, just simple equations. I've only seen people using recursive AIML for counting, Javascript implementations or using a external bot or api....

**Comment by AlekzNet** [comment]
Just created this pull request https://github.com/Program-O/Program-O/pull/177 for the new aiml.xsd file
