### ISSUE TITLE
How are dots treated?

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#166]
Do I understand correctly, that dots get removed from the patterns, just like other punctuation symbols? 

For example, "a. b" is interpreted as "a b" and not like two separate phrases "a" and "b", right?

**Comment by Dave-Morton** [comment]
periods (dots) are never valid within `<pattern>` tags at all. the only characters allowed within pattern-side tags (e.g. `<pattern>`, `<that>` or `<topic>` tags) are letters, numbers, space and the two AIML 1.0 wildcards ( * and _ ). The only exception to this is the use of `<bot>` tags within `<pattern>` or `<that>` tags.

That said, however, periods (dots) within the user's *inputs* are treated as sentence-splitters, and should create separate responses for each split input. For example, if the user says:

> Hello. How are you?

the chatbot should create two separate responses, and pass them both back in the correct order back to the user.

**Comment by AlekzNet** [comment]
Sorry for confusion but this is exactly what I meant. I have the following code:

```xml
<category>
<pattern>ABCD</pattern>
<template>ABCD</template>
</category>

<category>
<pattern>DEFG</pattern>
<template>DEFG</template>
</category>
```
But when I enter "ABCD. DEFG" as input, I'm getting the default response:

User: ABCD
Bot: ABCD
User: DEFG
Bot: DEFG
User: ABCD. DEFG
Bot: Default response

**Comment by Dave-Morton** [comment]
Sounds like you've found a bug. I'll have to look into it, but that may take some time. Between work, school and a plethora of broken vehicles (3 out of the 5 my family use have serious mechanical issues), I barely have time to breathe, but I'll put this to the top of the priority list, and work on it when I can. I'll keep you posted.

**Comment by patrickschur** [comment]
The only thing you need to do is to explode the sentence in `conversation_start.php`.
Add a foreach loop at line `191` and close it at line `254`:
```php
foreach (preg_split('/[.?!]/', $lc_say) as $say)
{
    // [...] line 192 - 254
    display_conversation($convoArr); // don't forget to add this line
}
```
This will only work with `JSON` as response format and in the XML GUI. It's also works with other response formats, but you'll only see the last message displayed.

**Comment by AlekzNet** [comment]
Very simple and logic solution! As a side effect all `<that>`s, `<topic>`s and `-`-response loops will be confused, but that's to be expected for several sentences.

Thanks much again!

**Comment by Dave-Morton** [comment]
That's not a bad plan, but the period isn't the only sentence splitting punctuation there is, so perhaps a slightly different approach is in order. Ideally, splitting should occur with the following punctuation:

`. ; : ?`

Note that there is no comma in that list. It should also be noted that sentence splitting based on punctuation alone is not a good idea, as abbreviations (e.g. Mr., Dr., etc) normally include periods, time formats (e.g. 12:30PM) contain colons, and other "proper grammar" could include punctuation that might be improperly split if a simple `preg_split` were used. This is a very complex task that should be planned for carefully.

**Comment by patrickschur** [comment]
I know that. It was just a workaround or an idea how to do it. Otherwise, I would have made a pull request. 

I've been dealing with the topic of how to separate a sentence, for a very long time. I would argue that it is not possible to separate a sentence without knowing its grammar. But there are solutions which work pretty well in most of the cases. Like this regex `/(?<=[.?!])(?![.?!])\s*(?!\d)/` which I have done some time ago.
Example: `What is 0.432 + 432.43? Hello!!My name is Patrick... It's 9:00AM. Really??`
Results in:
```text
Array
(
    [0] => What is 0.432 + 432.43?
    [1] => Hello!!
    [2] => My name is Patrick...
    [3] => It's 9:00AM.
    [4] => Really??
)
```

**Comment by FedgeNo** [comment]
You might be able to glean some stuff around here that helps as well if anyone has a lot of time on their hands. This team seems to do most of their work in Java but things like regexes and whatnot in their code should be easy enough to grab. Not sure if it's all even open source but you might find something. I use their stuff in some other projects and it works well for the most part. http://nlp.stanford.edu/

**Comment by patrickschur** [comment]
@FedgeNo Already known. There is also a PHP version of it. [PHP-Stanford-NLP](https://github.com/agentile/PHP-Stanford-NLP)

**Comment by Dave-Morton** [comment]
@patrickschur I actually hadn't known thatt here was a PHP version of the Stanford NLP. that's interesting. While it's really late in the game to add it to this version of Program O, it may be worth considering integrating into other chatbot projects that I have in mind. Thanks for the reference.

Till then, however, I think that the RegEx pattern you've posted may be a workable solution for now. At the very least it's a good starting point.
