### ISSUE TITLE
How to match an empty variable in <condition>

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#167]
Is it possible to match an empty  variable in `<condition>`? For example:

``` xml
<category>
<pattern>show topic</pattern>
 <template>
    <condition name="topic">
            <li value="">The topic is not set</li>
            <li value="*">Current topic is <get name="topic" /></li>
   </condition> 
 </template>
</category>
```

Currently `<li value="*">` is  chosen if the topic is set to `<set name="topic"></set>`.

**Comment by Dave-Morton** [comment]
Try rearranging the tags to see if the behavior changes. The LI tag containing the star (*) *should* match with any wildcards that might be available, or match with an empty string if there isn't.

Something you can do is to type "show topic" (no quotes) into the chatbot, then log into the debug file reader (you can get to it from the admin page). Look for the following:

> Parsing a CONDITION tag.

The Program O debugger is pretty detailed about reporting events and such, so you may find some useful information there.

**Comment by giuliopons** [comment]
I've checked not defined variable in this way, maybe it can help:

```
<category>
	<pattern>WHO AM I</pattern>
	<template>
		<condition name="username">
			<li value="*">You are <get name="username" /></li>
			<li>I don't know</li>
		</condition>
	</template>
</category>

```

**Comment by AlekzNet** [comment]
@giuliopons the last '<li>' always matches, regardless it's set or not. SO, it's not quite the same. See also: https://github.com/Program-O/Program-O/issues/169

**Comment by Dave-Morton** [comment]
@AlekzNet I'll have to test this a bit more, because that's not what I've been seeing.

**Comment by Dave-Morton** [comment]
Before I close this issue, is there anything else that we need to discuss?

**Comment by Program-O** [comment]
closing - last response over 30 days ago
