### ISSUE TITLE
The last <li> in <condition> always matches

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#169]
If the value of a variable does not match any of the `<li value="xxxxxxx">`, the last `<li value="yyyyyy">` will be chosen, regardless of the actual value:

``` xml
<category>
<pattern>vartest5</pattern>
 <template>
    The var name5 is <get name="name5"/><br />
    <condition name="name5">
        <li value="yes">Name5 is defined as YES -- <get name="name5"/><br /></li>
        <li value="no">Name5 is defined as NO -- <get name="name5"/><br /> </li>            
    </condition>
    Now let's set name5 to <set name="name5">maybe</set>
 </template>
</category>
```

Result:

User: vartest5
Bot: The var name5 is undefined
Name5 is defined as NO -- undefined
Now let's set name5 to maybe

User: vartest5
Bot: The var name5 is maybe
Name5 is defined as NO -- maybe
Now let's set name5 to maybe

**Comment by Dave-Morton** [comment]
If you have no "fallback" option (say, a `<li>` element with no value attribute) then that's exactly what will happen. In order to prevent this from occurring, you need to add a default list element with no name or value attributes to the end of the collection. Something like the following will work:

````xml
<category>
  <pattern>vartest5</pattern>
  <template>
    The var name5 is <get name="name5"/><br />
    <condition name="name5">
      <li value="yes">Name5 is defined as YES -- <get name="name5"/><br /></li>
      <li value="no">Name5 is defined as NO -- <get name="name5"/><br /> </li>
      <li>Name5 has not yet been set.</li>
    </condition>
    Now let's set name5 to <set name="name5">maybe</set>
 </template>
</category>
````

**Comment by giuliopons** [comment]
I have a similar problem, I want to give an answer before I've setted a variable **nome**, but I can't succeed in it when the variable is yet undefined. My AIML is:

```
<category>
	<pattern>WHO AM I</pattern>
	<template>
		<condition name="nome">
			<li value="*">star</li>
			<li value="">empty string</li>
			<li value="undefined">Undefined</li>
			<li value="unknown">Unknown</li>
			<li>Your name is:  <get name="nome" /></li>
		</condition>
	</template>
</category>

```

The response to this stimulus when **nome** is not setted is always:
```
Your name is: undefined
```
any suggesestion?

**Comment by giuliopons** [comment]
I've checked not defined variable in this way, maybe it can help:

```
<category>
	<pattern>WHO AM I</pattern>
	<template>
		<condition name="nome">
			<li value="*">You are <get name="nome" /></li>
			<li>I don't know</li>
		</condition>
	</template>
</category>

```

**Comment by Program-O** [comment]
closing over 30 days without a response, please reopen if not resolved

**Comment by AlekzNet** [comment]
Yep, not resolved.

**Comment by Program-O** [comment]
As dave mentioned without a default option it will pick the last option..
are we saying that the correct aiml functionality is to display nothing?

**Comment by Dave-Morton** [comment]
to the best of my knowledge, the current behavior is correct. If anyone has a suggestion for a more appropriate action I'm all ears.

**Comment by AlekzNet** [comment]
I would say, that displaying nothing would be the best way. You can always add another `<li>` without a value. Actually, if there is no standard, it's all about the agreements, right?

If this construction does not work correctly:

```xml
<condition name="name5">
        <li value="yes">Yes</li>
        <li value="no">No</li>            
    </condition>
```
it can be rewritten to:

```xml
<condition name="name5">
        <li value="yes">Yes</li>
        <li value="no">No</li>
        <li></li>            
    </condition>
```

**Comment by Dave-Morton** [comment]
To my way of thinking, "saying" nothing would just come off as awkward. However, upon re-reading the [AIML 1.0.1 Specification](http://www.alicebot.org/TR/2001/WD-aiml/#section-condition), a blank string is actually _supposed_ to be returned when nothing matches, so this is something that should be addressed within the code.

**Comment by AlekzNet** [comment]
So, common sense wins ;)

**Comment by patrickschur** [comment]
I think I've solved the problem. :tada:  If someone else could test that, I would be very grateful. In `parse_aiml_as_XML.php` at line `944` I added an `else`:
```php
if (aiml_pattern_match($testVarValue, $test_value))
{
    runDebug(__FILE__, __FUNCTION__, __LINE__, 'Pick XML = ' . $pick->asXML(), 4);
    break;
}
else
{
    $pick = $pick->asXML();
}
```
and set the `$response` variable at line `980` to:
```php
$response[] = ''; // instead of $response = (string)$pick;
```
If you want to keep the current default behavior than let the variable untouched.
