### ISSUE TITLE
Tags in comments break processing

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#170]
Just noticed, that if you comment any tag, the processing is "broken". For example:

``` xml
<category>
<pattern>comment test</pattern>
 <template>Hellotest

<!-- here goes a long comment  with a tag <person/> -->

 </template>
</category>
```

The result:

User: comment test
Bot: I do not know what to say here

**Comment by Dave-Morton** [comment]
That's because that's not valid XML, so Program O doesn't know how to handle the situation. I'll have to put in some error checking for that situation to see what's going on. I'll let you know what I find.

**Comment by AlekzNet** [comment]
Actually, it is a valid XML, that passes the XML validation test ;)

**Comment by Dave-Morton** [comment]
While that may be true in the most esoteric sense, in the example you gave the `<person>` tag is still within a comment tag, so it wouldn't be parsed anyway. There *is* a bug in part of the script that's causing the execution to stop, and I've corrected that bug by adding functions that first disable, then re-enable the comment tags before putting in the required `<text>` tags that allow Program O to handle mixed content AIML. I've tested this and it now works, but the comment tags are ignored, and thus not parsed. This is as it should be.

**Comment by AlekzNet** [comment]
Wow! Great! That was quick! May I have the corrected version to test, please?

**Comment by Dave-Morton** [comment]
It's available now under the DEV branch. Simply download it from here at GitHub.

Please note that all bug fixes are enacted on the DEV branch, and kep there until the version is thoroughly tested and found to be stable. then we merge the changes and bug fixes back into the MASTER branch after careful review. So if you want to try the latest bug fixes and newest features, I recommend tracking the DEV branch.

**Comment by AlekzNet** [comment]
Hm... The latest updates break everything. Now I'm always getting "I do not know what to say here" to anything.

**Comment by Dave-Morton** [comment]
Very odd. Can you please provide information on the server that's running Program O so that I might test it with the same OS/server and PHP version?

**Comment by AlekzNet** [comment]
These are the errors I see:

09/26/2016 14:19:02 - PHP ERROR [Notice] -Undefined variable: unknown_inputs in  o/library/misc_functions.php on Line 177
-----------------
Exception Message:
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''
bad SQL encountered in file o/library/misc_functions.php, line #183. SQL:
insert into `db_aio`.`` (`id`, `bot_id`, `input`, `user_id`, `timestamp`) values(null, :bot_id, :input, :user_id, CURRENT_TIMESTAMP);
PDO Error:
Array
(
    [0] => 00000
    [1] => 
    [2] => 
)

STH Error:
Array
(
    [0] => 42000
    [1] => 1103
    [2] => Incorrect table name ''
)

Exception Message:
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

**Comment by AlekzNet** [comment]
The server is Ubuntu 16.04 + PHP 7.0.11 + MySQL 5.7.15

**Comment by AlekzNet** [comment]
-----------------------
26-09-2016 14:41:48.65687[0][1] - Elapsed time: 0.805 milliseconds
[conversation_start.php][Called outside of function][100]
Debug level: 1
session ID = gps824pg2m9flbm5vjpcpeu2m5 
-----------------------
26-09-2016 14:41:48.65883[1][1] - Elapsed time: 1.952 milliseconds
[intialise_conversation.php][load_that][662]
Inputs returned:Array
(
    [0] => hello
    [1] => test
    [2] => tictactoe
    [3] => test
    [4] => hi
    [5] => Hitest
    [6] => comment test
    [7] => show topic
    [8] => testbr
    [9] => comment test
)
 
-----------------------
26-09-2016 14:41:48.65885[1][1] - Elapsed time: 0.027 milliseconds
[intialise_conversation.php][load_that][664]
Responses returned:Array
(
    [0] => I do not know what to say here
    [1] => I do not know what to say here
    [2] => I do not know what to say here
    [3] => I do not know what to say here
    [4] => I do not know what to say here
    [5] => I do not know what to say here
    [6] => I do not know what to say here
    [7] => I do not know what to say here
    [8] => I do not know what to say here
    [9] => I do not know what to say here
)
 
-----------------------
26-09-2016 14:41:48.65986[0][4] - Elapsed time: 1.005 milliseconds
[conversation_start.php][Called outside of function][183]
Debug level = 1 
-----------------------
26-09-2016 14:41:48.65988[0][4] - Elapsed time: 0.025 milliseconds
[conversation_start.php][Called outside of function][185]
Debug level = 4 
-----------------------
26-09-2016 14:41:48.6599[4][4] - Elapsed time: 0.016 milliseconds
[intialise_conversation.php][add_new_conversation_vars][165]
New conversation vars 
-----------------------
26-09-2016 14:41:48.65991[2][4] - Elapsed time: 0.010 milliseconds
[intialise_conversation.php][push_on_front_convoArr][204]
Pushing 'TEST' to the front of the [user_say] array 
-----------------------
26-09-2016 14:41:48.65992[4][4] - Elapsed time: 0.010 milliseconds
[intialise_conversation.php][load_blank_array_element][59]
Loading blank user_say array 
-----------------------
26-09-2016 14:41:48.65993[2][4] - Elapsed time: 0.014 milliseconds
[intialise_conversation.php][push_on_front_convoArr][204]
Pushing 'TEST' to the front of the [input] array 
-----------------------
26-09-2016 14:41:48.65995[4][4] - Elapsed time: 0.012 milliseconds
[make_conversation.php][make_conversation][22]
Making conversation 
-----------------------
26-09-2016 14:41:48.65995[4][4] - Elapsed time: 0.007 milliseconds
[misc_functions.php][normalize_text][111]
Begin normalization - text = 'TEST' 
-----------------------
26-09-2016 14:41:48.65997[4][4] - Elapsed time: 0.017 milliseconds
[misc_functions.php][normalize_text][126]
Normalization complete. Text = 'TEST' 
-----------------------
26-09-2016 14:41:48.65998[4][4] - Elapsed time: 0.007 milliseconds
[find_aiml.php][get_aiml_to_parse][851]
Running all functions to get the correct aiml from the DB 
-----------------------
26-09-2016 14:41:48.6601[4][4] - Elapsed time: 0.126 milliseconds
[find_aiml.php][find_userdefined_aiml][807]
Looking for user defined responses 
-----------------------
26-09-2016 14:41:48.66012[3][4] - Elapsed time: 0.014 milliseconds
[find_aiml.php][find_userdefined_aiml][819]
User defined SQL: SELECT * FROM `db_aio`.`aiml_userdefined` WHERE
    `bot_id` = '1' AND
    (`user_id` = 'gps824pg2m9flbm5vjpcpeu2m5' OR `user_id` = '-1') AND
    `pattern` = 'TEST' 
-----------------------
26-09-2016 14:41:48.66118[2][4] - Elapsed time: 1.066 milliseconds
[find_aiml.php][find_userdefined_aiml][838]
User defined rows found: '0' 
-----------------------
26-09-2016 14:41:48.66121[4][4] - Elapsed time: 0.027 milliseconds
[find_aiml.php][find_aiml_matches][898]
Finding the aiml matches from the DB 
-----------------------
26-09-2016 14:41:48.66123[4][4] - Elapsed time: 0.025 milliseconds
[find_aiml.php][get_last_word][22]
Sentence: TEST. Last word:TEST 
-----------------------
26-09-2016 14:41:48.66124[4][4] - Elapsed time: 0.010 milliseconds
[find_aiml.php][get_first_word][35]
Sentence: TEST. First word:TEST 
-----------------------
26-09-2016 14:41:48.66134[4][4] - Elapsed time: 0.100 milliseconds
[find_aiml.php][find_aiml_matches][912]
Stored topic = 'test' 
-----------------------
26-09-2016 14:41:48.66136[4][4] - Elapsed time: 0.020 milliseconds
[find_aiml.php][make_like_pattern][47]
Making a like pattern to use in the sql 
-----------------------
26-09-2016 14:41:48.66138[4][4] - Elapsed time: 0.014 milliseconds
[find_aiml.php][make_like_pattern][48]
Transforming thatpattern: I DO NOT KNOW WHAT TO SAY HERE 
-----------------------
26-09-2016 14:41:48.6614[4][4] - Elapsed time: 0.022 milliseconds
[find_aiml.php][make_like_pattern][57]
word list:
Array
(
    [0] => I
    [1] => DO
    [2] => NOT
    [3] => KNOW
    [4] => WHAT
    [5] => TO
    [6] => SAY
    [7] => HERE
)
 
-----------------------
26-09-2016 14:41:48.66144[4][4] - Elapsed time: 0.044 milliseconds
[find_aiml.php][make_like_pattern][92]
returning like pattern:

  `thatpattern` like 'I % HERE' OR
  `thatpattern` like 'I %' OR
(`thatpattern` LIKE '% DO %') OR (`thatpattern` LIKE '% DO NOT KNOW WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% NOT %') OR (`thatpattern` LIKE 'I %') OR (`thatpattern` LIKE '% NOT KNOW WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% KNOW %') OR (`thatpattern` LIKE 'I DO %') OR (`thatpattern` LIKE '% KNOW WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% WHAT %') OR (`thatpattern` LIKE 'I DO NOT %') OR (`thatpattern` LIKE '% WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% TO %') OR (`thatpattern` LIKE 'I DO NOT KNOW %') OR (`thatpattern` LIKE '% TO SAY HERE' ) OR (`thatpattern` LIKE '% SAY %') OR (`thatpattern` LIKE 'I DO NOT KNOW WHAT %') OR (`thatpattern` LIKE '% SAY HERE' ) OR (`thatpattern` LIKE 'I DO NOT KNOW WHAT TO %') OR (`thatpattern` LIKE '% HERE' ) OR (`thatpattern` LIKE 'I DO NOT KNOW WHAT TO SAY %') OR  
-----------------------
26-09-2016 14:41:48.66146[4][4] - Elapsed time: 0.016 milliseconds
[find_aiml.php][wordsCount_inSentence][105]
Sentence: TEST numWords:1 
-----------------------
26-09-2016 14:41:48.66147[3][4] - Elapsed time: 0.014 milliseconds
[find_aiml.php][find_aiml_matches][972]
Core Match AIML sql: SELECT `id`, `pattern`, `thatpattern`, `topic` FROM `db_aio`.`aiml` WHERE
   bot_id = '1'  AND (
  `pattern` = '_' OR
  `pattern` = '*' OR
  `pattern` = 'TEST' OR
  `pattern` = 'RANDOM PICKUP LINE'
   OR 
  `thatpattern` like 'I % HERE' OR
  `thatpattern` like 'I %' OR
(`thatpattern` LIKE '% DO %') OR (`thatpattern` LIKE '% DO NOT KNOW WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% NOT %') OR (`thatpattern` LIKE 'I %') OR (`thatpattern` LIKE '% NOT KNOW WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% KNOW %') OR (`thatpattern` LIKE 'I DO %') OR (`thatpattern` LIKE '% KNOW WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% WHAT %') OR (`thatpattern` LIKE 'I DO NOT %') OR (`thatpattern` LIKE '% WHAT TO SAY HERE' ) OR (`thatpattern` LIKE '% TO %') OR (`thatpattern` LIKE 'I DO NOT KNOW %') OR (`thatpattern` LIKE '% TO SAY HERE' ) OR (`thatpattern` LIKE '% SAY %') OR (`thatpattern` LIKE 'I DO NOT KNOW WHAT %') OR (`thatpattern` LIKE '% SAY HERE' ) OR (`thatpattern` LIKE 'I DO NOT KNOW WHAT TO %') OR (`thatpattern` LIKE '% HERE' ) OR (`thatpattern` LIKE 'I DO NOT KNOW WHAT TO SAY %')
  ) AND `topic`='pantyhose' order by `topic` desc, `pattern` asc, `thatpattern` asc,`id` asc; 
-----------------------
26-09-2016 14:41:48.66158[1][4] - Elapsed time: 0.103 milliseconds
[find_aiml.php][find_aiml_matches][997]
Error: FOUND NO AIML matches in DB 
-----------------------
26-09-2016 14:41:48.6616[4][4] - Elapsed time: 0.025 milliseconds
[find_aiml.php][get_convo_var][729]
Get from ConvoArr [conversation][default_aiml_pattern][1][1] 
-----------------------
26-09-2016 14:41:48.66162[4][4] - Elapsed time: 0.017 milliseconds
[find_aiml.php][get_convo_var][758]
Get from ConvoArr [conversation][default_aiml_pattern][1][1] FOUND: ConvoArr Value = 'RANDOM PICKUP LINE' 
-----------------------
26-09-2016 14:41:48.66164[1][4] - Elapsed time: 0.026 milliseconds
[misc_functions.php][Called outside of function][177]
PHP ERROR [Notice] -Undefined variable: unknown_inputs in o/library/misc_functions.php on Line 177 
-----------------------
26-09-2016 14:41:48.66193[0][4] - Elapsed time: 0.286 milliseconds
[PDO_functions.php][db_write][158]
An error was generated while writing to the database in file o/library/misc_functions.php at line 183, in the function addUnknownInput - SQL:
insert into `db_aio`.`` (`id`, `bot_id`, `input`, `user_id`, `timestamp`) values(null, :bot_id, :input, :user_id, CURRENT_TIMESTAMP);
PDO error: Array
(
    [0] => 00000
    [1] => 
    [2] => 
)

PDOStatement error: Array
(
    [0] => 42000
    [1] => 1103
    [2] => Incorrect table name ''
)
 
-----------------------
26-09-2016 14:41:48.66195[1][4] - Elapsed time: 0.019 milliseconds
[find_aiml.php][find_aiml_matches][999]
Added input 'TEST' to the unknown_inputs table. 
-----------------------
26-09-2016 14:41:48.66205[1][4] - Elapsed time: 0.102 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][127]
Current THAT = I DO NOT KNOW WHAT TO SAY HERE 
-----------------------
26-09-2016 14:41:48.66207[4][4] - Elapsed time: 0.022 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][136]
NEW FUNC Searching through 1 rows to unset bad matches 
-----------------------
26-09-2016 14:41:48.66209[1][4] - Elapsed time: 0.014 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][142]
Returning error as no results where found 
-----------------------
26-09-2016 14:41:48.6621[4][4] - Elapsed time: 0.013 milliseconds
[find_aiml.php][score_matches][317]
Scoring the matches. 
-----------------------
26-09-2016 14:41:48.66231[4][4] - Elapsed time: 0.213 milliseconds
[find_aiml.php][score_matches][567]
Sorted array $allrows:
Array
(
    [0] => Array
        (
            [aiml_id] => -1
            [bot_id] => 1
            [pattern] => no results
            [thatpattern] => 
            [topic] => 
            [score] => 261
            [track_score] => current bot, no topic to match, no thatpattern to match, common word match: no, uncommon word match: results
        )

)
 
-----------------------
26-09-2016 14:41:48.66238[2][4] - Elapsed time: 0.063 milliseconds
[find_aiml.php][get_winning_category][687]
And the winner is... -1! 
-----------------------
26-09-2016 14:41:48.66246[4][4] - Elapsed time: 0.083 milliseconds
[find_aiml.php][get_winning_category][700]
Returning the AIML template for id# -1. Value:
'I do not know what to say here' 
-----------------------
26-09-2016 14:41:48.66249[4][4] - Elapsed time: 0.034 milliseconds
[find_aiml.php][get_highest_scoring_row][671]
Best Responses: Array
(
    [0] => Array
        (
            [aiml_id] => -1
            [bot_id] => 1
            [pattern] => no results
            [thatpattern] => 
            [topic] => 
            [score] => 261
            [track_score] => current bot, no topic to match, no thatpattern to match, common word match: no, uncommon word match: results
        )

)
 
-----------------------
26-09-2016 14:41:48.66251[2][4] - Elapsed time: 0.013 milliseconds
[find_aiml.php][get_highest_scoring_row][672]
Will use randomly picked best response chosen out of 1 responses with same score: -1 - no results 
-----------------------
26-09-2016 14:41:48.66252[4][4] - Elapsed time: 0.016 milliseconds
[find_aiml.php][get_aiml_to_parse][885]
Will be parsing id:-1 (no results) 
-----------------------
26-09-2016 14:41:48.66254[3][4] - Elapsed time: 0.013 milliseconds
[parse_aiml.php][parse_matched_aiml][190]
Run the aiml parse in normal mode (normal or srai) 
-----------------------
26-09-2016 14:41:48.66255[2][4] - Elapsed time: 0.011 milliseconds
[parse_aiml.php][set_wildcards][250]
Setting Wildcards 
-----------------------
26-09-2016 14:41:48.66257[2][4] - Elapsed time: 0.021 milliseconds
[parse_aiml_as_XML.php][parse_aiml_as_XML][22]
Parsing the AIML template as XML 
-----------------------
26-09-2016 14:41:48.66259[2][4] - Elapsed time: 0.017 milliseconds
[parse_aiml_as_XML.php][add_text_tags][87]
Adding some TEXT tags into the template, just because I can... 
-----------------------
26-09-2016 14:41:48.66268[4][4] - Elapsed time: 0.097 milliseconds
[parse_aiml_as_XML.php][add_text_tags][113]
Returning template:
<template><text>I do not know what to say here</text></template> 
-----------------------
26-09-2016 14:41:48.66282[2][4] - Elapsed time: 0.136 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][176]
Recursively parsing the AIML template. 
-----------------------
26-09-2016 14:41:48.66288[4][4] - Elapsed time: 0.058 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][183]
Processing element template at level 0. element XML = <?xml version="1.0"?>
<template><text>I do not know what to say here</text></template>

**Comment by AlekzNet** [comment]
Hi Dave, did you have a chance to look at it?

**Comment by Dave-Morton** [comment]
I did, but between work, school and broken vehicles I've not yet had time to test the fix to make sure it doesn't make more problems than it solves. I should have time for this either tonight after class, or in the morning.

**Comment by AlekzNet** [comment]
No worries! Thanks much for your hard work!

**Comment by AlekzNet** [comment]
Dave, could you please tell me the names of the file you suspect might cause the problem? I will try to replace them with the Master version. I hope it will not break anything else.

**Comment by AlekzNet** [comment]
This is fixed now! Thanks much Dave!

**Comment by Dave-Morton** [comment]
Glad to hear it. :)
