### ISSUE TITLE
Problem with <srai> and <star>.

### ISSUE THREAD

**Issue by jig4physics** [Program-O/Program-O#173]
&lt;category>

&lt;pattern>Wha is *&lt;/pattern>
&lt;template>&lt;srai>&lt;star/>&lt;/srai>&lt;/template>
&lt;/category>

&lt;category>
&lt;pattern>JVM&lt;/pattern>
&lt;template>&lt;srai> Answer for JVM &lt;/srai>&lt;/template>
&lt;/category>

As I have shown in above AIML code, if I search about "JVM" my robot will provide perfect Answer. But as if I ask  "What is JVM". this time Robot Reply: "I dint find any answer, I will get back to you as soon as I learn about it."

Here there may be recursion problem, can you suggest me what changes should I made? or is it possible what i am asking for?

**Comment by AlekzNet** [comment]
Most likely related to https://github.com/Program-O/Program-O/issues/172

**Comment by Dave-Morton** [comment]
This issue is exactly the same one as #172 and is being looked into, but I haven't had any time lately to test the solution that I have in mind for it. Please follow that thread for updates. Thanks.
