### ISSUE TITLE
Conversations aren't what I would expect.

### ISSUE THREAD

**Issue by silverark** [Program-O/Program-O#175]
I've installed Program-o and imported the AIML from here: https://github.com/fastcoding/aiml-en-us-foundation-alice.v1-6

I updated the Bot personality from the admin area then went to test the app with some strange Results:

```
chatbot: Hey!
User: Hello
EstyHi there!
User: What is your name?
EstyWhen do you think artificial intelligence will replace lawyers?
User: How old are you?
EstyLet me put it this way, Seeker. I am better now than I have ever been in my entire life up to this point.
User: What is the Date Today?
EstyThat is deep.
User: How are you?
EstyI always try to avoid conflict.
```

I've checked in the admin area under the "search/edit aiml" and "what is your name" is in there as a pattern. Am I missing a step in the basic set up?

**Comment by Dave-Morton** [comment]
Do you have debugging enabled? If so, note the conversation ID in the admin page's "Test your bot" link, then ask the question again. Then click on the "View the Debug Files" link, log in (it's the same credentials, but a separate login), and look for that conversation ID in the dropdown list. You can trace the program flow of that particular volley from there. It may give some insights as to what's happening. I've put in some "search keywords" into the debug file generation, and I think that the best one to use for what you're looking for is the word '*blue*". that should take you to the list of potential response candidates for the input given. 

One of the things I'll be working on for the next release (out in a few days, hopefully) will be the ability to download a given debug file (or a "profile" of a given debug file - long story) to make it easier to post here in the issues. I'm still working on that, though, and I have little time to work on it, so it's slow going.

**Comment by silverark** [comment]
I've explored and tested and can't quite make it out yet. It was ignoring the "winner" and just showing something fromthe RANDOM PICKUP LINE instead. So I changed the key for the random pick-up, and still got strange results.

I removed and imported the AIML files again, with the same results. Should I maybe use some other AIML files? I typed two questions and got he rather large 65k line debugging file below, I'm not sure if this makes any more sense to you?
[basic-search.txt](https://github.com/Program-O/Program-O/files/548219/basic-search.txt)

**Comment by Dave-Morton** [comment]
Can you please post the AIML category that you are expecting to match with the input "HOW ARE YOU", so that I can see what it looks like? the best way to do this is to go to Search/Replace, find the AIML category, then note the filename that was uploaded to include it in the database, then extract the entire AIML category from that file and paste it into your next post (just make sure to include 4 spaces at the beginning of each line so it shows up as code - otherwise it won't look right).

**Comment by Dave-Morton** [comment]
Actually, I took the time to create a new chatbot using the AIML files you've mentioned. I can see that several files (listed below) did not pass validation, and so were not uploaded:

+ ai.aiml
+ atomic.aiml
+ biography.aiml
+ client.aiml
+ default.aiml
+ money.aiml

While uploading, I noticed a couple of bugs that seem to have crept in, so I've put them on the ToDo list. They don't affect the uploading of files, but they still need to be addressed. :)

**Comment by silverark** [comment]
Thank you so much for your help. I think I've just worked out what reductions are, and that the things I was searching for simply weren't present. I've just worked out what the "that" bit is for too! Sorry I'm new to this.

I searching in the files for "what is your name" and couldn't find it anywhere, but the 'defaults.aiml' does contain 'what is your *' so I'm guessing it would have matched.

I'm guessing I need to clean up the files to get them to import?

```
grep "WHAT IS YOUR NAME" *
bot.aiml:<category><pattern>WHAT IS YOUR NAME AGAIN</pattern>
reduction3.safe.aiml:<category><pattern>WHAT IS YOUR NAME *</pattern>
reduction3.safe.aiml:<template><srai>WHAT IS YOUR NAME</srai></template>
reduction3.safe.aiml:<template><srai>WHAT IS YOUR NAME</srai></template>
reduction4.safe.aiml:<template><srai>WHAT IS YOUR NAME</srai></template>
reduction4.safe.aiml:<template><srai>WHAT IS YOUR NAME</srai></template>
reduction4.safe.aiml:<category><pattern>WHAT IS YOUR NAME</pattern>
reduction4.safe.aiml:<that>WHAT IS YOUR NAME</that>
that.aiml:<that>* WHAT IS YOUR NAME</that>
wallace.aiml:<template>No. <srai>WHAT IS YOUR NAME</srai>
```

**Comment by silverark** [comment]
I can see the validation issues. Would you like me to fix them and make a pull request on fastcoding/aiml-en-us-foundation-alice.v1-6

**Comment by Dave-Morton** [comment]
I've already got that part fixed, but it needs more testing. Also, there are several other things that I've been working on that aren't finished yet, and separating out the parts that need more work from the rest would be a long, painful process. I have class right now, but I'm free this evening, so I'll try to get them done for release tomorrow.

**Comment by silverark** [comment]
Great, thanks. It's a great project. Hopefully once I'm up to speed I can offer some assistance.

**Comment by Dave-Morton** [comment]
Help is always appreciated, of course. I'm in study hall, in between classes, so I have a few moments to respond. The issues that I'm currently working to correct are #149 , #170 , #172 , #173  and #174 . I'm also working on a few bugs that have no associated issues, and on a couple of features that will help. Additionally, I'm in the middle of writing a new wiki page that outlines how to read a Program O debug file, which I think will help botmasters to troubleshoot unexpected/blank responses.

**Comment by Dave-Morton** [comment]
Having just re-read one of your earlier posts, I realized that I misunderstood what you said, before. If you correct the AIML files' validation issues I think it would be a good idea to put in a pull request to the AIML repo. Just be sure to document the changes made in the pull request, as well as the reasons behind those changes.

In the meantime, I thought I would mention that I've added an option to skip XML validation for uploading AIML files, for situations where an AIML file contains custom or HTML tags, neither of which are "valid" AIML. I'll probably to add a further option to simply validate the files against generic XML, rather than the more strict AIML standard. The "skip validation" option will be in the next release, but the other option won't be any time soon, I'm afraid.

**Comment by silverark** [comment]
Thank you Dave, I've now made the XML changes and have made a pull request. Most were spelling mistakes such as 'peron' rather than 'person' or 'BR' rather than 'br', or the closing tags were in the wrong place.

There was only one that I wasn't sure about, where the following tag was used:
```
<get_likes/>
```
I simply changed the sentence structure to use 'star' instead.

**Comment by Dave-Morton** [comment]
That tag is AIML 0.9, and translates to `<bot name="likes"/>` in AIML 1.0 if memory serves. I should also point out that most HTML tags (`<br>, <p>, etc.`) aren't "valid" AIML, so would still cause those AIML files containing them to fail validation (which I think is just stupid, but I didn't write the schema file that Program O uses for validation), so it's a good thing that I've added the option to skip validation. :)

**Comment by silverark** [comment]
Thanks for the 'likes' info. I will change that back. 

The files seemed to validate successfully in Program-O. I'm wondering if it's because it's using the 1.0.1 namespace which seems to allow for XHTML, SMIL and XSL-FO. So BR failed, but br was accepted.

**Comment by AlekzNet** [comment]
Related issue: https://github.com/Program-O/Program-O/issues/164

**Comment by Dave-Morton** [comment]
Thanks for the reminder, @AlekzNet -  Please see my latest response in that issue. :)

**Comment by Dave-Morton** [comment]
I've just pushed the latest release to the DEV branch. Feel free to check it out at your convenience.

**Comment by AlekzNet** [comment]
Aha! Downloading....

**Comment by AlekzNet** [comment]
Yes! Looks great so far!

**Comment by Dave-Morton** [comment]
Let's give it a few days, then if it all looks good I'll close this issue.

**Comment by silverark** [comment]
Thanks Dave. I can confirm that conversations are great now that all the files have imported.

**Comment by Dave-Morton** [comment]
Sounds good! One less issue to deal with. :)
