### ISSUE TITLE
<topic> content is ignored -- Undefined offset: 1 in core/aiml/parse_aiml_as_XML.php 

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#178]
I've started getting lots of these errors recently:

10/31/2016 13:57:07 - PHP ERROR [Notice] -Undefined offset: 1 in ...chatbot/core/aiml/parse_aiml_as_XML.php on Line 260
10/31/2016 13:57:07 - PHP ERROR [Notice] -Undefined offset: 1 in ...chatbot/core/aiml/parse_aiml_as_XML.php on Line 1136

The result is the default answer even to the direct matches. Line 260 is this one:

```php
    $star = $convoArr['aiml']['stars'][(int) $index];
```
from 

```php
function parse_star_tag($convoArr, $element, $parentName, $level)
```
But the matches should be direct, without any stars. Looks like that something is stuck somewhere and does not get updated.

**Comment by AlekzNet** [comment]
I made some tests and discovered, that it happens within topics. As soon as I removed the `<topic>` tag, it started working as expected. It's quite a complex file with * and _ with `<that>` with stars, so that might explain why it goes to the `parse_star_tag` function.

**Comment by Dave-Morton** [comment]
@AlekzNet if you could please post the AIML category that you expect to have triggered, the one that actually got triggered, and an excerpt of the conversation that triggered the wrong response I'll try to replicate your results this evening, after class (but before I head out to go trick-R-treating)

**Comment by AlekzNet** [comment]
OK, looks like it the old issue. Everything within a topic gets ignored. Here's a test:

```xml
<topic name="test">

<category>
<pattern>Hitest</pattern>
 <template>Hellotest topic <get name="topic" /></template>
</category>


<category>
<pattern>*</pattern>
 <template>We are in the topic <get name="topic" />
 <think> <set name="topic"></set></think> 
 
 </template>
</category>

</topic>
```
When I type 'Hitest' I'm getting a default response. It was fixed before, but reappeared after the last changes.

**Comment by Dave-Morton** [comment]
We can blame that on Microsoft this time. A while back my dev box's Windows install rebooted on me while I was in the middle of working on a project for class, and I ended up losing not only a small amount of what I was working on, but also what I had on "the back burner", which happened to be Program O files. I ended up having to do a system restore, but the files were lost anyway. I must have replaced the corrupted files from the wrong backup. I'll sort it all out this evening, once I get back from scaring children. :-P

**Comment by Dave-Morton** [comment]
Meanwhile, look at the main search SQL query, to see if the TOPIC portion of the query includes ` OR \`topic\` = ''`

**Comment by Dave-Morton** [comment]
By the way, @AlekzNet if you use Skype, and are available, please feel free to add me to your contacts. Look for `GeekCaveCreations`

**Comment by AlekzNet** [comment]
This is what I found in find_aiml.php (line 932):

```php
      $topic_select = "AND (`topic`='$storedtopic' OR `topic`='')";
```

**Comment by AlekzNet** [comment]
Good idea, but I use Skype for business (aka Lync), which does not support "usual" Skype.

**Comment by FedgeNo** [comment]
That looks like unescaped data going into an SQL query to me. I haven't looked at the code preceding that but I sure hope you're not doing that.

**Comment by Dave-Morton** [comment]
It's only in appearance. The function that executes the query uses prepared statements, and the variable in question doesn't use tainted data (e.g. direct or unprocessed user data), so there's nothing to be concerned over there. User input is processed at least three times by that point. :-)

**Comment by FedgeNo** [comment]
So you are doing that. Damn. I have had this running on a production server for some time.

**Comment by Dave-Morton** [comment]
Referring to your post from 9 hours ago, how are you setting the topic? The AAA set (Annotated ALICE AIML Set) contains a category for setting the topic, but if you're not using that AIML set then something like this might work for you: (**NOTE:** From memory, so...)

````XML
<category>
  <pattern> LET S TALK ABOUT *</pattern>
  <template>
    <think><set name="topic"><star/></set></think>
    Sure! We can talk about <get name="topic"> if you like.
  </template>
</category>
````

**Comment by Dave-Morton** [comment]
@FedgeNo it sounds like you think that what's being done there is unsecure. If that's the case I can assure you that it's well guarded against all known (by me, at least) vectors of attack, including CSRF, injection,session hijacking and more. I'm extremely concerned about security, and while I freely admit I'm not the world's best PHP coder, I'm pretty darned good, and I try my best to keep up with the current state of security.

**Comment by AlekzNet** [comment]
It does not matter if the topic is set or not. Anything that placed between `<topic>` and `</topic>` gets ignored. Even simpler, this construction:

```xml
<topic name="test">
<category>
<pattern>Hitest</pattern>
 <template>Hellotest topic</template>
</category>
</topic>
```
gives me the default answer on 'Hitest'.

**Comment by Dave-Morton** [comment]
Does that category show up in the Search/Edit page? And if so, is the topic field properly set?

**Comment by AlekzNet** [comment]
No, I'm wrong. Probably, I do not understand the logic. Let's assume two scenarios:

o- The topic is unset
o- The topic is set to 'weather'

What should I get if I type Hitest?

On a side note: how can I 'unset'  the topic?

**Comment by Dave-Morton** [comment]
If the current topic for the chatbot is "weather", then your "test" topic response will not work. Unsetting the topic is simple, really. In any `<template>` tag, just use this:

`<set name="topic"></set>`

That sets the topic to an empty string, and also returns that same empty string, so the `<think>` tag isn't required.

**Comment by Dave-Morton** [comment]
As to the "logic" part, if there is no topic, or if the topic is set to something other than what is set for a given AIML category, that AIML category is never loaded into memory for scoring. However, if the current topic is the same as one for a given category (in this case, "test"), **OR** if the current topic is unset, then the category in question is pulled from the database so long as the pattern (and thatpattern, when applicable) and scored. If it's the highest scoring category, then it's selected. Otherwise it's tossed aside like so much left-over chow mein from last night's gaming rave. :-P

**Comment by AlekzNet** [comment]
In other words, it's not possible to get inside the topic without setting it first?

**Comment by Dave-Morton** [comment]
Exactly! Thus, the category that I posted a while ago.

It's also important to note that **ALL** topics need a "breakout" category, to be used to set the topic to either blank (as mentioned previously), or to change the topic to something else. If you don't have such a "breakout" category, you'll get stuck in a "topic loop", and the bot will talk about nothing else. Just thought you should know.

**Comment by AlekzNet** [comment]
Just tested - this is how it works:

o- If the topic is unset or set to a different name, I can't get into topic test.
o- if the topis is set to 'test', but there is no '*' category inside, no breakout is needed
o- if the topis is set to 'test and there is a '*' category inside, I can't get out without a break out.

**Comment by Dave-Morton** [comment]
Actually, based on the AIML 1.0 standard, the behavior in #1 is quite logical. If you're not within a given topic (e.g. the topic is currently blank, or set to something other than "test", in your example), then it should not be considered to be a potential response. Otherwise, what would be the use of setting a topic in the first place?

**Comment by AlekzNet** [comment]
I thought that `topic` is just another method to get a higher priority. So, if the topic is not set, the categories within topics would have the same priority. But hiding some parts makes more sense indeed.
