### ISSUE TITLE
Beginner question about the <that> tag usage

### ISSUE THREAD

**Issue by CViniciusF** [Program-O/Program-O#181]
Hi, i'm starting to work with bots and AIML language but i can't figure out why the tag <that> is not working in this context.

[question.txt](https://github.com/Program-O/Program-O/files/594700/question.txt)

When I input fine or not fine it triggers the default error response.
Can someone help me with this?
Thank you all.

**Comment by AlekzNet** [comment]
Please check this issue: https://github.com/Program-O/Program-O/issues/179

**Comment by CViniciusF** [comment]
@AlekzNet I already read that issue but I didn't understand many things about that. As I said I'm starting to learn about this language. Is there something wrong with the question file that I attached or it should work?

**Comment by AlekzNet** [comment]
First of all, please download the latest version of chatbot/core/aiml/find_aiml.php from the dev repository and try again. If it does not work, remove the punctuation symbols from '<that>'.

**Comment by CViniciusF** [comment]
@AlekzNet I removed the punctuation symbols as you said and it worked. 
Thank you for helping!
