### ISSUE TITLE
Is there a way to redirect by an user Input?

### ISSUE THREAD

**Issue by CViniciusF** [Program-O/Program-O#182]
Hi, I'm trying a way to redirect an user when he types something like "Redirect me to google.com", but I don't know how to do that, I tried to use the `<system>start "http://google.com"</system>` but it doesn't work.
Thank you again for helping!

**Comment by AlekzNet** [comment]
You can use JavaScript in the `<template>`. The tags are `<script>` and `</script>`.

**Comment by AlekzNet** [comment]
Something like:

```xml
<category>
<pattern>Something</pattern>
 <template>
 	<script language="JavaScript">	
	 	..... something here ...
 	</script>
 </template>
</category> 
```

**Comment by CViniciusF** [comment]
Ok, I didn't know that I could insert JavaScript, thanks for helping again.

**Comment by CViniciusF** [comment]
I tried as you said but when I upload the file I get this message 

> Error 1871: Element '{http://www.alicebot.org/TR/2001/WD-aiml}script': This element is not expected. Expected is one of ( {http://www.alicebot.org/TR/2001/WD-aiml}set, {http://www.alicebot.org/TR/2001/WD-aiml}think, {http://www.alicebot.org/TR/2001/WD-aiml}br, {http://www.alicebot.org/TR/2001/WD-aiml}get, {http://www.alicebot.org/TR/2001/WD-aiml}random, {http://www.alicebot.org/TR/2001/WD-aiml}li, {http://www.alicebot.org/TR/2001/WD-aiml}srai, {http://www.alicebot.org/TR/2001/WD-aiml}star, {http://www.alicebot.org/TR/2001/WD-aiml}a, {http://www.alicebot.org/TR/2001/WD-aiml}person ). in file:/C:/xampp/htdocs/Program-O-master/admin/
> on line 101

It's like this tag isn't suportted do you know why I get this error?

**Comment by Dave-Morton** [comment]
You're correct in that "official" AIML 1.0 doesn't support the `<script>` tag, but @AlekzNet committed some code to the latest version in the DEV branch to allow those tags to be considered valid, so it sounds like you may have an older version, or have downloaded your current version from the MASTER branch. Try downloading the latest from the DEV branch, and see if that works.

**Comment by CViniciusF** [comment]
@Dave-Morton Thank you. It works now.

**Comment by Dave-Morton** [comment]
Glad to hear it. If you have any other issues, please let us know.
