### ISSUE TITLE
can not login admin area

### ISSUE THREAD

**Issue by hotmic** [Program-O/Program-O#184]
after setup , i can not access admin area, and i tried to create another admin account, neither failed. why?

**Comment by Dave-Morton** [comment]
What message are you getting when you try to log in? Also, can you provide your system specs?

**Comment by hotmic** [comment]
dear sir, finally i login, but very slowly.  

btw, does it support other languages like Chinese?

**Comment by hotmic** [comment]
IIS+php5.5

**Comment by Dave-Morton** [comment]
Since you're using IIS, you're most likely running Windows, so the IIS and Windows versions would also be helpful.

Also, is it just slow to log into the admin page, or is everything slow (e.g. chatbot, admin login AND login features/functions)?

Lastly, Program O **does** support other languages, with Chinese (Big5) being one of the languages used in testing.

**Comment by hotmic** [comment]
only login admin and other admin funs very slow.  AIML chinese processsing i guess must add space between each Chinese character.

**Comment by malmestig** [comment]
hi
I've run into that as well with IIS and PHP, likely due to IPv6 and loopback address resolving. 
For me was solved by changing localhost to 127.0.0.1 in php.ini

**Comment by Dave-Morton** [comment]
@hotmic no, you should not have to space out every character in Chinese. Just use it as you would when writing (or typing) a letter in Chinese.

@malmestig you beat me to it, but that's what I would have suggested, as well. there are Windows tweaks that could also be used, such as disabling IPv6, but I don't like to suggest those except as a VERY last resort.

**Comment by Dave-Morton** [comment]
@hotmic have you tried the fix that @malmestig suggested? If so, please let us know if it worked. thanks.

**Comment by hotmic** [comment]
it is running ok without the fix

**Comment by Dave-Morton** [comment]
Good to hear. :)
