### ISSUE TITLE
install_programo.php problem

### ISSUE THREAD

**Issue by qaisarkk** [Program-O/Program-O#185]
I am using XAMPP to host the files. When I run the install_programo.php file. During second step I get error: 'Error trying to create aiml table' despite I have entered all correct database information. 
P.S I am using mySql Command line separately to create the database.

**Comment by Dave-Morton** [comment]
One of the bug fixes I've been working on actually addresses this issue (I __THINK__). Without a bit more information than what was provided, it's a little hard to be certain, though. Please download the latest version from the DEV branch (just updated a half hour ago) and try again. Let me know if that helped. Thanks.

**Comment by Dave-Morton** [comment]
No further information on this issue has been provided in over a month, so I'm closing it. If you have more information, please open a new issue. Thanks.
