### ISSUE TITLE
Split bot answer in 2 messages

### ISSUE THREAD

**Issue by CViniciusF** [Program-O/Program-O#189]
Hi, is there a way to split bot answer in 2 messages? 
For example, bot gives an answer to an user and then he asks if he was useful with that answer, but not in the same message.
Thanks for helping.

**Comment by AlekzNet** [comment]
You can add an `<srai>` to the first `<template>`.

**Comment by AlekzNet** [comment]
Something like:

```xml
<category>
<pattern>Hi</pattern>
 <template>Hello <srai>XUSE</srai></template>
</category>

<category>
<pattern>Bye</pattern>
 <template>Bye <srai>XUSE</srai></template>
</category>

<category>
<pattern>XUSE</pattern>
 <template><br />Was I useful?</template>
</category>
```

**Comment by Dave-Morton** [comment]
That's not actually a second response, to be honest. If you want to do something of that nature _within_ Program O, then the short answer is "no". However, if you're using the JSON interface, and using jquery to interact with Program O, you can use a bit of creative JavaScript to pull it off. The process is a bit more complicated than I have time to outline right now, but I'll try to show a workable example when I get done with class, in a few hours.

**Comment by CViniciusF** [comment]
First of all, thank you for your answers. I thought that I could make it using only AIML but I Am currently trying to figure it out with JavaScript using the Json interface. Also I'm trying to split the bot message in two when the answer is too big, I think that I'll be able to do this with Js just need more practice with the language. But again, thanks for your attention @Dave-Morton and @AlekzNet

**Comment by CViniciusF** [comment]
Also @Dave-Morton If you could show your example I would be thankful.

**Comment by AlekzNet** [comment]
>  Also I'm trying to split the bot message in two when the answer is too big,
@CViniciusF can use use `<br/>`? ;)

**Comment by CViniciusF** [comment]
@AlekzNet I am using <br/>  but I built an interface similar to a chatbox and using <Br/> the message stays in the same messsage.

**Comment by Dave-Morton** [comment]
@CViniciusF I haven't forgotten about you. It's just been a very stressful evening, and I'm just now getting back to my computer, just prior to finally heading to bed for a short nap. I'll get to this, I promise. :)

**Comment by Program-O** [comment]
Does this help?
https://jsfiddle.net/4rkbsyue/1/
This response is split in this example into sentances, you could change it to spilt on a char count.
I have also added your question "Is it helpful" on to the end

**Comment by Program-O** [comment]
oops sorry i didnt mean to close it!

**Comment by Program-O** [comment]
obviously though, if the user responded to 'is it helpful' the server backend doesnt know that the bot asked that question :(
