### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#191]
Just upgraded PHP to version 7.1 on Ubuntu 16.10, and now I'm getting WSOD on the Admin page and no response from the bot. Investigating...

**Comment by AlekzNet** [comment]
Error #1:

```txt
[08-Dec-2016 22:07:33 UTC] PHP Fatal error:  Cannot redeclare session_gc() in /home/user/public_html/ai/o/library/misc_functions.php on line 171
```

session_gc() is a PHP 7.1 function. Commenting out the entire function definition fixed the error.

**Comment by AlekzNet** [comment]
Error 3:

This one is a bit more tricky. I can't fix it without a proper investigation and I'm not familiar with the code:

```txt
[08-Dec-2016 22:22:24 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to handle_exceptions() must be an instance of Exception, instance of ParseError given in /home/user/public_html/ai/o/admin/index.php:479
Stack trace:
#0 [internal function]: handle_exceptions(Object(ParseError))
#1 {main}
  thrown in /home/user/public_html/ai/o/admin/index.php on line 479
# 
```

In index.php:

```php
  function handle_exceptions(exception $e)
  {
    global $msg;
    $trace = $e->getTrace();
    file_put_contents(_LOG_PATH_ . 'admin.exception.log', print_r($trace, true), FILE_APPEND);
    $msg .= $e->getMessage();
    return 'logout';
  }
```

**Comment by AlekzNet** [comment]
Not actually an error, but still looks strange:

```txt
[08-Dec-2016 22:09:50 UTC] PHP Notice:  A non well formed numeric value encountered in 
/home/user/public_html/ai/o/config/global_config.php on line 239
```

Line 239 is:

```php
 $mem_limit *= 1024;
```

hm...

**Comment by AlekzNet** [comment]
Error 2 is fixed by changing from

```php
function handle_exceptions(exception $e)
```
to

```php
function handle_exceptions($e)
```

**Comment by Dave-Morton** [comment]
Thanks for the info, @AlekzNet . Given that Program O uses custom session handling, instead of commenting out the function, we'll need to rename it, and reference the renamed function. 

With regard to the exception handler, I'm fairly sure that instead of this:

````php
function handle_exceptions(exception $e)
  {
    global $msg;
    $trace = $e->getTrace();
    file_put_contents(_LOG_PATH_ . 'admin.exception.log', print_r($trace, true), FILE_APPEND);
    $msg .= $e->getMessage();
    return 'logout';
  }
````

It should actually read this way:

````php
function handle_exceptions(Exception $e)
  {
    global $msg;
    $trace = $e->getTrace();
    file_put_contents(_LOG_PATH_ . 'admin.exception.log', print_r($trace, true), FILE_APPEND);
    $msg .= $e->getMessage();
    return 'logout';
  }
````

(note the capital 'E' in the word 'exception' in line 1)

I _could_ be wrong about this one, though. Some testing is in order.


As far as the notice about the 'not well formed' variable, that could be re-coded to be `$mem_limit = $mem_limit * 1024`, and that should clear that problem. I've got PHP 7.0.13(?) installed on an Ubuntu 14.04 VM, but I haven't really delved into it yet. I'll have to make a point of doing so during my winter break.

**Comment by AlekzNet** [comment]
> As far as the notice about the 'not well formed' variable, that could be re-coded to be $mem_limit = $mem_limit * 1024, 

But `*=` operator is not deprecated and works fine. I don't get it...

**Comment by AlekzNet** [comment]
> Given that Program O uses custom session handling, instead of commenting out the function, we'll need to rename it, and reference the renamed function.

session_gc() is empty in Program O anyway

**Comment by Dave-Morton** [comment]
Good point, but the current state of that function is only temporary. I simply haven't had the time to write a proper function for performing random garbage collection on the custom session files that Program O generates. It's not a difficult task to perform, but things have just kept getting in the way. School's out for me in a few days, so I'll have more time to work on some of this stuff, and it looks as if I _may_ be getting some help soon, but I'm not certain of that bit yet.

**Comment by AlekzNet** [comment]
``txt
[08-Dec-2016 22:09:50 UTC] PHP Notice:  A non well formed numeric value encountered in 
/home/user/public_html/ai/o/config/global_config.php on line 239
```

OK, this one is fixed by changing one line from

```php
  $mem_limit = str_replace($quantifier, '', $sys_mem_limit);
```
to

```php
  $mem_limit = str_replace($matches[0], '', $sys_mem_limit);
```

or the whole block:

```php

  $sys_mem_limit = ini_get('memory_limit');
  $quantifier = preg_match('~\D~', $sys_mem_limit,$matches);
  $quantifier = strtolower($matches[0]);
  $mem_limit = str_replace($matches[0], '', $sys_mem_limit);
```

Reason: If memory_limit is set to 128M, strtolower changes "M" to "m", hence it does not get replaced by str_replace.

**Comment by AlekzNet** [comment]
Yes, this one works :)
```php
function handle_exceptions(Exception $e)
```

**Comment by Dave-Morton** [comment]
We could also do away with the code that deals with memory management while we're at it. That was also a failed experiment, I'm afraid. I just never got around to removing it, since while it wasn't helping, it also wasn't hurting, either.
