### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#192]
This is not related to PHP 7.1, because I've seen this error before:

```txt
12/08/2016 23:28:38 - PHP ERROR [Notice] -Undefined offset: 1 in 
/home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml_as_XML.php on Line 699
12/08/2016 23:28:38 - PHP ERROR [Notice] -Undefined offset: 2 in 
/home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml_as_XML.php on Line 260
12/08/2016 23:28:38 - PHP ERROR [Notice] -Undefined offset: 1 in 
/home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml_as_XML.php on Line 260
12/08/2016 23:39:04 - PHP ERROR [Notice] -Undefined offset: 1 in 
/home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml_as_XML.php on Line 1136

```
When one of these errors appear in the error.log file, I'm getting either a weird answer (not from the default set) or no answer at all. Also it takes much longer to get an answer.

**Comment by Dave-Morton** [comment]
If memory serves, I've seen this before, but for the life of me I can't recall the details. I'm not in a position to dig into this right now, but I'll leave this page open, and make a note of looking into it in the morning.

**Comment by AlekzNet** [comment]
I noticed that it happens at a certain level of recursion. For the "standard" Alice set, the killing phrase is: "I'm fine, you?"  ;) 

It gets transformed into:
1) I M FINE YOU
2) I AM FINE YOU
3) my sign is (FINE *)   <- for some reason it picks up this line from the srai_lookup table (the first one)
4) FINE * <- for some reason it proceeds to recurse further
5)  *  <- on this `<sr/>` search it breaks



```txt
09-12-2016 21:12:56.43982[4][4] - Elapsed time: 0.018 milliseconds
[parse_aiml_as_XML.php][add_text_tags][113]
Returning template:
<template><sr/></template>
-----------------------
09-12-2016 21:12:56.43987[2][4] - Elapsed time: 0.047 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][176]
Recursively parsing the AIML template.
-----------------------
09-12-2016 21:12:56.43989[4][4] - Elapsed time: 0.020 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][183]
Processing element template at level 0. element XML = <?xml version="1.0"?>
<template><sr/></template>
-----------------------
09-12-2016 21:12:56.4399[4][4] - Elapsed time: 0.010 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][203]
function parse_template_tag does not exist. Parsing tag as text.
-----------------------
09-12-2016 21:12:56.43991[2][4] - Elapsed time: 0.012 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][176]
Recursively parsing the AIML template.
-----------------------
09-12-2016 21:12:56.43992[4][4] - Elapsed time: 0.012 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][183]
Processing element sr at level 1. element XML = <sr/>
-----------------------
09-12-2016 21:12:56.43993[4][4] - Elapsed time: 0.013 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][190]
Function parse_sr_tag does exist. Processing now.
-----------------------
09-12-2016 21:12:56.43994[4][4] - Elapsed time: 0.011 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][193]
Passing element sr to the parse_sr_tag function
-----------------------
09-12-2016 21:12:56.43996[4][4] - Elapsed time: 0.012 milliseconds
[parse_aiml_as_XML.php][parse_sr_tag][698]
Parsing an SR tag.
-----------------------
09-12-2016 21:12:56.43998[1][4] - Elapsed time: 0.021 milliseconds
[parse_aiml_as_XML.php][Called outside of function][699]
PHP ERROR [Notice] -Undefined offset: 1 in /home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml_as_XML.php on Line 699
```

From what I see it has something to do with how srais are searched in the srai_lookup table, but I might misunderstand something.

**Comment by Dave-Morton** [comment]
No, I don't think you are. The SRAI lookup table and search routines were an experiment in performance improvement that seem to be causing more trouble than they're worth, and I need to sit down and re-think the entire idea. It's entirely possible that I may have to scrap the plan for now, until I can come up with a better implementation.

**Comment by AlekzNet** [comment]
As far as I can see, there is no weight calculation for srai_lookup, the first matching entry is returned, right?

**Comment by Dave-Morton** [comment]
No there isn't. It's a straight up search for matching patterns, with the first found match being returned. The `<that>` tag isn't even taken into account (though I think in retrospect that this was a mistake). the idea was that if a match was found in the SRAI lookup table, then a full search of the main AIML table could be skipped, saving a __TON__ of time. But as time went on, problems were found (such as ignoring the `<that>` tag, and the improper handling of values for the `<star>` tag) that have proven to reduce, or even negate the performance benefits.

**Comment by AlekzNet** [comment]
Is it possible to bypass srai_lookup somehow for testing?

**Comment by Dave-Morton** [comment]
Sure, but I'd have to dig into the code to determine the best way to do so. The function is designed to run the full search in the event that no matches are found, so it may be best to just simulate an empty search result somehow. I'm working on one of my final projects for school, so I can't look into it right this second, but if you would like to give it a go, you can start in the function `run_srai()`, and go from there.

**Comment by Dave-Morton** [comment]
BTW, in case you (or anyone else) might be interested, I've been chronicling my progress with most of my classes at http://daveswnc.blogspot.com/ - Most of what I've posted about is work that I'm rather proud of, so I like "showing off". :)

**Comment by AlekzNet** [comment]
> you can start in the function run_srai(), and go from there.

Thanks! I commented out the whole lookup section and "something" started working and I did not notice any performance impact. 

However, the error persist. A simple construction: `So _` => `<sr/>` does not work:

```txt
    [user_say] => Array
        (
            [1] => SO WHAT NOW
            [2] =>
            [3] =>
            [4] =>
            [5] =>
            [6] =>
            [7] =>
            [8] =>
            [9] =>
            [10] =>
        )

)

-----------------------
10-12-2016 19:41:43.63815[2][4] - Elapsed time: 0.011 milliseconds
[parse_aiml.php][set_wildcards][290]
Checking 'SO (.*)' against 'So, what now?'.
-----------------------
10-12-2016 19:41:43.63823[2][4] - Elapsed time: 0.079 milliseconds
[parse_aiml.php][set_wildcards][304]
Something is not right here.
-----------------------
10-12-2016 19:41:43.63852[2][4] - Elapsed time: 0.289 milliseconds
[parse_aiml_as_XML.php][parse_aiml_as_XML][22]
Parsing the AIML template as XML
-----------------------
10-12-2016 19:41:43.63858[2][4] - Elapsed time: 0.060 milliseconds
[parse_aiml_as_XML.php][add_text_tags][87]
Adding some TEXT tags into the template, just because I can...
-----------------------

10-12-2016 19:41:43.63868[4][4] - Elapsed time: 0.106 milliseconds
[parse_aiml_as_XML.php][add_text_tags][113]
Returning template:
<template><sr/></template>
-----------------------
10-12-2016 19:41:43.63876[2][4] - Elapsed time: 0.080 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][176]
Recursively parsing the AIML template.
-----------------------
10-12-2016 19:41:43.6388[4][4] - Elapsed time: 0.039 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][183]
Processing element template at level 0. element XML = <?xml version="1.0"?>
<template><sr/></template>

-----------------------
10-12-2016 19:41:43.63882[4][4] - Elapsed time: 0.019 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][203]
function parse_template_tag does not exist. Parsing tag as text.
-----------------------
10-12-2016 19:41:43.63884[2][4] - Elapsed time: 0.021 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][176]
Recursively parsing the AIML template.
-----------------------
10-12-2016 19:41:43.63886[4][4] - Elapsed time: 0.014 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][183]
Processing element sr at level 1. element XML = <sr/>
-----------------------
10-12-2016 19:41:43.63887[4][4] - Elapsed time: 0.013 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][190]
Function parse_sr_tag does exist. Processing now.
-----------------------
10-12-2016 19:41:43.63888[4][4] - Elapsed time: 0.010 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][193]
Passing element sr to the parse_sr_tag function
-----------------------
10-12-2016 19:41:43.63889[4][4] - Elapsed time: 0.012 milliseconds
[parse_aiml_as_XML.php][parse_sr_tag][698]
Parsing an SR tag.
-----------------------
10-12-2016 19:41:43.63892[1][4] - Elapsed time: 0.029 milliseconds
[parse_aiml_as_XML.php][Called outside of function][699]
PHP ERROR [Notice] -Undefined offset: 1 in /home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml_as_XML.php on Line 699
```

The corresponding line 699:

```php
    $response = run_srai($convoArr, $convoArr['aiml']['stars'][1]);
```

The whole function:

```php
  /**
   * Parses the AIML <sr> tag
   *
   * @param array $convoArr
   * @param SimpleXMLElement $element
   * @param string $parentName
   * @param int $level
   * @return string
   */
  function parse_sr_tag($convoArr, $element, $parentName, $level)
  {
    runDebug(__FILE__, __FUNCTION__, __LINE__, 'Parsing an SR tag.', 4);
    $response = run_srai($convoArr, $convoArr['aiml']['stars'][1]);
    runDebug(__FILE__, __FUNCTION__, __LINE__, 'Finished parsing SR tag', 4);
    $response_string = implode_recursive(' ', $response, __FILE__, __FUNCTION__, __LINE__);
    return $response_string;
  }
```

**Comment by Dave-Morton** [comment]
>Checking 'SO (.*)' against 'So, what now?'.

That tells me that the function is checking against the unmodified user input (user_raw), rather than the __normalized__ value, which would be `SO WHAT NOW`. This will cause unforeseen failures to match, at the very least, and PHP notices about invalid RegEx patterns, at the worst (I _think_).

**Comment by AlekzNet** [comment]
What means, that something above does not place the `<star/>` into `$convoArr['aiml']['stars'][1]`

**Comment by AlekzNet** [comment]
> PHP notices about invalid RegEx patterns, at the worst (I think).

Aha, that might cause empty `$convoArr['aiml']['stars'][1]`

**Comment by AlekzNet** [comment]
No, I tried also `So, what now`, `so what now`, and `SO WHAT NOW`, the result is the same - empty answer.

**Comment by AlekzNet** [comment]
Scrap the last one. It was caused by a not finished AIML file. After I removed the srai_lookup part it looks better. 

But now I'm getting another error:

```txt
12/10/2016 21:17:25 - PHP ERROR [Notice] -Undefined variable: lookingfor in /home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml.php on Line 463
```

```php
      $allrows = get_highest_scoring_row($convoArr, $allrows, $lookingfor);
```

it's from `function run_srai(&$convoArr, $now_look_for_this)` 

But most likely it does not affect the logic. Checking further...

**Comment by AlekzNet** [comment]
So, do we agree to remove srai_lookup part? If yes, I will submit a pull request.

**Comment by Dave-Morton** [comment]
Perhaps we should comment it out for now, and look into how best to implement it, rather than remove it altogether. The concept is a sound one, but the implementation needs work.
