### ISSUE TITLE
<srai> inside of a <that> tag?

### ISSUE THREAD

**Issue by CViniciusF** [Program-O/Program-O#193]
A `<srai>` tag works inside a `<that>` clausule?
I'm trying to make larger contexts inside a conversation but i'm having trouble because I have some bot's answers that are too big to put inside `<that>complete` bot anwser `</that>` so I'm trying to do something like `<that><srai>abreviation</srai></that>.` But it seems like it's not working.
Thank you for helping as always.
Example:
```
<category>
    <pattern>DOSMTANSWER</pattern>
    <template>
      To do something you have to...
    </template>
</category>
<category>
    <pattern>HOW TO DO SOMETHING</pattern>
    <template>
      <srai>DOSMTANSWER</srai>
    </template>
</category>
<category>
    <pattern>Got it</pattern>
    <that><srai>DOSMTANSWER</srai></that>
    <template>
        That's good to hear.
    </template>
</category>
```
The example above works, but if I start a conversation with "Got it" bot will answer "That's good to hear."
Edit 2:
```
<category>
    <pattern>DOSMTANSWER</pattern>
    <template>
      To do something you have to...
    </template>
</category>
<category>
    <pattern>HOW TO DO SOMETHING</pattern>
    <template>
      <srai>DOSMTANSWER</srai>
    </template>
</category>
<category>
    <pattern>Got it</pattern>
    <that>TO DO SOMETHING *</that>
    <template>
        That's good to hear.
    </template>
</category>
```
With this code same thing happens.

**Comment by AlekzNet** [comment]
Can you use `*` in `<that>`? Something like:  `<that>here * that example of *</that>`?

**Comment by CViniciusF** [comment]
@AlekzNet I've edited the issue with an exemple for better understanding

**Comment by AlekzNet** [comment]
What you can do, is to put "Got it" inside a topic.

**Comment by CViniciusF** [comment]
> What you can do, is to put "Got it" inside a topic.
Can you show me an example?

**Comment by AlekzNet** [comment]
```xml

<category>
    <pattern>HOW TO DO SOMETHING</pattern>
    <template>
      <srai>DOSMTANSWER</srai>
      <think><set name="topic">howto</set></think>
    </template>
</category>

<topic name="howto">
<category>
    <pattern>DOSMTANSWER</pattern>
    <template>
      To do something you have to...
    </template>
</category>

<category>
    <pattern>Got it</pattern>
    <that><srai>DOSMTANSWER</srai></that>
    <template>
        That's good to hear.
        <think><set name="topic"></set></think>
    </template>
</category>

<category>
    <pattern>*</pattern>
    <template>
        <think><set name="topic"></set></think>
        <sr/>
    </template>
</category>

</topic>
```

**Comment by AlekzNet** [comment]
To be honest, I did not know that `<srai>` works inside `<that>` :)

**Comment by CViniciusF** [comment]
@AlekzNet Did you test the code you sent? I don't know why but it doesn't works here

**Comment by AlekzNet** [comment]
No, I did not ;) What does not work exactly?

**Comment by CViniciusF** [comment]
I get the default response when first input "how to do something"

**Comment by AlekzNet** [comment]
I edited the code 2 min after I posted. Please check the order in the 1st category:

```xml
      <think><set name="topic">howto</set></think>
      <srai>DOSMTANSWER</srai>
```

**Comment by CViniciusF** [comment]
Also, i don't know about this

> This is the expected behaviour. "That-matching" adds to the total score. If <that> does not match, but <pattern> does, the category will be chosen, provided there is no other category with a higher score.

Because I have clausules like 
`<category>
    <pattern>HOW TO DO SOMETHING</pattern>
    <template>
      To do something you have to... <br/>
      Did you get it?
    </template>
</category>
<category>
    <pattern>YES I GOT IT</pattern>
    <that>TO DO SOMETHING YOU HAVE TO DID YOU GET IT</that>
    <template>
      That is good to hear.
    </template>
</category>
<category>
    <pattern>NO I DON'T</pattern>
    <that>TO DO SOMETHING YOU HAVE TO DID YOU GET IT</that>
    <template>
      Oh that's bad.
    </template>
</category>`

And if I start the conversation by saying "Yes I got it" bot will anwser me the Default Response and not "That is good to hear".

**Comment by AlekzNet** [comment]
What happens if you replace your "thats" with 

`<that>TO DO SOMETHING YOU HAVE TO * DID YOU GET IT</that>`

or

`<that> * DID YOU GET IT</that>`

**Comment by CViniciusF** [comment]
@AlekzNet 

```
<category>
    <pattern>HOW TO DO SOMETHING</pattern>
    <template>
      To do something you have to... <br/>
      Did you get it?
    </template>
</category>
<category>
    <pattern>YES I GOT IT</pattern>
    <that>* DID YOU GET IT</that>
    <template>
      That is good to hear.
    </template>
</category>
<category>
    <pattern>NO I DON'T</pattern>
    <that>* DID YOU GET IT</that>
    <template>
      Oh that's bad.
    </template>
</category>
```

In this case, if I start the conversation with "Yes I got it" he will answer "That is good to hear." which is not what should happen.

**Comment by AlekzNet** [comment]
> if I start the conversation with "Yes I got it" he will answer "That is good to hear." which is not what should happen.

Yes, as I said this is how it should work. What happened with the "topic" solution? Did you check tghe order of "think" and "srai"?

**Comment by AlekzNet** [comment]
Also, I would remove the apostrophe in the last pattern:

```xml
<category>
    <pattern>NO I DON T</pattern>
```

**Comment by CViniciusF** [comment]
@AlekzNet I have to leave work now but I'll check again with the topic solution and talk to you if that works, when I first tryied it gave me the default response when I said "how to do something". But thank you for helping.

**Comment by Dave-Morton** [comment]
`<that>` tags cannot contain `<srai>` tags, I'm afraid. The only tag allowed within "pattern-side" tags (e.g. `<topic>`, `<pattern>` and `<that>`) is the `<bot>` tag. Even the template-side `<that>` tag cannot contain `<srai>`, but for a completely different reason. the template-side `<that>` tag is what's known as an atomic tag, which means that it cannot contain _any_ content. I'm sure that this isn't what you wanted to hear, but there it is.

**Comment by AlekzNet** [comment]
Apparently, it works, even if it should not ;)

**Comment by AlekzNet** [comment]
Yes, I've just tested the code I posted above with the validation turned off - IT WORKS! :D

**Comment by CViniciusF** [comment]
@AlekzNet but the behavior of a that clausule with srai inside is different. Seems like it ignores the that and give the answer even if it is out of contexto.

**Comment by CViniciusF** [comment]
@Dave-Morton A general question, is it someway possible to make the bot give an answer only if it is inside of a context?

**Comment by AlekzNet** [comment]
> Seems like it ignores the that and give the answer even if it is out of context.

@CViniciusF no, the code I posted works as I described. I've tried.

**Comment by Dave-Morton** [comment]
You know, that behavior is actually a bug, but I'm not sure I want to "fix" it. This is finals week in school, so I haven't any real time to address these issues at the moment, but I'll keep them visible, so that I can jump into them once classes are done.

**Comment by AlekzNet** [comment]
I would call it a very useful feature, not a bug ;) Also, it does not break anything.

**Comment by CViniciusF** [comment]
I guess that I was using `<that>` clausule when I was supposed to use Topic, but thanks @AlekzNet @Dave-Morton for always helping.

Ps; @AlekzNet With your topic example I could do what I was trying to.

**Comment by AlekzNet** [comment]
Great! ;)

**Comment by AlekzNet** [comment]
Do we want to make it official? If yes, I can tweak aiml.xsd ;)

**Comment by Dave-Morton** [comment]
Sure, @AlekzNet - Let's work on that. :)

**Comment by AlekzNet** [comment]
Done in https://github.com/Program-O/Program-O/pull/203 ;)

**Comment by AlekzNet** [comment]
I think this one can be closed.
