### ISSUE TITLE
Wrong URL for the API

### ISSUE THREAD

**Issue by razvanbolintis** [Program-O/Program-O#194]
I have installed the chatbot and when I want to test my bot I receive the following:
The URL for the API is currently set as:
http://172.18.30.13:899Program-O-masterhttp://172.18.30.13:899guihttp://172.18.30.13:899jquery.
Test this to make sure it is correct by clicking here. Then remove this message from gui/jquery/index.php And don't forget to upload your AIML files in the admin area otherwise you will not get a response!

How can I change the URL?
I have my virtual host at 172.18.30.13 on port 899

**Comment by AlekzNet** [comment]
Are you on the dev or the master branch?

**Comment by razvanbolintis** [comment]
master branch

**Comment by Dave-Morton** [comment]
@razvanbolintis take a look in GUI/jquery/index.php for the variable `$URL`. There is also internal documentation in that file that explains the process.

@AlekzNet it's fairly obvious from the URL @razvanbolintis posted that they were using the MASTER branch. Just sayin'. :P

**Comment by AlekzNet** [comment]
Actually not... Depends on the actual files. Bugs can be everywhere :D

For example, my admin panel shows "master", however it's dev.

**Comment by Dave-Morton** [comment]
That's because that's the default setting for the admin page, and must be manually changed. I was going by the folder name of "Program-O-master". If I recall correctly, downloading the zip file from the DEV branch ends up creating a folder name of "Program-O-dev", instead. It's been a while since I downloaded the zip from the DEV branch, so I could be wrong... :)

**Comment by AlekzNet** [comment]
> That said, however, someone could start out with the MASTER branch, then replace files in that folder from the DEV branch zip, so it's not 100%. ;)

My case exactly ;)

**Comment by Dave-Morton** [comment]
I think it's safe to say that this issue has been "dead" long enough to warrant closing. @razvanbolintis If more information becomes available, or you still have this problem, please let us know so that we can reopen it. Thanks.
