### ISSUE TITLE
Is not a number (<math>)

### ISSUE THREAD

**Issue by patrickschur** [Program-O/Program-O#202]
It looks like the `<math>` tag is not working correctly. I have the following code:
```xml
<category>
    <pattern>WAS IST * PLUS *</pattern>
    <template><math>ADD <star/> <star index="2"/></math></template>
</category>
```

Result:
User: was ist 20 plus 30
Bot: 50 (works as expected)

User: was ist 20 + 30
Bot: is not a number!

The first thing I thougt was that `normalize_text` doesn't work. But it looks like the error is somewhere else.

**Comment by Dave-Morton** [comment]
It looks as if the `+` symbol is not being converted to `ADD`. Let me look  to see what I can find.

**Comment by patrickschur** [comment]
I found an error (don't know it is related to this):
```text
PHP ERROR [Notice] -Undefined offset: 2 in /var/www/html/Program-O/chatbot/core/aiml/parse_aiml_as_XML.php on Line 311
```

**Comment by Dave-Morton** [comment]
It is. If you look in the debug file for that volley (you _DO_ have debugging set to show all and save it to a file, don't you?), you'll also find something that looks like this:

`Checking 'WHAT IS (.*) PLUS (.*)' against 'what is 6 + 4'. `

This is the crux of the problem. the script is checking against the raw (non-normalized) input, so the `+` symbol is not matching the word `PLUS`. Not quite sure how we're going to get around this unless an "edge case" provision is made within that particular function, and I'm loathe to do that unless there's no alternative.

**Comment by Dave-Morton** [comment]
Ok, I've decided to test the implementation of the "edge case" provision that I was thinking about, and it seems to work. In the file `chatbot/core/aiml/parse_aiml.php`, function `set_wildcards()`, line 287, I inserted the following code:

```php
    $user_raw = $convoArr['aiml']['user_raw'];
    $search = array ('+','-','*','/');
    $repl = array('PLUS','MINUS','TIMES','DIVIDEDBY');
    $user_raw = str_replace($search, $repl, $user_raw);
```

then replaced this line:

`$checkagainst = $convoArr['aiml']['user_raw'];`

with this one:

`$checkagainst = $user_raw`

This has the effect of taking the "raw" input, and only normalizing the math symbols, then checking against that, rather than the actual "raw" user input. It seems to work, but as I said, I'd much prefer to find a better way to do this. If you have a better solution I'm all ears. :)

**Comment by patrickschur** [comment]
Please have unstanding that I need some time to involve me into this project. :) Anyway is there any reason why the script is checking against the _RAW_ input? Why not use the `normalize_text` function? 
I replaced the line 332 in `chatbot/core/aiml/parse_aiml.php` to:

```php
$checkagainst = normalize_text($convoArr['aiml']['user_raw']);
```
It seems to work as well. Maybe this is a better solution?

**Comment by Dave-Morton** [comment]
The main reason for the script checking against the "raw" input is that by not doing so, some of the chatbot's response ends up being set to all uppercase for the `<star>` tags, which is undesirable. That problem was mentioned in a few issues ( #172 and #174 come to mind).

**Comment by patrickschur** [comment]
What is wrong with my solution?

**Comment by Dave-Morton** [comment]
I'll give you an example. Say you have the following AIML category:

```xml
<category>
  <pattern>AIML STAR TEST * * * *</pattern>
  <template>
    The stars are as follows:<br/>
    1: <star/><br/>
    2: <star index="2"/><br/>
    3: <star index="3"/><br/>
    4: <star index="4"/><br/>
    Does that help?
  </template>
</category>
```

And you enter the following text:

>AIML STAR TEST one two three four

The chatbot would output the following:

```
The stars are as follows: 
1: ONE 
2: TWO 
3: THREE 
4: FOUR 
Does that help?
```

This is an obvious problem, considering that all of the `<star>` tag replacements have been normalized. The output should instead look like this:

```
The stars are as follows: 
1: one 
2: two 
3: three 
4: four 
Does that help?
```

this is why the script can't check against the normalized input.

**Comment by patrickschur** [comment]
Yeah... I know... I have extended the function `normalze_text` to a new parameter:
```php
function normalize_text($text, $to_upper = true)
```
and replaced the line:
```php
$checkagainst = $convoArr['aiml']['user_raw'];
```
with this one
```php
$normalized_text = $to_upper ? _strtoupper($normalized_text) : $normalized_text;
```

Ta-da! It works :)

**Comment by patrickschur** [comment]
Yeah... I know... I have extended the function `normalze_text` to a new parameter:
```php
function normalize_text($text, $to_upper = true)
```
and replaced the line:
```php
$normalized_text = _strtoupper($normalized_text);
```
with this one
```php
$normalized_text = $to_upper ? _strtoupper($normalized_text) : $normalized_text;
```
now we can replace the line before:
```php
$checkagainst = $convoArr['aiml']['user_raw'];
```
with
```php
$checkagainst = normalize_text($convoArr['aiml']['user_raw'], false);
```

Ta-da! It works :)

**Comment by Dave-Morton** [comment]
Ah. That's one way to do it, certainly. Let me review this and compare your method to mine.

**Comment by Dave-Morton** [comment]
there are some other things in `normalize_text()` that should be made, so I think I'll go with your solution, along with making the improvements I'm thinking of.

**Comment by patrickschur** [comment]
What are you thinking about? :)

**Comment by Dave-Morton** [comment]
There are a __LOT__ of calls to `preg_replace()` that could be handled more efficiently, and some of the RegEx patterns are inefficient. Setting up a couple of arrays and making a single call to the function would make for cleaner code.

**Comment by patrickschur** [comment]
I've already thought about that too.

**Comment by Dave-Morton** [comment]
I sent you an email about this discussion. :)
