### ISSUE TITLE
Undefined Variable (Both Branches)

### ISSUE THREAD

**Issue by RumbleFrog** [Program-O/Program-O#204]
So, with certain responses, it returns nothing and logs this:

```
12/30/2016 03:57:40 - PHP ERROR [Notice] -Undefined variable: lookingfor in C:\xampp\htdocs\chatbot\core\aiml\parse_aiml.php on Line 527
[30-Dec-2016 03:57:40 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function _convert_case() in C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php:769
Stack trace:
#0 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php(228): parse_formal_tag(Array, Object(SimpleXMLElement), 'formal', 2)
#1 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php(1324): parseTemplateRecursive(Array, Object(SimpleXMLElement), 2)
#2 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php(515): tag_to_string(Array, Object(SimpleXMLElement), 'set', 1, 'element')
#3 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php(228): parse_set_tag(Array, Object(SimpleXMLElement), 'set', 1)
#4 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php(256): parseTemplateRecursive(Array, Object(SimpleXMLElement), 1)
#5 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml.php(549): parseTemplateRecursive(Array, Object(SimpleXMLElement))
#6 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php(805): run_srai(Array, 'call me *')
#7 C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_a in C:\xampp\htdocs\chatbot\core\aiml\parse_aiml_as_XML.php on line 769
```

Program O version:            2.6.3
  Server Software:              Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.13
  PHP Version:                  7.0.13
  OS:                           Windows NT
  OS Version:                   build 14393 (Windows 10)
  MySQL Version:                10.1.19-MariaDB
  Multi-byte functions enabled: true

**Comment by RumbleFrog** [comment]
Also, is there a list of AIML files I could download, some I have are either outdated or some tags aren't supported.

**Comment by AlekzNet** [comment]
Yep, this is what I noticed (mentioned in another issue) and currently tracing. But I see it in another file:

```txt
12/30/2016 03:40:25 - PHP ERROR [Notice] -Undefined variable: lookingfor in /home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml.php on Line 527
```

It happens here:

```txt
-----------------------
30-12-2016 03:40:25.63715[4][4] - Elapsed time: 1.203 milliseconds
[find_aiml.php][score_matches][603]
Sorted array $allrows:
Array
(
    [0] => Array
        (
            [id] => 615284
            [pattern] => COMPUTER
            [thatpattern] =>
            [topic] =>
            [aiml_id] => 615284
            [score] => 260
            [track_score] => current bot, no thatpattern to match, direct pattern match, direct word match: pantyhose
        )

)

-----------------------
30-12-2016 03:40:25.6372[1][4] - Elapsed time: 0.056 milliseconds
[parse_aiml.php][Called outside of function][527]
PHP ERROR [Notice] -Undefined variable: lookingfor in /home/user/public_html/ai/o/chatbot/core/aiml/parse_aiml.php on Line 527
-----------------------
30-12-2016 03:40:25.63737[2][4] - Elapsed time: 0.162 milliseconds
[find_aiml.php][get_winning_category][736]
And the winner is... 615284!
-----------------------
```

```php
function run_srai(&$convoArr, $now_look_for_this)
. . .

   //score the relevant matches
    $allrows = score_matches($convoArr, $allrows, $now_look_for_this);
    //get the highest
    $allrows = get_highest_scoring_row($convoArr, $allrows, $lookingfor);
```

`$lookingfor` is not defined anywhere indeed.

**Comment by RumbleFrog** [comment]
You want me to offload my database for you? Also, may I get some guidance to where I should get AIML from, most of them are incompatible.

**Comment by RumbleFrog** [comment]
And it start working randomly, prob another pattern. Still need to address this issue in case it happens again.

**Comment by Dave-Morton** [comment]
From the looks of it, the wrong variable was used, perhaps. Instead of `$lookingfor`, it probably should have been `$now_look_for_this`. I'll swap them and give it a try.

**Comment by patrickschur** [comment]
@RumbleFrog if you still looking for aiml files to download, please have a look at this sites (there are also some german files):
- [Alicebot](http://www.alicebot.org/aiml/aaa/)
- [Howie](https://github.com/linzhp/Howie/tree/master/standard)
- [Rosie](https://github.com/pandorabots/rosie/tree/master/lib/aiml)

**Comment by Dave-Morton** [comment]
You can also look at the files on [my downloads page](http://www.geekcavecreations.com/?downloads). I have a couple of AIML sets there, both Unicode and standard. Both have had their bugs and outdated tags fixed. There's also a file called Profanity.aiml that deals with users cursing. It's kind of funny if the user uses foul language too many times because the bot that uses this file in it's makeup will "kick" the user completely off the page, sending them to Google using the javascript call `location.replace()`, so there is no "back button". :D

**Comment by AlekzNet** [comment]
BTW, I can't prove yet, that the response is incorrect.

**Comment by Dave-Morton** [comment]
I haven't seen any unexpected responses yet, but I suppose it's still possible.

**Comment by AlekzNet** [comment]
Yes, I haven't seen any wrong results either.

**Comment by patrickschur** [comment]
I think this can be closed.

**Comment by Dave-Morton** [comment]
The "rule" is more or less to close after 30 days, and that hasn't passed yet. Another week won't hurt. :)

**Comment by Dave-Morton** [comment]
Ok, this is now old enough without new information to warrant closing.
