### ISSUE TITLE
user_id is always null

### ISSUE THREAD

**Issue by patrickschur** [Program-O/Program-O#212]
The title should already say everything.
Here is a small excerpt from my db_write.txt
```txt
Bad SQL encountered in file /var/www/html/Program-O/library/misc_functions.php, line #229. SQL:
INSERT INTO `test`.`unknown_inputs` (`id`, `bot_id`, `input`, `user_id`, `timestamp`) VALUES(null, :bot_id, :input, :user_id, CURRENT_TIMESTAMP);
PDO Error:
Array
(
    [0] => 00000
    [1] => 
    [2] => 
)

PDOStatement Error:
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'user_id' cannot be null
)

Exception Message:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null;
Parameters:
Array
(
    [:bot_id] => 1
    [:input] => 
    [:user_id] => 
)
```

**Comment by Dave-Morton** [comment]
Looking at the code, it seems that the variable `$user_id` may not have been set yet. If that variable were to be removed from the global scope assignment on line 963 of `find_aiml.php`, and the following line were added just after it:

`    $user_id = $convoArr['conversation']['user_id'];`

That should take care of the issue. I've been dealing with certain crises lately, so haven't been able to work on Program O at all these past few days. I don't see it getting any better over the next couple of weeks, but I'll keep watching here on GitHub for small, simple things that I can do.

**Comment by patrickschur** [comment]
I have made the change, but this brought nothing. The problem is still there.
