### ISSUE TITLE
Admin Account and Current bot

### ISSUE THREAD

**Issue by groupsgmail** [Program-O/Program-O#214]
How to make that one admin use only one bot?
For example the first user has opened  Bot ID 1 and can not discover Bot ID 2.
The second user Bot ID 2 opened and can not discover Bot ID 1.

**Comment by FedgeNo** [comment]
If you don't already have an idea of how the code for that sort of thing would work, your quickest option is probably to set up multiple installations of the software in different folders with different database configurations.

**Comment by Program-O** [comment]
good suggestion FedgeNo...

I am afraid it is beyond the scope of this Program O support to tell you how to go about altering the admin area at this level for this size of task.

If you want to try to do it yourself you need to 
* create a table to create a link between the user id and the bot id which they are allowed to see
* when the user logs on get a list of bots they are allowed to see
* store that list in a session
* refer to that list for every action that involves a bot id to see they are allowed
* e.g. show bot where bots are in my bot list 
* e.g. save bot only if bot is in my bot list

As you can probably tell this is a massive rewrite. So if you are looking at that list and thinking how do i do that? how do i do this?... the use FedgeNo's idea.
