### ISSUE TITLE
chat history

### ISSUE THREAD

**Issue by rupesh1910** [Program-O/Program-O#216]
![oie_ulrmsdu8nyly](https://cloud.githubusercontent.com/assets/15318452/22021827/42df982c-dce5-11e6-83ff-4b6104ae3280.png)
Hi there is no chat history where user can scroll and see his previous the chat get deleted.

**Comment by Program-O** [comment]
When the user sends an input to the bot Program O responds with the your input and the bot response.
You should be able to develop your own method of displaying the entire conversation in your application.
Or you could just query the db directly to get all the conversation logs for the chat

**Comment by Dave-Morton** [comment]
It's been over a month since anything was added here, so I'm closing this issue. If this is still a problem please create a new issue. Thanks.
