### ISSUE TITLE
AIML Issue with <that></that>

### ISSUE THREAD

**Issue by enriquo** [Program-O/Program-O#224]
Hi. I was doing some experiment with the <that></that> tag and I encoutered this **probably** bug, but maybe it's just me. I'm doing something wrong?
Because the problem is that every time, in every situation I type in ProgramO the word "NO" it gets me to this category, also if the bot hasn't said anything before! How it's possible? I deleted every other category in which the <pattern> was "NO", but nothing changed.

```
<category>
        <pattern>NO</pattern>
        <that>* IS YOUR NAME</that>
	<template>Ok, I will not save it as your name.</template>
</category>
```

Is this a known bug?

**Comment by AlekzNet** [comment]
`<that>`  simply adds a priority. If you want to exclude the `NO` category from picking up, you have to use `<topic>`.  See explanation here: https://github.com/Program-O/Program-O/issues/178

**Comment by Program-O** [comment]
closed as last response over 30 days ago
