### ISSUE TITLE
program o error message "somthing went wrong ! error :" in jquery bot

### ISSUE THREAD

**Issue by walide67** [Program-O/Program-O#226]
when i use j query version of program o bot ( "talt to your bot"in admin page) .. i get error message said "somthing went wrong ! error"
can you tell me please what's wrong 
i load one aiml file 
i see topic for change the $url variable .. for what ??

**Comment by walide67** [comment]
not the bot give me the response ... but response i dont wait it .. bot response me "indefined " i think the problem in when reseve the result i but in index.php 
`$.get('<?php echo $url ?>', formdata, function(data){
             
            document.getElementById('messages').innerHTML=("<span id=\"user_say\">Utilisateur </span> : "+message+"<br/><span id=\"bot_say\">Bot :</span> : "+data.botsay);
tell me where is the problem

**Comment by patrickschur** [comment]
For some inexplicable reason I have no idea what are you trying to say. :smile: 
Try to express yourself better and use fewer points. Please make a screenshot or copy and paste the error message. This is the only way I can help you.

Did you use the `master` or `dev` branch? Most of the bugs have been fixed in the `dev` branch.

**Comment by walide67** [comment]
i am sorry for my english hhh
ok i use master when i send a message to my bot give me a response 'undefined' 
my code "$.get('<?php echo $url?>',formdata,function(data){
            alert(data.botsay); 
            document.getElementById('messages').innerHTML=("<span id=\"user_say\">Utilisateur </span> : "+message+"<br/><span id=\"bot_say\">Bot :</span> : "+ data.usersay);
          })"

**Comment by Dave-Morton** [comment]
@walide67 Please read [*This Wiki Post*](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) in order to learn what sort of information you should provide in order for us to be able to help you better. Once we get this information then we can assist you with this problem. Thanks.

**Comment by patrickschur** [comment]
@walide67 As I can see you speak French. If you feel more comfortable try to explain your problem in french. I will see what I can do.

**Comment by Atanacius** [comment]
By the way, did you have curl PHP extension activated?

**Comment by Program-O** [comment]
reclosing ticket 
@Atanacius  i deleted your comment please open a new thread if you have an issue 
thanks :D
