### ISSUE TITLE
Vulnerability - Comparison operator (md5 Hashes)

### ISSUE THREAD

**Issue by patrickschur** [Program-O/Program-O#227]
I found a vulnerability, more or less. One of the issues is that the `chatbot/debug` and `logs` page is accessible for everyone. Now you have to login. Let's say you know the name of the admin (**possible!**) and the password is `Password147186970!` (wich is hashed to `0e153958235710973524115407854157`).

Of course you do not know the password. So you will use a standard phrase like this `240610708` which is also hashed to `0e462097431906509019562988736854`.

What happened now is unhappy, at line `76` the hashes will be compared:
```php
$pass = '0e462097431906509019562988736854'; // hash of "240610708"
$verify = '0e153958235710973524115407854157'; // from the DB (hash of "Password147186970!")
if ($pass == $verify) {
    // will be evaluated to true
    // because PHP convert the type to a scientific notation which is 0
}
```
And there are much more phrases out there...

To prevent this we can use the `===` identical operator and a more secure hash function.
I would suggest to use a function like `password_hash` but this required a PHP version greater or equal to 5.5.

**Comment by Dave-Morton** [comment]
Great catch, @patrickschur ! This is something that needs to be addressed, but I don't think that we should force users to upgrade their PHP version for this one issue when we can make some simple changes to correct it using code available in 5.3 - I'll look at the code and see if we can easily case the variables as strings and use the `===` operator to make sure that the variables are being compared properly.

**Comment by Dave-Morton** [comment]
I've managed to correct this in the following manner:

```PHP
    if ($row !== false)
    {
        $verify = (string) $row['password']; // cast the result as a string, just to make sure the comparison is properly made, later.

        if ($pass === $verify)
        {
            $_SESSION['isLoggedIn'] = true;
            header('Location: ' . _DEBUG_URL_);
        }
        else {
            $iframeURL = _LIB_URL_ . 'accessdenied.htm';
        }
    }
```
Please note the casting of the DB result to a string, in addition to the use of `===` for the comparison. This should eliminate the problem seen in the past.

**Comment by patrickschur** [comment]
Great! But we should also think about using a different hash function in a newer version of Program-O.
