### ISSUE TITLE
Using XML to send the conversation to a chat box on my dating site.

### ISSUE THREAD

**Issue by aarondwerner** [Program-O/Program-O#232]
I'd like to have the bot engage users on my site. My site is developed ontop of PHP and more specifically i'd like the bot to engage users via a chat box. My question is now that I've got the bot installed and functional, how do i integrate the API into the chat box. I can't find much documentation on Program-O.

**Comment by FedgeNo** [comment]
I've got quite an old version on my site but here's the JavaScript I wrote for that purpose. It's based on MooTools but if you're alright with JavaScript you might get some ideas from it.

https://fedgeno.com/assets/badbot.js

**Comment by FedgeNo** [comment]
Of course I am using JSON, not XML, as it's a lot simpler to use JSON when you're dealing with JavaScript.

**Comment by Dave-Morton** [comment]
@aarondwerner Have you looked at the XML GUI example that is provided? It provides a relatively simple means for obtaining XML data from the Program O API, though I think that the JSON GUI may well be the best method for integrating aan already existing website with Program O.

**Comment by patrickschur** [comment]
I just wanted to mention: Please **do not use** the XML GUI at this time. It is vulnerable via XSS:
```text
&lt;img src=x onerror=alert(1)>
```
and if you are using your own solution (`conversation_start.php`), please note that you are **not using** `urldecode` because the entire script is not safe against XSS attacks with double encoded strings. The string `%253Cscript%253Ealert%25281%2529%253B%253C%252Fscript%253E` would be accepted by the script. After the normalization it would be `%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E` and if you decode this you would get `<script>alert(1);</script>`.

**Comment by FedgeNo** [comment]
Getting a little off topic here but if the XML GUI can be accessed at a standard (relative to conversation_start.php, for instance) location and can't be completely disabled via configuration options if people directly hit that URL, it should be removed entirely until it's fixed.

**Comment by aarondwerner** [comment]
Alright. My site is my420match.com . Instead of building a page for a "chat box" to be built on, i'd like the bot to tie to a user profile and act as a person. Once a member of the site, you can message people through either a normal email-type message or a private chat message. In the database I can see chat conversations between users. So what I'm looking for is quite extensive and in-depth. This is why I was looking for documentation of any sort. Essentially I'd like the bot to engage users within 45 minutes of joining the site, would need to build logic into the software so that it knew which bot was located in correlation to the new user that it was targeting. .... Baby steps. First is to get the conversation piped into the chat box.

![image](https://cloud.githubusercontent.com/assets/19333530/23052747/f6199498-f490-11e6-8538-34d4db41303d.png)

**Comment by aarondwerner** [comment]
I have a plugin built into the site that automatically sends a message to new users as any profile that I dictate. So perhaps the code for this particular plugin can be dissected and provide information as to how the bot can be integrated that way.

Later down the road timers and logic could be built into the engagement of users.

**Comment by patrickschur** [comment]
@FedgeNo I just wanted to mention that. Sry for off topic. I haven't made any further investigations, but it looks like your `install_programo.php` script is accessible for everyone. Maybe you should change that. ;)

**Comment by Program-O** [comment]
Closing the last response is over 30 days old...
For future reference this question is outside the scope of the issues section of Program O, mainly because it does not deal with a bug specifically. Questions of this nature are best handled over at https://stackoverflow.com/search?q=%22Program-O%22
