### ISSUE TITLE
<star/> not functioning correctly

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#236]
I have tried some simple functions and the <star/> variable does not get set with any data on certain operations.

Here is the test using the current release.
 
<category><pattern>YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><star index="1"/></template></category>
<category><pattern>YOUR MY GENIE</pattern><template>It fills me with pride to be your genie.  </template></category>
 
Slow Putzo: your my genie i like you  <--- my input
Barbarella Genie: It fills me with pride to be your genie.  <--- bot response
 
It should do the srai and then come back and print the value in star which should be “I like you”
I have tried both <star/> and <star index="1"/>
 
What I was originally trying to do was this:
<category><pattern>YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><srai><star/></srai></template></category>
To process the two statements in the response.

Back in release 2.4.6 this worked somewhat different but still failed, so this bug has been around awhile.  In that release if you ended the first sentence with a period or any punctuation, the star variable would not be loaded, but if you did not use any punctuation it would not match on the following srai using the star/.  I mention this only to point out there has been a flaw in the code in this area for some time now.

I have not attempted to use the category where I do the sari using the star/ in version 2.6.4

Tom

**Comment by patrickschur** [comment]
Can you show use your code? I do not understand exactly what you are trying. Have you tried to use a whitespace between the `*`?

**Comment by tringate** [comment]
wow, it edited out all of the code I had posted.  Let me try this again.

Here is the test using the current release.
`<category><pattern>YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><star index="1"/></template></category>
<category><pattern>YOUR MY GENIE</pattern><template>It fills me with pride to be your genie.  </template></category>
`
Slow Putzo: your my genie i like you <--- my input
Barbarella Genie: It fills me with pride to be your genie. <--- bot response

It should do the srai and then come back and print the value in star which should be “I like you”
I have tried both `<star/> and <star index="1"/>`

What I was originally trying to do was this:
`<category><pattern>YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><srai><star index="1"/></srai></template></category>
`
To process the two statements in the response.

**Comment by tringate** [comment]
Oh, and yes, I have tried varying amounts of white space.

**Comment by tringate** [comment]
it sure is hard to get code to show up without it being really confusing.
Here is the first two categories in individual lines.

`
<category><pattern>YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><star index="1"/></template></category>
<category><pattern>YOUR MY GENIE</pattern><template>It fills me with pride to be your genie.  </template></category>

`

**Comment by tringate** [comment]
I'm having problems trying to enter code.
`<category><pattern>YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><star index="1"/></template></category>`
`<category><pattern>YOUR MY GENIE</pattern><template>It fills me with pride to be your genie.  </template></category>`

**Comment by patrickschur** [comment]
That's definitely a bug. Great work! :+1: I'll see what I can do to fix this.

**Comment by patrickschur** [comment]
I did a fast workaround for you. Looks like it works. But this needs some testing before I can start a pull request.

Go to the file `chatbot/code/aiml/parse_aiml.php` and change the line `290`:
```php
$convoArr['aiml']['stars'] = array();
```
to this line
```php
if (!isset($convoArr['aiml']['srai_input'])) {
    $convoArr['aiml']['stars'] = array();
}
```

**Comment by tringate** [comment]
I made the change and while it did make the simple example of code work, it has broken other things.

I have another category in my AIML that is now catching the input.  I will do my best to give you the related categories so you can see what might be going wrong now.

Here are the categories that I have dealing with this particular phrase.  You will notice I have changed it to now do two SRAI's to process the two statements contained in the input.
`<category><pattern>YOU ARE MY *</pattern><template>We are as one.  </template>`
`<category><pattern>* YOU ARE MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><srai><star index="2"/></srai></template></category>`
`<category><pattern>* YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><srai><star index="2"/></srai></template></category>`
`<category><pattern>YOU ARE MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><srai><star/></srai></template></category>`
`<category><pattern>YOU ARE MY GENIE</pattern><template><srai>YOUR MY GENIE</srai><srai><star index="2"/></srai></template></category>`
`<category><pattern>YOUR MY GENIE *</pattern><template><srai>YOUR MY GENIE</srai><srai><star/></srai></template></category>`
`<category><pattern>YOUR MY GENIE</pattern><template>It fills me with pride to be your genie.  </template></category>`

If I enter in the following input:
You are my genie. I own you.
I get the following reply:
Slow Putzo: you are my genie. I own you
Barbarella Genie: We are as one.
or
Slow Putzo: your my genie. I own you
Barbarella Genie: We are as one.

The above categories are not all in the same file in my AIML set.  the first one is a very old category that has been around for years and is in my "y.aiml" file.  The others are in my "new additions.aiml" file.

The response to "I own you" is:
Slow Putzo: i own you
Barbarella Genie: Are you my master?

and the response to "your my genie" is:
Slow Putzo: your my genie
Barbarella Genie: We are as one.
Before the change to the program-o code this response was:
"It fills me with pride to be your genie.  Are you my master?"

The correct response to "You are my genie. I won you."  should be
"It fills me with pride to be your genie.  Are you my master?"

As you can see, the change has affected several other category resolutions.

My AIML set uses this technique in many many different groups of categories.

It is how we handled multiple common sentences used in replies back when I was working with the A.L.I.C.E. foundation in 2001.

Is there an easy way to put multiple category groups into this system?  I had to do each line individually.

Tom

**Comment by Dave-Morton** [comment]
Just thought I'd toss out there that @tringate is a friend of mine, and long time user of Program O. He uses it as a sort of avatar controller for Second Life, and his AIML is rather complex as a result. This problem of his was also occurring, but with different slightly different symptoms, in version 2.4.6 so it may be that we're looking at different bugs in the two versions, but that have similar effects. I'm still hip-deep in baby dragons with school, so I haven't been able to look into it yet.

**Comment by tringate** [comment]
Patrick,
Ignore my last post.

The fix does appear to fix the problem.

I had to dump my AIML from program-o, and clear the SRAI lookup table, and then reload my AIML.

After doing that, all of the categories worked properly.

Slow Putzo: you are my genie. I own you
Barbarella Genie: It fills me with pride to be your genie. Are you my master?

This is what the results are with basically a fresh install using the AIML.

I would consider this bug fixed with this code change, but something else is wrong in that a fresh install was needed to actually correct the issue.

I do not know of any way to clear the SRAI table other than delete all AIML, then do the SRAI load wich results in zero  table entries, then reload the full AIML set again.

Humm, I have not reloaded the SRAI table either.  Let me quickly do that to make sure the bug stays fixed.

Ok, reloaded the lookup table and tested with this same phrase and with a different one to ensure it really is working.

Slow Putzo: your my genie, i like you
Barbarella Genie: It fills me with pride to be your genie. I like to make new friends.

This has checked many of the categories this bug affected and they all performed correctly.

Thanks for the comment Dave.  I think my testing of the big move forward from version 2.4.6 to 2.6.4 is going very well.

I have been testing many things, and so far only this one issue which I do consider a NEW issue has been found.

I should mention many things are working much better too.

Tom

**Comment by tringate** [comment]
Anyone who says the development team isn't fast needs to rethink that opinion.  This bug was fixed in a matter of a few hours with the code sent out for testing and verification.

**Comment by Dave-Morton** [comment]
@tringate You shouldn't have had to dump the AIML prior to running the SRAI lookup script. Program O clears that table before refilling it, so the dump/reload wasn't really necessary.

As far as posting multiple lines of code, you can use markdown to accomplish that. [This page](https://guides.github.com/features/mastering-markdown/) explains how to do that. :)

**Comment by patrickschur** [comment]
@tringate A lot has happened since I came into this project. I'm trying to bring fresh wind into the project. :smile:

**Comment by AlekzNet** [comment]
I edited the code a bit, looks better now ;)

**Comment by Dave-Morton** [comment]
Is this working now, Tom? ( @tringate )

**Comment by tringate** [comment]
Dave,

Yes, I used the revised code and patched my install of the 2.6.4 release and ran several tests to verify I could use two srai's in the response to respond to the two distinct sentences.  I did it with and without a period at the end of the first sentence and both worked just fine.  See the responses to both tests below:

 Slow Putzo: you are my genie I own you
Barbarella Genie: It fills me with pride to be your genie. Are you my master?

Slow Putzo: you are my genie. I own you
Barbarella Genie: It fills me with pride to be your genie. Are you my master?

I tried a few others I could remember that are in my AIML and they worked correctly too.

**Comment by Dave-Morton** [comment]
Great! I'm glad that this could be resolved.

**Comment by tringate** [comment]
@Dave-Morton  was it ok that I closed this issue?  That won't prevent it from being added to the next release will it?  I do not know what your procedures are in closing an issue.  Hope I didn't mess this up.

**Comment by Dave-Morton** [comment]
You're fine, Tom. An issue's status doesn't affect the code for the project at all, so it doesn't matter whether the issue is open or closed, from that standpoint. If the code is working for you without creating more bugs, then by all means, feel free to close the issue. 😄 - Otherwise, let it stay opened. We're all good here.

**Comment by tringate** [comment]
closed.
