### ISSUE TITLE
<set> email issues

### ISSUE THREAD

**Issue by brunogpires** [Program-O/Program-O#237]
Hello.

I'm not sure if this is due the recent merge ( which im using ), but whenever i make my bot learn an e-mail:

<set name="user_email"><star/></set>

The email seems to be stripped.. Perhaps it's related with some security fix.

Input:
brunopiresbr@gmail.com

Bot output:
brunopiresbr gmail com

**Comment by Dave-Morton** [comment]
Hi, Bruno.

Did it work in previous versions of Program O? Also, it would be great if you could provide a bit more information about the OS, server software and PHP versions, so that we might be able to duplicate the issue if necessary. Thanks.

**Comment by brunogpires** [comment]
Hello @Dave-Morton, thanks again for your fast reply.

Im not quite sure if it worked in the past ( sorry ).. My bot is under development yet, and i just came to this issue by now.

I couldn't find questions related to this issue on google ( or even related to people having issues to store emails on <sets> ), so i believe that this might be a timely problem.

I will keep looking for a fix, and let you guys know if i find something out. 

Regarding the informations you asked, i believe that phpinfo might do the job, right?

![image](https://cloud.githubusercontent.com/assets/25889121/23273953/c2216be4-f9df-11e6-95db-80ea4cbbd3fb.png)

**Comment by brunogpires** [comment]
I'll try to rollback my files, and see if it worked before..

**Comment by brunogpires** [comment]
Yeah, i rolled back the files, and still got the same issue. After a small research, i saw on botlibre that i should use a tag <denormalize> around a <star> tag, but this command is not known.

**Comment by Dave-Morton** [comment]
I've removed the image from your post for security reasons. While php_info() _does_ provide the necessary information, it ALSO provides information that could make your site more vulnerable to attack. It's best not to expose your website in that manner.

A better way to be able to provide the necessary information is to make sure that debugging is setup in Program O, and set to save files. Then post a debug file here (you can attach the log files to your post). The first entry in any debug file is a list of the system specifications. I wrote it that way to make it easy to obtain the needed data.

As far as the `<denormalize>` tag is concerned, it's not available in Program O yet because that's an AIML 2.0 tag, and Program O still only supports AIML 1.0. We're working on a newer engine that will have AIML 2.0 support, but that's a long way off still.

**Comment by brunogpires** [comment]
Thank you @Dave-Morton, it's a simple test server. Im uploading the log file.

There are several portuguese expressions, but in the end of the file you might see the issue happening. 

I thought it should be a simple issue, but seems like it's not. The question is, how come nobody ever suffered with this in the past?

Regarding the aiml 2.0, im aware that it's still far from us, but i'll be help help if possible =) 

[Debug.txt](https://github.com/Program-O/Program-O/files/797476/Debug.txt)

**Comment by Dave-Morton** [comment]
I think that it may be that nobody has suffered from this in the past because nobody has tried it in the past?

One thing that could be done to correct this issue is to create a parser for the `<denormalize>` tag. but that requires some skills and experience that most botmasters simply do not have.

**Comment by patrickschur** [comment]
@brunogpires Remove or comment out the lines `349` and `391` in `chatbot/core/aiml/parse_aiml.php` and line `133` in `library/misc_functions.php`. :grin:

**Comment by brunogpires** [comment]
@patrickschur Sadly this wont help, because the change made on normalize_text function, will impact in all sentences sent to the bot, making it not to remove punctuation even from non star tag sentences. 
But you gave me a place to start. Im trying to find a solution given the code structure, and will let you guys know when i find a way out =)

**Comment by patrickschur** [comment]
Surely it's not the best solution but it works. :stuck_out_tongue_winking_eye:

**Comment by brunogpires** [comment]
Im not sure if this solution impacts in other functionalities, but this is what worked to me:

parse_aiml.php [339]
if (preg_match_all("~$ap~siu", $convoArr['aiml']['user_raw'], $matches))

im appliying the match on the user_raw itself, instead the normalized text. That allowed me to skip any punctuation replaces comming in star tags, keeping the original behaviour and making it work exactly as i wanted.

I'd appreciate if you ( @patrickschur ) could give some advice regarding this change.

**Comment by patrickschur** [comment]
> Im not sure if this solution impacts in other functionalities, but this is what worked to me

Yes it does. This will break the functionality of many tags (get, set, srai, star etc.). How did you get it running?
