### ISSUE TITLE
Feature request/improvement for AIML validation

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#240]
This is actually two items but they concern the same function within program-o.

The first is to have program-o automatically add "custom tags" to the AIML validation checking.  I do not know what is needed to properly check a custom made tag, but to ignore the check is not a desirable thing if you happen to use custom tags throughout your AIML set. 

My AIML set has over 12,000 categories and is contained in 67 individual files.  Only 6 files do not have custom tags in them.  Since I normally make edits to many files during an edit session and then load them all as one single zip file I really never do a validity check.  I am sure there are some errors and I know for a fact there are many duplicates.  I accidentally run across them all the time.

The second is to add the flagging of duplicate matching AIML categories during the validation.

I know Dave is considering adding the ability for program-o to remember what box has been checked in the upload window which would remove the annoyance of getting validation errors if you forget to check the box to ignore them and you have custom tags.  That is certainly a good idea, and probably very easy to do, so I hope my suggestion to add these two additional functions to the validation check does not hinder that implementation.

**Comment by Dave-Morton** [comment]
Both of those are good ideas, Tom. I'll add them to the ToDo list.

**Comment by Shaolinshifu** [comment]
Is there any way to make bot chat facebook with programO, sir?

**Comment by AlekzNet** [comment]
@tringate All currently supported by ProgramO custom tags (like wiki, math, etc) should validate properly. Or did you create your own custom tags, that do not come with ProgramO?

**Comment by Dave-Morton** [comment]
He's created several, actually. @tringate uses Program O as a special controller for NPC's in Second Life.

@Shaolinshifu It's certainly possible, but that is outside the scope of the project. there are several resources available for using the Facebook API, so it shouldn't be all that difficult to set something up. Also, your question is not related to this issue, so I encourage you to start a new issue when you have a question that isn't related to the issue being discussed. Thanks.

**Comment by tringate** [comment]
Yes, I have created my own.  I have rewritten the math to include compare, as well as:
    function parse_math_tag($convoArr, $element, $parentName, $level)
    function parse_getgenie_tag($convoArr, $element, $parentName, $level)
    function parse_setgenie_tag(&$convoArr, $element, $parentName, $level)
    function parse_getavie_tag($convoArr, $element, $parentName, $level)
    function parse_setavie_tag(&$convoArr, $element, $parentName, $level)

Not sure if the valid tags are in some table or list but wherever they are maybe the "addons" folder could be scanned by the validity checker and add any custom tags found there.  My file is called:
parseGenieTags.php
and is in a folder within addons called:
genie_tags

The math tag does not throw an error since been commented out in the custom_tags folder.

The get and set tags follow the exact same syntax as the base get and set tags.

My custom tags are made so I can use a single AIML set to function as individual bots for each avatar and NPC in the opensim program.

**Comment by AlekzNet** [comment]
@tringate can you add your tags to the ProgramO dev branch and let me know what they are? I will update the schema.

**Comment by AlekzNet** [comment]
I mean if you think that your new tags can be useful for anybody else, of course ;)

If not, I will post what needs to be added here.

**Comment by tringate** [comment]
@AlekzNet  I doubt they would be of much help to anyone unless they were implementing the entire system both in opensim and program-o.  I have been chatting with Dave and asked him if it was possible to put my entire project into github.  He offered to help me set that up.

I have heard about "schema" but really do not understand exactly what that is.  As for posting to the development branch, I do not have a clue how to do that.

I would be very happy to edit any files on my own to let the validation routines work with my additions.  As a thought, would it be possible for people who do add custom tags to somehow put the schema information into the addon php file itself?

**Comment by AlekzNet** [comment]
OK, it's not that difficult. What you need is to edit admin/aiml.xsd file and search for `<wiki>`, that will give you some hints. 

Add your new tag in this section (copy the wiki line and replace witki with your tag:

```xml
. . .
<xs:complexType name="Flow" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
       <xs:group ref="aiml:inline"/>
. . .
         <xs:element ref="aiml:wiki"/>
. . .
    </xs:choice>
  </xs:complexType>
```

and create the description of the new tag (copy everything and replace wiki with your tag:

```xml
  <xs:element name="wiki">
    <xs:complexType mixed="true">
       <xs:complexContent>
        <xs:extension base="aiml:Flow">
        </xs:extension>
    </xs:complexContent>
    </xs:complexType>
  </xs:element>
```

Unless your tags are very special, this should work in 98% cases.

**Comment by tringate** [comment]
@AlekzNet  I modified the file and now the validation function is checking all of my AIML.  It was a good thing, because I found maybe a couple dozen bad AIML categories.

Thanks for the information.

**Comment by AlekzNet** [comment]
Good! ;)
