### ISSUE TITLE
i am new with aiml 

### ISSUE THREAD

**Issue by walide67** [Program-O/Program-O#241]
hello 
i want to understand the deference between the two wildcard _ and * 
thanks

**Comment by AhilJose** [comment]
I would like to add some sentence of AIML documentation:

> The AIML vocabulary consists of words, spaces and the special characters “*” and “_”, known as wildcards. Wildcards are used to replace a string (words or sentences). The AIML interpreter gives higher priority to categories containing patterns that use the wildcard “_” than “*”. Then, the categories with the wildcard “_” are analyzed first.
>  In this case, the name informed by user in the sentence “MY NAME IS *”, Line 2, is identified by “*” wildcard. After this, in Line 4 the <set name= “nameUser”> <star/> </set> command stores, in the variable nameUser , the text captured by the <star/> command , which in this example is the name of the user. 
> ```
> 1.<category>
> 2.     <pattern> MY NAME IS * </pattern>
> 3.     <template>
> 4.         Hello <set name="nameUser"> <star/> </set>
> 5.     </template>
> 6.</category> 
> ```
The wildcard "_" matches user input keywords with this. No matter how many or what it is !!!!

Hope you understand.

**Comment by AlekzNet** [comment]
`_` has the highest priority, even if you have a direct match. For example:

```xml
<category>
     <pattern>_</pattern>
     <template>
         First match
     </template>
</category> 

<category>
     <pattern>Hello</pattern>
     <template>
         Second match
     </template>
</category> 

<category>
     <pattern>*</pattern>
     <template>
         Last match
     </template>
</category> 
```

**Comment by Dave-Morton** [comment]
In @AlekzNet example, only the first pattern will ever be matched. the `_` wildcard is very powerful, and will cause unexpected results if not used properly. there are _other_ conditions that apply, such as `TOPIC` and `THAT` tags, so the `_` wildcard is __NOT__ absolute, but the `_` wildcard also applies to these other tags as well, so this AIML category:

```XML
<topic name="_">
    <category>
        <pattern>_</pattern>
        <that>_</that>
        <template>This will <strong>ALWAYS</strong> match!</template>
    </category>
</topic>
```

Will catch every possible user input. Obviously, this is not desired, so I again urge caution when using the `_` wildcard. Just sayin'.

**Comment by walide67** [comment]
ok understand ... thanks for all :) <3

**Comment by walide67** [comment]
hello for all
please tell me how i tech my bot how to answered the yes or no question with aiml
e.g :
bot : do you understend
if human set yes there are a answer else if set no there are another answer
thank you

**Comment by Dave-Morton** [comment]
The answering of a "yes or no" question requires context, so that the bot knows what the answer relates to. This requires the use of the `<that>` tag. Here's an example that includes the "original" question:

```xml
<category>
    <pattern>*</pattern><!-- the pattern here is unimportant for this situation. set it as necessary -->
    <template>Do  you like pizza?</template>
</category>

<category>
    <pattern>YES</pattern>
    <that>DO YOU LIKE PIZZA</that>
    <template>I like it, too.</template>
</category>

<category>
    <pattern>NO</pattern>
    <that>DO YOU LIKE PIZZA</that>
    <template>Really? It's one of my favorite meals.</template>
</category>
```

This is how the chatbot needs to be programmed for every "yes or no" question it asks. Without this type of programming, the chatbot won't know what the answer given by the user relates to. Yes, this means a __LOT__ of work, but this is the way it needs to be done to give the user a good experience.

**Comment by walide67** [comment]
than you dav 
i do this but the progra o give me the default answer " no aiml or category .... "  ... my code with french
```
`<category>
<pattern>ok</pattern>
<template>Je suis à votre service à tout moment vous voulez, Avez-vous une autre question ?</template>
</category>
<category>
<pattern>oui</pattern>
<that>Je suis à votre service à tout moment vous voulez, Avez-vous une autre question ?</that>
<template>
quelle est ta question ??!
</template>
</category>
<category>
<pattern>no</pattern>
<that>Je suis à votre service à tout moment vous voulez, Avez-vous une autre question ?</that>
<template>
ok, Merci d'avoir parlé avec moi 
</template>
</category>`
```

**Comment by AlekzNet** [comment]
I would remove all punctuation symbols from `<that>`

**Comment by walide67** [comment]
it is work now thank you @AlekzNet  and thanks to all

**Comment by Dave-Morton** [comment]
You have punctuation in your patterns, primarily in your `<that>` patterns. That punctuation must be removed before it will work. None of the input pattern tags (`<pattern>`, `<that>` or `<topic>` are allowed to have any sort of punctuation at all. Fix those problems and try it again.

**Comment by Dave-Morton** [comment]
lol it seems that my page had not totally updated, so I didn't see Alekz' reply. Good call, @AlekzNet !

**Comment by AlekzNet** [comment]
:)
