### ISSUE TITLE
aiml and javascript

### ISSUE THREAD

**Issue by walide67** [Program-O/Program-O#242]
hello everyone ... how are you today ??
i want today to get information from database use ajax ( javascript and php ) 
and display the result into the temblate of bot this is my script 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<aiml>
<category>
<pattern>
je recherche *
</pattern>
<template>
<think>
<set name="mot"><star/></set>
</think>
<script language="JavaScript">
var mot='<get name="mot"/>';
var data="mot="+mot;
if (window.XMLHttpRequest)
{ 
    xhr = new XMLHttpRequest();    
} 
else  if (window.ActiveXObject)   
{
    xhr = new ActiveXObject("Microsoft.XMLHTTP");
}
 xhr.onreadystatechange  = function() 
    { 
       if(xhr.readyState  == 4)
       {
        if(xhr.status  == 200){ 
            
			document.write("there are : "+xhr.responseText);
		}	 
        
    }else{ 
           alert("Error code "+xhr.status);
        }
}
xhr.open( "POST", "http://localhost/site/recherche_bot.php",  true); 
   xhr.send(data);   
</script>
</template>
</category>
</aiml>
```

**Comment by patrickschur** [comment]
S'il vous plaît répondre à nos questions avant de vous causer constamment de nouvelles questions.
Et quel est exactement votre problème? Et ne pas écrire simplement votre code.

Please answer our [questions](https://github.com/Program-O/Program-O/issues/226) before you constantly cause new issues. And what exactly is your problem? Please describe it and do not just post your code. :pray: 
I can not figure out what is wrong if I only have the code.

**Comment by walide67** [comment]
my code not give me a result the answer of bot is empty .... if i have misteks or problems in my code tell me please

**Comment by AlekzNet** [comment]
Most likely the script does not know where to document.write. I would create an HTML element with a id tag (e.g. `<div>`), and tell the script to replace the content of this tag.

**Comment by Dave-Morton** [comment]
More that that, I would put the bulk of the JavaScript into the HTML of the interface as functions and just put JavaScript function calls into the AIML. This is much more efficient, and conserves both browser resources and typing.

**Comment by AlekzNet** [comment]
Yes, this is what I did ;)

**Comment by walide67** [comment]
ok ... how i can get the value of aiml variable and put it into javascript variable
e.g (in my code i put ):
<template>
<think>
<set name="word"><star/></set>
</think>
<script language="JavaScript">
var word='<get name="word"/>';
</script>
</template>
put it dont work .. i get nothing ???

**Comment by Dave-Morton** [comment]
Take a look at the following AIML category. It more accurately shows what happens:

```xml
<category>
    <pattern>JAVASCRIPT TEST *</pattern>
    <template><think><set name="test"><star/></set></think>
        Sending <star/> to JavaScript.
        <script language="JavaScript">
            var test1 = '<get name="test"/>';
            var test2 = '<star/>'; 
            console.log('test1 =', test1, ', test2 =', test2);
        </script>
        Test complete. Check the console log.
    </template>
</category>
```
When you add this to your bot and then enter `javascript test foo` into the chatbot's interface, you should get the following in your JavaScript console:

`test1 = <get name="test"/> , test2 = foo`

This is certainly unexpected, and is therefore a bug, but it's an odd one. I've added some diagnostic code to the script and the following output was generated to describe the template's XML code:

```
09-03-2017 07:52:08.80508[2][4] - Elapsed time: 0.066 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][204]
Current XML:
SimpleXMLElement Object
(
    [think] => SimpleXMLElement Object
        (
            [set] => SimpleXMLElement Object
                (
                    [@attributes] => Array
                        (
                            [name] => test
                        )

                    [star] => SimpleXMLElement Object
                        (
                        )

                )

        )

    [text] => Array
        (
            [0] => Sending 
            [1] =>  to JavaScript.
            [2] => Test complete. Check the console log.
        )

    [star] => SimpleXMLElement Object
        (
        )

    [script] => SimpleXMLElement Object
        (
            [@attributes] => Array
                (
                    [language] => JavaScript
                )

            [text] => Array
                (
                    [0] => var test1 = '
                    [1] => '; var test2 = '
                    [2] => '; console.log('test1 =', test1, ', test2 =', test2);
                )

            [get] => SimpleXMLElement Object
                (
                    [@attributes] => Array
                        (
                            [name] => test
                        )

                )

            [star] => SimpleXMLElement Object
                (
                )

        )

)

 
-----------------------
```
As you can see, the `<get>` tag is certainly a part of the output (`[get] => SimpleXMLElement Object`), but it's simply not being processed. I'll have to look into this a bit. Meanwhile, you can use `<star/>` instead of `<get>` for simple JavaScript.

**Comment by Dave-Morton** [comment]
Ok, I've isolated the problem, but I won't have time to fix it for a while. the problem lies in the fact that the function parse_html_tag (which handles __ALL__ HTML tags, including `<script>` tags) only does a simple text replacement  "<star/>" with the first variable in the STAR stack. there is no XML parsing done at all within that function. This obviously needs to change, but it will take some time to get it fixed.

**Comment by walide67** [comment]
thak you @Dave-Morton :)

**Comment by Dave-Morton** [comment]
This one was bothering me, so I made the time to address the issue. I'll be pushing a fix shortly.

**Comment by Dave-Morton** [comment]
@walide67 I've pushed the fix now, so at your convenience please download the latest version from the `DEV` branch and let me know if that takes care of the problem.

**Comment by AlekzNet** [comment]
@Dave-Morton your changes fix something and break something :D  Now I see that conversations are getting thrown out of topics.

**Comment by Dave-Morton** [comment]
@AlekzNet  can you provide an example, and the AIML categories involved so that I can do some testing? Thanks.

**Comment by AlekzNet** [comment]
I haven't done a thorough checking yet. I just noticed a strange behaviour. In a couple of cases I did not get an answer at all. Possibly something else is broken....

**Comment by Dave-Morton** [comment]
Send me your error logs and debug files via email and I'll see if I can determine what's going on. :)

**Comment by walide67** [comment]
good evening world
1- i don't understate this :
this is the aiml code : 
```
<category>
<pattern>
je recherche *
</pattern>
<template>
<think>
<set name="mot"><star/></set>
</think>
<script language="JavaScript">
var mot='<star/>';
alert(bot_recherche(mot));
</script>
</template>
</category>
``` 
the javascript (jquery) code 
```
function bot_recherche(mot){
	motsend="mot="+mot;
	$.ajax({
    url: 'http://localhost/site/recherche_bot.php',
    type:'post',
	data: motsend,
    dataType: 'text',
    success: function(data){
		alert("function : "+data);
		return data;
		
    }
});
}
```
when i write search hotel i get the alert of aiml code in the first with undefined result then i get the alert of the javascript function with the value of data "hotel" 
normally ... the javascript function run in the first and then the aiml code run second 
help me please 
2- how i can get the value of javascript variable and set it into aiml variable ???

**Comment by Dave-Morton** [comment]
Something to bear in mind is that a jQuery AJAX call is _asynchronous_, which means that the results aren't immediately available. Thus, when you do something like `alert(bot_recherche(mot));` there is no value assigned to the "variable" yet. Instead, you should do something like this:

```xml
<category>
    <pattern>search  *</pattern>
    <template>
        <think><set name="mot"><star/></set></think>
        <script language="JavaScript">
            var mot='<star/>';
            bot_recherche(mot);
        </script>
    </template>
</category>
```

with the JavaScript being this:

```JavaScript
function bot_recherche(mot){
	motsend="mot="+mot;
	$.ajax({
    url: 'http://localhost/site/recherche_bot.php',
    type:'post',
	data: motsend,
    dataType: 'text',
    success: function(data){
		alert("function : "+data);
		return data;
		
    }
});
}
```
As for your second question, the problem here is that all communication between the chatbot and JavaScript is essentially one way (from the chatbot to JS), unless you "trick" the bot into thinking that a command from JS came from the user. This is no easy thing to do unless you intercept the user's input, and modify it to insert commands, then use AIML to "extract" those commands and process them separately. This is __extremely__ advanced stuff, and far outside the scope of the support provided here. I'm afraid that's the best answer I can provide here. Sorry.

**Comment by walide67** [comment]
i want to put the data that returned by javascript into the template of the chatbot , i use the multi bot like this : 
user : hello 
bot : hi 
user : how are you ?
bot : i am fine 
........

**Comment by ruchikanagarkar** [comment]
```
<category>
 	<pattern>JAVASCRIPT TEST *</pattern>
	 <template><think><set name="test"><star/></set></think>
	     Sending <star/> to JavaScript.
	     <script language="JavaScript">
	         var test1 = '<get name="test"/>';
	         var test2 = '<star/>'; 
	         console.log('test1 =', test1, ', test2 =', test2);
	     </script>
	     Test complete. Check the console log.
	</template>
</category>

 
When you add this to your bot and then enter `javascript test foo` into the chatbot's interface, you should get the following in your JavaScript console:
 
`test1 = <get name="test"/> , test2 = foo`

```

 I tried the same in my code but it seems not to be working . For `test2`, I am not getting the value `foo`. `test1` returns `<get name="test" /> and `test2` returns <star></star>`.

**Comment by dangeer** [comment]
Hi all,. how to integrate javascript inside aiml ? 
this did not work at all in my code:
  <script language="JavaScript">
          //script here
        </script>
nor this <javascript></javascript>
