### ISSUE TITLE
Learning

### ISSUE THREAD

**Issue by aimar-lints** [Program-O/Program-O#243]
I would like to use a learning function from conversation, from sentence "bad answer".
[http://chat.preziland.com/bot/gui/jquery/multibot_gui_with_chatlog.php](http://chat.preziland.com/bot/gui/jquery/multibot_gui_with_chatlog.php)
It does not write a new answer to the mysql table aiml_userdefined column "template"
- there are no srai value.

chatbot: Hey!
User: chat
chatmeWhat?
User: bad answer
chatmeI don't have an answer for you.
User: bad
chatmeWhat?
User: yes
chatmeI don't have an answer for you.
User: bad answer
chatmeWould you like to teach me a new answer to " YES "?
User: yes
chatmeOK, what should I have said?
User: no
chatme" no..."? Do you want me to remember that?
User: yes
chatmeFine. I'll try to remember to respond, " no " when you say, " YES "
User: ok
User: yes
chatme 

function is working but the answer is emty. 

it does record a word to a database but not the answer.

The same thing with wordpress plugin here:
[http://chat.preziland.com/](Preziland chat)

You:halloo
Bot:What?
You:bad answer
Bot:I don\'t have an answer for you.
You:bad answer
Bot:Would you like to teach me a new answer to " BAD ANSWER "?
You:yes
Bot:OK, what should I have said?
You:bad bad
Bot:What?
You:bad
Bot:I don\'t have an answer for you.

**Comment by AlekzNet** [comment]
What AIML script are you using for learning?

**Comment by aimar-lints** [comment]
Script?
Think it is jquery
From Admin panel I see the response format: JSON

**Comment by AlekzNet** [comment]
I mean: what AIML code (patterns, templates) are you using?

**Comment by kenkit** [comment]
His bot has a bug, am also looking for good aiml files compatible with this project, I once used charliebot.
It was the best I could think of i terms of aiml

**Comment by kenkit** [comment]
mine is ok.
```
🇨 🇴 🇸 🇲 🇴, [18.03.17 09:51]
hello

The Eleventh Bot, [18.03.17 09:51]
I lost my train of thought.

🇨 🇴 🇸 🇲 🇴, [18.03.17 09:57]
haloo

The Eleventh Bot, [18.03.17 09:57]
Perhaps I'm just expressing my own concern about it.

🇨 🇴 🇸 🇲 🇴, [18.03.17 09:57]
bad answer

The Eleventh Bot, [18.03.17 09:57]
Would you like to teach me a new answer to " HALOO "?

🇨 🇴 🇸 🇲 🇴, [18.03.17 09:57]
yes

🇨 🇴 🇸 🇲 🇴, [18.03.17 09:58]
hi

The Eleventh Bot, [18.03.17 09:58]
" hi..."? Do you want me to remember that?

🇨 🇴 🇸 🇲 🇴, [18.03.17 09:58]
yes

The Eleventh Bot, [18.03.17 09:58]
Fine. I'll try to remember to respond, " hi " when you say, " HALOO "

🇨 🇴 🇸 🇲 🇴, [18.03.17 09:58]
ok

The Eleventh Bot, [18.03.17 09:58]
How can you tell if I am a person or a robot?
```

**Comment by Dave-Morton** [comment]
The transcripts are all well and good, but there are better ways to see where things are failing. Please read [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to learn the best method for providing information about the issue. The transcripts provide information about __what__ is going wrong, but does not provide the __why__.

**Comment by kenkit** [comment]
The response is empty, the above is an intent from api.ai
===>Sorry, I didn't get that. and Sorry, what was that? are from

**Comment by Dave-Morton** [comment]
@kenkit did you have a chance to look at the wiki page I linked in my last post? Without the necessary information it's impossible for me to help you to correct the problem. I wish it could be different, but that's how it stands.

**Comment by kenkit** [comment]
I'll have a look into later as I finish up my project.
The hard part is nearly over.

**Comment by kenkit** [comment]
by the way, if anyone want's to test my bot it's on Telegram @the_eleventh_bot
Give me some feedback

**Comment by Dave-Morton** [comment]
I currently do not have the time available to do that, as I'm trying to finish school assignments for the week, but I may be able to look into it once I'm done.

**Comment by AlekzNet** [comment]
So, @kenkit and @aimar-lints , what are the actual problems?

**Comment by aimar-lints** [comment]
So my goal is:
1. Would like to see someones demo, where that learning function is working.
2. Would like that chatbot could learn from chat. Like learnbot/learningbot.
If bot doesnot know answer, it starts learning (I do not need to put text "wrong answer"):
default sentence, if answer is not found - Would you like to teach me a new answer to " " (Yes or No?):

Would you like to teach me a new answer to " " (Yes or No?)
if user says "yes" 
OK, what should I have said? 
" "? Do you want me to remember that? (Yes or No?)
Fine. I'll try to remember to respond, "" when you say, " "
You can try to say "" now

My idea was that program-o chatbot could learn / update its database automatically based on user inputs.
For example if user interacts and bot does not know that answer it will ask for it and it gets the answer, it will remember / writes to database. 
It is almoust working, thats why I liked program -o. Only problem that I have it is writing an emty answer to database admin_added.aiml. 
http://chat.preziland.com/bot/gui/jquery/multibot_gui_with_chatlog.php

My installation or setup was not ok first time. I might not have all required tables. There might be problems with config. There might be other problems too. 
But, I have not seen any working learning bot yet with program -o.
There are MS framework https://dev.botframework.com/ and other AIML programs, but I like php and MySQL based bots more.

For now, my bot have errors like this:
Something went wrong! Error = SyntaxError: Unexpected end of JSON input

And from error log:
03/21/2017 15:51:12 - PHP ERROR [Notice] -Array to string conversion in /core/aiml/parse_aiml_as_XML.php on Line 171
03/21/2017 15:51:12 - PHP ERROR [Notice] -Array to string conversion in /core/aiml/parse_aiml_as_XML.php on Line 171
03/21/2017 15:51:12 - PHP ERROR [Notice] -Undefined offset: 0 in core/aiml/parse_aiml_as_XML.php on Line 884
03/21/2017 16:09:44 - PHP ERROR [Notice] -Array to string conversion in /core/aiml/parse_aiml_as_XML.php on Line 171
03/21/2017 16:09:44 - PHP ERROR [Notice] -Array to string conversion in /core/aiml/parse_aiml_as_XML.php on Line 171
03/21/2017 16:09:44 - PHP ERROR [Notice] -Undefined offset: 0 in /core/aiml/parse_aiml_as_XML.php on Line 884

**Comment by AlekzNet** [comment]
There is an example of the learning implementation here: http://www.square-bear.co.uk/aiml/ -> learn.aiml

**Comment by Dave-Morton** [comment]
@aimar-lints It would be helpful to know some specifics of your Program O install so that we can better help you. Please read [__this wiki post__](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to learn what information is needed and how to obtain it. Then please post that information here so that we can help. Thanks.

**Comment by patrickschur** [comment]
@aimar-lints You can't train your bot on such patterns like yours " ". Program-O will remove all unnecessary characters, after the normalization process you will receive an empty string and that would be a blank/invalid pattern. :)

**Comment by aimar-lints** [comment]
This link seems to be something what I was looking for 👍 
http://www.square-bear.co.uk/aiml/
learn.aiml - allows users to teach your bot new facts rather than just correcting its replies using badanswer.aiml.

Is it possible to use autolearning for AIML bot? From conversation.
Like if there are two same sentences, bot remembers it as a right answer otherwise it repeats a question.

What is hot? 
The sun is hot.
What is hot? 
The sun is hot.

What is hot
the sun

Who is an AI expert?
Dr Wallace.
Who is an AI expert?
Me

Who is an AI expert?
Who is an AI expert?
Dr Wallace.

Who is an AI expert?
Dr Wallace.

**Comment by AlekzNet** [comment]
> Is it possible to use autolearning for AIML bot? From conversation.
The general answer is "no". 

If you have a big conversation database, I would go for a neural network (LSTM/GRU/GridGRU)

**Comment by kenkit** [comment]
I fixed nearly all the bugs in my bot, i've also noticed that some people have become regular users.
If you guys need help I can also donate conversations for analysis and bug fixing. Or you can just chat with the bot directly, it's linked to more than 4 systems.
