### ISSUE TITLE
CONDITION tag nor working correctly

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#244]
This is hard to believe, but I have tried this exact AIML category in just about every form possible, and it simply does not work.

```xml
      <category>
         <pattern>CMDOUTFIT1</pattern>
         <template>
            <think>
                <set name="test">t</set>
            </think>
            <br />|<get name="test"/>|
            <condition name="test">
               <li value="t">FIRSTGREET</li>
               <li>RETURNGREET</li>
            </condition>
        </template>
      </category>
```
I purposely coded it so that the value it was testing for was always a "t" so there could be no possible miss understanding that it should match the first test of FIRSTVISIT.  However it always gives me the answer RETURNVISIT, which is the default catch all ending list of tested conditions.

The reason this baffles me is because I use hundreds of these condition statements in my AIML and it simply would not work if the condition function was this broken.

Here is the response from the bot:

Slow Putzo: CMDOUTFIT1
April Genie: 
| t | RETURNGREET

I tried this with a very small AIML load after dumping all my AIML and doing a srai lookup build which resulted in a single found entry to the table to ensure there was little other AIML that could be involved in this failed result. .

I have stared at it for endless hours thinking this is one of those typical can't see the trees for the forest, but I don't see anything wrong with the category.  I apologize in advance if this is what this is.

I have tried both possible list conditions naming the variable in the condition statement and like this.  Both give the same response.

The only thing I have not done is to retype the entire category in as a new category.  I know that sounds dumb, but I have had problems in the past where there were hidden characters in the text I guess and retyping the category solved the problem.  It has been a very long time since I have seen that issue.

**Comment by Dave-Morton** [comment]
lol oops? I found the problem, @tringate . It seems that some debugging code was left in place by mistake that only affects trying to set a client property (predicate) with a name of `test`. There's a line of code in the file `chatbot/core/aiml/parse_aiml_as_xml.php` on line number 606 that hard-codes the value for the client property "test" to be "passed", so your setting the property to `t` is completely ignored. To fix the issue, simply look for the following line of code:

`$convoArr['client_properties']['test'] = 'passed';`

and delete it. I'll be pushing the fix shortly, but for now, removing that line of code should take care of the problem.

**Comment by tringate** [comment]
@Dave-Morton 

Thanks for reaffirming my sanity.  I could not understand how so many of these same conditions worked just fine but this one didn't.  Never considered it could be the value name that was the issue.  You might want to correct the line above it, the debug line and correct the word "ben" to "been"

Tom
