### ISSUE TITLE
Fresh Install Failed

### ISSUE THREAD

**Issue by ZastieX** [Program-O/Program-O#245]
Hi, I'm new to Program O. I've tried to install the Program o in my localhost but got HTTP Error 500.
I have followed the instruction and never had Program o installed before.
I copied the following specs from my phpMyAdmin:
**Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7 and MySQL 5.5.27**

The error log:

> [15-Mar-2017 06:18:25 UTC] PHP Fatal error:  Call to undefined function openssl_random_pseudo_bytes() in C:\xampp\htdocs\Program-O-master\install\install_programo.php on line 364

I tried to google the problem but no solutions. 
Anyone can help me? Thanks

**Comment by patrickschur** [comment]
Looks like your PHP version wasn't compiled with support for OpenSSL. Also please have a look at the `php.ini`. There is a line somewhere in the file that begins with `;extension=php_openssl.dll` if you find this, delete the semicolon and restart your server. If this didn't work, I would suggest you to update to a newer version of PHP.

**Comment by ZastieX** [comment]
Wow. It works! Thank you so much. I deleted the semicolon there.

**Comment by ZastieX** [comment]
I've just finished filling out the form, submitted it, and got an error when trying to open the main page

Parse error: syntax error, unexpected 'DOCUMENT_ROOT' (T_STRING) in C:\xampp\htdocs\programo\config\global_config.php on line 40

Here is line 40-43, it's under Define URL Paths

$doc_root = $_SERVER['DOCUMENT_ROOT'];
$bu = str_replace($path_separator, '/', _BASE_PATH_);
$baseURL = str_replace($doc_root, '', $bu);
define ('_BASE_URL_', $baseURL);

What should I do? Honestly, I'm not really familiar with php.

**Comment by patrickschur** [comment]
Crazy, that is the first time I heard that someone has problems with the installation process. But I am optimistic that we can solve your problem. 

I never heard of such strange behaviour before. Would it be possible that you delete Program-O and reinstall again? 

But before could you send me your `programo/logs/error.log` or `programo/logs/admin.error.log` file? Optional you can post it here.

And I apologize for the circumstances.

**Comment by Dave-Morton** [comment]
In addition to the information that @patrickschur is asking for, could we also get the following, please?

1. Version of Windows.
2. Xampp version
3. Program O version

This will help us to create the exact conditions under which you're receiving this error message. Thanks.

**Comment by ZastieX** [comment]
Yes, of course. Thanks for replying
1. WIndows 7 64bit
2. XAMPP 1.8.1
3. Program O 2.6.4 (from version.txt)

Anything else?

**Comment by Dave-Morton** [comment]
Windows 7 is a bit behind the times, but as I still have a VM with Win 7 installed I think I can work with it. I'll need to research a little to see what the various software versions are for Xampp 1.8.1 but I should be able to put something together shortly so that I can do some testing.

**Comment by ZastieX** [comment]
Yes, @Dave-Morton . Thanks, and sorry for taking your time, sir.

**Comment by Dave-Morton** [comment]
Not to worry, @ZastieX - that's what I'm here for. :)

**Comment by patrickschur** [comment]
@ZastieX I am still present. :D 
But I didn't receive any log file until now. :(

**Comment by ZastieX** [comment]
Yes, @patrickschur . I edited my reply above. I didn't see your reply before. :D
There is only index.php and install.error.log

**Comment by patrickschur** [comment]
What is in the file `install.error.log`?

**Comment by ZastieX** [comment]
[15-Mar-2017 12:52:49 UTC] PHP Fatal error:  Call to undefined function openssl_random_pseudo_bytes() in C:\xampp\htdocs\programo\install\install_programo.php on line 364

I dont think it's related with the problem.

**Comment by Dave-Morton** [comment]
Well, given that it's a _fatal_ error, it was definitely causing the script to fail, at first. But uncommenting that line in php.ini and restarting Apache took care of that. Now we have to work out why your Xampp install isn't recognizing a very common PHP/Apache variable (`$_SERVER['DOCUMENT_ROOT']`).

**Comment by ZastieX** [comment]
Yes @Dave-Morton . The error was before I did @patrickschur 's solutions.

**Comment by patrickschur** [comment]
@Dave-Morton What do you think about of this?
```php
$doc_root = str_replace($_SERVER['SCRIPT_NAME'], '', $_SERVER['SCRIPT_FILENAME']);
```

@ZastieX I have the feeling that something is wrong with your configuration file. Could you tell us how the document root looks like in your `XAMPP/apache/conf/httpd.conf` file?

**Comment by ZastieX** [comment]
Is it this one, @patrickschur ?

`DocumentRoot "C:/xampp/htdocs"`

**Comment by Dave-Morton** [comment]
Those variables are far different, Patrick. I'm almost done installing Xampp (VirtualBox and Windows 7 as a guest make for a terribly slow-running system), then I can do some testing.

**Comment by patrickschur** [comment]
@Dave-Morton Yeah, but I get the same output. :)
@ZastieX Yes, looks good for me.

**Comment by ZastieX** [comment]
I will be off now. It's already midnight in my place. So, don't wait for my reply within few hours. Thumbs up to both of you!

**Comment by Dave-Morton** [comment]
While running the install script, I ran across an interesting problem where the `is_writable()` function was returning false (generating warnings in the install script), even though the logs, config and debug folders were able to be written to. I ended up reworking the tests for writability in such a way as to not wholly rely on that function, and it seems to be working. I still haven't seen @ZastieX problem yet, but I'm only just now able to get past the warnings about non-writable directories.

**Comment by Dave-Morton** [comment]
Alright. After installing Xampp 1.8.1, configuring it, and making sure that there were no problems with the server software, I uploaded the latest version of Program O from the `MASTER` branch and ran the install script. The only problem that I ran into was the issue I already mentioned about folders being not writable when they were. I didn't see anything regarding the `document root` problem that @ZastieX had reported. At this point, I'd suggest either upgrading to a newer version of Xampp, or deleting the Program O folder and trying to install it again, from scratch. Both Windows 7 and Xampp 1.8 are __seriously__ behind the times, and are almost too old to be supporting Program O on. I understand not wanting to lose windows 7, it's myall time favorite M$ operating system, but I think it's time to move on, don't you? 😄

**Comment by AlekzNet** [comment]
> I understand not wanting to lose windows 7, it's my all-time favorite M$ operating system, 
> but I think it's time to move on, don't you?
Why? You've clearly said, that it's your favourite MS OS ;) Or do you mean move on and install Linux? :D

**Comment by Dave-Morton** [comment]
lol, no. but Windows 7 past it's "end of life" (as of Jan. 13th, 2015), so is no longer supported by M$. this means that any "new" security vulnerabilities are no longer addressed. Windows 8 will "die" on Jan. 9th of next year as well. [This page](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet) from Micro$oft provides the details. but this is a bit off topic, so... 😃

**Comment by ZastieX** [comment]
Thanks for trying to solve my issues, everyone. Really appreciate it.
I tried to do the installation again twice. The second attempt, I put wrong hostname and a php script shown ended with failed database connection. Then I go back to the installation form again (pressed back button on my browser), and fill the correct hostname, and voila.. it worked!
I don't really understand what's going on. Hopefully there won't be any issue again.

Regarding my OS, yes, I've also planned to upgrade it since MS finished it. 

Any thoughts on why did it work?

**Comment by Dave-Morton** [comment]
It's entirely possible that it was just a random glitch with either the upload (or copy) process, or the execution of the install script itself. I've seen other instances of this, but having different symptoms. It's not common, but it happens enough to be both confusing and irritating. I'm glad you got it working now. If you have any other problems, please let us know.

**Comment by alshaikh1** [comment]
@Dave-Morton I was getting the same error before I tried your trick (wrong server name etc) and it worked. 
Strange but thank you.
