### ISSUE TITLE
composer install of program-o?

### ISSUE THREAD

**Issue by hesomWela** [Program-O/Program-O#247]
Hello,

I am trying to use the core functionality in one of my apps, is there an easy way to do so? 

Thanks

**Comment by Dave-Morton** [comment]
As I've never integrated any of my projects to use Composer, I don't have a useful answer for you at this time. I am, however, doing research on the subject so that I can provide some usable information in the future. If you know something about the process I'd be happy to hear your thoughts.

**Comment by hesomWela** [comment]
Thanks for the follow-up. My goal is to integrate Program-O into our platform. 

In the meantime, I could setup the app an utilize the APIs. I found this package that could work (https://github.com/a2design-inc/AIML), but it does not look like it has all of the features of AIML wired up yet.

**Comment by patrickschur** [comment]
@hesomWela I have already some experience with composer on my own projects. What I can tell you is that Program-O is not modular. So there are no classes you could call. The entire project is programmed procedural. What makes it not easy to harmonize with composer. Also there is a installation routine. How would you integrate that to work with composer? 

As you can see, this requires a lot of work, to work with composer. That could be a feature for a newer version of Program-O.

Maybe you just like to download the source code via Composer? If so, that could be done. :)
