### ISSUE TITLE
Looking for compatible aiml files

### ISSUE THREAD

**Issue by kenkit** [Program-O/Program-O#248]

**Comment by kenkit** [comment]
Where are the best aiml files compatible with programO ?

**Comment by Dave-Morton** [comment]
This question has been asked a number of times over the years, and over that time, the answer has changed frequently. Thus, I've decided to create a [public repo](https://github.com/Dave-Morton/PGO_AIML) of the AIML files I use when testing Program O's various functions. It's almost identical to the [Annotated ALICE AIML set](http://www.alicebot.org/aiml/aaa/), but with some corrections to fix typos and clean up invalid XML. It's not perfect, and as it sits it can easily be seen as an ALICE clone, but it's a great starting point for a generic chatbot.

**Comment by scandragon** [comment]
Unfortunately, the aiml files are useless.
Please check them with the xml validator as well as your aiml validator. Without working aiml files, your bot does not work

**Comment by Dave-Morton** [comment]
Useless how? I've personally validated and tested each of those AIML files, both individually and within a zip archive, and they all upload without errors and work within a chatbot. If you're seeing errors when attempting to upload the, @scandragon please provide uw with the errors you see, along with information about your Program O install. Thanks.

**Comment by AlekzNet** [comment]
@scandragon and @kenkit : please formulate the problems. 

As for free AIML files, you can play with these ones:

http://www.square-bear.co.uk/aiml/
