### ISSUE TITLE
 sequence diagram for chaterbot of program o ...need help

### ISSUE THREAD

**Issue by walide67** [Program-O/Program-O#253]
hello everyone 
i want to create a sequence diagram to explained how my chat bot work 
i create my chat bot with program o
so ... i want to know how program o work in detail or How to handle the user input
thanks for all ...

**Comment by patrickschur** [comment]
Sorry but it's not our job to do your homework or what ever you are planning to do with it.
If you want to know how Program-O works please study the source code or read the AIML standard.
This sort of question is not a issue for me.
Anyway to help you a little bit I will describe the process for you very short.

The first step would be to validate your uploaded AIML file by the aiml.xsd file. That's a file which descripe the syntax of AIML. After that when no errors were found Program-O will save all categories in a database.

Now if you chat with Program-O the user input will be normalized. That means all special characters like punctuations will be removed. After that Program-O splits the user input in words and try to search for a pattern in the database which contains one or more words of the input. If he found something Program-O tries to find the best matching pattern and executes the matching category. After successful execution you will get a response back. Your answer.

Be in mind that this is a really short description of how Program-O work.

**Comment by walide67** [comment]
thank you ... your answer help me :)

**Comment by Dave-Morton** [comment]
To add to what @patrickschur described, if you have debugging turned on, and configured to save to a file, you can look through one of the debug files created during conversations to see exactly which steps Program O takes to go from raw user input to the returned response. The debug files were designed to be completely readable by Humans, and each step is given a fairly easily understandable description.

Hope this helps.

**Comment by Program-O** [comment]
closing - last response over 30 days ago
