### ISSUE TITLE
PGO_AIML2.0 fresh install hack

### ISSUE THREAD

**Issue by awicaksi** [Program-O/Program-O#254]
Hi, I am eager to know what's new in AIML 2.0 version, so I install the PGO_AIML2.0 branch.

But to make it works, I face this minor issues:

1. Error 500, the log said
`PHP Fatal error:  require_once(): Failed opening required '_BOTCORE_AIML_PATH_parse_aiml_2.0.php' (include_path='.:/usr/share/php') in /home/app/var/www/PGO_AIML2.0/chatbot/core/aiml/parse_aiml_as_XML.php on line 13`

So I add this in global_config.php line 35

`define('_BOTCORE_AIML_PATH_', _BOTCORE_PATH_ . "aiml$path_separator");`

Solved.

2. On Admin page, when I tried "Talk to Bot" link,
it went blank because the targeted link was: `http://localhost/gui/jquery/bot_id=1`

So I edit index.php,

line 24 into
`$qs = '?';`

and line 28 into
`$qs .= http_build_query($get_vars);`

Solved.

I do not know whether those are issues or not, but did I do the correct way to fix them? Or I should simply obtain the fixes (redownload maybe).
So far I found no other problems on admin. Can't wait to explore the AIML 2.0. Thanks!

**Comment by patrickschur** [comment]
I'm glad to hear that. That you can't wait to explore AIML2. The same thing happened to me. :)
But have in mind that the status of the branch is still work in progress. I'm sure that he forgot the `define`

**Comment by patrickschur** [comment]
I'm glad to hear that. That you can't wait to explore AIML2. The same thing happened to me. :)
But have in mind that the status of the branch is still work in progress. 
I'm sure that he just forgot the `define` instruction.

Anyway your changes looks good, feel free to start a pull request or wait for a reply from @Dave-Morton.

**Comment by Dave-Morton** [comment]
@awicaksi Your fixes are just fine. I don't have time now to make the changes to the branch (work and school are taking up my time), but I'll make notes for the upcoming weekend. I should also have time then to add a couple of more functions to support additional AIML 2.0 tags, and possibly solve the issue with the `<oob>` tag not fully working.

**Comment by awicaksi** [comment]
Thanks for the replies, guys. To be able to support this exciting project within your busy live is simply amazing (Thanks!).
