### ISSUE TITLE
Installation and Other problems (Urgent Help PLEASE)

### ISSUE THREAD

**Issue by Icrafterphy** [Program-O/Program-O#255]
( ! ) Parse error: syntax error, unexpected 'DOCUMENT_ROOT' (T_STRING), expecting ',' or ')' in D:\wamp\www\Program-O-master\config\global_config.php on line 40

It's what it's showing after installation and running `http://localhost/Program-O-master/admin` 

Please I want urgent Help regarding this.. My email- icrafter.phy@gmail.com

**Comment by Icrafterphy** [comment]
Immedietly after Installing I saw this-

D:\wamp\www\Program-O-master\install\install_programo.php:222:
class PDOException#3 (8) {
  protected $message =>
  string(92) "SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No such host is known. "
  private $string =>
  string(0) ""
  protected $code =>
  int(2002)
  protected $file =>
  string(57) "D:\wamp\www\Program-O-master\install\install_programo.php"
  protected $line =>
  int(215)
  private $trace =>
  array(2) {
    [0] =>
    array(6) {
      'file' =>
      string(57) "D:\wamp\www\Program-O-master\install\install_programo.php"
      'line' =>
      int(215)
      'function' =>
      string(11) "__construct"
      'class' =>
      string(3) "PDO"
      'type' =>
      string(2) "->"
      'args' =>
      array(3) {
        ...
      }
    }
    [1] =>
    array(4) {
      'file' =>
      string(57) "D:\wamp\www\Program-O-master\install\install_programo.php"
      'line' =>
      int(98)
      'function' =>
      string(4) "Save"
      'args' =>
      array(1) {
        ...
      }
    }
  }
  private $previous =>
  class PDOException#2 (10) {
    protected $message =>
    string(89) "PDO::__construct(): php_network_getaddresses: getaddrinfo failed: No such host is known. "
    private $string =>
    string(0) ""
    protected $code =>
    int(0)
    protected $file =>
    string(57) "D:\wamp\www\Program-O-master\install\install_programo.php"
    protected $line =>
    int(215)
    private $trace =>
    array(2) {
      [0] =>
      array(6) {
        ...
      }
      [1] =>
      array(4) {
        ...
      }
    }
    private $previous =>
    NULL
    public $errorInfo =>
    NULL
    public $xdebug_message =>
    string(490) "
PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in D:\wamp\www\Program-O-master\install\install_programo.php on line 215

Call Stack:
    0.0040     425016   1. {main}() D:\wamp\www\Program-O-master\install\install_programo.php:0
    0.0130     446168   2. Save() D:\wamp\www\Program-O-master\install\install_programo.php:98
    0.0150     467608   3. PDO->__construct() D:\wamp\www\Program-O-master\install\install_programo.php:215
"
    public $severity =>
    int(2)
  }
  public $errorInfo =>
  NULL
}
Cannot connect to the database! SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No such host is known.

**Comment by patrickschur** [comment]
You can't connect to the database because he can't resolve the host. Either you have no MySql activated or you have made a mistake during the installation (maybe a typo in the db host field).
Make sure you have MySql installed/activated and then please reinstall Program-O.
Let us know which settings you are using for the db fields except the username and password.

In most of the cases the db host is localhost and the port can be left empty.

**Comment by Dave-Morton** [comment]
@patrickschur it could also be that the WAMP server isn't setting the DOCUMENT_ROOT environment variable for some reason. This isn't __usually__ the case with Apache, but I suppose it's *possible*.

@Icrafterphy a little more information is needed. I can see from your posts that you're on a Windows machine, and that you're using what's called a "WAMP stack" (Apache web server, MySQL database server and PHP for Windows), but there is no information about what versions of each are installed, so if you could provide that information it would help us a lot. Here's what we need the most:

+ Windows version (7, 8, 10, etc.)
+ Apache Version (2.2, 2.4, etc.)
+ PHP version (5.3, 5.5, 7.0, etc.)

We don't really need the MySQL version right now, but may later (though that's not very likely).

**Comment by Icrafterphy** [comment]
Thanks Dave..
My problem is solved with installation.
But I noticed-
1. <that>..</that> tag isn't working...
2. It's not prioritizing the existing aiml categories when it comes to * wildcard pattern with a that tag...
It'll be very helpful for me if u help me fixing this.
The two noticed problems doesn't occur when I run my bot on Pandorabots playground....

**Comment by Dave-Morton** [comment]
@Icrafterphy if you could post a debug file here that's related to each problem that would help a good deal. If your bot isn't set up to create debug files please let me know and I'll walk you through the process of changing that.

**Comment by alianrkeasan** [comment]
I've got the same error during installing:

Parse error: syntax error, unexpected 'DOCUMENT_ROOT' (T_STRING), expecting ',' or ')' in C:\Apache24\htdocs\newbot\config\global_config.php on line 40

My PHP settings are availabe here http://143.54.95.244/teste_h.php

**Comment by Dave-Morton** [comment]
@alianrkeasan I noticed that exact problem while debugging a different problem with the latest version. It seems that an extra backslash character was somehow inserted on line 40 (the line that sets the session directory for Program O), and removing it "fixed" that issue. However, I haven't been able to figure out why or how that errant character got inserted, and after more than a dozen attempts to recreate the problem, I was unable to get it to reoccur. I'll continue to investigate this, but if you wish, please feel free to simply correct the typo and test the install. I'll keep you posted on what I find if you would be so kind as to do the same.

**Comment by alianrkeasan** [comment]
I could not find the backlash ou mentioned.

The strange is that I've installed the new program-O version, the same version, in another system, with Wampp, and it did not occur.

Just now that I'm working with apache and PHP in separate.

**Comment by alianrkeasan** [comment]
Here's what I did:

I've copied the file that was working and replace it on my unworking system, changing database configurations of course.

But now I'm with this problem on my jquery interface:

Notice: Undefined index: HTTP_X_FORWARDED_PORT in C:\Apache24\htdocs\newbot\gui\jquery\index.php on line 25

**Comment by Dave-Morton** [comment]
There were some pretty substantial changes made to the database in this most recent version, so you're likely to encounter other errors. the CHANGELOG file has instructions on the correct procedure for installing it, including either emptying the current database of ALL tables or creating a new one, which is probably a better option.

As to the error message about that undefined index, it's not a huge issue, really. some servers don't set that variable, so Program O will complain about it, but it won't affect the operation of the script. At some point in the near future I'll alter that code to test for it before testing it's value.

**Comment by ofirattia** [comment]
You need to remove the backslash in line 34 and it will be ok.
define('_SESSION_PATH_', _ADMIN_PATH_ . 'ses_52ed6890a72aaac189d25a6a\' . $path_separator);

"ses_52ed6890a72aaac189d25a6a\"
change it to
ses_52ed6890a72aaac189d25a6a

**Comment by Dave-Morton** [comment]
That folder name is generated by script elsewhere in the code during the installation process, and it was in that generation code that the problem was occurring. As mentioned earlier, this has already been corrected in the `DEV` branch, which I am actively trying to remove bugs from. It _should_ be pretty well bug-free right now. I've already thoroughly tested it in Windows, and am now doing the same in Ubuntu. It should be completely tested by the weekend.

**Comment by Program-O** [comment]
re-closing and locking please do not reopen.
this has been resolved and fix released to dev
awaiting merge to master
