### ISSUE TITLE
Program O error message not working

### ISSUE THREAD

**Issue by Laureen-giac** [Program-O/Program-O#258]
In MYSQL, 'bot' table, I have the error message response set to **'Sorry I don't know the answer to that'**. But I am always getting **'undefined'** as my error message when chatting with the bot using the HTML or Jquery interface. 

What could possibly be the problem ? Thanks. :)

**Comment by Dave-Morton** [comment]
Hi, Laureen!

A little more info from you would go a long way toward helping us to help you. Please read [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) about reporting issues, then post the following:

+ Program O version (is it the latest? And from which branch?)
+ Server OS and version (even if it's local)
+ PHP version

Also, if you have debugging turned on, you can either attach a debug file here, or paste it into your next post (attaching it would be best), that would be most helpful. With this information I'm sure we can get your problem sorted out in no time. :)

**Comment by Program-O** [comment]
closing - last response over 30 days ago
