### ISSUE TITLE
Make a webservice for debugging on front-end

### ISSUE THREAD

**Issue by korrio** [Program-O/Program-O#263]
Feature request:

For example, if I want to know the current conversation's context (topic) or which AIML file bot used for the answer (or even which line of AIML that bot interpreted), I can easily collaborate with the team to develop a better bot knowledge.

Possible outcome:
http://conversation-simple.mybluemix.net/

**Comment by patrickschur** [comment]
Just turn on the debug mode... It may not look so fancy, but does its job.

**Comment by korrio** [comment]
I turned on debug mode, where can I see the result ?

**Comment by Dave-Morton** [comment]
In the admin is a link to show the debug viewer. Once you click the link, a new tab (or window?) will open. Log in with the admin credentials and look for the conversation ID for the conversation volley that you desire. The debug file only holds the information from the most recent input/response, but it contains *LOTS* of data. For the most part it's easy to read, but will take practice to understand what everything means. If you get confused, post the file and ask whatever questions you like. We'll do our best to answer them.

**Comment by Dave-Morton** [comment]
A similar question was asked in issue #268 so this is something that I'm going to look into, but I'm going to ask the same question here that I asked in that thread: What specific information would you like to see get returned from the API? Obviously things like TOPIC, THATPATTERN and the filename that held the AIML category come to mind, but what else would you see as useful? Right now only the conversation ID, what the user input and the bot's response are returned, but it wouldn't be impossible to add to the data returned.

**Comment by korrio** [comment]
TOPIC, THATPATTERN and the filename that held the AIML category and Conversation ID 

For me, just one more thing
- <get>/<set>

**Comment by Dave-Morton** [comment]
the conversation ID is already part of the output, so no problem there. the rest shouldn't be a problem, except for maybe the `<get>/,set>` values, as this could be any or no value at all. but perhaps the database ID of the category in the DB might help there, instead. That way you can look up the category in the Search/Edit page of the admin and see what it contains.

**Comment by Dave-Morton** [comment]
Ok, the recent push I did adds a "data" array to the JSON object that the API returns. You can access it as response.data.{insert property name here} - the properties are:
+ aiml_id: the ID of the AIML category in the database
+ pattern: The `pattern` of the AIML category selected
+ thatpattern: The `that` of the AIML category selected
+ topic: The `topic` of the AIML category selected
+score: the score awarded
+track_score: The description of attributes that earned the aforementioned score__*__

__*__ This is a bit tricky to explain, up until you see what's there. Just have a look at the value and it should become clear. If not, just ask about it. :)

**Comment by Program-O** [comment]
closing -released fix and no further input from korrio
