### ISSUE TITLE
DOCUMENTATION: Request for a more detailed quick-start usage guide

### ISSUE THREAD

**Issue by KgotsoK** [Program-O/Program-O#273]
Hi

There are things like session generation, session management, attaching a username to a conversation etc. that need to be clear to a new user of this library. The guide does not need to be exhaustive, but to promote adoption of this useful tool, The basics need to be in-place.

1. How to start and continue a conversation (what you send, what you get back).
2. How session management works in Program-O.
3. How to resume a conversation.

Yes I have a better idea of how all these actions are performed after reading through the code, but my team and any other person who is interested in Program-O should not go through this learning curve which takes time. PLEASE add some basic API usage info showing off some of the basic functionality described in the points above.

**Comment by Dave-Morton** [comment]
So far as API usage is concerned, I agree that more info needs to be made available in the documentation, and this is something that will be addressed during my summer break from school. But subjects such as session generation/management is a bit advanced for most individuals who use Program O for their chatbots. Perhaps an "advanced user's manual" might be in order, but that's a bit far off at this point in time. I'll put the idea to the dev team, though, and work out with them where the idea should go in the ToDo list.

**Comment by Dave-Morton** [comment]
I've made a start on the API guide, and it can be found [here](https://github.com/Program-O/Program-O/wiki/Using-the-Program-O-API). I'll put more detail into it when I'm between semesters.

**Comment by KgotsoK** [comment]
Thanks for considering @Dave-Morton . Great tool, this.

**Comment by KgotsoK** [comment]
Just had a look at the API guide... Great start! Thanks for taking the time!

**Comment by Dave-Morton** [comment]
If you have any suggestions or feedback for improving the guide, please feel free to let us know.

**Comment by KgotsoK** [comment]
Will do! With more usage, I will surely end up contributing as well.

**Comment by Program-O** [comment]
closed as fixed
