### ISSUE TITLE
Problema na instalação 

### ISSUE THREAD

**Issue by Davi21** [Program-O/Program-O#276]
Cannot connect to the database! SQLSTATE[28000] [1045] Access denied for user 'brasil046_boot'@'localhost' (using password: YES)

**Comment by patrickschur** [comment]
Please do **not** copy & paste the output of PHP errors into the comment section.
I had to edit it and removed your database password and anything else.

More information would be good insteadof copy & paste the error code.
For me it looks like you have a typo in it. The name of your database is `brasil046_bot` but you tried `brasil046_boot` (notice the additional `o`).

**Comment by Davi21** [comment]
Obrigado, estou tentando continuo com o mesmo erro

**Comment by Dave-Morton** [comment]
Quando você configurar o banco de dados, você copiar a senha para um arquivo de texto, ou você anotá-lo? Às vezes, pode ser muito fácil obter um personagem errado ao escrever as coisas. Eu cometi esse erro muitas vezes. Então, eu sugiro mudar a senha para algo memorável por agora, apenas para testar as coisas, então, uma vez que você começa a trabalhar, alterá-lo para algo mais seguro.

**Comment by Davi21** [comment]
Fiz isso, mesmo assim continua com o mesmo erro

**Comment by Dave-Morton** [comment]
Então você mudou a senha para outra coisa, apenas para testar as coisas, e você ainda obter o mesmo erro?

**Comment by Davi21** [comment]
Isso ainda mostra o mesmo erro

**Comment by Dave-Morton** [comment]
Então você tem um problema com seu banco de dados. Se possível, tente excluir o banco de dados, criar outro e criar um novo usuário com uma senha completamente diferente, tente instalar o Program O novamente.

**Comment by AlekzNet** [comment]
... and I spent 9 months trying to learn Portuguese to no avail ... :D

**Comment by Davi21** [comment]
Continua o mesmo erro criei outro banco e mesmo assim da o mesmo erro

**Comment by Dave-Morton** [comment]
Você pode acessar o banco de dados através de gerenciamento de software como phpMyAdmin?

@AlekzNet I don't know a bit of Portuguese. I just use Google Translate. It's probably poor Portuguese, but at least it gets the point across. :)

**Comment by AlekzNet** [comment]
I guessed so :D I do not mean to say that someone can't learn a language I failed at, but rather praise the latest technology, that can on one hand make the communication much easier without "wasting" time on less important things, but on another provoke laziness and discourage learning. So that was a useless multilayered self-reflective philosophical note from my side :D

**Comment by patrickschur** [comment]
@Davi21 Do you have access to your database now?

**Comment by alianrkeasan** [comment]
Hey everybody, I'm using PHP 7, mysql 5.6 and apache 2.4 in windows, all ok, other sites running, but my program-o 2.6.5 dev installation wont run. What is going on?

**Comment by patrickschur** [comment]
@alianrkeasan What do you mean with it won't run?

**Comment by alianrkeasan** [comment]
I mean, the webadmin page where you fill the forms to the clean installation.

**Comment by patrickschur** [comment]
More informations please... I have a fresh installation here and it works great.
Have you already done a new installation?

**Comment by alianrkeasan** [comment]
Yes, I've done it in another server. but with Wampp. Now i'm working with separated features: php, mysql and apache.

**Comment by patrickschur** [comment]
So you get a blank page? What exactly is not working?
I mean what do you want to change when you press "Save"?

**Comment by alianrkeasan** [comment]
Yes I get a blank page. I dont know what is not working.
I cant even see the form to fill. 
I navigate to my folder localhost/chatbot and the installation dont go through.

**Comment by patrickschur** [comment]
Please have a look at the `logs` folder there must be a file called `error.log` or installation_error.log something like that. I don't know the exact name but if there is a file have a look at it.
This will help you or maybe me ;)

**Comment by alianrkeasan** [comment]
[02-Jun-2017 00:34:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\Apache24\htdocs\chatbot\install\install_programo.php:370
Stack trace:
#0 C:\Apache24\htdocs\chatbot\install\install_programo.php(36): create_session_dirname()
#1 {main}
  thrown in C:\Apache24\htdocs\chatbot\install\install_programo.php on line 370

**Comment by patrickschur** [comment]
Perfect :)
You have to install OpenSSL or if you use WAMPP or something else like that, you need to change the line  `;extension=php_openssl.dll` to `extension=php_openssl.dll` in you php.ini.

The php.ini is on the following paths:
wamp\bin\php\php{YOUR_PHP_VERSION}\php.ini
wamp\bin\apache\apache{YOUR_APACHE_VERSION}\bin\php.ini

**Comment by alianrkeasan** [comment]
I have Openssl installed

OpenSSL/1.0.1p

I've enabled the extensions on php.ini (all folders)

But it keeps the same way:

02-Jun-2017 01:54:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\Apache24\htdocs\chatbot\install\install_programo.php:370
Stack trace:
#0 C:\Apache24\htdocs\chatbot\install\install_programo.php(36): create_session_dirname()
#1 {main}
  thrown in C:\Apache24\htdocs\chatbot\install\install_programo.php on line 370

**Comment by Dave-Morton** [comment]
Did you restart your server afterward, by chance?

**Comment by alianrkeasan** [comment]
I would like to thank you Patrick and Dave for the help.
Thanks to your help I've succeed on installling my program-o.

**Comment by Dave-Morton** [comment]
Glad to hear it. Could you share with us what you ended up doing? It may help others in the future.

**Comment by alianrkeasan** [comment]
So, I've read that you need to replace the dlls libeay32.dll and ssleay32.dll, 

from your new PHP version to your apache bin,

but when I tried I could not because the apache was running.

Then I've stopped it and replace the dlls.

**Comment by Dave-Morton** [comment]
Thanks for letting us know, @alianrkeasan.
