### ISSUE TITLE
major flaw uisng json with api and spaces

### ISSUE THREAD

**Issue by Doorstop2** [Program-O/Program-O#277]
So i fully setup my api 

http://xxxx/prog/chatbot/?bot_id=1&say=hello my name is blank&format=json

now as you can see the spaces are not recognized you simply wont get a response back 

BUT 

if i do http://xxxx/prog/chatbot/?bot_id=1&say=hello%my%name%is%blank&format=json

The % will tell its a space and it will reply

and 

http://xxxx/prog/chatbot/?bot_id=1&say=hello&format=json

because there is no spaces i will get a reply also now i was going to use this with discord i have it working but if there are spaces as you see above there will be no reply even just doing it on your own link just go to https://jsonformatter.curiousconcept.com/ to run a test you will see yourself 

this is a fresh install 2.6.5 latest version

**Comment by Dave-Morton** [comment]
If this is a problem you might consider using the javascript function `encodeURIComponent()` to change spaces and other characters into something that can be accepted in a browser address bar. jQuery does this automatically when using the `$.ajax()` and `serialize()` functions together, so I've never really bothered to add the extra code (no sense in doing it twice after all).

**Comment by Doorstop2** [comment]
where is the file that does this for the api so i can add this function i cant seem to find it

**Comment by Dave-Morton** [comment]
I have to assume that you're using the JSON format for the bot. Are you using the jquery example for your GUI, or did you write your own?

**Comment by Doorstop2** [comment]
right in the admin panel i have json for the bot and no i do test it with the gui default and it works no problem but my problem is i want to use the api url to output to discord which i can infact i have used your bots api to test this and it works like a charm 

so this is my problem 

i'm a Admin for a big Discord Bot "Proxy is the creator" "Echo" https://echo.xtclabs.net/home.php 

so one of our latest keys {getapi} which only works with json due to discord

echo is a very advanced bot which allows you to build code in discord we call ARS you can build anything

but lets get to the point with my test your free api 

i was able to make this 

//auto &@Echo {params}={init}
{getapi:
{src:http://api.program-o.com/v2/chatbot/?bot_id=6&say={params}&format=json} 
{print:botsay}

the {params} key catches the words and brings it to the other {params} key 

so say i type @echo hello the bot will reply spaces and all work now i wanted to install and build my own api  so i did 

 //auto &@Echo {params}={init}
{getapi:
{src:http://xxxx/prog/chatbot/conversation_start.php?say={params}&format=json
{print:botsay}

also tested 

//auto &echo {params}={init}
{getapi:
{src:xxxxx/prog/chatbot/conversation_start.php?say={params}&format=json
{print:botsay}

so these two ARS does not even matter if these are in discord just go to the direct link if you spell 

Hello bot will reply 

if i say 

Hi hows your day? the json will kill it unless there is "%" now if i do this in your test GUI it works no problem because it seems your program in browser converts this while in discord it does not thus some sort of error 

and another problem i noticed is the bot will make new sessions every time you say something threw the api

**Comment by Dave-Morton** [comment]
If you're using your own version of an API to talk to discord, then I would need to see the code before I could advise you. If you wish to keep such code private, you're welcome to email it to me and I can look it over and make suggestions, but the bottom line is that when your script gets the response from the bot you need to convert that response to a format that Discord can accept. then you should have no difficulty.

With regard to the new session each time, are you setting the session ID (it's a variable called `convo_id` in the query string) and using that each time you send to the bot? 

You may wish to look in the [wiki](https://github.com/Program-O/Program-O/wiki) for the API reference, just so you know what Program O expects, and what it returns. this should  help with that new session issue.

**Comment by Doorstop2** [comment]
thanks for your help i will look into this :D

**Comment by patrickschur** [comment]
@Doorstop2 could you solve your problem?

**Comment by Doorstop2** [comment]
No i have been very busy and don't really have enough time its really just the spacing issue i have tested if i spell hell%how's%your%day? it will work

**Comment by Dave-Morton** [comment]
Perhaps a slight modification to the output portion of the script is in order where if a certain input variable is set (something like '&discord=true" would work) then the spaces are switched with % so that discord doesn't blow a gasket.

**Comment by RunOnSoftware** [comment]
Why would you send a % as a space when the standard is to either use a + or %20?  

e.g.
http://xxxx/prog/chatbot/?bot_id=1&say=hello%20my%20name%20is%20blank&format=json
or
http://xxxx/prog/chatbot/?bot_id=1&say=hello+my+name+is+blank&format=json

**Comment by Program-O** [comment]
I think this is just a mistake from the original poster.
%20 is a space and not %
closing as no comment in over 30 from op
