### ISSUE TITLE
AIML 2.0

### ISSUE THREAD

**Issue by korrio** [Program-O/Program-O#283]
Does programm-o fully support AIML 2.0 or just some new syntax in AIML 2.0 ?

**Comment by patrickschur** [comment]
Currently we are working on a full AIML 2.0 support. Until now Program-O supports only a subset of AIML 2.0.

The supported subset looks like the following:
- input
- date
- condition
- learn
- eval
- bot (within pattern)

**Comment by Dave-Morton** [comment]
Actually, @patrickschur all of those tags mentioned are AIML 1.01 tags, though the `<learn>` and `<eval>` tags were quasi-proprietary to Pandorabots initially. Just sayin' 😉

**Comment by patrickschur** [comment]
`<date>`, `<input>` and the `<bot>` tag within patterns are AIML 2.0 (pandorabot extensions) but ok. ;)
And the condition tag in AIML 2.0 is a little bit different from this in AIML 1.01.

**Comment by Atanacius** [comment]
I admit, AIML 2.0 in Program-O will be amazing !

So please keep up the good work in Program-O by adding full AIML 2.0 Specifications as listed here: 
https://docs.google.com/document/d/1wNT25hJRyupcG51aO89UcQEiG-HkXRXusukADpFnDs4/pub

By the way, also by using specs on Pandorabots: 
http://docs.pandorabots.com/tutorials/substitutions-and-sentence-splitting/

Thanks for all the great works !

(I actually made a Program-O AIML bot for advertising purpose, it works very well, but by using AIML 2.0 specs it will really be far more better than actually !!)

**Comment by Dave-Morton** [comment]
@Atanacius Thanks for your kind words, and for the links. Though we haven't done much with this the past few weeks due to scheduling issues, it's still very much on the ToDo list.

**Comment by Atanacius** [comment]
Thanks for your answer @Dave-Morton it is nice to hear that :)

**Comment by Program-O** [comment]
I would like to add that the version 3 will be fully AIML2.0 compliant and you will be able to create your own tags so you can basically do whatever you want
Keep an eye on the website for announcements 
https://program-o.com/
👍

**Comment by SacDin** [comment]
Is this scheduled ?
