### ISSUE TITLE
importing aiml files into database adds the last category twice

### ISSUE THREAD

**Issue by rwaters71** [Program-O/Program-O#284]
If you import any aiml file to the database, seems the last category in the file is imported twice in the aiml table. This is easily reproducible by simply making a small aiml file with a couple of categories, importing the file, and then looking up the entries in the aiml table.

I don't believe this would cause much of an issue with pattern matching in the grand scheme of things (unless one edits just one of those categories), just noticed it and thought I'd share.

**Comment by Dave-Morton** [comment]
I appreciate that, @rwaters71 - And while it's not earth-shatteringly important, it's something that needs to be looked into. Thanks for bringing it to our attention.

**Comment by patrickschur** [comment]
@rwaters71 Thanks again and thanks for you efforts to make Program-O better. :)
