### ISSUE TITLE
Installation script "forgets" DB username (dev)

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#290]
Just noticed something new. I was testing the installation script and got the following error message:

<pre>
Program O has encountered a problem with connecting to the database. With any luck, the following message will help: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)
</pre>

The username was specified in the forms, but looks like the script "loses" it: `''@'localhost'`.

**Comment by AlekzNet** [comment]
What should the DB username be: adm_dbu or dbu (I found both in install_programo.php)?

**Comment by Program-O** [comment]
$dbu is the db username (for mysql)  
and $adm_dbu is the admin area password

can you just try it again please to make sure it wasnt an error and i will have a look

thanks 
🍡

**Comment by AlekzNet** [comment]
I tried many times ;) (with the same result)

**Comment by Dave-Morton** [comment]
No, this is actually a known issue that I'm actively working on. It seems that my attempt to get the install script to use PDO_functions.php wasn't as successful as I had hoped, and I'm working on fixing the issue. I'll have a bug fix shortly.

**Comment by Dave-Morton** [comment]
I've found and fixed this issue, but forgot to reference it when I pushed the changes. Please download the latest version from the `DEV` branch and let us know how you fare.

**Comment by AlekzNet** [comment]
Yeeeeeeaaahhh! It works now!!!

**Comment by Dave-Morton** [comment]
Glad to hear it. Please let us know if you have any problems, and how you like the new features. 👍
