### ISSUE TITLE
Default <li> in <condition> when the variable is undefined (dev)

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#291]
Let's take the following construction:

```xml
<category>
<pattern>vartest1</pattern>
 <template>
 	<condition name="name1">
 	 	<li value="test1"> Name1 is defined as <get name="name1"/></li>	 	   
 		<li value="*"> Name1 is defined as <get name="name1"/></li>
 		<li>Let's define name1 as test1
                     <think><set name="name1">test1</set></think>
                </li>
    </condition>
    The variable is defined as <get name="name1"/>
 </template>
</category>
```

The result is:

```txt
User: vartest1
Bot: The variable is defined as undefined
```
Question: how to specify a default `<li>`?

As far as I understand the standard (http://www.alicebot.org/TR/2001/WD-aiml/ - 7.3.1.4.1. Default List Items ), it should be `<li>` with no attributes.

**Comment by Dave-Morton** [comment]
You are correct, so this is, indeed, a bug. I'm currently working on the install bug you've reported, but will work on this one after.

**Comment by AlekzNet** [comment]
Aha, actually, the default `<li>` is chosen, but from what I understand, the text is lost:

```txt
24-06-2017 23:43:45.89285[4][4] - Elapsed time: 0.009 milliseconds
[parse_aiml_as_XML.php][parse_condition_tag][944]
Found a match. Pick = <li><text>Let's define name1 as test1                     </text><think><set name="name1"><text>test1</text></set></think></li>
-----------------------
24-06-2017 23:43:45.89286[2][4] - Elapsed time: 0.008 milliseconds
[parse_aiml_as_XML.php][implode_recursive][137]
Imploding an array into a string. (recursively, if necessary)
-----------------------
24-06-2017 23:43:45.89287[4][4] - Elapsed time: 0.008 milliseconds
[parse_aiml_as_XML.php][implode_recursive][155]
The variable $input is of type array
-----------------------
24-06-2017 23:43:45.89287[4][4] - Elapsed time: 0.007 milliseconds
[parse_aiml_as_XML.php][implode_recursive][185]
Imploding complete. Returning ''
-----------------------
24-06-2017 23:43:45.89288[4][4] - Elapsed time: 0.009 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][234]
Adding '' to the response array. tag name is condition
-----------------------

```

**Comment by Dave-Morton** [comment]
So a bug, but not the bug we thought? Ok, I can live with that. As I said, this is next on the list.

**Comment by AlekzNet** [comment]
Looks like this line nullifies the result:

```php
    $children = (is_object($pick)) ? $pick->children() : null;
```
Line 964 in chatbot/core/aiml/parse_aiml_as_XML.php

**Comment by AlekzNet** [comment]
OK, `$pick` is a string, not an array, hence `$children` becomes null. But in this case, the `$result` is also null:

```php
$children = (is_object($pick)) ? $pick->children() : null;

    if (!empty ($children))
    {
        foreach ($children as $child)
        {
            $response[] = parseTemplateRecursive($convoArr, $child, $level + 1);
        }
        runDebug(__FILE__, __FUNCTION__, __LINE__, "Response = " . print_r($response, true), 4);
    }
    else {
        $response[] = '';
    }
```

**Comment by AlekzNet** [comment]
The following change (that was also in the previous versions of parse_aiml_as_XML.php):

```php
    else {
        $response[] = $pick;
    }
```

works, but breaks the further parsing. For example, tags `<think>` are ignored and the result is:

```txt
User: vartest1
Bot: 
* Let's define name1 as test1 test1
The variable is defined as undefined
```
The whole `<li>` statement becomes an HTML `<li>` instead of AIML `<li>`.

So, I'm a bit lost in the logic...

**Comment by Dave-Morton** [comment]
Had to run some errands, but I'm back at this (the other issue is fixed, but I thought to push this fix at the same time, if I can). Thanks for that information. It gives me something to investigate.

**Comment by Dave-Morton** [comment]
Found it! The following line of code:

`$pick = $pick->asXML();`

transforms `$pick` from a SimpleXMLElement into a text string. It's not in earlier versions of the script (at least not one from 2013), so I'm going to see  if I can figure out _WHY_ it's there, and what to put in it's place.

**Comment by Dave-Morton** [comment]
After careful examination of that section of the code, it appears that the best remedy is to just remove that line of code. Doing so fixes the issue and doesn't appear to have any unwanted side effects. This should be watched carefully, and more testing should be done, but I think for the time being I'll just leave that line of code commented out.

**Comment by Dave-Morton** [comment]
Oops? forgot to reference this issue in the push. My bad. It's up, though, and should take care of the problem now.

**Comment by patrickschur** [comment]
We had this issue already... I think. See #169 and #167

**Comment by Dave-Morton** [comment]
From the way I'm reading them, #169 is almost the exact opposite of this issue. #167 may be similar, though.

**Comment by AlekzNet** [comment]
Both #167 and  #169 are about the AIML logic. This one is about programming bugs ;)
