### ISSUE TITLE
Log viewer issues (dev)

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#295]
More weird ones, sorry  ;) Possibly these are known issues, but I could not find them in either open or close ones, so let's keep them here for the "documentation purposes":

1- "Conversation logs" link points to admin/index.php?page=logs what produces WSOD with the following PHP error:

```txt
[25-Jun-2017 20:37:58 UTC] PHP Fatal error:  Uncaught TypeError: 
Argument 1 passed to handle_exceptions() must be an instance of Exception, 
instance of ParseError given in /home/alekz/public_html/o/admin/index.php:557
Stack trace:
#0 [internal function]: handle_exceptions(Object(ParseError))
#1 {main}
  thrown in /home/alekz/public_html/o/admin/index.php on line 557
```

2- "Log file viewer"  asks for the admin name and password. Entering the credentials or clicking on "Reload page"  points to http(s)://... /home/alekz/public_html/o/logs/ - file system path, not the URL.

3- Reloading  logs/index.php after entering the credentials shows "Access denied!" message for a second  (Session/Cookies issue?)

4- "Debug File Viewer" has the same issues, it points to  /home/alekz/public_html/o/chatbot/debug/ and shows "Access denied!"

**Comment by patrickschur** [comment]
Could you remove the line 24-26 in admin/logs.php and try it again? :)

**Comment by AlekzNet** [comment]
These?

```php
    $session_name = 'PGO_Admin';
    session_name($session_name);
    session_start();
```

No changes.

**Comment by AlekzNet** [comment]
BTW, if I point the browser directly to logs.php, I"m getting the following error:

```txt
[25-Jun-2017 22:39:34 UTC] PHP Parse error:  syntax error, unexpected '<<' (T_SL), expecting case (T_CASE)
 or default (T_DEFAULT) or '}' in /home/alekz/public_html/o/admin/logs.php on line 138
```

**Comment by AlekzNet** [comment]
Aha, I think it's a GIT leftover or a  bug. Getting logs.php directly from github...

**Comment by AlekzNet** [comment]
No, no difference.

**Comment by patrickschur** [comment]
Strange... What have you done @Dave-Morton? :D

**Comment by Dave-Morton** [comment]
I honestly don't know, mate. It all works fine for me.

**Comment by AlekzNet** [comment]
Hm, if I'm the only one, then it could be that something is screwed up on my side :D

**Comment by AlekzNet** [comment]
After I redownloaded logs.php the conversation viewer is working now! But the log and debug viewer are still not.

**Comment by Dave-Morton** [comment]
@AlekzNet let me have your server specs again, please. It's been a while and I don't remember them. I'll try it on the closest VM I have, just to make sure.

**Comment by AlekzNet** [comment]
PHP Version 7.1.6-1~ubuntu17.04.1 (deb.sury.org PPA)

A couple of years ago the PHP variables were not auto-initialized properly, and I had to define them manually. But since I changed the server settings everything worked as it should. Until now ;)  

I think it's a good idea to create a Program-O test/diag PHP file that will show how the variables are defined and calculated (using excerpts from the real code). That would greatly simplify the troubleshooting for everybody.

**Comment by patrickschur** [comment]
@AlekzNet Apache or Nginx? Because I'm using Ubuntu 16.04.2 and PHP 7.1.6 and it works fine.

**Comment by AlekzNet** [comment]
Apache. 

OK, I will redownload some files (just in case), and thoroughly check all the variables and settings. If it works for you guys, most likely it's a problem on my side ;)

Thanks much!

**Comment by Dave-Morton** [comment]
@AlekzNet did you get this straightened out?

**Comment by AlekzNet** [comment]
No changes here :( And I was distracted from the test script (as always :D )

**Comment by AlekzNet** [comment]
Actually, the conversation logs stopped working again (getting a white page). Will redownload all files again and start from scratch.

**Comment by Dave-Morton** [comment]
Please keep us informed. 😄

**Comment by AlekzNet** [comment]
Made a clear install (with the old database) - no changes:( 

2- "Log file viewer" asks for the admin name and password. Entering the credentials or clicking on "Reload page" points to http(s)://... /home/alekz/public_html/o/logs/ - file system path, not the URL.

4- "Debug File Viewer" has the same issues, it points to /home/alekz/public_html/o/chatbot/debug/ and shows "Access denied!"

Conversation log works fine.

**Comment by Dave-Morton** [comment]
And you're seeing nothing in the logs? Because I use both viewers on the current `DEV` version on Windows 10 Pro/Apache with no issues at all. I'll check the `MASTER` branch's current version as well.
{time passes}
I just downloaded and installed the latest version of the `MASTER` branch, and again, no issues can be found. So at this point I have no idea what to tell you, other than to try a full, clean download/install of either branch into a new folder and try that. If that also fails, then something in your OS may be broken(?)

**Comment by Dave-Morton** [comment]
Earlier you mentioned a testing/diagnostic script for Program O that would check certain variables and paths. I'd like to discuss this further, just not here. I'm sure you have my email address, but do you also have my Skype handle? Skype is the best way to contact me, as I have it open 24/7. I don't want to give it out here, but if you don't have it please email me and I'll send it to you.

**Comment by Dave-Morton** [comment]
I was actually referring to any log files that might be in the filesystem, rather than through the viewer, since the viewer isn't working. 😄

**Comment by Dave-Morton** [comment]
@AlekzNet is this still an issue, or can we close this? Also, if it's fixed, what were the steps to correct this? Please let me know. Thanks.
