### ISSUE TITLE
tag <get> problem...

### ISSUE THREAD

**Issue by Kineforce** [Program-O/Program-O#297]
Hi people, all right? So... i'm working in a robot of conversation about sustentability, and i'm having a problem to make the tag <get> works, here's the error message : 
![sem titulo](https://user-images.githubusercontent.com/29745011/27619738-059ee0fa-5b9b-11e7-8fd9-7d33adc1baff.png)  

"Error 1868: Element '{http://www.alicebot.org/TR/2001/WD-aiml}set': The attribute 'name' is required but missing. in /home/cedcombr/public_html/claudio/admin/ on line 99, column 0 
<think><set> name="nome">*</set></think>. " I'm Brazilian so, i speak Portuguese, dont mind it please, and i'm don't have much experience in programation, anybody here can help me? 

Ps: Sorry my bad english XD

**Comment by Program-O** [comment]
i am just about to go to bed.....
but what is the full contents of line 99?
let me know and i will get back to you asap

**Comment by Kineforce** [comment]
Oh, problem solved XD, i changed Username to Nameuser, and its works now! Haha
