### ISSUE TITLE
How to match none or more words in user input?

### ISSUE THREAD

**Issue by kishorhase** [Program-O/Program-O#298]
I am working on  Program O Version: 2.6.5 and AIML version 1.0.1.
AIML 1.0 only has * and _ to match 1 or more words, but our requirement is to match 0 or more words.
How we will achieve this requirement?

**Comment by Program-O** [comment]
This actually works as expected in the v3 with the new AIML2 wildcard's tag $ and #
I think the only way you can do this in the v2 is to change the pattern matching in the set_wildcards() function

For example in set_wildcards()
there is a block which builds the pattern that will be used in a regular expression 

$ap = trim($pattern);
    $ap = str_replace("+", "\+", $ap);
    $ap = str_replace(" * ", " (\S*) ", $ap);
    $ap = str_replace(" _ ", " (\S*) ", $ap);
    $ap = str_replace("* ", "(\S*) ", $ap);
    $ap = str_replace("_ ", "(\S*) ", $ap);
    $ap = str_replace(" *", " (.*)", $ap);
    $ap = str_replace(" _", " (.*)", $ap);
    $ap = str_replace("*", "(.*)", $ap);
    $ap = str_replace("_", "(.*)", $ap);
    $ap = str_replace("(\S(.*))", "(.*)", $ap);
    $ap = str_replace("(.(.*))", "(.*)", $ap);
    // Set pattern wildcards
    $pattern_wildcards = str_replace("_", "(.*)?", str_replace("*", "(.*)?", $pattern));

You would need to mess about and with that block until you get it working how you expect
 
1 example would be ....
replace this
$ap = str_replace(" * ", " (\S*) ", $ap);
with either....
str_replace(" * ","(\s.*\s)+/", $ap); matches one or more ' words '
str_replace(" * ","/(\s.*\s)*/", $ap); matches zero or more ' words '


If you need help with building regular expressions or any other general code related questions please can you ask them on the stackoverflow as we are trying to keep the github for bug reporting only....
https://stackoverflow.com/search?q=%22program+o%22

Or even more general questions can be posted on the program o forum.
https://program-o.com/forum/  

Thank you and good luck

**Comment by kishorhase** [comment]
I have modified following function
file name:  chatbot/chatbot/core/aiml/pase_aiml.php 
function name : set_wildcards

function set_wildcards($convoArr, $pattern, $type){
	......
	$ap = trim($pattern);
	$ap = str_replace("+", "+", $ap);
	//$ap = str_replace(" * ", " (\S*) ", $ap);
	$ap = str_replace(" * ","/(\s.\s)*/", $ap); //matches zero or more ' words '
	$ap = str_replace(" _ ", " (\S*) ", $ap);
	$ap = str_replace("* ", "(\S*) ", $ap);
	$ap = str_replace("_ ", "(\S*) ", $ap);
	$ap = str_replace(" ", " (.)", $ap);
	$ap = str_replace(" ", " (.)", $ap);
	$ap = str_replace("", "(.*)", $ap);
	$ap = str_replace("", "(.)", $ap);
	$ap = str_replace("(\S(.))", "(.)", $ap);
	$ap = str_replace("(.(.))", "(.)", $ap);
	// Set pattern wildcards
	$pattern_wildcards = str_replace("_", "(.)?", str_replace("", "(.)?", $pattern));
	.....
}

Please find the details...
 
AIML File : 

<?xml version="1.0" encoding="UTF-8"?>
<aiml version="1.0.1" xmlns="http://www.alicebot.org/TR/2001/WD-aiml">
    <category>
        <pattern>Hi</pattern>
        <template>Please provide your name. <think>
                <set name="topic">userinfo</set>
            </think>
        </template>
    </category>
    <topic name="userinfo">
        <category>
            <pattern>*</pattern>
            <template>
                <think>
                    <set name="name">
                        <lowercase>
                            <star/>
                        </lowercase>
                    </set>
                </think>
                Hello <get name="name"></get>, how may I help you? <think>
                    <set name="topic">start</set>
                </think>
            </template>
        </category>
    </topic>
    <topic name="start">
        <category>
            <pattern> * apply * job * </pattern>
            <template>
                <srai>Career Information</srai>
            </template>
        </category>
        <category>
            <pattern> * register * job * </pattern>
            <template>
                <srai>Career Information</srai>
            </template>
        </category>
        <category>
            <pattern> * submit * application * </pattern>
            <template>
                <srai>Career Information</srai>
            </template>
        </category>
        <category>
            <pattern> * send * resume * </pattern>
            <template>
                <srai>Career Information</srai>
            </template>
        </category>
        <category>
            <pattern>Career Information</pattern>
            <template>Please check our portal careers page. i.e. example.com or click <a href="http://example.com" target="_blank">here</a>
            </template>
        </category>
    </topic>
</aiml>


User might be enter query following ways ... 

Where do I go to apply for a job?
apply for new job
apply job
How do I register for a job? 
rgister job
Where do I submit my job application?
How do I submit a job application? 
Where do I send my resume/CV? 

For all query result should be same : Please check our portal careers page. i.e. example.com or click <a href="http://example.com" target="_blank">here</a>

**Comment by Program-O** [comment]
did this your AIML file or did you copy it?

i followed the pattern of conversation

elizabeth: hi
test: Please provide your name.

elizabeth: elizabeth
test: Hello elizabeth, how may I help you?

elizabeth: how can i apply for a job?
test: Please check our portal careers page. i.e. example.com or click here

which works....
instead of changing the core of program o which is pretty advanced just do the simple thing of changing your aiml file

from this to this
  <topic name="start">
          <category>
              <pattern> * apply * job * </pattern>
              <template>
                  <srai>Career Information</srai>
              </template>
          </category>
          
     ..... etc etc

to ADD this as well

  <topic name="start">
          <category>
              <pattern> * apply * job * </pattern>
              <template>
                  <srai>Career Information</srai>
              </template>
          </category>
 <category>
              <pattern> * apply * job</pattern>
              <template>
                  <srai>Career Information</srai>
              </template>
          </category>
          
     ..... etc etc
