### ISSUE TITLE
Error on detecting proper responses on aiml that does not have blankspaces

### ISSUE THREAD

**Issue by bvcrisostomo2** [Program-O/Program-O#308]
I tested this on different workstations and the problem persists.

Uploading a <pattern> that does not have blank spaces will make the bot unable to read it and gives out the Error response message. For e.g.

<pattern>Hi</pattern> will make the bot respond the error response message
where as:
<pattern>Hi there</pattern> will make the bot respond on whats in the <template>

This happens on bot with id's 2 and above.

**Comment by Dave-Morton** [comment]
Hi, Brian, and thanks for letting us know about your difficulty.

I have to admit that what you've posted makes little sense to me. If you could provide us with some additional information it would be a huge help. Please read [this wiki post](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to learn what information is needed and how to obtain it. It's also important to know whether you're using the `MASTER` branch or `DEV`, as the code is very different in some places.

**Comment by bvcrisostomo2** [comment]
Further more when you add string/s after the white space e.g.

pattern: Hi there
template: Hello
It will work on bot id's 1 and 2

**Comment by Dave-Morton** [comment]
How are you testing bot 2? Are you changing the URL to include `bot_id=2`? And can you please post a debug file where the response is not working so that I can see what's going on? Thanks.

**Comment by ShaneMcCusker** [comment]
I am also seeing this issue. AIML with a single word pattern works with bot_id = 1 but does not work with bot_id = 2.

**Comment by bvcrisostomo2** [comment]
I tried changing the url to use bot_id=2, didn't work. And I have tried using the select dropdown.
There is no actual error page, it's just that the Bot responds with the default error response message.

**Comment by Dave-Morton** [comment]
Ok, two questions:
1. Did you make bot 2 a child of bot 1 to see if that had any effect?
2. Did you make sure when uploading AIML for bot 2 that you had already selected that chatbot in the bot selection screen?

**Comment by patrickschur** [comment]
I tested this on my machine. I made exactly what you did + I made one bot a child of another and it works like a charm. Looks like you have to use the DEV branch.

The dev branch is **74** commits ahead of the master. Possible there was a bug fix. :)

**Comment by Dave-Morton** [comment]
That's entirely likely, @patrickschur. I think that once I get my development computer back online I'll see about merging branches. It's well past time for that, I think.

**Comment by bvcrisostomo2** [comment]
1. I made bot 2 child of bot 1, and it works, thanks!
2. Yes I've made sure that I am uploading the AIML files on the selected bot (bot 2).

I'll try using the dev branch, if the same thing happens

**Comment by Dave-Morton** [comment]
I'm hoping that no further input on this issue is a good thing, so I'm closing this issue. If you're still having trouble, please start another issue, with more details (if possible). thanks.
