### ISSUE TITLE
parse_aiml_as_XML.php error

### ISSUE THREAD

**Issue by tbenjis** [Program-O/Program-O#309]
This error occurs for all users and does not update user_name field. This error makes it difficult to track conversation logs as they always show `#seeker` for all users.
```
Bad SQL encountered in file /home/tbenjis/bot/chatbot/core/aiml/parse_aiml_as_XML.php, line #551. SQL:
UPDATE `bot`.`users` SET `user_name` = 'zach' WHERE `id` = 27;
PDO Error:
Array
(
    [0] => 00000
    [1] => 
    [2] => 
)

PDOStatement Error:
Array
(
    [0] => HY093
    [1] => 
    [2] => 
)

Exception Message:
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens;
Parameters:
Array
(
    [:user_id] => 27
    [:escaped_var_value] => zach
)
```

**Comment by Dave-Morton** [comment]
@tbenjis  it would be helpful to know the Program O version, etc. and whether it's from the `MASTER` or `DEV` branches. If you could provide that information it would help us to help you.

**Comment by tbenjis** [comment]
its from the dev branch the current version as of today.

**Comment by Dave-Morton** [comment]
Thanks. I'll look into it.

BTW, I'll be visiting @Program-O today (in person!), and will be away from my computer from tomorrow (July 31, 2017) until late August. I'm going on vacation, and moving to Maryland, so will not be available until then. I'll have my laptop, so can check in, but won't be able to work on bugs till I'm back online.

**Comment by tbenjis** [comment]
That's fine, I'll try to provide more details as I can.

**Comment by Dave-Morton** [comment]
It might help if you could provide the debug file, and what OS you're using (though the debug file contains this information).

**Comment by Dave-Morton** [comment]
Never mind. I see the problem. I'll have a fix for it shortly.

**Comment by tbenjis** [comment]
oh great!

**Comment by Dave-Morton** [comment]
I just pushed the fix. Download it again and give it a try.

**Comment by tbenjis** [comment]
yes works now.

**Comment by Dave-Morton** [comment]
Glad to hear it. 👍

**Comment by patrickschur** [comment]
@Dave-Morton 
> Thanks. I'll look into it.
>
> BTW, I'll be visiting @Program-O today (in person!), and will be away from my computer from tomorrow > (July 31, 2017) until late August. I'm going on vacation, and moving to Maryland, so will not be available > until then. I'll have my laptop, so can check in, but won't be able to work on bugs till I'm back online.

It's ok, I'm here. :D
