### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by tbenjis** [Program-O/Program-O#311]
Noticed spellcheck does not work because of the use of `commonWords` instead of `spellcheck_common_words` in `chatbot/addons/spell_checker/spell_checker.php`. Line 24

**Comment by Dave-Morton** [comment]
Um... All I can say here is "Ooops?" 

This isn't enough to do a full push on, given that I'm shutting my computer down when I finish this post, but I'm assuming that you've swapped out `commonWords` with `spellcheck_common_words` to correct your version and it's working as expected?

I've already made the change to my local `DEV` branch, but I'll hold off pushing it until I have more improvements/fixes to publish. If you're still having trouble with this, please post back with details. Thanks.

**Comment by patrickschur** [comment]
Spellcheck works just fine. Program-O uses a variabled called `$_SESSION['commonWords']` defined in the global config file to do spellchecking.

The right approach would be to remove line 19-22. :)

**Comment by tbenjis** [comment]
Yes this is true. I noticed the problem is that the commonWords.dat file contains single letters such as t or u which prevents the spellcheck from working. Resolving this would be replacing the commonWords.dat file with the spellcheck_common_words.dat file.

Also there is no need for line 19-22.

**Comment by patrickschur** [comment]
@tbenjis 
> Also there is no need for line 19-22. $_SESSION['spellcheck_common_words'] doesn't seem to be used anywhere in the script.

This is what I've already said. ;)

Anyway I fixed the issue. Please let me know if you find more issues and thanks for your help. :)
