### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by YairHadari** [Program-O/Program-O#312]
Hi,

The link to the documentation at https://github.com/Program-O/Program-O/wiki/Program-O-v2-Documentation is missing.

Can you please assist?

Thanks,
Yair

**Comment by patrickschur** [comment]
Hi, it was taken down. The site was just an automatic generated documentation about all functions used in Program-O.

If you're looking for the real documentation use the [wiki](https://github.com/Program-O/Program-O/wiki). ;)

**Comment by YairHadari** [comment]
Thanks Patrick!!!
Is there any starter guide for beginners?

Yair

On Aug 1, 2017 11:57, "Patrick Schur" <notifications@github.com> wrote:

Hi, it was taken down. The site was just an automatic generated
documentation about all functions used in Program-O.

If you're looking for the real documentation use the wiki
<https://github.com/Program-O/Program-O/wiki>. ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Program-O/Program-O/issues/312#issuecomment-319311339>,
or mute the thread

**Comment by Dave-Morton** [comment]
There isn't yet, as such, but one is in the works. Probably by the end of the year we should have something in place. Right now, myself and @Program-O are on holiday for a few weeks (not together, though we got to meet up last Sunday), so won't be actively contributing for a while, but @patrickschur will still be here to answer any questions or respond to any issues that present themselves.

**Comment by Program-O** [comment]
I was considering putting the documentation back online but it is so out of date after all the changes it is not worth it.
As it will take too long to update it.
Version 3 documentation is being written as we speak so we do not make the same mistake twice
apologies and thank you for your understanding
