### ISSUE TITLE
Database connection port setting ignored by install script

### ISSUE THREAD

**Issue by pluton-house** [Program-O/Program-O#316]
Hi,

When attempting to use a MySQL database port other than the default 3306, the alternative port is ignored by the install script and the installation fails.

**Comment by Dave-Morton** [comment]
Thanks, Clive. We'll get this handled shortly. We don't generally do pull requests into the `MASTER` branch, however. We mainly try to put them into the `DEV` branch instead, so any future PR's should be handled there. Just a friendly heads up. 😄

**Comment by patrickschur** [comment]
Ok I made the PR into the `DEV` branch. 
If there is nothing else I would close this issue now.

**Comment by Dave-Morton** [comment]
Nope. We're good to go, @patrickschur. Thanks for your efforts. :)

**Comment by pluton-house** [comment]
OK thanks for accepting my contribution, That makes a lot of sense! I'll know better for next time...
