### ISSUE TITLE
I have this issue : There was an error moving the file.

### ISSUE THREAD

**Issue by alex5505** [Program-O/Program-O#325]
[admin.error copy.log.txt](https://github.com/Program-O/Program-O/files/1271657/admin.error.copy.log.txt)

**Comment by Dave-Morton** [comment]
The overwhelming theme that I'm seeing in that error log is this:

`failed to open stream: Permission denied`

in your `uploads` folder. I recommend verifying that the `uploads` folder has not only the correct permissions, but also the correct owner/group settings as well. They should have the same owner and/or group as the web server does, as well as read/write permissions (execute isn't needed for that directory). 
given the directory structure I'm seeing in the file path I have to assume a *nix OS, but as to which I have no clue, so I'll leave the implementation of my recommendation up to you. Please let me know what you find.

**Comment by alex5505** [comment]
I am on mac

On Sep 2, 2017 03:14, "Dave Morton" <notifications@github.com> wrote:

The overwhelming theme that I'm seeing in that error log is this:

failed to open stream: Permission denied

in your uploads folder. I recommend verifying that the uploads folder has
not only the correct permissions, but also the correct owner/group settings
as well. They should have the same owner and/or group as the web server
does, as well as read/write permissions (execute isn't needed for that
directory).
given the directory structure I'm seeing in the file path I have to assume
a *nix OS, but as to which I have no clue, so I'll leave the implementation
of my recommendation up to you. Please let me know what you find.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Program-O/Program-O/issues/325#issuecomment-326712553>,
or mute the thread

**Comment by Dave-Morton** [comment]
OS X is still a flavor of Linux, so my assumption and suggestions still stand. But that gives me a bit more to go by, so I can get a little more specific with my suggestions. [This StackOverflow article](https://stackoverflow.com/questions/2001881/correct-owner-group-permissions-for-apache-2-site-files-folders-under-mac-os-x) should help with setting proper permissions for your server's DOCUMENT_ROOT folder, and it can also be applied to your Program O directory and it's children. Give that a try, then let me know how it goes.

**Comment by alex5505** [comment]
Ok thank you

On Sep 2, 2017 13:48, "Dave Morton" <notifications@github.com> wrote:

OS X is still a flavor of Linux, so my assumption and suggestions still
stand. But that gives me a bit more to go by, so I can get a little more
specific with my suggestions. This StackOverflow article
<https://stackoverflow.com/questions/2001881/correct-owner-group-permissions-for-apache-2-site-files-folders-under-mac-os-x>
should help with setting proper permissions for your server's DOCUMENT_ROOT
folder, and it can also be applied to your Program O directory and it's
children. Give that a try, then let me know how it goes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Program-O/Program-O/issues/325#issuecomment-326739425>,
or mute the thread

**Comment by Dave-Morton** [comment]
Touching base on this. Have my suggestions helped?

**Comment by Dave-Morton** [comment]
I'm guessing from the silence that this is no longer an issue, so I'm closing this issue. If it still plauges you we can reopen it. Just reply. :)
