### ISSUE TITLE
AIML is not being recognized for any new bot that is created

### ISSUE THREAD

**Issue by hesomWela** [Program-O/Program-O#331]
We have one chatbot (id = 1) and have AIML for it. That one works great. I am in the process of creating a new one (id = 2) and whatever I do, I can not get it to response to the AIML I am entering for that bot. Any ideas?

**Comment by quiraang** [comment]
Have you got the bot_id in the url??

Eg example.com/gui/jquery/? Bot_id=2

**Comment by hesomWela** [comment]
@quiraang yep, bot_id=2&say=start&convo_id=jln39isvl980t8pvrtvo60bfti&format=json

**Comment by quiraang** [comment]
Ok, have you loaded aiml into the second bot

**Comment by quiraang** [comment]
I made the two mistakes above

**Comment by hesomWela** [comment]
yes. On my testing environment, I updated to the latest version (2.6.7) and it seemed to have resolved the issue. On prod, I am on version 2.6.5. 

When you create a new bot, is there something I need to do to activate/kick start it?

**Comment by Dave-Morton** [comment]
When you create a new chatbot, you should make sure that the new bot is selected in the admin before continuing. From time to time (not often) the bot selection screen needs to be "reminded" which bot you're working on. Once you've ensured that you're working with the correct bot, then add the bot personality settings, then either upload any AIML categories you have for that bot, or begin teaching it. Once you get that done, all you have to do is make sure that the interface page that you're using knows which bot to talk to, and you should be in good shape.
