### ISSUE TITLE
API break or down?

### ISSUE THREAD

**Issue by Jorisvideo** [Program-O/Program-O#333]
Hello for some day the api does not seem to respond is it break on the use I do it does not work anymore :(

![image](https://user-images.githubusercontent.com/23628673/31995568-4505b712-b985-11e7-8ba2-8a308cec83a7.png)

Can we get info on the V3 with a docs to use it?
Sorry for my bad english

**Comment by TheShooter71** [comment]
Hello, I confirm what Joris says! Your API is down

**Comment by Program-O** [comment]
Thank you for reporting that.
Thankfully the v3 demo is working I will get on it and see what happened to the the v2.
There is currently a server migration going on so hopefully its just that,
also it does stop responding when under high load
i will get back to you soon

**Comment by Program-O** [comment]
Hi there,
This has been fixed now .... thanks again for reporting it 💃
