### ISSUE TITLE
API JSON with characters unicode 

### ISSUE THREAD

**Issue by Javac7** [Program-O/Program-O#334]
I am from Brazil and am having a charset problem when I am going to use the file "conversation_start.php".
Words that have accentuation are coming with strange charset. Can you help me? Thank you!

Link: http://localhost/program-o/chatbot/conversation_start.php?bot_id=1&say=hello

JSON: 
{"convo_id":"0tnc6vi9icmmopsuftaebuk830","usersay":"hello","botsay":"N\u00e3o entendi, desculpe.","data":{"convo_id":"0tnc6vi9icmmopsuftaebuk830","bot_name":"ChatoBot","bot_id":"1","format":"json","unknown_user":"Aluno","user_id":"172","totallines":1,"user_name":"Aluno","conversation_lines":"1","remember_up_to":"10","debugemail":"botmaster@mail.com","debug_level":"4","debugmode":1,"save_state":"session","default_aiml_pattern":"RANDOM PICKUP LINE","bot_parent_id":"1","rawSay":"hello","data":{"aiml_id":"-1","bot_id":"1","pattern":"no results","thatpattern":"","template":"N\u00e3o entendi, desculpe.","topic":"","score":261,"track_score":"current bot, no thatpattern to match, common word match: no, uncommon word match: results"}}}

See the index "botsay", the original response is "Não entendi, desculpe". 
but I get "N\u00e3o entendi, desculpe." 

My file "global_config.php" is set to UTF-8 charset.

**Comment by Dave-Morton** [comment]
I just tested that expected response by creating an AIML category with `Não entendi, desculpe` for both the pattern and the template (with minor modifications to the pattern, of course), and got "Não entendi, desculpe" for a response with my local install of Program O, so something seems to be amiss with your install, OR your AIML. Since I don't have any information on your Program O install (e.g. OS, server software & version, PHP version, etc.), I'm just guessing here, but I think that your AIML may have been added as ASCII encoded text. This can happen if your AIML file is ASCII encoded, rather than encoded in UTF-8. It's not just Program O that has to use UTF-8 encoding when using non-English characters; it's the AIML files themselves that also must use the encoding, as well. I suggest checking that out, and if that doesn't correct the problem, post back with the information I listed about your Program O install, and we can investigate further. Another thing that you can do is to go into the admin page for Program O, click on "Teach", and enter in "NÃO ENTENDI DESCULPE" for the pattern, and "Não entendi, desculpe" for the template, then test it in your chatbot's UI, and see what comes out. If it comes back as "Não entendi, desculpe", then you know it's not Program O, but your AIML. You can also look at the category in the admin page's Search/Edit AIML panel, and see what it looks like there, making corrections if you find something out of place. That's about the best I can offer right now. If you follow my advice here and it still fails to output the correct text, then more information will help.

**Comment by Javac7** [comment]
I installed and configured everything again, but I was not lucky because I came across the same error, see below: 

JSON:
{"convo_id":"cd6b89ih14si96pf5m90vmm9v0","usersay":"hello","botsay":"N\u00e3o entendi, desculpe.","data":{"convo_id":"cd6b89ih14si96pf5m90vmm9v0","bot_name":"ChatoBot","bot_id":1,"format":"json","unknown_user":"Seeker","user_id":"3","totallines":1,"user_name":"Seeker","conversation_lines":"1","remember_up_to":"10","debugemail":"allyson.martinz@gmail.com","debug_level":"1","debugmode":1,"save_state":"session","default_aiml_pattern":"RANDOM PICKUP LINE","bot_parent_id":"1","rawSay":"hello","data":{"aiml_id":"-1","bot_id":1,"pattern":"no results","thatpattern":"","template":"N\u00e3o entendi, desculpe.","topic":"","score":261,"track_score":"current bot, no thatpattern to match, common word match: no, uncommon word match: results"}}}


I'm trying to print directly in the browser.

My server: 
Server:  Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/5.6.31
Xampp version: 3.3.2

Thank you!

**Comment by Javac7** [comment]
When I access page http://localhost/Program-O/gui/jquery/?bot_id=1 the json comes all correct, but when I try to directly access the file http://localhost/program-o/chatbot/conversation_start.php?say=hello to write directly to the browser, the answer comes wrong. Why???

**Comment by Dave-Morton** [comment]
Two things: 
1. which browser?
2. Do you know how to check headers in your browser's console environment?

Also, have you tried to follow my suggestion about creating an AIML category within Program O to see how it responds? If so, how did that response look? If not, please try it so that we know how it turns out. This is an important troubleshooting step, and it will be difficult to find the cause of your problem without knowing the outcome of that test.

**Comment by Javac7** [comment]
My browser: Google  Chrome 
Version 61.0.3163.100 (oficial version) 64 bits

See my console below: 

Preview => {convo_id: "toladtmg3oni29hma07m4foqi3", usersay: "hello", botsay: "Não entendi, desculpe.",…}
botsay: "Não entendi, desculpe."
convo_id:"toladtmg3oni29hma07m4foqi3"

Response => {"convo_id":"toladtmg3oni29hma07m4foqi3","usersay":"hello","botsay":"N\u00e3o entendi, desculpe.","data":{"convo_id":"toladtmg3oni29hma07m4foqi3","bot_name":"ChatoBot","bot_id":1,"format":"json","unknown_user":"Seeker","user_id":"11","totallines":1,"user_name":"Seeker","conversation_lines":"1","remember_up_to":"10","debugemail":"allyson.martinz@gmail.com","debug_level":"1","debugmode":1,"save_state":"session","default_aiml_pattern":"RANDOM PICKUP LINE","bot_parent_id":"1","rawSay":"hello","data":{"aiml_id":"-1","bot_id":1,"pattern":"no results","thatpattern":"","template":"N\u00e3o entendi, desculpe.","topic":"","score":261,"track_score":"current bot, no thatpattern to match, common word match: no, uncommon word match: results"}}}


Headers =>
Request URL:http://192.168.1.12/Program-O/chatbot/conversation_start.php?say=hello
Request Method:GET
Status Code:200 OK
Remote Address:192.168.1.12:80
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Access-Control-Allow-Origin:*
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Length:740
Content-Type:text/plain; charset=utf-8
Date:Tue, 31 Oct 2017 23:33:59 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=5, max=100
Pragma:no-cache
Server:Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/5.6.31
Set-Cookie:PGOv2.6.7=toladtmg3oni29hma07m4foqi3; path=/
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-Powered-By:PHP/5.6.31
x-server-os:Windows NT - build 9200 (Windows 8 Professional Edition)
X-XSS-Protection:1; mode=block


Why my response show strange characters?

**Comment by Javac7** [comment]
Sr. Dave, Look my array $convoArr

Array ( [conversation] => Array ( [convo_id] => tgk6d5q84f2svcglghgodol624 [bot_name] => ChatoBot [bot_id] => 1 [format] => json [unknown_user] => Seeker [user_id] => 56 [totallines] => 1 [user_name] => Seeker [conversation_lines] => 1 [remember_up_to] => 10 [debugemail] => allyson.martinz@gmail.com [debug_level] => 1 [debugmode] => 1 [save_state] => session [default_aiml_pattern] => RANDOM PICKUP LINE [bot_parent_id] => 1 [rawSay] => hello [data] => Array ( [aiml_id] => -1 [bot_id] => 1 [pattern] => no results [thatpattern] => [template] => Não entendi, desculpe. [topic] => [score] => 261 [track_score] => current bot, no thatpattern to match, common word match: no, uncommon word match: results ) ) [client_properties] => Array ( [ip_address] => 192.168.1.12 [name] => Seeker ) [time_start] => 1509496121.0332 [aiml] => Array ( [user_raw] => hello [lookingfor] => HELLO [pattern] => no results [thatpattern] => [template] => Não entendi, desculpe. [html_template] => [topic] => [score] => 261 [aiml_id] => -1 [stars] => Array ( ) [parsed_template] => Não entendi, desculpe. ) [user_say] => Array ( [1] => HELLO [2] => [3] => [4] => [5] => [6] => [7] => [8] => [9] => [10] => ) [input] => Array ( [1] => hello [2] => [3] => [4] => [5] => [6] => [7] => [8] => [9] => [10] => ) [that_raw] => Array ( [1] => Array ( [1] => [2] => Não entendi, desculpe. ) [2] => [3] => [4] => [5] => [6] => [7] => [8] => [9] => [10] => [12] => ) [that] => Array ( [1] => Array ( [1] => NÃO ENTENDI DESCULPE ) [2] => [3] => [4] => [5] => [6] => [7] => [8] => [9] => [10] => [12] => ) [parsed_template] => Array ( [1] => Não entendi, desculpe. [2] => [3] => [4] => [5] => [6] => [7] => [8] => [9] => [10] => ) [template] => Array ( [1] => Não entendi, desculpe. [2] => [3] => [4] => [5] => [6] => [7] => [8] => [9] => [10] => ) [send_to_user] => {"convo_id":"tgk6d5q84f2svcglghgodol624","usersay":"hello","botsay":"N\u00e3o entendi, desculpe.","data":{"convo_id":"tgk6d5q84f2svcglghgodol624","bot_name":"ChatoBot","bot_id":1,"format":"json","unknown_user":"Seeker","user_id":"56","totallines":1,"user_name":"Seeker","conversation_lines":"1","remember_up_to":"10","debugemail":"allyson.martinz@gmail.com","debug_level":"1","debugmode":1,"save_state":"session","default_aiml_pattern":"RANDOM PICKUP LINE","bot_parent_id":"1","rawSay":"hello","data":{"aiml_id":"-1","bot_id":1,"pattern":"no results","thatpattern":"","template":"N\u00e3o entendi, desculpe.","topic":"","score":261,"track_score":"current bot, no thatpattern to match, common word match: no, uncommon word match: results"}}} )

Why in array i get "Não entendi, desculpa" and in ['send_to_user'] i get "N\u00e3o entendi, desculpe." ???

**Comment by Javac7** [comment]
Solved problem See below: 

//display_conversation($convoArr);  original line commented.

/* decoding and encoding of the array again */
$vetor = array();
$vetor['resposta'] = $jsonParaVetor = array(json_decode($display,TRUE));
$resposta = json_encode($vetor,JSON_UNESCAPED_UNICODE);
print_r($resposta);

**Comment by Dave-Morton** [comment]
I'm glad you got it working, and I'll put that fix in as soon as I come up with variable names that I can understand (I suspect that what you have there are Portuguese for "vector" and "reset", but those aren't as descriptive of the process as I would like). 😄

**Comment by Dave-Morton** [comment]
As a side note, this will NOT work in PHP versions lower than 5.4.0, so those with PHP versions from 5.3.0 to 5.3.29 will receive not only no benefit from this fix, it *may* break your install, so be warned. PHP only supports version 5.6.0 and above anyway, so if you have an older version, it's time to upgrade.
