### ISSUE TITLE
Remote installation issue

### ISSUE THREAD

**Issue by CptCurty** [Program-O/Program-O#339]
First of all, I would like to thank all the contributors  for making this amazing AIML interpreter. Unfortunately I have a little issue. First I only had my bot on localhost, but recently I decided to put it on an online domain. I ran a clean install and almost everything worked. But what I noticed was that when I used <set name = 'name'><star/></set> to save the users name, the displayed username remained Seeker.  I don't have this problem on my localhost, even though they use the same AIML files. Another thing is that the online bot doesn't display the Current Github version. What do you think the issue is?
Version 2.6.7
master branch
Windows 10 
PHPmyAdmin 
PHP version 7.1.11
edit: I use session to save variables but somehow when I start-up the bot, it knows the last saved username .
Greetings CptCurty

**Comment by MrAlicard** [comment]
Do you use JSON? Because I have sometimes also this problem and sometimes I get undefined.
If you use json gui then update once again the unknow name part and delete 2 cookie which are Program_O_JSON_GUI. Then test again your bot. You will see it works. 😄 I know this is not good solution, I only mentioned. 😀 

But probably, your bot doesn't work properly because other reasons. 🤔

**Comment by Dave-Morton** [comment]
Greetings! I'm sorry that you're having this issue. Can you please provide the server specs for your remote Program O install? that will help me to try to duplicate the problem. I'm assuming that the specs you've provided are for your local machine. :)

**Comment by CptCurty** [comment]
Yes the provided specs are indeed for my local machine. 
So I had to look up the server information and I am not sure what information you require.
But it uses plesk and has:
 4 vCores;
 8 GB of guaranteed RAM;
 IPv6;
 Ubuntu 14.04 LTS;
400GB HP 3PAR storage

**Comment by Dave-Morton** [comment]
What I need for the server specs is this:

OS/version: (already provided, thanks)
PHP version: (5.4+ required)
Program O version: (also already provided, assuming it's the same version for your local setup)

Also, a detailed, specific list of symptoms that you're experiencing would help, and whether there are any log files being generated. the logs are in the logs directory, of course. 😉

**Comment by CptCurty** [comment]
PHP version 7 is used. So in the logs file parse_aiml_as_XML.php.parse_set_tag.error.log i get multiple errors. Bad SQL encountered in file  ../Program-O-master/chatbot/core/aiml/parse_aiml_as_XML.php, line #551 and  Base table or view not found: 1146 Table 'terminator.users' doesn't exist. And in install_programo.php.Save.error: Bad SQL encountered in file ../Program-O-master/install/install_programo.php, line #304. SQL:
CREATE TABLE IF NOT EXISTS `users` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_name` text NOT NULL, `session_id` varchar(256) NOT NULL, `bot_id` int(11) NOT NULL, `chatlines` int(11) NOT NULL, `ip` varchar(100) NOT NULL, `referer` text NOT NULL, `browser` text NOT NULL, `date_logged_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `state` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
PDO Error:
Array
(
    [0] => 00000
    [1] => 
    [2] => 
)

PDOStatement Error:
Array
(
    [0] => HY000
    [1] => 1293
    [2] => Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
)

Exception Message:
SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause;
Parameters:
****
And in admin.error.log: 
PHP Warning:  curl_exec() has been disabled for security reasons in ../Program-O-master/admin/index.php on line 539

And the symptoms are:
I don't see the Github version on the admin page;
Somehow the name of the last user returns when I start a new conversation(only verbally the displayed name still is seeker);

**Comment by Dave-Morton** [comment]
Well, THAT'S a first. That same table structure has been unchanged since version 2.0 and I've never encountered that error before. This leads me to wonder what MySQL version your server is running. Either way, I can probably edit the SQL file that contains that query and edit it so that there is only one `timestamp` column. The `date_logged_on` field can just be a VARCHAR probably. I don't know. I'll have to think on this.

**Comment by Dave-Morton** [comment]
AHA! I see why this is. On MySQL versions prior to 5.6.5 this was a thing to worry about, but no longer. If your MySQL version on your remote server is lower than that, I strongly recommend asking your hosting provider to upgrade. If this is not possible, there is another workaround, but it's a bit convoluted. Please let me know when you can. thanks.

**Comment by CptCurty** [comment]
Ah yes, MYSQL version is 5.5.58 , I requested an update and I will see what that will bring me. 
Thanks in advance!

**Comment by Dave-Morton** [comment]
No worries. Love to help. You **DO** realize, of course, that once/if your hosting provider upgrades, you'll have to do a full, clean install of Program O again, preferably to a clean, empty database. Just a heads up. 😄

**Comment by CptCurty** [comment]
I have clean installed it a couple of times now, so it should go fairly quickly, haha. I appreciate your help, and of course your contribution to Program-O. Just a quick question, when/is Version 3 going online?
 I would love to use AIML 2 !

**Comment by CptCurty** [comment]
So I did everything, and it works! At least the user name problem. I now get this when I first load HTML chat : 
14-11-2017 19:30:43.61961[0][2] - Elapsed time: 0.475 milliseconds
[conversation_start.php][Called outside of function][57]
Conversation starting. Current system specs:
  Program O version:            2.6.7
  Server Software:              Apache
  PHP Version:                  7.1.11
  OS:                           Linux
  OS Version:                   #1 SMP Fri Sep 1 20:42:18 MSK 2017
  MySQL Version:                5.6.38
  Multi-byte functions enabled: true 
-----------------------
14-11-2017 19:30:43.62124[0][2] - Elapsed time: 1.636 milliseconds
[conversation_start.php][Called outside of function][124]
Debug level: 2
session ID = 8v6e92pbiha6d1fehm06enqcrd 
-----------------------
14-11-2017 19:30:43.62144[2][2] - Elapsed time: 0.201 milliseconds
[handle_user.php][load_new_client_defaults][24]
Loading client defaults 
-----------------------
14-11-2017 19:30:43.62146[2][2] - Elapsed time: 0.016 milliseconds
[conversation_start.php][Called outside of function][260]
Conversation intialised waiting user 
-----------------------
14-11-2017 19:30:43.62147[2][2] - Elapsed time: 0.012 milliseconds
[conversation_start.php][Called outside of function][266]
Closing Database 
-----------------------
14-11-2017 19:30:43.62148[2][2] - Elapsed time: 0.007 milliseconds
[PDO_functions.php][db_close][61]
This DB is now closed. You don't have to go home, but you can't stay here. 
-----------------------
14-11-2017 19:30:43.62154[0][2] - Elapsed time: 0.062 milliseconds
[conversation_start.php][Called outside of function][273]
Conversation Ending. Elapsed time: 2.400 milliseconds. 
-----------------------
Debug Level: 2
-----------------------
Debug Mode: 2
-----------------------
CONVERSATION ARRAY
-----------------------
Array
(
    [conversation] => Array
        (
        )

    [aiml] => 
    [topic] => Array
        (
            [1] => 
        )

    [that] => Array
        (
            [1] => 
        )

    [input] => Array
        (
            [1] => 
        )

    [stack] => Array
        (
            [top] => om
            [last] => om
        )

    [client_properties] => Array
        (
            [name] => Seeker
            [id] => 8v6e92pbiha6d1fehm06enqcrd
        )

    [user_say] => Array
        (
            [1] => 
        )

    [that_raw] => Array
        (
            [1] => 
        )

    [parsed_template] => Array
        (
            [1] => 
        )

)

-----------------------
Total execution time: 2.400 Milliseconds. Goodbye.
Program O Example GUI Page - HTML

**Comment by Dave-Morton** [comment]
As would we all. I only just got a peek at the PRE-alpha code a couple of days ago. It looks promising, but it's a long way from being ready. In version 3, BTW, the API will be stand-alone, with the admin being a separate package. I'm not sure when either of them will be released, but it's going to be soon.

**Comment by Dave-Morton** [comment]
It appeared that you posted while I was crafting my last reply. oops?

cURL is used in the following places:
- the admin page to check the current version of Program O on gitHub
- the Twitter and XML GUI pages
- the function to parse the `<wiki>` custom AIML tag

The admin page has a test to see if the cURL functions exist, so that's not a problem, but the `<wiki>` tag is, so unless you can convince your hosting provider to enable it (not likely, TBH, but worth a try) I would avoid trying to use that custom tag, as well as the Twitter and XML interfaces.

**Comment by CptCurty** [comment]
cURL is not necessary for me so I will leave it be then. The rest works fine now! Again, thank you very much! I will close this issue.

**Comment by Dave-Morton** [comment]
My pleasure. Let us know if you run across anything else.
