### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by prdpspkt** [Program-O/Program-O#356]
Program -o- 2018 New year release. Not installing in Xampp with  PHP 7.2.

**Comment by Dave-Morton** [comment]
Can you please look at [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) and provide `all` of the necessary information so that we can assist you further? Knowing the server software and PHP version helps, but we also need the OS, and which version it is.

**Comment by Dave-Morton** [comment]
After 30 days of no new input, I'm closing this issue. If you have more to add, please feel free to reopen this.
