### ISSUE TITLE
Error message: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by AlexNoxious** [Program-O/Program-O#357]
Hello, i've the following error while installing OProgram:

`
Program O has encountered a problem with connecting to the database. With any luck, the following information will help:
Error message: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)
Host: localhost
Port: 3306
User:
Pass: 
`
The information that im entering are:

`
/------------------------------------------------------------------------
// DB settings
//------------------------------------------------------------------------

$dbh     = 'localhost';
$dbPort  = '3306';
$dbn     = 'database_name';
$dbu     = 'database_user';
$dbp     = 'mypassword';
`

I've a shared hosting. 
Can you help me?

Thanks

Diego

**Comment by AlexNoxious** [comment]
Hello Dave. I have access to phpmyadmin and the database has been created correctly.
The key I have in the database is the same key as the one in the backend (mydomain.com/bot/admin); but the problem persists.

**Comment by Dave-Morton** [comment]
I'm not quite certain what to suggest here, aside from verifying that your config file has the correct credentials set. the relevant section in the config file looks like this:

```
//------------------------------------------------------------------------
// DB settings
//------------------------------------------------------------------------
# remote server location
$dbh     = 'localhost';
# database port
$dbPort  = '3306';
# database name
$dbn     = 'database_name';
# database username
$dbu     = 'database_user';
# database password
$dbp     = 'database_password';
//Login credentials for the admin page
$adm_dbu    = 'admin_user';
$adm_dbp    = 'admin_password';
```

Of course the credentials in your config need to match your database credentials, as opposed to the values shown here, but that's a common sense thing, so...

Just remember that every setting shown here is `CaSE SensiTivE`, so make sure that everything in your config is perfectly exact. If they are, but you still have trouble logging in, then you may wish to create a new user for that particular database with new and different credentials, change the config file accordingly, and see if that helps. If so, great! problem solved! If not, I have no idea where to go from here.

**Comment by OverlanAI** [comment]
You have to set the mysql user to be useable via LAN ip calls not localhost and you should never use ROOT as the user anyway (thats not wise). Always set a password for the Mysql User in anycase including root.
Program O is making the proper Mysql requests to mysql so this problem is with mysql.

tnx (my dines worth) :-)

**Comment by Dave-Morton** [comment]
Since we have no additional input on this from the original poster, I'm closing this issue. If new information is available, please reopen it so we can help.
