### ISSUE TITLE
release 2.6.8 <condition> not able to find specific string data in value=

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#360]
If a condition statement tries to look for the values of "undefined" and "true" it fails to recognize the correct entry in a list.

Testing was done with a clean install and only the test case AIML loaded.
I used the Program-O built in tool "Test your bot" to run this test

Here is test AIML for this bug along with the present response received.

```
<category><pattern>TESTUNDEFINED</pattern><template>
setting temp to: <set name="temp">"undefined"</set><br/>
temp was set to: <get name="temp"/><br/>
<condition name="temp">
<li value="true">*** ERROR *** condition thinks temp is set to true<br/></li>
<li value="undefined">*** PASSED *** condition thinks temp is set to undefined<br/></li>
<li>*** ERROR *** condition thinks temp is NOT set to undefined<br/></li>
</condition>
temp was set to: <get name="temp"/><br/><br/>
setting temp to: <set name="temp">"true"</set><br/>
temp was set to: <get name="temp"/><br/>
<condition name="temp">
<li value="undefined">*** ERROR *** condition thinks temp is set to undefined<br/></li>
<li value="true">*** PASSED *** condition thinks temp is set to true<br/></li>
<li>*** ERROR *** condition thinks temp is NOT set to true<br/></li>
</condition>
temp was set to: <get name="temp"/><br/>
</template></category>

```

Here is the response:

Seeker: TESTUNDEFINED
root: setting temp to: "undefined" 
temp was set to: "undefined" 
*** ERROR *** condition thinks temp is NOT set to undefined 
temp was set to: "undefined" 

setting temp to: "true" 
temp was set to: "true" 
*** ERROR *** condition thinks temp is NOT set to true 
temp was set to: "true" 

[_Test-cases-basic.zip](https://github.com/Program-O/Program-O/files/1713001/_Test-cases-basic.zip)

I have attached my testcase file to this bug report

**Comment by patrickschur** [comment]
@tringate Just remove the double quotes from your sets and it will work. Everything inside of `set` will be assigned to the variable. So it makes sense that Program-O can't find the actual value because there is not value with double quotes. ;)

**Comment by tringate** [comment]
You are absolutely correct.  I got carried away with cut and paste and caused this issue for myself in this test case.  Dumb mistake on my part.

I'm closing this as my user error.
