### ISSUE TITLE
release 2.6.8 <condition> function not handling the testing of an unassigned name= correctly

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#361]
This is not a new bug but one that should be fixed.

If a condition statement tests an unassigned name= item it does not assume an "undefined" value as does the GET function.

This makes it impossible to test for an unassigned value using the condition function.  It is not consistent with having a GET function return a value of "unassigned" when it tries to get an unassigned variable.

With the new bug of not being able to even check for the string "unassigned" if you first use a GET and then SET to create a variable with a value of "unassigned" these two bugs render many sections of AIML useless when they use to work ok.

**Comment by Dave-Morton** [comment]
This one I think I'v got a handle on, but like many other times, the fix is tied up with other fixes that aren't yet ready to be pushed. As soon as I get to a place where I can push the changes I'll holler back. :)

**Comment by tringate** [comment]
Dave,

No problem.  I’ll test whatever fixes develop. I am going to spend some time writing a small regression tester.  I envision a simple php tool that will run a set of test cases against any bot that is loaded with a special file of test case AIML.  Is it possible you already have such a tool that I could use to write individual test cases so a full regression test can easily be run against any new release?  I want a tool that will run all test cases from the simplest up to the most advanced AIML types of operations with clear messages as to if they
pass or fail.

Tom

**Comment by tringate** [comment]
This is a valid issue, however my statement about not being able to set an unassigned  variable to be "unassigned" and then using the condition tag to find the now existing variable set to the  value  "unassigned" is bogus as I had included the quot's when testing this.  Having the condition return a value of unassigned to a non existent variable should be the desired operation so it can be acted upon as being non existent/unassigned.

**Comment by tringate** [comment]
This issue can be closed.  The issue is been addressed in release 2.6.9.

**Comment by Dave-Morton** [comment]
Well, not exactly. At least, not completely; until now that is. Fix for the rest coming soon.

**Comment by tringate** [comment]
This condition bug is fixed in release 2.6.10
