### ISSUE TITLE
Release 2.6.9 STAR is broken in regression testcase

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#364]
The basic regression test for TESTSTAR fails in release 2.6.9.
It returns:
Seeker: TESTSTAR foo
root: Star is set to: f in TESTSTAR * 
Star is set to: f in PRINTSTAR * when called from TESTSTAR * 

It is only catching the first character of the STAR value it appears

Test case AIML:
```
<category><pattern>TESTSTAR *</pattern><template>
Star is set to: <star/> in TESTSTAR *<br/>
<srai>PRINTSTAR <star/></srai>
</template></category>

<category><pattern>PRINTSTAR *</pattern><template>
Star is set to: <star/> in PRINTSTAR * when called from TESTSTAR *<br/>
</template></category>```

**Comment by tringate** [comment]
OK, :uncle" how do you insert code into a bug report?  The insert code link puts in two single quotes but it still isn't showing up.

**Comment by patrickschur** [comment]
@Dave-Morton You removed my [bug fix](https://github.com/Program-O/Program-O/commit/c712ae7e52dd6306d8b786a6faf8b310881f1e56) for this... The dollar signs that are used in the regex in function `set_wildcards` are neccessary.
```php
if (preg_match_all("~{$ap}$~siuU", $checkAgainst, $matches))
```

**Comment by Dave-Morton** [comment]
I must have done it, but I cannot remember doing so. My bad. ☹️

**Comment by tringate** [comment]
Dave
This bug is not fixed in the current dev release I downloaded today 2018-02-19.  All the files in that zip file have a date of 2018-02-16 11:09 AM and this bug is still in those files.

This bug is not the same bug Patrick fixed.  The test case es that fail are #7 and #8.  The are using STAR to pass information in a SRAI which is failing to find anything in STAR.
`
Seeker: QUICKTEST1
root: 
*** THESE TESTS MUST RUN BEFORE TESTING MORE COMPLEX AIML *** 
Testing atomic (srai) *** PASSED *** 
Testing atomic category *** PASSED *** 
Testing (think) *** PASSED *** 
Testing undefined (get) undefined *** PASSED if is says undefined *** 
Testing (set) (get) *** PASSED *** 
Testing (condition) 
*** PASSED *** 
*** PASSED *** 
*** PASSED *** 
Testing STAR *** *** 
Testing STAR with (srai) *** *** 
Testing complex (condition) 
setting temp to: 
*** testing condition group: (Condition name= value=) using value="*" to find: 
*** testing condition group: (Condition name=) LIST value= no match 
*** testing condition group: (Condition) LIST name= value= no match 

temp was set to: 


setting temp to: 
*** testing condition group: (Condition name= value=) using value="*" to find: 
*** testing condition group: (Condition name=) LIST value= no match 
*** testing condition group: (Condition) LIST name= value= no match 

temp was set to: 


setting temp to: 
*** testing condition group: (Condition name= value=) using value="*" to find: 
*** testing condition group: (Condition name=) LIST value= no match 
*** testing condition group: (Condition) LIST name= value= no match 

temp was set to: 


setting temp to: 
*** testing condition group: (Condition name= value=) using value="*" to find: 
*** testing condition group: (Condition name=) LIST value= no match 
*** testing condition group: (Condition) LIST name= value= no match 

temp was set to: 

`
This is what QUICKTEST1 produces using the present dev code which depends on SRAI working.  The actual AIML QUICKTEST1 is calling are these two AIML categories

`

<category><pattern>TESTSTAR *</pattern><template>
*** <star/> ***
</template></category>

<category><pattern>TESTSTARSRAI *</pattern><template>
<srai>STARSRAI <star/></srai>
</template></category>

`
The value of STAR that is being passed is the word PASSED which never is found in the STAR by the SRAI category.

I don't know if this is a failure of git hub having the wrong code even after you pushed the fixes or if there are two bugs and we are thinking they are one.

**Comment by tringate** [comment]
I can confirm that the test case now operates correctly.
