### ISSUE TITLE
Word sensor is not enabled but the flag is set to enabled

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#367]
In order to make word censor work i still have to un-comment the line
$convoArr =  run_censor($convoArr); in load_addons.php Line 66.
The enabled flag with addons is set to enabled but does nothing so it looked like it was working when it was not. 
Small thing and un-commenting that line is all that was needed.
The other enabled flags are WAI just not that one.
NOTE: Do not add word swaps that add or remove punct. marks like THATS to be changed to THAT'S or the other way around. Gremlins will haunt you lol
tnx

**Comment by Dave-Morton** [comment]
You're right about the gremlins, but you `CAN` change "THATS" to "THAT S" or "THAT IS". Where the word censor and spellcheck function operate the user's input has already been stripped of punctuation, so adding it back will, indeed, haunt you. :smile:

**Comment by OverlanAI** [comment]
Perhaps a check could be added before it commits an improper word swap like that. Kinda of a big dummy check as its easy to do that and not know you just screwed things up,
Someplace in my mess of php snips i have a one line php check for any punct. marks in the string so that's  just a go or no go check before the input will pass.
Anyway its not a big deal just can become a problem that is easy to make and not know you did.

tnx

**Comment by Dave-Morton** [comment]
For now, given the fact that both the spellchecker and word censor are still considered "experimental", I'm going to leave it as-is, but I'll make a note to mention how to activate it in the wiki.
