### ISSUE TITLE
Tracking multi user names in near real time ADVANCED

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#368]
First my hack then ill explain. I comment out the IF block in conversation start.php Lines 201 and 203 so that $convoArr['conversation']['user_name'] = $user_name = $form_vars['name'];  is always using form NAME that my script is always sending.
Now to the why, In my use my scripts send out the convoID and user name of who ever it hears talking near my script, Works great but then there is a gotcha to it.
If sally and bill and bob are all chatting program O cannot keep the user names strait when the aiml is including the name of the user as part of its reply. So it quickly started calling sally, bill and there in was the gotcha.
After a lot of messing around i found that Program O does do real good job at tracking of a some times changing convoID. Since my script already knows every users name (changes fast) and also has its own convoID (to track as a wraper)  before one word is spoken it can track a group conversation quite well.
So i got out my rusty code hammer and made that hack to see if program O could handle that sort of input. 
It can and does but my hack is not a good way to go about it because it happens on the 2nd pass not the first. So it is crude for now but happens to work well enough for testing.
What should happen (I THINK)  is the $username from form simply updates the client_properites table (name VALUE) with the current user name my script  is always sending but changes often and the convoID remains the same.
As i am still trying understand program Os plumbing i feel it a good time to talk with others about it
before i do something crazy.
Anyway so far it is working  and program O seems more than able to handle it.
I know this is not how program O or most AI chat system are ment to work but i love to come up with new uses. In my case i need it to work like that somehow.

TNX, sorry for long post and i am not sure where i would post this at exactly anyway.

**Comment by Dave-Morton** [comment]
For discussions about Program O that don't actually involve issues or bugs, I strongly suggest using [chatbots.org](http://chatbots.org). I'm an admin there, and I'm always happy to listen and share, and talk about not only Program O, but chatbots in general, as well. :smile:
