### ISSUE TITLE
Can we use UUID vrs the current convoID please

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#373]
This is more of a wish than a problem and may solve some security issues is to allow the use of a proper UUID in place of the current convoID.
Right now if you send it a UUID as the convoid it throws a few errors.
One because of the dashes in a UUID and also the length is a bit longer than it will store.
I got to this after finding out that my AI has problems knowing for a fact that i am its real botmaster and found it was way to easy to fool.
I looked at few solutions and did not really like them a lot.
A UUID can be bound to the actual user that is speaking and then forever track them since each UUID will never be the same one after it is assigned. That lets  the AI to have data to tell if some one is lieing to it or not. It would no longer care what a user says since it can test for a match via there UUID.

Anyway i did set things so i can pass it a Proper UUID as a convoID and caused no problems. but  others might also might find that useful and perhaps solve a few problems along the way.

Just food for thought
TNX

**Comment by OverlanAI** [comment]
As a sub note about this, i also this this may be an easyer way to block AIML commands that can come up in normal user chat rather than some horrid word filter. The only time it should act on an AIML command via chat line input is when it is really its botmaster and not someone trying to mess with it.

**Comment by Dave-Morton** [comment]
the conversation ID (convo_id) can be set to any value you wish, so if you want to generate a UUID to use, by all means feel free to do so. For bot systems that are attached to a site that uses membership of some sort, this is exactly what should be used. Program O only generates a conversation ID if one is not supplied by the interface, so making your own isn't a problem at all.

I'm not quite certain what you mean by your second post, so could you please explain it a bit more? Thanks.

**Comment by OverlanAI** [comment]
AHH ok my bad, what I ment is that Porgram-O does not like me sending it a  full UUID because of the dashes and also the length of a UUID is longer that it will let me use (Evan if I remove the dashes).
So I will get 2 errors about both, so I still cannot send it a full UUID as the convoID.
A proper uuid4 is
                                  e86fbd2b-7545-4868-9a94-82d602909b27
And it will not let me use it with out me having to hack Program-O.

If you need an easy way to test it or just FYI why a UUID is good way to go.
https://www.uuidgenerator.net

As for the last part of my post, that has todo with how I can expand using UUIDs to solve a few problems we found that can let bad guys cause massive CPU and or stack over flow problems because of using some of the AIML functions from the normal user text input. (I will not go into that here as that is a security issue for me).

In any case It has to allow me to send it a proper UUID first before we can work on the last part of this.

Tnx

**Comment by OverlanAI** [comment]
not dead, i have to hack your code so it will take full UUID.
Why i need it to work as convoID is that a UUID is passed from frontend to progam o
it matters so that the users uuid tracks cross platform as id
UUID is well understood and also correct.
From front end to program o back end the uuid is king
I need it to use real as in uuid
tnx

**Comment by Dave-Morton** [comment]
After doing a bit of research here, it would seem that your PHP config may be the problem, and why I'm not seeing the same trouble. Your UUID certainly contains valid characters (a-z, A-Z, 0-9 and the hyphen (dash) character), which means that it's the length that's the problem. There are two setings in php.ini that affect this: `session.hash_function` and `session.hash_bits_per_character`, and depending on the values of these settings, can cause a length restriction for the session ID of between 27 and 40 characters. Your UUID is 37 characters long, so it may well be that you either need to make a change to your PHP settings, or use a shorter UUID.

Sadly (or perhaps not, depending on your views on security), __BOTH__ of these PHP settings were removed in PHP 7.1, making them unnecessary, so you may also wish to consider upgrading to PHP7 as well.

**Comment by OverlanAI** [comment]
having problems getting programO to work in php7 so i made the changes you suggested and ill get back to you soon as i see if thats all it was. 
tnx

**Comment by Dave-Morton** [comment]
What sort of problems? This is information that could prove useful for others in the future, and may help us to make improvements to Program O itself. 😄

**Comment by OverlanAI** [comment]
Looks like the php.ini changes work when using UUID for convo_id now.  Always seems to be the last thing i would have thought to check lol.
As far as problems with PHP 7+, i will have to get back to you on that and would a another report anyway.
As to the php.ini changes to WAMP , it might be a good idea to add that to the notes or something in case someone else runs into it.
Ill leave this open for a day or so then close it.
tnx
