### ISSUE TITLE
robot show 'thinking'

### ISSUE THREAD

**Issue by zj2050** [Program-O/Program-O#375]
robot  show 'thinking'

**Comment by Dave-Morton** [comment]
In order to help, we're going to need a bit more information. Please read [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to learn what sort of information we need. Also, take a look in the `logs` folder for an error log, and post anything that seems relevant.

**Comment by zj2050** [comment]
@Dave-Morton 
thanks , the next is log info

03/01/2018 10:16:09 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:09 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:10 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:10 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:10 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:10 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:10 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:10 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 312
03/01/2018 10:16:11 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:11 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:11 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:11 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:11 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:11 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:12 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:12 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:12 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:12 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:12 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 312
03/01/2018 10:16:12 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:13 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:13 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:13 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:13 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 312
03/01/2018 10:16:13 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 1310
03/01/2018 10:16:23 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:24 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 312
03/01/2018 10:16:24 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 312
03/01/2018 10:16:40 - PHP ERROR [Notice] -Undefined index: srai_input in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml.php on Line 297
03/01/2018 10:16:40 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 312
03/01/2018 10:16:40 - PHP ERROR [Notice] -Undefined offset: 1 in E:\eFrontLMS\SuiXinBoPHPServer\ChatAI\268\chatbot\core\aiml\parse_aiml_as_XML.php on Line 312

**Comment by zj2050** [comment]
@Dave-Morton  but it's correct at html path ' /gui/plain/index.php '
ajax and xml api url show hint:

> The URL for the API is currently set as: 

E:/eFrontLMS/SuiXinBoPHPServer/ChatAI/268/chatbot/conversation_start.php.

Please make sure that you edit this file to change the value of the variable $url in this file to reflect the correct URL address of your chatbot, and to remove this message.


how to edit it?  no  variable $url searched in file  conversation_start.php

**Comment by Dave-Morton** [comment]
You're going to have to manually change that URL, as it's actually showing the file path. This happens on an uncommon basis with Windows. That can be changed in the file gui/jquery/index.php - That file is well documented, so you should have no trouble changing the variable. The variable is `$url` and is assigned on line 34 in the current version. Under that is some internal documentation to aid you in deciding what to set it to. If you have any problems or questions doing this, please let us know.

**Comment by zj2050** [comment]
@Dave-Morton  thanks ， i have got it

**Comment by Dave-Morton** [comment]
Glad to hear it. The errors showing up in the error log aren't really related to this issue, but they are something I'm aware of already, and am working to fix for the next release, which SHOULD be in a day or two. I'm still testing to make sure all the bugs are fixed before I put the changes up here.
