### ISSUE TITLE
Teach new one but has incorrect reponse

### ISSUE THREAD

**Issue by zj2050** [Program-O/Program-O#376]
teach a new chinese words,  and it's added into database
but when ask chatbot, it say by english

Seeker: 你好
Chatbot: Can we get back to business?

**Comment by Dave-Morton** [comment]
Most likely it's because the AIML files you're using are written in english. Program O cannot translate Chinese into English, after all. 😉

**Comment by zj2050** [comment]
@Dave-Morton I'm not use AIML file and  add it with admin Teach function
![err](https://user-images.githubusercontent.com/4464947/36826298-563cf2cc-1d47-11e8-8a5b-a7e4d8f4bda7.PNG)

**Comment by Dave-Morton** [comment]
The AIML that's created with either the teach page, or in Search/Edit AIML may not be in an actual file that's uploaded, but it can still be downloaded. If you don't mind sharing, a look at the files you've created may help us to understand the problem. If you wish, you can use the Download AIML page to download the file(s), and then simply drag & drop them right into your next post.

**Comment by zj2050** [comment]
@Dave-Morton not create any file, just do teach function, the attach is down file, thanks very much
[tsing.AIML.zip](https://github.com/Program-O/Program-O/files/1769940/tsing.AIML.zip)
