### ISSUE TITLE
Bot Personality

### ISSUE THREAD

**Issue by morgan-wela** [Program-O/Program-O#377]
How does the bot personality function work? I'm not sure how this information presents itself in the flows.

**Comment by Dave-Morton** [comment]
The bot "personality" is stored in the database for each chatbot, and is accessed with the AIML `<bot>` tag. For example, if you have the following AIML category for your bot, a user could ask the bot what its favorite color is, and it can give an accurate response:

```
<category>
    <pattern>WHAT IS YOUR FAVORITE COLOR</pattern>
    <template>My favorite color is <bot name="favoritecolor"/>.</template>
</category>
```

but in order for the bot to respond to such a question, there needs to be a corresponding value set in the database. To do that, log into the admin page, go to "Bot Personality" and fill in the portion of the form that says "Favorite Color". There are a number of pre-defined but empty form elements there. None of them are required, so fill out only the ones you want to actually use. there are also some options for adding your own, custom settings/values, in case there's something you want to use that isn't already covered.
