### ISSUE TITLE
HandyApp

### ISSUE THREAD

**Issue by FrankRSK** [Program-O/Program-O#379]
Here i have try to make am App for Android to make Program-O mobile.
https://github.com/FrankRSK/Program-O-Erweiterung

**Comment by Dave-Morton** [comment]
Thanks for letting us know about that, @FrankRSK . I, personally, don't have an Android device to test it on, but perhaps someone else on the dev team might. Best of luck with your project. :smile:

**Comment by patrickschur** [comment]
@FrankRSK Es wäre schön wenn du den Text in der Readme in das Englische übersetzen könntest, damit ihn jeder hier verstehen kann. Außerdem wäre es nicht schlecht wenn du ein Screenshot deiner App veröffentlichen könntest. Nicht jeder kennt sich mit der Android-Programmierung aus, geschweige denn kann die `.aia` Datei öffnen.

@Dave-Morton You have no android device? Shame on you. :D

**Comment by Dave-Morton** [comment]
I don't even own a smartphone. And yes, that's by design. 😛

**Comment by FrankRSK** [comment]
@patrickschur Danke für den Hinweis, habe ich befolgt, obwohl men Englisch grottenschlecht ist. Zum Thema Android-Programmierung und aia Dateien: Auch ich kann gar nicht programmieren, habe das mit dem Onlinetool http://ai2.appinventor.mit.edu erstellt. Geht kostenlos und ohne Vorkenntnisse, nicht professionell, aber funktioniert und ist brauchbar.

In my bad english: You dont need to know about Android programing. You can use the free Tool http://ai2.appinventor.mit.edu for using the aia file and bring it to your device (if you have one). It is not professionell, but it works fine. 

![screenshot_2018-03-09-06-38-06](https://user-images.githubusercontent.com/37167516/37193360-c0136078-2369-11e8-8ac6-9a78278b009f.png)

**Comment by patrickschur** [comment]
@FrankRSK Tut mir leid, dass ich mich so lange nicht gemeldet habe... Hatte viel zu tun. Obwohl nach deiner Aussage dein Englisch sehr schlecht ist, hast du Mut gehabt und dich auf GitHub registriert und ein englisches Kommentar verfasst. Das alleine verdient schon Anerkennung. :)
Jedenfalls was ich dir noch sagen wollte, ich würde vielleicht nochmal das Design deiner App überarbeiten. Gerade die Icons und die Sprechblasen. Da es derzeit nicht nach einem Chat aussieht, wenn du verstehst was ich meine. Ansonsten kann ich dir noch raten, dass du dich näher mit Java auseinandersetzt und der Android-Programmierung. Vielleicht kannst du uns dann eine verbesserte Version vorlegen welche bereits auf Program-O v3 basiert? :grin: 
Liz arbeitet nämlich gerade an Program-O v3.

**Comment by OverlanAI** [comment]
Love this!, you got bawls man.
+1
tnx (now make it work on my Ipad) lol
