### ISSUE TITLE
<topic> not working in latest release?

### ISSUE THREAD

**Issue by xhtmlguru** [Program-O/Program-O#380]
I've installed the latest version on a localhost and again on a web server. Had issues with both but this issue is regarding a web deployment.

I'm very familiar with AIML and I'm having trouble getting topic tags to work in this latest version. 

My PHP and mySQL meet the requirements and I've run older versions of program-o on this same server without issue.

I am running a bot with ONLY this AIML. The topic is correctly set in the JSON output but categories inside of topic tags aren't matched despite this.

`<?xml version="1.0" encoding="UTF-8"?>`
`<aiml version="1.0">`

  `<category>`
    `<pattern>WHAT IS THE TOPIC</pattern>`
    `<template>`
      `<get name="topic"/>`
`    </template>`
`  </category>`
  `<category>`
    `<pattern>*</pattern>`
    `<template>No answer found.</template>`
  `</category>`
    
`<category>`
`<pattern>LET US TALK ABOUT *</pattern>`
`<template>`
  `The topic is now <set name="topic"><star /></set>`
`</template>`
`</category>`

`<topic name="COFFEE">`

`<category>`
`<pattern>I DRINK IT PLAIN</pattern>`
`<template>I prefer mine with cream and sugar</template>`
`</category>`
    
`<category>`
   ` <pattern>*</pattern>`
    `<template>coffee pickup</template>`
  `</category>`    
  
   ` <category>`
    `<pattern>reset</pattern>`
    `<template>topic reset to <set name="topic">GENERAL</set></template>`
  `</category>`

`</topic>`

`<topic name="TEA">`

`<category>`
`<pattern>I DRINK IT PLAIN</pattern>`
`<template>I prefer mine with honey and lemon</template>`
`</category>`
    
`<category>`
    `<pattern>*</pattern>`
    `<template>tea pickup</template>`
  `</category>` 
    
  `  <category>`
    `<pattern>reset</pattern>`
    `<template>topic reset to <set name="topic">GENERAL</set></template>`
  `</category>`

`</topic>`
    
`<category>`
`<pattern>I DRINK IT PLAIN</pattern>`
`<template>You drink what plain?</template>`
`</category> `
    
`<category>`
`<pattern>COFFEE</pattern>`
`<template>topic reset to <set name="topic">COFFEE</set></template>`
`</category> `     
    
    
`</aiml>`
`

**Comment by xhtmlguru** [comment]
FYI, I have installed from the dev branch into a different folder on the same server and it works fine.

**Comment by Dave-Morton** [comment]
the `DEV` branch is probably the best version to use right now. We've been working hard on getting all of the old bugs fixed, polishing up some of the newly added features, and making it just work. There's still some work to do, but overall it's much improved. We'll probably not be merging into the `MASTER` branch for a while yet, since more testing is required, but it'll get there at some point. :)

**Comment by xhtmlguru** [comment]
Thanks! I'll use the dev branch until version 3 is released.
