### ISSUE TITLE
how can i use set and map in programm o

### ISSUE THREAD

**Issue by siteschrift** [Program-O/Program-O#384]
hey, greetings from germany.
one question how can i use set and map in programm 0

thank you for the answear

**Comment by Dave-Morton** [comment]
You cannot yet. Program O does not yet support AIML 2.0 I'm afraid. That support is coming, but it's not quite ready yet. I wish I had better news, but sadly, I do not.

**Comment by siteschrift** [comment]
hello Dave,
thank you for your fast answear. can i ask one more question
programm 0 is on a mysql database.   I have a seperate database where i have created a list of words it is somehow possible that i can access this word in a dialog. for example:
<category>
<pattern>translate * into spain</pattern>
<template>
the answear is $other database
</template>
</category>

in my other database are of course a lot of vocabulary
what can I do that makes sense

best regard from raining kiel

Roland

**Comment by Dave-Morton** [comment]
Probably the best way to approach this would be to create a custom AIML tag to handle the functionality you need, but I guess it depends on exactly what you wish to accomplish, aside from accessing information from this other database. Can you be very specific, please about what you want to do? the more detail you can provide, the better I can help.

**Comment by siteschrift** [comment]
hello Dave
is there a possibility to talk to you via skype? I would pay for that, too.

**Comment by Dave-Morton** [comment]
by the way, if you want to _give_ Program O the ability to handle `<set>` and `<map>` tags it's at least partially possible (at least on the template side), also by writing in the functionality as custom tags. In fact, it's entirely possible to get Program O, as it currently sits, to support the entire AIML 2.0 specification that way, with only one exception, and that's the pattern-side `<set>` tag. the only thing here is that this is beyond the scope of the roadmap for Program O version 2. With version 3 so close to release as an early alpha version (and no, I don't yet have a date - Liz is in charge of that, and I haven't heard from her in a while), I have neither the time, nor, frankly the interest, to write a couple dozen custom AIML tag functions to add AIML 2.0 support. If someone out there is willing to give it a go, I'm all for it, and am willing to help where I can, but I won't take that task on myself.

**Comment by Dave-Morton** [comment]
Sure. I'm on Skype all the time. My Skype handle is GeekCaveCreations. Just remind me of this GitHub issue in your contact request.

**Comment by patrickschur** [comment]
@siteschrift greetings back from germany. :)

**Comment by Dave-Morton** [comment]
With no response back from the OP, I'm closing this issue. If more information becomes available, please either reopen this issue, or open a new one. Thanks.
