### ISSUE TITLE
Bot name appended to file name after download as zip

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#385]
Program-O-dev (current git).

Why i had no great problems with it appending the bot name to the file names after exporting my set as a zip.
 I did find a few problems where 'FILE NAME' tags are used in the aiml.
When the set is restored, the file name in the aiml no longer matches so i end up having to re-edit the aiml  files that call on FILE.

Also ran into an issue with the export where there may have been an edit mistake made where on download of the whole set (zip) will make the file with an AIML error empty rather that it just exporting the file as is. That means that it is also checking the AIML on export when i see no point in it doing that since it will check it on import anyway. I think all it should do is to inform me about a file that may have some mistake in it (on export as zip) but not leave me with an empty file where i have no idea where i made a mistake at..
Mostly both problems are annoying not big time bug problems.

TNX (I been wrong B4 and ill be wrong again)

Hacker thought: May be to add in away where program-O will check the AIML stored in the DB for any new mistakes as maint. (like 1x a day it will scan it) and let the admin know if there is some oops.

**Comment by Dave-Morton** [comment]
The download script doesn't validate the AIML prior to creating either the individual AIML files or the ZIP file, so I'm not sure why some of your AIML files are coming out empty. I'm not seeing this particular problem at all, so I'm not sure what to tell you.

That said, however, I _did_ find the problem with the filename not being updated in the individual AIML files, and that's been corrected. Expect a new version soon with that correction in place.

As to adding a way to validate the AIML categories stored in the DB, that's a feature that isn't on the roadmap for version 2, but it may be something that we might consider for version 3, so stay tuned for details.

**Comment by OverlanAI** [comment]
well do this, edit a li but remove the /li then export the set knowing that you made that wrong.
As a test lol !
But as long as humans never screw up, it all fine.
TNX (im just a hacker and need a hug) lol

**Comment by OverlanAI** [comment]
Its all good man, just trying to make it more "Damm i just screwed up" less of a problem is all.
Every one knows Program-O is the what they been looking for so, lets get this right.

Tnx (Hackers can dance better than you think, just not to the same beat) lol

**Comment by OverlanAI** [comment]
Program O has encountered an error. this may help:
    Error # 2
    Message: DOMDocument::loadXML(): error parsing attribute name in Entity, line: 49
    File: H:\wamp64\www\Program-O-dev\admin\download.php, line 210
    Program O has encountered an error. this may help:
    Error # 2
    Message: DOMDocument::loadXML(): attributes construct error in Entity, line: 49
    File: H:\wamp64\www\Program-O-dev\admin\download.php, line 210
    Program O has encountered an error. this may help:
    Error # 2
    Message: DOMDocument::loadXML(): Couldn't find end of Start Tag botname line 49 in Entity, line: 49
    File: H:\wamp64\www\Program-O-dev\admin\download.php, line 210
The file Rue.AIML.zip is being processed. If the download doesn't start within a few seconds, please click here.

Oh joy, now when i open that zip the file with the error will only have a header and no AIML .. 1k file.

tnx

**Comment by OverlanAI** [comment]
As far as my main report and after manually patching, this seems to have done the trick.
So i will close this since it is setting the right file name calls (mostly found in alice.aiml).
As to the other part i will open a new report about it since the 2 things are not exactly related.
tnx
