### ISSUE TITLE
500 Internal error

### ISSUE THREAD

**Issue by quiraang** [Program-O/Program-O#389]
Hi,

I have a horrible feeling that this something stupid that I have done - if so I apologize in advance for wasting your time.

I've installed the latest DEV branch in a new install folder, new subdomain name,  and a new DB instance. I try using the json test gui and I get: ( in the browser console):
`GET http://aidev.simonmacdonald.me/chatbot/conversation_start.php?say=hi&convo_id=2nj52is62f3641hqebifl70886&bot_id=1&format=json 500 (Internal Server Error)`

I've checked server logs and permissions and everything looks OK, but I'm obviously missing something. Previous installs of older version have worked OK in the past. 

Can someone point me to the error of my ways.
Thanks

Simon

**Comment by Dave-Morton** [comment]
Hi, Simon.

Have you checked the Program O error logs? You can find them in the `logs` folder, within the install path.

Additionally, can you log into the admin page? Knowing that will potentially help to diagnose the issue.

And lastly, have you read the [wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) on how to report issues? It tells you what information we need to be able to help you.

**Comment by quiraang** [comment]
Hi Dave,
 Extra info as requested : -

Server:  AWS EC2 running Amazon Linux 2014

http://aidev.simonmacdonald.me/gui/jquery/?

Apache version 2.2.32
MySQL version 5.5.56
PHP 5.3.29
Client: Windows 10, Firefox 58.0.2 (64-bit), Chrome Version 65.0.3325.162 (Official Build) (64-bit)
Admin page works and AIML uploaded ok
[error.log](https://github.com/Program-O/Program-O/files/1832823/error.log)
[install.sql.error.log](https://github.com/Program-O/Program-O/files/1832824/install.sql.error.log)

**Comment by Dave-Morton** [comment]
It appears that you may actually have two potential problems here. Let's deal with the most critical first.

The file error.log reports only one error, but it's repeated 6 times. That error is listed, below:

`[19-Mar-2018 12:36:18 UTC] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/sites/aidev/chatbot/core/conversation/intialise_conversation.php on line 451`

Line 451 in Ptogram_O_Root/chatbot.core/conversation/initialize_conversation.php contains the following code:

`$insertParams = [];`

After doing a little digging, I realized to my horror that this array assignment syntax isn't valid until PHP version 5.4 - Before that version, such an assignment throws a syntax error, which is what's happening here. This means a couple of things here, and gives you options. I'll cover each, below:

1. I need to change the minimum version requirements for Program O from 5.3.0 to 5.4.0
2. Your PHP version is actually too low to run Program O in its current state

I've already made the change in the install file (though I still need to change the requirements in the README file, as well as other places), but that doesn't change your current situation. thus, you have options:

1. Upgrade your EC2 instance to use a more up to date PHP version (I highly recommend upgrading to AT LEAST 7.0, actually)
2. Try to edit the code in your Program O install to work with your current PHP version (potentially very time/labor intensive)
3. Not use Program O

I know that last option sounds harsh, and I don't _really_ advise you to do it, but it __is__ an option. Of the three choices _'ve given, the first one is your best bet. I've worked with AWS EC2, and changing PHP version isn't difficult. In fact, here's a [GitHub gist](https://gist.github.com/mavieth/b6b3b622dd9f863ca2c7db2da04ab215) that covers the process. this is, by far, the easiest, most efficient, and least time consuming option.

**Comment by quiraang** [comment]
Thanks Dave,

I'll upgrade to php7. I need to do this carefully as I run several wordpress sites on that server, so I shall proceed with caution.

regards

Simon

**Comment by Dave-Morton** [comment]
I've changed the PHP version requirements in the install script from 5.3.x to 5.4.x in order to prevent this occurrence in the future. I still have to go through the various documentation (readme, changelog, etc.) to reflect the change, but that's a task for another time. 😄

**Comment by OverlanAI** [comment]
tryed php 7 and 7.x on wamp and still have not seen this error.
Lots of other odd stuff but, IDK.
Are you running it in NIX ?

**Comment by OverlanAI** [comment]
And yah ill post about the odd stuff with it running in php 7.x soon as i get hippo back in the crew again.
If its NIX , then yah stack gets yah, On win .. never.
Tnx (<-- Avoids the pointy sticks) lol

**Comment by quiraang** [comment]
I've upgraded my EC2 server to Php 7. 0 and the problem is resolved.
Thank you for your help.
