### ISSUE TITLE
Thats NOT AI

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#391]
aiml 2. ick is not AI
It is a cop out and mostly just an NLP with an attitude.
AI to me never should depend on external (not our stuff) to work.
To AI the web is just data that is raw and consumes it for us.
2.itch nahh. 
We got junk like that and none of that is real AI.

Tnx (Hackers do it cuz we can) lol.

**Comment by OverlanAI** [comment]
Support Project-O, lets do this!

**Comment by patrickschur** [comment]
I like your commitment, but please, this is an issue tracker not a discussion forum.

**Comment by Dave-Morton** [comment]
@OverlanAI if you wish to discuss things regarding Program O that aren't issues or bugs, I suggest [chatbots.org](http://chatbots.org). I'm an admin there, and we discuss a wide variety of things related to internet chatbots, Artificial Intelligence, and other subjects about the field. You would be more than welcome to talk about Program O there. Just a suggestion. 😄
