### ISSUE TITLE
2.6.10 Admin UI for user added aiml display is wrong

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#393]
Win 10 pro WAMP (current) Java (current).
Just that that section of the admin UI, we see the edit screen lay out cut off by the frame and re-sizing has no effect.
Also the delete tabs for each item shows up in the right upper part of the screen and only one is seen vrs on the left as before and each entry had a 'delete' tab.
The other EDIT sections in the UI seem fine but that one. 

tnx

**Comment by OverlanAI** [comment]
Update, I tried all of the browsers i have and see it displayed the same in each.
Opera, MS Edge ,Chrome, Firefox (all current 64 bit).

**Comment by OverlanAI** [comment]
still see the same issue, the admin screen for this section still displays wrong and item delete (line by line) is wrong.
The good news is the rest of the admin edit screens look and work ok.
Not sure if the search box's work yet.
tnx

**Comment by Dave-Morton** [comment]
Can you please post a screenshot, so we can see it? 
Also, if you look at the console (F12 on most browsers), are there any JS or CSS errors listed?

**Comment by OverlanAI** [comment]
![userdefscreen](https://user-images.githubusercontent.com/36704725/38873683-5a6268bc-4224-11e8-9740-8ccc1209c3ac.PNG)

I do not see any errors listed using the console
tnx

**Comment by Dave-Morton** [comment]
Judging from the appearance, I think that the CSS file may be the issue here, but since I can't reproduce the problem here, it's rather difficult to suggest where/how to troubleshoot, other than to suggest using your browser's "style inspector" (usually by right-clicking on an element you want to look at and selecting "inspect" (actual labels will vary).

**Comment by OverlanAI** [comment]
![with padding on normal](https://user-images.githubusercontent.com/36704725/38878955-337ab810-4230-11e8-9321-9348cd0d7eba.PNG)
i can center that up by changing the padding (this is how it looks normaly).

**Comment by OverlanAI** [comment]
![withpadding off](https://user-images.githubusercontent.com/36704725/38879019-5849c690-4230-11e8-9860-782c04aaac76.PNG)
And this is with the padding off and centers that section ok.
Have no idea what is up with the delete button in the upper right.

**Comment by OverlanAI** [comment]
even what i center it up the Thead still seems shifted to the left but since i have no idea what that screen should look like i am just guessing.
tnx

**Comment by Dave-Morton** [comment]
I've played with the CSS for this in the "Reunion Update" (the most recent push I've done, as of this morning, the 8th of May, 2018), so please try the latest `DEV` branch and see if that helps. :smile

**Comment by OverlanAI** [comment]
That did the trick, all of the admin edit pages look the same now and are framed ok.
Also the delete buttons are back where they should be.
This can be a closed issue at this point.
If i discover something else i will just start a new one abut it since nothing in this report will matter going forward now.
+1
tnx
