### ISSUE TITLE
Problem with exported bot set as zip with empty files

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#394]
Program O has encountered an error. this may help:
Error # 2
Message: DOMDocument::loadXML(): error parsing attribute name in Entity, line: 49
File: H:\wamp64\www\Program-O-dev\admin\download.php, line 210
Program O has encountered an error. this may help:
Error # 2
Message: DOMDocument::loadXML(): attributes construct error in Entity, line: 49
File: H:\wamp64\www\Program-O-dev\admin\download.php, line 210
Program O has encountered an error. this may help:
Error # 2
Message: DOMDocument::loadXML(): Couldn't find end of Start Tag botname line 49 in Entity, line: 49
File: H:\wamp64\www\Program-O-dev\admin\download.php, line 210
The file Rue.AIML.zip is being processed. If the download doesn't start within a few seconds, please click here.

Oh joy, now when i open that zip the file with the error the bad file will only have the ?XML header and no AIML .. 1k file.

If i make a mistake with a TAG ending like li> is LI or some other tag ending that is incorrect i get the above result.
Mostly just be real careful when editing.
tnx

**Comment by patrickschur** [comment]
Looks like you have a syntax failure in your XML. Can you send us the line where the error occurs?

**Comment by OverlanAI** [comment]
That is correct, The main problem is when you export the aiml set that somehow you made a mistake in, when whole file will be empty where the mistake was made.
It is easy to make a typo and you would not necessarily know you have until you go to re-load the zip again and at that point it may be too late with no way to fix it since the all of the aiml in the file will be gone where it should ignore the mistake and export the files as is.
tnx

**Comment by OverlanAI** [comment]
If you want to test this, make an intended mistake in one of the files for your set like srai/ (missing a >) then select all files and export as zip. You should see the above error but that does not tell you anything useful and exports it anyway. Then when you look at the file in the zip that you made the mistake in you will see only a 1k xml header and all of the amil is gone in the rest of the file.
What would be best is for it to catch the typo at the time of edit and simply not let the user enter it in that way.
Mostly i feel something is lacking at the time you are editing some aiml line in the admin edit  section.
tnx

**Comment by OverlanAI** [comment]
Okay, i can understand that, mostly what matters is that people and dev are aware of the lack of robustness at that stage and what the result could be if extra care is not taken as they edit things.
keeping the raw AIML files that were used as backup is wise at this point.
Anyway i ran into the issue so i thought it best to say something about it before i forget it lol.
tnx

**Comment by OverlanAI** [comment]
Turning lemons into lemonade kind of thinking may be to trap that type of error and then have it display a warning and they will need to fix the problem then try exporting there set again and that if they do not may loose some aiml content. (or something like that).
Why thats not a fix at least it would be more helpful i think.

Tnx (umm lemonade)

**Comment by OverlanAI** [comment]
After talking this over with others in my crew and also dealing with things where the cure is worse than effect.
Would be a simple error trap with a message to the admin (with some usable detail given) that the admin needs to fix the problem before it will be exported.
It is less disruptive to the code base and besides Thats part of the admins job anyway lol.
Doing it the other way would just add many more things to go wrong basically and also somewhat rare type of problem.
TNX

**Comment by Dave-Morton** [comment]
Frankly, I think that for this we should have the function skip any file that fails validation, with an "error message" stating that it was skipped, and (possibly) why (but just listing the first occurrence of any errors, but noting that "there were {x} number other errors"). 

just a thought here. 😄

**Comment by OverlanAI** [comment]
Yes, something simple would be fine so that IF there is an oops, that we have some idea where to look for it and fix it.
No point getting crazy about it.
Adding a lot of code for something like this would be silly and could just add more problems than it solves so KISS is best now that i see what i mess it could be.
tnx

**Comment by OverlanAI** [comment]
I do recall seeing a bug report but it is long gone now about exported sets getting corrupt on export. I am thinking this may be what was making it look like that.
Unless you dig in to find the cause, it could seem that way since the error given doesn't really tell you anything and it still exports it anyway.
Then when it was loaded back in again it would catch it saying it was bad so that report may seem correct but not in the way the poster thought.
It may be that it was an edit gone bad and not caught that made it look like that on re-load.
When i do dev a project and have testers, I tell them that if something does not look right, I want to know about it. There is no right or wrong to there feedback. I would rather know what others are seeing than not say anything ;-)
tnx again

**Comment by Dave-Morton** [comment]
> I would rather know what others are seeing than not say anything

I feel the same way, and I __always__ encourage people (dev team and the general public alike) to shout out with anything that seems amiss. False positives are far preferable to no feedback at all.  😄

**Comment by OverlanAI** [comment]
still an issue but you guys and gals are cooking up the good stuff so ill live with OOOPS! 
:-)

**Comment by OverlanAI** [comment]
Well MR mort, i sent out mail to others  that love to hate me (dev mostly) to get in here and take a look.
I told them to be nice and will see how that match up will go. (Program-o meets 3d spaces in a huge way).
i think they dream in binary lol.
