### ISSUE TITLE
Release 2.6.10 2018-03-30 (condition name="" value="") failing

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#395]
Test cases 8,16,19,22,25,28 all of which use the form `<condition name="" value="">` fail.

I noticed that this form of condition statement that used the STAR does work and that is the bug this release fixed.

the other forms of the condition statement appear to be working fine.

Here is test case #16.

```xml
<!-- test case 16 -->
<category><pattern>TESTCASE16</pattern><template>
<think>
<set name="testvalue">ok</set>
</think>
<condition name="testvalue" value="ok">*** PASSED ***</condition>
</template></category>
```

This test case executes with nothing printed.
Seeker: TESTCASE16
root:

**Comment by Dave-Morton** [comment]
@tringate it may help if you could provide the debug file for that test case, so we can see what's going on when it fails.

**Comment by patrickschur** [comment]
You should know that the bug is not completely fixed yet. I already published two fixes but one is still missing. Because I little misunderstood the new form of `<condition name="*">` I think.

**Comment by tringate** [comment]
Patrick, I also moved this one to in progress.  I believe all three of these bugs are inter related.

Here is the current section of the test cases that fail.  There are 5 failing out of the 82.

I did find some things in the test cases that were bad logic, and fixed them.  I'll need to post in slack this corrected version so if you want to use it  to check your fixes you will have the most updated version.

Most of my mistakes were caused by copy/paste errors.  I hope I have found them all now but I carefully checked each of these failing tests to make sure they were logically correct.  I then went through the entire group that deals with the condition tag.

Of the 82 test cases these are the four that still fail.  They are all using the "*"

test case 026 - OK 
test case 027 - *** FAILED FALSE MATCH *** testing (condition) using (srai) with (star/) to undefined NAME 
test case 028 - *** FAILED FALSE MATCH *** testing (condition [NAME]) using (srai) with (star/) to undefined NAME 
test case 029 - OK 
test case 030 - *** FAILED FALSE MATCH *** testing (condition) using name="*" 
test case 031 - *** FAILED FALSE MATCH *** testing (condition [NAME]) using name="*" 
test case 032 - OK

**Comment by OverlanAI** [comment]
Yah, near as i can see here, it is not working. common use is for clientprofile.aiml, and sofar just returns unidentified OR null. Many times is will get suck in a loop.
clientprofile.aiml (alice 1.91 set) is using most everything in your test. 
TNX

**Comment by OverlanAI** [comment]
Added that manually, so far so good but it needs to run for a few days before i will have an avg. score Using Super RUE set.
Anyway looks good so far.
tnx

**Comment by OverlanAI** [comment]
Well after a lot of testing i think the fixes are correct but uncovered a new bag of worms that i have posted in other places because its a bit fuzzy as to what is or is not correct.
Anyway it is still a good patch.
tnx

**Comment by OverlanAI** [comment]
Humm ran into where that situation is used in ALICE 1.9 set(master) as well as  the evil value="*".
Mostly used as it trys to work out a client profile so that is not asking for things that have already been set and are no longer OM.
Though they tend to use OM along with value="" (that should be same as OM i think).
There are other ways around the problem but seems in both cases in pre 2.0 to be valid.
Often they use nested conditional checks and gets quite complex but also very slick if it works right.

**Comment by tringate** [comment]
looking at your failure report it appears you have a very strange installation.  The test cases presume no other AIML is loaded and that the database is a blank virgin database with no previous information in it.

Your first failure of test case 008 does not make any sense if those conditions exist because it is a very simple atomic category calling a srai to check the value of STAR.

I normally do not clear my database, but then the only AIML I have run on the test system is the test case AIML set.  Until it runs error free, more complex AIML is not going to work right at all.

It's like having a computer that comes up with 2 plus 2 equals 5.  That needs to get fixed before trying to do anything else with it.
