### ISSUE TITLE
Ran in to an issue with popom om that is not clear to me

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#397]
What i ran into was my bot was getting stuck in the same topic when it should have popom om to pick a new random topic but failed to leave its loop. I traced it back to stack.aiml and found ether a bug or they have a typo. If you look at what it does when that is called, there is no place in there that actually sets the topic, It sets top with the random pick not the name topic.
When i changed set top to set topic (typo?) it now breaks out of a topic loop, and makes what it picked the new topic as i would expect. (i am including the file for ref.).
My problem is, i do not know if my change to the amil is correct or if there is a bug in program O.
(also noticed it is slow to show me what is in the stack when i think that should  be really fast not struggling to do it).
As far as my tests on stack goes, it seems fine in general.
Anyway something seems wrong. Hopefully it is just a typo that was made in alice 1.9 master and would not surprise me thats all it is but i thought i better ask the cool kids first.
[stack.zip](https://github.com/Program-O/Program-O/files/1888439/stack.zip)

tnx

**Comment by Dave-Morton** [comment]
Closing the issue takes it off our monitoring software, so we prefer to leave them open till resolved completely.

**Comment by OverlanAI** [comment]
Well if nothing else, that file is useful for a lot of things when you need to know exactly what is set in the stacks. It has helped me debug a few problems.
As far as what way is the right way i still have doubts.
tnx

**Comment by OverlanAI** [comment]
well sofar i ran into a few SRAI that calls it self that outputs nothing if it hits one (just bails out from the looks of it) but the few rare ones i found are ghosted anyway meaning something above it is catching it so it never gets called to start with. In the pre-patched version of program that was the case so could be why i have never seen it not say anything at all.
What i think i will do is a make a utility script that will output a list of ghosted srai's using the DB.
However something still seems odd since logically it should never hit a ghosted SRAI in the fist place.
I am still not convinced that this is whats going on due to the random nature of the problem.
Meantime i am getting rid of or fixing any i find in that state.
Anyway a utility script that checks for ghosted SRAI's (unreachable or calls it self) would be really handy since it can do that directly with the DB and would just take it a few seconds to get a list of the bad ones if there are any found.
I still do not think this is the cause but it can make it  not say anything at all. My guess is somehow it is falling through to a ghosted call when it should not or at least did not use to do. But just for giggles ill make sure there are none.
TNX (I've been wrong b4 and i will wrong again.)

**Comment by OverlanAI** [comment]
so what all this work and testing, let the kid find out on his own, seems he knows it all!

**Comment by OverlanAI** [comment]
Fix it on your own then, see you on the fork

**Comment by OverlanAI** [comment]
W-hat you got dont fix or care about anything. done!

**Comment by BeZazz** [comment]
> W-hat you got dont fix or care about anything. done!

Please be a man of your word.
I am sick to death of your constant ramblings.
