### ISSUE TITLE
MORT you cant do that

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#398]
Best of the best go? PAHH
it never works that way man.
Yah i got burnt out and used but i never gave up. screw them
Take a break, i did and i get that.
But dam man
I spent years head to head with best coders telling me crap and did like you have here. 
I burnt out too but i did it on the "Cant just got done now you stand on it " and in there face!
Pull up your balls man and just say your tired and ill find yah real crew with repect.
This is the good stuff and you know it.
tnx (hackers dont code we just kick ass).

**Comment by OverlanAI** [comment]
well get mad then tell me i am wrong but this is the good stuff and so what i vent.
If you care then lets do it, mort gets a time out now what?

**Comment by OverlanAI** [comment]
we can branch this and take chain saws to it but thats not fair. 
Step up and get it better!

**Comment by OverlanAI** [comment]
FIX learn mode FIX srai .. do stuff so i can do y thing please.

**Comment by OverlanAI** [comment]
If you dont i will let my crew take chain saws to all of this!

**Comment by Dave-Morton** [comment]
Dude, RELAX! I haven't "quit". I __AM__ taking a break. I'll be back, I promise.

**Comment by OverlanAI** [comment]
I know i can make your project get bigger traction in the sim world and doing that is no joke.
I know what will happen when i open that gate.
And there all pricks but also best of the best right.
Looked you up, you earnd your bones :)
tnx (time to dance)

**Comment by OverlanAI** [comment]
i sent out word about this project but just to a few k. 
Get your foil hat on, helps on the way.

**Comment by OverlanAI** [comment]
watch the up tick in down loads now, you got the good stuff and there coming for it man. Not one joker in the deck :)
