### ISSUE TITLE
FORMS username not set in users table

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#402]
When supplying username via HTTP post The user name remains seeker in USERS table.
session_id works correctly however.

tnx

**Comment by Dave-Morton** [comment]
I've taken a look at this, and it seems there's a bug (of sorts) with it. If you look in the file chatbot/conversation_start.php, right around line 200 - 202, you should find the following code:

```
    if (!empty($form_vars['name']))
    {
        $convoArr['conversation']['user_name'] = $user_name = $form_vars['name'];
    }
```
Try replacing it with the following and see if it helps:

```
    if (!empty($form_vars['name']))
    {
        $user_name = $form_vars['name'];
        $convoArr['conversation']['user_name'] = $user_name;
        $convoArr['client_properties']['name'] = $user_name;
    }
```

Testing on the test GUI (the one I use to develop, based on `test_gui.php`, in the JSON GUI folder, but with some modifications to test using a 'name' field) shows this bit of code works right off the bat, with no prior vollies required.

**Comment by OverlanAI** [comment]
looks like a good fix, save me a lot of crazy swapping but not clear about what data should be in the USER table, The convo_id does track so i made the assumption that the user name in the same table should also track the convo_id in the users table.
In the code base that gets confusing as to what name is ends up as what.
But the main thing is that client_properties (USER VALUE)  track correctly (and your patch takes care of that +1)., That is what matters most.
Anyway and sofar i can track track any user via UUID (convoID all the way to the DB) and to the logs and now your patch lets the bot track users via there FORM name as part of the conversation and log.
I was mostly tracking that all provided data is end to end and ran into problem.
tnx

**Comment by OverlanAI** [comment]
A sub note. Having this work end to end, lets us track an client input end to end but it also helps performance overall when client names and ID changes many times during a streaming chat.
ProgramO has the plumbing to keep things stable in worse case testing to one bot.
It is also nice from an admin view to be able to track exactly who said what that caused X bad thing to happen. (IE we know who to yell at or ban lol).
Anyway this same patch should be back ported since this was an old issue.
TNX (you guy earn one more hacker point).

**Comment by OverlanAI** [comment]
well since this is now in current dev, this can be closed too.
tnx
