### ISSUE TITLE
When is a SPACE TAB bad

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#403]
I think i ran into why my SRAI (does not fill the the table) and My idea is because it barfs on TAB SPACES not spaces.
This is a case where we have an srai within a SRAI tag set with STAR but turns out what looks like spaces were TAB spaces in between the SRAI tag set.
My Idea is it makes it barf but "I have been wrong before and ill be wrong again!".
In any case TAB SPACE's and excessive spaces with in the SRAI set is pointless as far as we can tell.
That does not mean that PHP Mysql thinks it is.
Also in my reading of AIML  there is a difference between CAP SRAI calls are not the same as lowercase.
But seems programO makes it all uppercase anyway.
I just say that as that hints at an exact match may still be needed including spaces with in the SRAI tags?

Tell me im wrong lol

**Comment by Dave-Morton** [comment]
I've looked this over, and done some testing on both my Linux and Windows installs, and do not see this, so perhaps some additional information would be in order. Please look at [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to see the sort of information we need in order to run proper tests. Thanks.

**Comment by OverlanAI** [comment]
Well this was more of a question than it was a bug but since this post i found other issues that made me jump to a wrong conclusion. The space tab tab within the srai tag set was a guess on my part that any SRAI lookup MUST be an exact match including added spaces.
Anyway this was more of a question about if that should matter or not.
tnx

**Comment by OverlanAI** [comment]
I will try and illustrate my question a bit more.
`<srai>I AM IN CHINA <star/> </srai>`
Ok in that example we have a space after the star but between SRAI tags. As near as i can tell that has no effect on look up or format if i remove the SPACE.  (this is why i was asking how picky is the matching).
`<srai>I AM IN CHINA <star/> tab tab</srai>`
Became a another question where now we don't just have a simple space but also (according to notepad++) we have SPACE TAB TAB.
As i edit i tend to remove what seems of no matter and just just for neatness on my part.
Or am i shooting my self in the foot doing that?
There are other case where on to the left of the star the spaces do matter like
`<srai>I AM IN THE CHINA <star/> ROOM 12</srai>`
In more extreme cases there may be many spaces and tabs in between the SRAI tags including nested srai calls.
So all this led to me needing to ask how badly this can can mess with things OR are all of the cases handled already in programO and me neating up the AIML is the only effect there should be?
Mostly i want to eliminate a possible source of an issue.
TNX

**Comment by OverlanAI** [comment]
A hacker brain thought assuming none of the above really causes problems is when i upload an AIML file that it clean that up for us then store it to the db. Seems that would at least make the data more compact and perhaps speed things up since it will not need to trim as much if it has already been done to start with.
Then the only time programO needs to trim is when a direct entry is added.
Just a thought.

**Comment by OverlanAI** [comment]
And one other case that i know has an effect.
`<srai>ARE ALL <star/>, SPACE TAB TAB OR Excessive SPACING<star index="2"/></srai>`
Seems to have a many odd effects if not cleaned up as
`<srai>ARE ALL <star/>, <star index="2"/></srai>`
Anyway as i do not know exactly what is ok vrs what is not is why im asking the cool kids about it.
TNX(No such thing as silly questions, Only silly answers to them..)

**Comment by OverlanAI** [comment]
off topic huh.. bahh you do the work then, what do you need MIT for?
