### ISSUE TITLE
get some variable in custom tag 

### ISSUE THREAD

**Issue by ngocquynh85** [Program-O/Program-O#407]
I'm writing some custom tag. 
Is there easy way to:
+ get session_id (convor_id)
+ get, set client properties. 

Or I have to work directly with database.

**Comment by Dave-Morton** [comment]
Both of those things are available in the variable $convoArr, which is a very comprehensive array. If you create a custom AIML tag parsing function, you'll be needing to make sure that $convoArr is passed into that function as the first variable anyway. You can find the convo_id by accessing `$convoArr['conversation']['convo_id']` and the client properties  at `$convoArr['client_properties']`.

There are also ways to access those variables in other means as well, but those are the best ways to do so. There's a function that fires at the "cleanup" stage of each volley that stores the client properties in the DB, so all you really need do is set them the same way that you set any element of an array, such as `$convoArr['client_properties']['foo'] = 'bar';`, 

If you wish to generate debug messages for your custom tag parsing function, there's also a handy little function that allows for that. It's called `run_debug()`, and it's called like this:

`runDebug(__FILE__, __FUNCTION__, __LINE__, $message_string, $debug_flag);`

... where `$message_string` is the information that you want to pass to the debugger for display, and `$debug_flag` is an integer that corresponds to the 'importance', or priority of the message. The accepted values for `$debug_flag` are 1 through 4, and they correspond to the following debug 'levels':

 * 1 = errors and warnings
 * 2 = general information,
 * 3 = sql related messages (query strings, query results, etc.),
 * 4 = log it no matter what

Please note that these are _not_ binary flags, but are evaluated as integers, so you don't need to worry about "and'ing", or "or'ing" values. Also, if you're going to be accessing the database for some reason and wish to pass the SQL query to the debugger (especially if you're using replacement parameters in your queries - which you __REALLY__ should be, even for simple queries) there's a function for doing that, called `db_parseSQL()` for doing just that. It takes your query string, and the array of replacement parameters and returns a "human readable" SQL query string that could then be sent to the debugger, or sent to a log file (there's a function for that, too, but I'll save that for later). but that function DOES NOT escape or filter the query, so it's not safe to use for executing. That's handled in other `db_*` functions. Have a look at /library/PDO_functions.php for more details.

I know that this is qa __lot__ more information than you asked for, but I feel that some of it is important to pass along, and is relevant to writing functions for parsing custom AIML tags, so I thought I would share. I hope you find it useful. 😄

**Comment by Dave-Morton** [comment]
Oh, make sure that if you're going to __*SET*__ a new client property in `$convoArr` you make sure that `$convoArr` is accessed by reference. In order to do that, simply put an ampersand before the variable in your function definition (e.g. `function parse_my_tag(&$convoArr, $element, $parentName, $level){}`). I expect that you may already know this, but it's almost always better to have more information than less, so... 😉

**Comment by Dave-Morton** [comment]
@ngocquynh85 did my suggestions help, or is this still a problem?

**Comment by ngocquynh85** [comment]
sorry for my late reply. 
Its great. Thank you so much.
