### ISSUE TITLE
Error on download as SQL

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#410]
Program O has encountered an error. this may help:
    Error # 2
    Message: Invalid argument supplied for foreach()
    File: H:\wamp64\www\Program-O-dev\admin\download.php, line 260

The other choices of download work ok, just not that one.

tnx

**Comment by Dave-Morton** [comment]
Have you looked at the code for that error (download.php, around line #260) to see what the problem might be?

It's good to report on things like this, but it might also be good to try to offer a solution as well. 😄 It's contributions like that that go a long way toward earning the respect and admiration of the community. Just sayin'. 😉

**Comment by OverlanAI** [comment]
Bahh, the data values are never sent to the insert command so all you get is a lot of 1k sql files in it.
It  writes out everything mysql need to know including the insert into commands. all that looks fine, just no data in the files.

**Comment by Dave-Morton** [comment]
Well, THAT's broken. 😄 

I've ended my sabbatical, so I'll look into this, but there are older issues that need attention first.

**Comment by OverlanAI** [comment]
this can be closed as the patch is in dev now. tnx
