### ISSUE TITLE
Spellcheck Search Function throws an error

### ISSUE THREAD

**Issue by Dave-Morton** [Program-O/Program-O#411]
While doing some routine maintenance for a client, I was trying to find a word in their spellcheck table by entering the word (Sheila) into the search box. Rather than getting an expected targeted list of potential words, I got every word in the table, along with the following in the message div:

```
 Program O has encountered an error. this may help:
    Error # 8
    Message: Undefined index: search
    File: /path/to/bot/admin/spellcheck.php, line 276
```

further testing on my local server for the current version of Program O exhibited the same behavior, so it seems to be a legitimate bug. I'm just reporting it here for documentation purposes.

**Comment by OverlanAI** [comment]
so does the search for word sensor (same error as above).

**Comment by OverlanAI** [comment]
Also noticed that user_added aiml search box does nothing at all (no error given).

**Comment by patrickschur** [comment]
This is fixed in newer versions.
