### ISSUE TITLE
Spellcheck does not load words from nav list for editing

### ISSUE THREAD

**Issue by Dave-Morton** [Program-O/Program-O#412]
As I was continuing to test the bug fix for issue #411 I found that clicking on a word in the spellcheck page's right nav of word corrections that already exist only displays a "clean and empty" correction page. Neither the misspelled word, nor its correction are entered into the editing form. Again, this issue is only here for documentation purposes. I'm already on the task of correcting it. 😄

**Comment by patrickschur** [comment]
Related to #425 and already fixed.
