### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nunojesus** [Program-O/Program-O#419]
Hi, concrats for your project!
Do you have a logotype? If you need one I can do it for free, I love to contribute to opensource projects, so if you want one just say it.

Cheers!

**Comment by Dave-Morton** [comment]
There's an "unofficial" logo, but I'm not sure what Liz wants to do with it, to be honest. I'll share some links for both the logo we have, and something fun that I've been working on that's related.

[Original Logo](http://www.geekcavecreations.com/svgTest/OldLogo.png)

[Logo SVG Test](www.geekcavecreations.com/svgTest/LuvBunny.html)

**Comment by nunojesus** [comment]
Ok, if you need some help with the logo just say it, Im here to help.

Greetings!
Nuno
