### ISSUE TITLE
Search does not work in 'Spell Check' and 'Word Censor':

### ISSUE THREAD

**Issue by Josef-Meier** [Program-O/Program-O#425]
on version: 2.6.8
Using "Search' in "Spell Check" and "Word Censor" does not work.
Following error message is output:
Error # 8
Message: Undefined index: search
in File: /srv/www/htdocs/nossl/opensim_lsl/ProgramO/admin/spellcheck.php, line 276 and
File: /srv/www/htdocs/nossl/opensim_lsl/ProgramO/admin/wordcensor.php, line 274

Possible solution:
If the entry 'search' is "added to the arrays 'spellcheck and 'wordcensor'
in allowedPages.php"  then it works again:

    'spellcheck' => array(
        'missspell'  => FILTER_SANITIZE_STRING,
        'correction' => FILTER_SANITIZE_STRING,

        //// J.Meier
        'id'         => FILTER_SANITIZE_STRING,
        'missspelling' => FILTER_SANITIZE_STRING,
        'search'     => FILTER_SANITIZE_STRING,
        ////

        'group'      => FILTER_SANITIZE_STRING,
        'action'     => FILTER_SANITIZE_STRING,
        'page'       => FILTER_SANITIZE_STRING,
    ),

    
    'wordcensor' => array(
        'word_to_censor' => FILTER_SANITIZE_STRING,
        'replace_with'   => FILTER_SANITIZE_STRING,
        'censor_id'      => FILTER_SANITIZE_STRING,
        'group'          => FILTER_SANITIZE_STRING,
        'action'         => FILTER_SANITIZE_STRING,
        'page'           => FILTER_SANITIZE_STRING,

        //// J.Meier
        'search'         => FILTER_SANITIZE_STRING,
        ////
    ),

The additional entries 'id' and 'missspelling' in the array 'spellcheck' still fix the error #412
"Spellcheck does not read words from a nav list for editing" in Spell Check.

**Comment by OverlanAI** [comment]
+1 to this, and the HREF changes.  Tested in 2.6.9 and 2.6.10 with good results.
Nice catch!

tnx
