### ISSUE TITLE
User defined aiml search looks in wrong column in admin 

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#431]
I noticed when i search for a pattern in the User Defined aiml admin page that it is actually doing the search on the user id column and not the pattern.
tnx

**Comment by patrickschur** [comment]
Thanks I've noticed that the complete table was messed up. I fixed that. :)

**Comment by OverlanAI** [comment]
Looks good, tnx for the fix. Can close this or i will later.
