### ISSUE TITLE
FUND DAVE WE NEED YA

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#438]
IDk how but he got the big C and dead sux!
Set up something so he and his family can cover what it costs to fight that crap.
I met and was lucky to spend time with devs like him.
You do not get the rare few that give a crap like him..
The rare are the ones that give everything to you and never ask you for anything!
Dave is one of the rare so after he gets better thats not the end of it..
Gotta pay the bills too.
I think keep it simple .. pay-pal direct but we need to do something here.
If it was you, what would you like the others to do for you?
TNX (Hacker got heart for the good stuff)

**Comment by OverlanAI** [comment]
Medical costs big time but we got the good stuff.
Dave gave us all this so send what you can spare.
Kinda like save Einstein!
What if it was you?
Help him and his family with a few spare quatloos.
It will make you feel good!

**Comment by Dave-Morton** [comment]
There's no reason to donate funds to cover my medical costs. As a veteran of the U.S coast Guard from the late 70's and early 80's, I get ALL of my medical expenses covered by the Veterans Administration. If someone WANTS to send me money, I won't object, of course. 😄 But it won't be used for medical expenses. It will likely be used to support my addiction to fishing. 😛

**Comment by OverlanAI** [comment]
I said there comming and man wow. you nent program- o in one way but now its 3d.
So let them poke and prod till you feel ok.
Im just 64 now but im never right man
https://www.youtube.com/watch?v=uS90B4sZf7U
it helps

**Comment by OverlanAI** [comment]
seems im not allowed to care as off topic, why did you give that ass hat the keys?
