### ISSUE TITLE
2 things we are not doing yet

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#441]
I was going back through some MIT lecturers about novice base AI and 2 things stuck out that we are missing.

1. Backtracking
    This is when i ask the program how it arrived at saying what it did for any given reply it makes.
    (this is done so we can check the program logic mostly in case we are missing something we should not be but also can give it away to explain if it is challenged).

2. Two truths and a lie layer over the current scoring algorithm that helps steer it to the more likely correct reply by adding weight to the existing score.

In both cases we try to take the user from always being the Oracle of  everything they say as true and can steer its reply to one that challenges that user in a logical way. 

If i say "Hi my name is bill and i am a girl." it is ok at that point for it to say "Hello Bill."
if i say "Hi my name is bill and i am a man" we are still ok by it saying "Hello Bill."
if i say "Hi my name is bill and i am a man"  it would add weight to the score and should say "Hello Mr. bill!"

That is a very basic example of what i mean, If i said to it again
 "Hi my name is bill and i am a girl." Now it is time for the program to challenge the user with a question since we are at an impasse with the logic. we have 2 true and 2 false so it might ask "Why is your name bill but your gender is female?".

In this way at least we can set things up for a better reply and not completely making all users the Oracle of  everything.
The only true Oracle should only be the bot master.
Why the problems sound hard to solve they actually are not.

TNX

**Comment by OverlanAI** [comment]
2 ways this is done, Nearest neighbor or Shortest distance types of search.
Program-o can give us what we need where we use the index number (so we can back track) and the current score value of each forward choices there may be.
In this case we want it to ignore low score choices and only look for branches that have a higher one. (our steering wheel if you will).
The idea is so that it will only look down paths as it searches for what ever path has a better chance to find the most correct reply.
When or if it hits a dead end or 2 paths = the same score it backs up the car and explores a different path and eliminates the ones it tried already.
At each step the index # is held in memory so it can back up the car when i needs to or did find the best reply it could and can now be used to play back how it decided what reply to use.
There are difference between the 2 types used but without getting to a lot of MIT math, it will come down to performance choices. The fastest may not always find the max score possible but it is very fast and has a good chance that it will mostly be correct. The other way is used when was must always have the highest score possible and do it as fast as it can to solve.
Both can and are used quite commonly.
The other thing is we would no longer need SRAI at all due to how this works.
In both cases we have the ability to backtrack by playing the index values backwards after it found the correct reply.
Going further the backtrack index values can also be saved that later can be selected if there is one and jump to the correct reply that it already solved in the past. (becomes a type of SRAI)
However that is not necessary to do and would get into problems when we add more choices in.
So with a slight rethink we can get rid of a few things and gain something that is more powerful.
Both algorithms are easy to look up on the web but may look a bit scary, however they are not as complex to code and Program-o has the plumbing to use them.
Anyway this is food for thought.

**Comment by OverlanAI** [comment]
Going further.
What it is doing is splitting the total rows in the aiml table by 2. An upper range and lower range of index to look down.
as it looks down one or the other it is looking for the first none 0 score it then does the same on other range. What ever index range has the higher score becomes the main one it will look down and ignores the other index ranges. This process is a form of reduction and so we gain speed since each forward split becomes an even smaller set of index ranges it will look in.
Nodes that have no or low scores will not be used as it gets closer to the correct answer and at the same time becomes faster each step.
Each split of index range becomes less and less to look down but at the same time is getting closer to the best score it can find.
So what happens is we don't have to look down through say 100k rows of data each time or just settle on the first few choices as the only choices by not bothering to look down zero or low score nodes.
It will have the ability to back up and try the other fork in the road and so on.
This makes this very fast by a factor of 2 and will end with the highest score it can find.
If we want to remember the index paths we can or forget them after it found the best reply can be used to make it  faster the next time it get the same user input later on.
When you think about it, Like this it gets easier to understand why it is done using one or the other type of search when we start out with (i have no idea how to get there yet) that is our users input.
We gain speed and a very high chance it will reply with the best one it has.
TNX

**Comment by Dave-Morton** [comment]
You **DO** realize, don't you, that backtracking is already incorporated into AIML in the form of both pattern-side _and_ template-side `<that>` tags, and that it's up to the skill and experience of the botmaster to properly utilize these tags to good effect, yes?

Can't comment on the rest. too tired and weak to put in the effort

**Comment by OverlanAI** [comment]
HAY BOSS ....
Good to hear from you again.
Yes i was aware of what we have and i know it works but when at some point it has to deal with GB of data it will grind to a halt unless there is index range pruning logic done.
Anyway i was just describing basic ideas but thats not the end of it.
The algorithms just give us  a better search function with some logic of its own.
Just because it finds the best scores doest not mean it ends right there but gives it a lot of breathing room and flexibility as a function.
Just because it finds something with the best score does not mean that it is the best reply just yet.
For example i may set the min max score so the function will return close enough results that each have the exact index number that points to them that it passes to the next function.
So if i only want a list of a few choices it finds like say a score of 180 or higher then more logic can be done, A lot like it does now with winning score but we are not using score since it already did that for us.
Anyway theres more to it than just the search but it could end right at that point and call it day.
Its gets into what you were suggesting about SRAI bool index and a few other ideas you had.

For now just keep working on getting better man, we are doing our best to keep the light on for you.
TNX

**Comment by OverlanAI** [comment]
Aiml backtracking just shows me the results that i already know but what it does not do is to describe the decision making process it used where i can see the score tree and choices.
Think of more like working a math problem backwards to check the result and decide if it is correct or not. I know the input values and i know the result it comes up with but in order for the result to be true it also needs to work backwards from the result to the same input values.
In backtracking this is what they mean and to display this to the user in a way it can be understood.
How that is done starts with the search algorithm where is can keep track of that information at the same time it is doing a search anyway.
The "How did you decide to say that?" question is a by product of something it does anyway so why not use it too.
Its useful for debug or looking for bottle necks and might be interesting to a user to see if they want to.
OR we just get rid of the byproduct after each round if we dont want to do that.
MIT loves to see things like that that can show forward and backward that prove that the result is TRUE.
Anyway within the search, it already uses it internally so it can be saved for other uses if we want to.
For now the new search mod is not quite ready, seems php has a quirks of its own lol.
TNX

**Comment by OverlanAI** [comment]
Btw what is it sorting first?
My guess is pattern first then thatpattern (if you are sorting thatpattern on the next recursion).
It only matters so i know the order used. If it is pattern then that makes it easyier becuse we can split the index range lexically.
So if it is looking for I HAVE A BALL .. it starts with "I" so it would only look down that range assuming we split the first index ranges like that. Anything in the other 1/2 is ignored on the first scoring pass.
That way it is only looking at a small range of things that all start with "I" and ends at "J" with the first score pass done on just that range. If the range of "I" is wide then it can split it again by the next word letter of "H" and so on then score everything in a small index range for the rest of it.
The same thing can be done with thatpattern on the next pass or if it just on pattern first we just have it also score THATPATTERN if there is one on the first pass. But it really doesn't matter what one since the same process is used and depends on if we are scoring both things as one value or as 2 different scores.
Hopefully i ask that question right lol.
The idea is so it only does a more depth type search where the odds are highest that it will find the needle we are looking for in a huge haystack very quickly.
TNX (Just because i want a German car does not mean i want to go to Germany to get it)

**Comment by Dave-Morton** [comment]
I'd have to look at the SQL query in order to tell you, sorry. Prolly by topic, then thatpattern, then pattern, maybe?

**Comment by OverlanAI** [comment]
Ahh answered my own question, it is a push bot so pattern is always first because the bot has not said anything yet.
Anyway i ran into something else that didn't seem right to me in scoring.
i have 2 patterns where the direct pattern is "What is my name" but i also have another one that is "What is my *".
So what i got is a higher score on "What is my *" and not the direct match that to me should always override anything else given thats an ABS match to what i asked.
A direct match is as good as we get in my thinking.
Anyway seems that is not the case and found that strange.
If i say to it WHAT IS MY NAME and the pattern is also WHAT IS MY NAME then i would think that should override everything else and skip anymore scoring in that case.
But if i said WHAT IS MY AGE and there is no exact match then ok fall to "WHAT IS MY *".
Anyway that kind of made a do a HUH? lol
I know that i can do all that in "WHAT IS MY *" and not bother with the direct match but that still seems odd to me.
TNX

**Comment by OverlanAI** [comment]
You had notes about it, So im back on track again. Its always pattern first since it is a push bot.

**Comment by OverlanAI** [comment]
One thing that jumps out is that it does a top-down or bottom-up search. Why that is ok if there are not a lot of them you can just bulldoze thru them all and not be so bad.
But when you split the range then to search the world data just got a lot smaller and faster.
So lexical would help a lot for a 1st patten search since your splitting the index range at least in half so you have a lot less bulldozing thru all of it going on each round.
Anyway you added a lot of good notes so that helps.

**Comment by OverlanAI** [comment]
An example of what may help is first we get total rows in the aiml table then device it by 2 (split the alphabet in half. If we cannot divide by 2 the add 1.
That gives us 2 ranges (upper part and lower part)
The user says "Hello my name is bob.", since the first letter or word we have is Hello. we only look in that half (upper one) since thats where things will be found that start with H or hello xxxxxx.
In just doing that and if it found nothing (no match) then it will know that a lot sooner because we did not bulldoze all the way to the end of the table. If it is there or something close enough then it just found it in half the time because its not looking from A-Z each round.
Thats at least a good start in making world data (all of it) a lot smaller.
Thats just a simple example because we could sill have 1k patterns that start with H or the word hello so it would temp. split it again in the same way it did already.
Anyway thats the basic idea how we get to what we want to score the quickest (we would at least be looking in the ball park and not looking thru the whole world data.
TNX

**Comment by OverlanAI** [comment]
Anyway once the above function worked out a small range where what we are looking for might be found, it them pass's the very small index range to the scoring function to do its magic on.
Then the scoring function only has a limited number of things to look at if something was found in the first step.
TNX

**Comment by OverlanAI** [comment]
So far lexical is working but i ran into an argument about mixing min/max logic.
All of the algorithms are gold star but it will take a combo.
Anyway Evan lexical search cuts down on how big the world data is by a factor of 3.
Right now its a ping pong about the best approach or how to combine them.
But all agree that world data search is bad when we get a real big data world it has to look in.
Anyway crazy math but they got big heads so im on hold lol.
TNX

**Comment by OverlanAI** [comment]
Yah screw MIT too, we are all just silly i guess
