### ISSUE TITLE
Unknown cause but have seen it manytimes

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#444]
`08/21/2018 15:14:03 - PHP ERROR [Notice] -Undefined variable: tmp_sentence in H:\wamp64\www\ProgramO\chatbot\core\conversation\intialise_conversation.php on Line 320

08/21/2018 15:14:03 - PHP ERROR [Warning] -array_reverse() expects parameter 1 to be array, null given in H:\wamp64\www\ProgramO\chatbot\core\conversation\intialise_conversation.php on Line 320

08/21/2018 15:14:03 - PHP ERROR [Warning] -array_unshift() expects parameter 1 to be array, null given in H:\wamp64\www\ProgramO\chatbot\core\conversation\intialise_conversation.php on Line 335`

function push_on_front_convoArr.
I added at line 267
$tmp_sentence[] = ''; //Added OLAI just to define it but the error could be misleading.
TNX

**Comment by Josef-Meier** [comment]
@OverlanAI 
Hello OverlanAI ,
If you also use the version 2.6.10, that would be very strange that in the "intialise_conversation.php" at line 335 an error is issued. I have a comment line at that position.
And before at line 320, there is no variable "tmp_sentence" for me.
However, I am using a modified version of "intialise_conversation.php" because of 
Issue # 420, where I added a function "update_users()" from line 536.
Do you also use a self-modified version of the "intialise_conversation.php"?
I do not know. If there are differences between PHP in Windows and Linux. With my PHP under Linux the comment lines are also included.

```
Line 317:     for ($i = $rememLimit_tmp + 1; $i <= count($convoArr[$arrayIndex]); $i++)
Line 318:    {
Line 319:        if (isset ($convoArr[$arrayIndex][$i])) {
Line 320:            unset ($convoArr[$arrayIndex][$i]);
Line 321:        }
Line 322:    }
```

```
Line 334: /**
Line 335:  * function load_bot_config()
Line 336:  * A function to get the bot/convo configuration values out of the database
Line 337:  *
Line 338:  * @param  array $convoArr - current state of the conversation
Line 339:  * @return array $convoArr (updated)
Line 340:  */
```
Best regards

**Comment by OverlanAI** [comment]
I am running current dev 2.6.10 on WAMP (current) using PHP 7.0.x. (NON PRODUCTION MODE). WIN 10 pro, 16 gig ram, SSD, 8 core AMD@ 4.2 ghz. 1080 TI nvida with 3 displays.

The above errors are a Random condition that i have seen in the past but was never able to pin it down to the cause.
I did do a clean install a few days ago so it may be a problem that was already in dev and not something i added.
However there could be something that PHP is not happy about so i will run it again in 7.1.x and 7.2.x.
I often will do a clean install before i test for new suspected problems or when i am working on something experimental.
The reason i run 7.0.x is because i find that the current master and dev. versions often work well with it.
Dev will work ok on any of them (less a few known problems with php 7.2.x.).
Anyway I will try a few things and then your suggest change to narrow it down a bit more.
Mostly because this was a clean install and i report anything i see that doesn't look right so that it is at least posted.
Given this is a random problem makes it harder to to trace. 
TNX

**Comment by OverlanAI** [comment]
`//if there definately is something in the sentence array build the temp sentence array
        if (($cmatch > 0) && ($matches !== FALSE))
        {
            foreach ($sentences[1] as $index => $value)
            {
                if ($arrayIndex == "that")
                {
                    $t = ($value != '') ? clean_that($value, __FILE__, __FUNCTION__, __LINE__) : '';

                    if ($t != "") {
                        $tmp_sentence[] = $t;
                    }
                }
                else {
                    $tmp_sentence[] = $value;
                }
            }
            //reverse the array and store
            $sentences = array();
            $sentences = array_reverse($tmp_sentence);
        }`
Just for ref. to the section it refers too in the error and this is a section that is current in DEV.
I did add your hack to the top of this file but i do not see how it has anything to do with the error.
TNX

**Comment by OverlanAI** [comment]
This may be a side effect caused by #499
Just happens to hit MAX nesting level at that point then JIT goes off leaving no array.

**Comment by OverlanAI** [comment]
you dont listen to dave so have nothing
