### ISSUE TITLE
The version 2.6.5

### ISSUE THREAD

**Issue by alianrkeasan** [Program-O/Program-O#446]
Hi all,

Where can I download the version 2.6.5?

I need it because I have another chatbot in this version, and I want to replicate the exact same.

For me, it is the best version. I can't find it anywhere, why?

**Comment by patrickschur** [comment]
You can't download version 2.6.5 anymore. You only have the option to download version [2.6.8](https://github.com/Program-O/Program-O/tree/2.6.8) or [2.6.3](https://github.com/Program-O/Program-O/tree/2.6.3). I would suggest you to download the newest dev branch to get the latest features and bug fixes.
