### ISSUE TITLE
SRAI bug where table does not get filled on WIN

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#448]
`Program O has encountered an error. this may help:
    Error # 8
    Message: Undefined offset: 0
    File: H:\wamp64\www\ProgramO\library\PDO_functions.php, line 355

    Program O has encountered an error. this may help:
    Error # 2
    Message: array_keys() expects parameter 1 to be array, null given
    File: H:\wamp64\www\ProgramO\library\PDO_functions.php, line 355

    Program O has encountered an error. this may help:
    Error # 2
    Message: implode(): Invalid arguments passed
    File: H:\wamp64\www\ProgramO\library\PDO_functions.php, line 371`

That is all that is reported, I did check that  $lookups vales are there and seem correct.
TNX

**Comment by Josef-Meier** [comment]
@OverlanAI 
Does the error occur in Menu "SRAI Lookup" when manually filling the table?
Best Regards

**Comment by OverlanAI** [comment]
Yes correct.
The only SRAI is what it adds on its own when it runs into one during a conversation but thats not how it was meant to be.
I currently have 10k non-repeating SRAI calls.
It will fill it in correctly using the same set but running MASTER and not DEV 2.6.10.
tnx

**Comment by OverlanAI** [comment]
What is does do correctly is to clear out the old SRAI table if there are any in it. CORRECT
Then it reports the total SRAI calls it finds for the set. CORRECT
Then it reports how many SRAI calls that are not duplicate calls. CORRECT (and the numbers are correct)
Then it reports that it inserted 0 into the table, WRONG
When i look at the SRAI_LOOKUP table with php_myadmin there is nothing in it.

Anyway thats about all i know about this bug, Dave seem to know what was wrong but that was around the same time he got really sick so thats where this problem has been for awhile now.
TNX.

**Comment by OverlanAI** [comment]
Yes and sometimes it works for me as well but Dave looked at this and thought what happens is that its clearing the temp. array that holds the index that it should insert before Mysql has done it.
That might explain why on a small amount of SRAI calls it works because that happens very fast where i huge number of them takes much longer to process.
When i look at that section where it puts whats in the temp. array back again there is no check done between the insert and it making the temp array NULL.
How that can happen i am not sure but, The error is the error and my results are that it usually fails.

An interesting thing though is i rather like it to just add to the table what it has actually used in conversations and not all 10k of them. In an odd way it helps because the bot is only putting in the SRAI table what it needs as it needs it.
It is not broken as far as it not working it just did not set up as they meant it to.
The other thing i forgot to say is i do have 5 bots not just one.
Anyway for me it is not WAI on WIN10 and your running on linux like most of the devs are and for them they have not seen the problem but dave was able to test in WIN 10 pro and did see issues.
tnx

**Comment by Josef-Meier** [comment]
Hello
At first it looked good with "Fill Lookup Table" . But I have found duplicate or multiple identical entries. See picture attached.
I think I have to open my own issue, because i have the version
 2.6.10.
Best Regards

![srai_lookup_2_6_10_duplicates](https://user-images.githubusercontent.com/40842710/44687539-c80a6f00-aa51-11e8-80fb-45341745a889.png)

**Comment by OverlanAI** [comment]
To make this more clear, The problem i ONLY have when i run 2.6.10 DEV.
Master does not have this problem for me.

**Comment by OverlanAI** [comment]
I noticed that the multi-insert is a call to a PDO function so mabey a bit more error logging in that function will spread some light on the problem, I dont see anything compaining on the mysql side of it and php has PDO mod enabled.
I tryed to update using  v 5.6.x 7.0.x 7.1x and 7.2x (thats what i use currently) but that did not change the problem.
From what i can tell in the srai_update.php it all looks good until it gets to the multi_insert line.
TNX

**Comment by OverlanAI** [comment]
Also at around line 202 in SRAI_lookup.php, Dave had me add a line that corrects the displayed non-repeating value that i continue to has to add.

`$lookups = array_unique($lookups, SORT_REGULAR); // Added hot fix from dave so that the displayed count is correct.
    $now = microtime(true);
    $cet = round($now - $let, 3);
    $let = $now;
    $lookupsCount = count($lookups);
    $lookupsCount = number_format($lookupsCount);`

His hot fix did take care of part of a problem but changed nothing when it came to it doing the PDO db_multi_insert or possibly the db_write functions where i think it fails at.
TNX

**Comment by OverlanAI** [comment]
Seems this is a timing problem between php and mysql.
If the mysql is getting slow (big log files ect.) it may not be ready when it gets to the multi-insert.
Php thinks its done and Mysql is like "Huh ... what ... Never mind".
after i flushed the logs and things like that it then finally added the SRAI's to the table.
Anyway i still find that odd but there should be a check done to make sure mysql did what the script thinks it did and not just assume it did.
TNX

**Comment by OverlanAI** [comment]
Ahh it is hitting a MAX as i see in #449.
Once anything hits the max nesting level it bails on everything it is doing including filling the table.
With small numbers of SRAI or SR tages to parse it fills it ok.
When there are many it hits that brick wall each time.
TNX

**Comment by OverlanAI** [comment]
Seems that #449 is exactly why it was not filling in the SRAI table for me. It hits the max nested and ends right there so nothing is written to the table.
When i changed it to MAX_nested = 1024 with my huge set it fills it as expected but i run the risk of it hitting MAX MEMORY then.
Nether should happen in the first place in my opinion and never did happen when i used MASTER with the same set.
Since when it hits the MAX in ether case error logging also stops so the logs do not reflect information to set the BLAME as to what nested loop it is in.
Once the max is hit, PHP halts everything resets the scripts again, so to the user it looks more like just strange glitch and can give misleading bug reports because they have been doing something that happens to hit the tipping point for MAX NESTED and,or MAX MEMORY.
Mutli-bots make this far worse since the MAX is not changed but you have many things going on at the same time for each bot that is active and chatting.
Anyway i can only roughly narrow it down in core and that just knowing it is hitting the MAX often is not helping to point to the WHY well enough.
Extending the MAX is bad idea as pointed out PHP and STACKOVERFLOW and my own tinkering also shows me they are correct. Extending the MAX is just borrowing time but will not defuse the bomb.
TNX

**Comment by OverlanAI** [comment]
all yours man, good stuff
