### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by alianrkeasan** [Program-O/Program-O#450]
I recently installed 2.6.10 dev and the spell check is not working.

It says "There was a problem editing the correction - no changes made".

**Comment by OverlanAI** [comment]
There is a patch posted for that and another section here but it has not been pushed to Dev yet.
TNX

**Comment by alianrkeasan** [comment]
Where is the patch?

**Comment by Josef-Meier** [comment]
@alianrkeasan 
Hello,
to Spellcheck there were 2 Issues # 425 and # 426.
As it looks like they were patched.

https://github.com/Program-O/Program-O/blob/dev/admin/allowedPages.php
https://github.com/Program-O/Program-O/blob/dev/admin/spellcheck.php
Best Regards

**Comment by alianrkeasan** [comment]
Thank you.

But how can I install these patches?

**Comment by OverlanAI** [comment]
Well it looks as though they did push the changes to the current dev branch.
Could you provide a bit more information about what you are seeing?
You can find the debug logs in a side folder where you installed program-o.
TNX

**Comment by Josef-Meier** [comment]
@alianrkeasan 
Hello,
I have a LINUX-Apache-MySQL-PHP7 (LAMP) environment.
Please click on my links at my comment before. Then downloaded the patches on right-click at "RAW"-Button.
![screen_1](https://user-images.githubusercontent.com/40842710/45108457-ebfa3e80-b13c-11e8-8830-55ec78aaeb42.png)

Then I backed up the original files "allowedPages.php" and "spellcheck.php" with "move" and loaded the new ones into the admin folder of Program-O. Check the the owner - and file permissions of the patched files.
The file "allowedPages.php" seem OK now, but  "spellcheck.php" does not work.
The developer has made further changes.
I have a problem with line 385. It seems it need a NULL value as in the previous version before the last patch.
If I change the line then "spellcheck" works for me.
Change Line 385 into:
$sql = "INSERT INTO `spellcheck` VALUES (NULL, :missspell, :correction)";
As it looks like, Issue # 426 needs to be reopened.
Best Regards

**Comment by OverlanAI** [comment]
Yah the TABLE does not allow NULL in any of the columns so it cant insert it.

**Comment by Josef-Meier** [comment]
@alianrkeasan
Hello, 
The two issues # 425, # 426 also contain simple solutions to the "spellcheck" problem. Only a few lines have to be edited. Regardless of whether Windows or Linux, this should work.
So need not wait for a new version. But there are a few other issues. 

@OverlanAI 
Hello,
Is a question of SQL syntax.
The number of fields must match the number of values.
Following possibilities:
1) INSERT INTO `spellcheck` VALUES ('XXXXX','AAAAA'); => Error #1136
2) INSERT INTO `spellcheck` VALUES (NULL, 'XXXXX','AAAAA'); = > is OK
3) INSERT INTO `spellcheck` (missspelling,correction) VALUES ('XXXXX','AAAAA'); => is OK

Best Regards

**Comment by OverlanAI** [comment]
@alianrkeasan 
Well you can use word sensor in the mean time, it can at least swap out misspelled words for the correct word so that you can get on with what you need to do why we have another look at this.
Thank you for the reports, sometimes we get busy looking for the big problems and forget about the small ones lol.

@Josef-Meier 
Can you re-open #425 and #426 please.

TNX

**Comment by alianrkeasan** [comment]
Ok thank you, that will work.

**Comment by OverlanAI** [comment]
Okay in the file Spellcheck.php (in the admin folder) line 216 should be

` $sql = "INSERT INTO `spellcheck` VALUES (NULL,'$missspell','$correction')"; //OLAI CHANGE `

and NOT

` // $sql = "INSERT INTO `spellcheck` VALUES (:missspell, :correction)"; // WAS `

The allowed pages file is fine.
TNX (Sometimes its the small things that get yah)

**Comment by Josef-Meier** [comment]
Hello,
sorry, I had specified the wrong line number in my last comment.
It's line 215 in patched spellcheck.php version 2.6.10 dev in my "vi" editor.

Is a question of SQL syntax, because id is auto increment.

It would have to be changed from:

```$sql = "INSERT INTO `spellcheck` VALUES (:missspell, :correction)";```

to:

```$sql = "INSERT INTO spellcheck VALUES (NULL, :missspell, :correction)";```

Best Regards

**Comment by OverlanAI** [comment]
@Josef-Meier 
Or you can do it like that, Just a different way to do the same thing is all.
I just used the line i already have been using for a long time now was all and know it work's.
At least she can use spellcheck again.
TNX

**Comment by Josef-Meier** [comment]
@OverlanAI 
Hello,
yes, there are more possibilities. :blush:
Best Regards

**Comment by alianrkeasan** [comment]
Thank you very much guys, I changed the line as told by  @Josef-Meier  and now my spellcheck is working fine.
