### ISSUE TITLE
Response Sequence requiring previous replies.

### ISSUE THREAD

**Issue by GDNighthawk** [Program-O/Program-O#456]
Hi, I've been playing around with different scripts for something I'm trying to make and bumped into yours, I find it very easy to use, but I'm curious if you could do things like this, I tried inserting the previous response in the "thatpattern" field, but doesn't seem to do anything, the bot just changes topics or keeps repeating the same thing. What I'm basically trying to do is have a bot store information locked behind different passwords and once the password is detected open up a new branch of conversations. Something like this: 

User: Hey Alexa!
Bot: Hey.
User: Open Protocol Skype Passwords.
Bot: Protocol Request Confirmed, awaiting password.
User: *password*
Bot: Password confirmed, which password would you like to know.
User: Give me the password for user John Doe.
Bot: *password*

Obviously, the password should match the one expected by the bot in order to unlock the new conversation path. 

Is anything like that possible? Thanks!

**Comment by OverlanAI** [comment]
Well that can be done in a few ways where you are setting a value in a set name XXXX value that you can get name XXXX in some other section of your aiml when you need to use it again once its set.
Thatpattern is more of a control type thing where if what the bot said in the first round matches one of the thatpetterns.
Anyway it can be done in AIML but it will take more than just thatpattern.
set name xxxx values are volatile in that they are a temp. type of memory.
There are other ways it can be done if you need each password to be persistent.
If you could ask your question with a more general idea about the result you expect, that would be more helpful.
TNX

**Comment by OverlanAI** [comment]
Thump Thump.. is this thing on?

**Comment by Dave-Morton** [comment]
That can certainly be done, but it's done within the AIML code specifically, and not within Program O. Technically, this is beyond the scope of Program O, but I'm always happy to help a fellow botmaster with AIML construction. I just don't want to do it here. Please send me an email at dmorton(at)geekcavecreations(dot)com and we can hash things out offstage. 😄
