### ISSUE TITLE
Got skill?

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#457]
Lets do this, progam- got all the core we need to make the other go "Huh? you cant do that!".
Says them .. that sexy talk to me.
In fact we can do that because we stand on shoulders of a giant. All this work matters.
We stand on the shoulders of project-o so we can make a bigger giant now.
AIML is easy but thats not the end of ideas is it?
Dave and his crew pointed you in the right direction now
The combo of all AIML is in other cores is not the same in program-o.
Consider MYsql as TB of everything and we get the best MIT to deal with it.. 
We got it all from java to php and the best stuff you know.
I want to see TB of aiml in program-o, and it wont blink .
To me and crew that like sex but yah.
So lets do this right now.
TNX (hackers vent with an idea)

**Comment by OverlanAI** [comment]
one song to you and yah it gonna happen 
https://www.youtube.com/watch?v=84PETdu743A

TNX (no one dies we use move to the other you).

**Comment by OverlanAI** [comment]
I will give you a clue as to who a i am and why i love this project.
Opensim dev rejected Aurora because we did not believe in "cant be done".
Now you all stand on it, Thats crew :)

**Comment by OverlanAI** [comment]
So if you got skill then lets fix it right and do the cant be done anyway!

**Comment by OverlanAI** [comment]
Yah i got you ,mail so what?
https://www.youtube.com/watch?v=aZObv6QgRXc
show me
TNX (dont mean you got skill)

**Comment by OverlanAI** [comment]
If you got better then show us right here right now,
If we are wong then show us else we do this right.
Its not about right way.
send everything that fails so we don't do that.
show us each time you tried and fail to make it work.
 when you do that we know what fails to work.
It helps so we dont waste time.

**Comment by OverlanAI** [comment]
tune or dont bother
https://www.youtube.com/watch?v=jEG0-3xlAkg&index=6&list=RD4up6_OphOMY
all it is now

**Comment by OverlanAI** [comment]
tnx but no. i need
https://www.youtube.com/watch?v=O_1ruZWJigo&index=11&list=RD0u8teXR8VE4
not lame AIML must be .. Time to change the std.
but tnx

**Comment by OverlanAI** [comment]
no hun  tnx for the mail. i love cal tech but
i need
https://www.youtube.com/watch?v=WtuoFv4dcwM&index=12&list=RD0u8teXR8VE4
not wish.
TNX( crew dont work like that)

**Comment by OverlanAI** [comment]
sweet the best dammed hacker i know said "why not"
mmm
https://www.youtube.com/watch?v=I_2D8Eo15wE
geting crew and not one cares about AIML std.
TNX

**Comment by OverlanAI** [comment]
yah hun at mel os dev 
She is a real brat but best if the best .. Boom
https://www.youtube.com/watch?v=wZkTh_T75QY
Crew but know hard code
Dave .. chain saws are coming and they all hate me lol.
but they know how real it is man.

**Comment by OverlanAI** [comment]
no hun, this is better .. put your lights on and stop please with the hate.
https://www.youtube.com/watch?v=KCBS5EtszYI
your better than that

**Comment by BeZazz** [comment]
Think you forgot your meds this morning.

**Comment by quiraang** [comment]
@overlanai - I do not know what the hell you are talking about and I don't think I'm alone with that view.




Most of your recent comments have been gibberish and you are just wasting my time 




Cheers


Quiraang 




sent from my mobile







On Thu, Oct 4, 2018 at 10:34 AM +0100, "OverlanAI" <notifications@github.com> wrote:












yah hun at mel os dev

She is a real brat but best if the best .. Boom

https://www.youtube.com/watch?v=wZkTh_T75QY

Crew but know hard code

Dave .. chain saws are coming and they all hate me lol.

but they know how real it is man.
