### ISSUE TITLE
well looks like its time to fork

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#458]
seems new ideas are not wanted now. 
Did what we could.

**Comment by OverlanAI** [comment]
The custom tags were added value to this project, Dave encouraged that and we gave you the code.
We will out it anyway why you hide your head in the sand.
You got commit, dave gave it to you and all i see is you deleting a lot of hard work,  without any thought.
Mort invited us to the party man.
TNX (knows where the door is)

**Comment by Program-O** [comment]
We do appreciate new ideas, thank you for all your input.
We just ask that you keep issues to 1 issue at a time and all comments should be on topic.
If you open a issue with a new feature and submit a pull request with the new code in that is perfect...
and that is the correct way to get a new feature in the codebase.
All off topic comments will be removed as a kindness to the person who is reading this in 3 years from now trying to solve a problem they are having... I am sure you understand
Thanks again 
:)

**Comment by OverlanAI** [comment]
well you just pissed off the wrong crew man. You are wrong!

**Comment by OverlanAI** [comment]
Dave asked us .. asked me to keep it real (not dead bs).
But you do your thing and we will do what dave said.
You better ask the boss cuz you just pissed off a lot of great minds!

**Comment by Program-O** [comment]
You sound quite scary and i actually feel like you are threatening me.
I am sorry the I have caused such offence.
That wasnt my intention 'to piss off the wrong crew man' all i wanted to do is clear up the issues board. 
If you want to do general none-issue related chat then please come over to our forum/twitter/slack/facebook.

You can send a message to admin@program-o.com for more information on our social media or check the website. 

Thank you

**Comment by Program-O** [comment]
@OverlanAI This is your first and final warning... This is my Project... I AM Program O. Please stop rampaging on the issues leaving off topic comments or i will have to block you.
And i dont want to do that ... I think we can all be friends and work together, so lets please just do that.
Are we ok?
