### ISSUE TITLE
Star doesn't work

### ISSUE THREAD

**Issue by StrangerGithuber** [Program-O/Program-O#463]
Hello
I don't understand why but it doesn't work for me.
Probably I use this in bad way because in log I don't see any error file.
Anyway here is the aiml which I tested:

```
<?xml version="1.0" encoding="UTF-8"?>                                                 -->
<aiml version="1.0">
  <category>
    <pattern>TEST MESSAGE</pattern>
    <template><random><li>So it is a test, <get name="username"/>?</li><li>I see, <get name="username"/>?</li><li>Hahaha ok, <get name="username"/>?</li></random><br/>So it is a test.<think><set name="topic">TEST MESSAGE</set></think></template>
  </category>
  <topic name="TEST MESSAGE">
    <category>
      <pattern>YES IT IS</pattern>
      <that>SO IT IS A TEST</that>
      <template>I see, so it is.</template>
    </category>
    <category>
      <pattern>YES _</pattern>
      <that>SO IT IS A TEST</that>
      <template>I see so yeah I see</template>
    </category>
  </topic>
</aiml>
```

If I write **Test message** then I get **So it is a test, Myname? So it is a test.** 
This part works fine.
If I write after **Yes it is** then I get normally the **I see, so it is**. It works fine too.
BUT if I answer directly **Yes test messages the best** instead _Yes it is_ , then I get the default pickup line pattern.

I tried use both * and _ but didn't work any of them. What is the problem?

**Comment by StrangerGithuber** [comment]
Ohh I see. I usually look the dev most of the time. I need look the other branch too, it seems. :) Then I will wait until you are sure if the fix is valid. :) Thank you the hardwork. :)

**Comment by Program-O** [comment]
In the mean time if you just remove the '?' after it will work

**Comment by StrangerGithuber** [comment]
Yeah, it works on localhost without "?". :) I don't have better to do so I will test that branch too which you mentioned and I will write my experience. :)

**Comment by StrangerGithuber** [comment]
Sorry for double message.
So I tried out the https://github.com/Program-O/Program-O/tree/Bug%23461-missing-unique-keys branch and I got an error message. (With master and dev I didn't get any error). Hopefully you will understand what is the problem because I don't know.

So here is the error message:
```
Bad SQL encountered in file C:\xampp56\htdocs\chatbot\library\misc_functions.php, line #231. SQL:
INSERT INTO `chatbot`.`unknown_inputs` (`id`, `bot_id`, `input`, `user_id`, `timestamp`) VALUES(null, 1, 'yes gergerg', 1, CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE `timestamp`=:CURRENT_TIMESTAMP;
PDO Error:
Array
(
    [0] => 00000
    [1] => 
    [2] => 
)

PDOStatement Error:
Array
(
    [0] => HY093
    [1] => 
    [2] => 
)

Exception Message:
SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens;
Parameters:
Array
(
    [:bot_id] => 1
    [:input] => yes gergerg
    [:user_id] => 1
)

```

**Comment by Program-O** [comment]
thanks for the update i will have a look at that asap

**Comment by Dave-Morton** [comment]
Judging from the error message, there seems to be a typo in the code that creates the SQL query. Look for the following in the code, near line 231:

`ON DUPLICATE KEY UPDATE `timestamp`=:CURRENT_TIMESTAMP`

and remove the colon in front of CURRENT_TIMESTAMP. That should fix the problem.

**Comment by StrangerGithuber** [comment]
Hmm yeah, it fixed the error message but same time remained the above problem.
So I added **CLOSE TOPIC** and **_** patterns.

```
<aiml version="1.0">
  <category>
    <pattern>TEST MESSAGE</pattern>
    <template>Hahaha ok?<br/>So it is a test.<think><set name="topic">TEST MESSAGE</set></think></template>
  </category>
  <topic name="TEST MESSAGE">
    <category>
      <pattern>YES IT IS</pattern>
      <that>SO IT IS A TEST</that>
      <template>I see, so it is.</template>
    </category>
    <category>
      <pattern>YES _</pattern>
      <that>SO IT IS A TEST</that>
      <template>I see so yeah I see</template>
    </category>
    <category>
      <pattern>_</pattern>
      <template>
        <think>
          <set name="inp">
            <star/>
          </set>
        </think>
        <condition name="inp">
          <li value="CLOSE TOPICCTWO">Ok, topic closed.<set name="topic"/></li>
          <li>
            <random>
              <li/>
              <li>...</li>
              <li>* no sound *</li>
              <li>* tumbleweed rolls past *</li>
              <li>Lalalalalala?</li>
            </random>
          </li>
        </condition>
      </template>
    </category>
    <category>
      <pattern>CLOSE TOPIC</pattern>
      <template>Ok closed.
<set name="topic"/></template>
    </category>
  </topic>
</aiml>
```

1. Now I can't go to **YES IT IS** pattern either.
I get this error instead:
```
10/31/2018 09:49:50 - PHP ERROR [Notice] -Undefined variable: tmp_sentence in C:\xampp\htdocs\chatbot\chatbot\core\conversation\intialise_conversation.php on Line 279
10/31/2018 09:49:50 - PHP ERROR [Warning] -array_reverse() expects parameter 1 to be array, null given in C:\xampp\htdocs\chatbot\chatbot\core\conversation\intialise_conversation.php on Line 279
10/31/2018 09:49:50 - PHP ERROR [Warning] -array_unshift() expects parameter 1 to be array, null given in C:\xampp\htdocs\chatbot\chatbot\core\conversation\intialise_conversation.php on Line 294

```
_(It is ok if there is the path. It is to test the functions)_

2. I can't close the topic with **CLOSE TOPIC** pattern. If I write **CLOSE TOPICCTWO** then it will close the topic and normally continue talk other things.

The idea came from: https://github.com/pandorabots/Free-AIML/blob/master/shutup.aiml

**Comment by patrickschur** [comment]
Ok I see three problems here.

1. @StrangerGithuber Your AIML test code is not quit right. The pattern `yes _` should be `yes *`, because the `_` has a higher priority than `*` and a word match. This means that the category with the pattern `yes it is` will never be executed.

2. According to the AIML working draft the purpose of `<that>` is to match the bot’s last utterance, specifically, the last sentence of the last response. 
But Program-O doesn't do that. Instead it checks the complete sentence and not the last sentence like it should be. In your example one of the possible that patterns would be `SO IT IS A TEST UNDEFINED SO IT IS A TEST` and not `SO IT IS A TEST` like you would expect. So the that pattern will never match.

3. The other bug is in the scoring algorithm of Program-O. Because the that pattern will never match, it checks for a direct match of both patterns. The pattern that was found in the database and your input. Let's say your input is `yes it is` and the pattern that was found in the database is also `yes it is`. You can see that this will match. But `yes test message the best` does not match `yes _` or `yes it is` either. That's the reason why only on of your categories matches. It ignores the topic pattern completely.

A fix to this issue will follow in the next few hours.

**Comment by StrangerGithuber** [comment]
Yep, it works now. Thank yout the fix. :) It works with * and _ too. :) Now I can continue the project. You are hero. 👍
