### ISSUE TITLE
Installation Loop

### ISSUE THREAD

**Issue by stormdragon2976** [Program-O/Program-O#464]
I have installed the bot successfully and it says to go to the admin page and finish it, but when I go there, it redirects me to the installation page and wants to install again.

I'm using Ubuntu 18.04 with Caddy. If I remove the installation directory as per the instructions, it says "file not found". If I don't remove it, it starts the installation process again.

**Comment by Program-O** [comment]
It’s going to be a while before I can look into this properly as I am about to go away for quite a while, but what happens if u remove the install directory after you install it?

**Comment by stormdragon2976** [comment]
It just goes to a "file not found" page instead of the installer.

**Comment by Program-O** [comment]
Sorry you already said that didn’t you, erm I won’t be able to help you with this for a while but basically it’s just looking for the existence of the config file , have a look in your code and make sure it’s there ... and if u want to hack a temp fix then just hard code the path to the config file in code that checks for file_exists ... good luck

**Comment by Dave-Morton** [comment]
It sounds to me as if the config file that was _supposed_ to be created may not exist. Look in the config folder for the file global_config.php. if it's not there, then you may wish to check folder permissions to make sure that PHP can create the file, then run the install again. If the file already exists, I would suggest looking for gremlins in the system 😄

**Comment by stormdragon2976** [comment]
Thanks for the help. This got me pointed in the right direction. The installation page said the directories were the correct perms, but it still did not create the file. I'm guessing this is because  caddy writes as caddy, and php-fpm writes as www-data.

I changed the config directory to 777 while configuring, and it worked like a charm. Hopefully this will help anyone else with the same problem.

**Comment by Program-O** [comment]
Great news!!
I will look at putting another warning on the installation complete page, to warn people if the config file hasn’t been created ..

**Comment by Dave-Morton** [comment]
I'm glad that you were able to get it sorted out. While I'm not able to be as involved as I was once, due to my illness, I'm still very much interested, and I check in when I can.

@Program-O I like your idea of doing an existence check for the config file. That should save a bit of frustration in the future. 😄

**Comment by stormdragon2976** [comment]
One more thing that kind of threw me for a  loop. The installation checker did not check for and let me know I was missing php-xml. i was able to figure out what I needed from the logs using journalctl though.

**Comment by Dave-Morton** [comment]
@stormdragon2976 that's good to learn. I'm sure that the team will look into adding that requirement check. thanks for letting us know.
