### ISSUE TITLE
Program-o  responds too late in my site[Solved]

### ISSUE THREAD

**Issue by masa2146** [Program-O/Program-O#474]
I installed program-o on my site. I made the necessary settings. He responds too late when I write something. There are 14,000 data in the SRAI table, so can it be? What should I do? :)

**Comment by patrickschur** [comment]
How long does it take to get a response? How many categories do you have and have you tried to delete the SRAI table? Which PHP version do you use?

There is not much you can do to increase the performance.

**Comment by masa2146** [comment]
response time is changing from question to question. Example, ask "who are you?" for response time is 2 seconds but "what is your favorite color" for response time is 9 seconds.  PHP version 5.6.36. I didn't try to delete the SRAI table. Should I delete the SRAI table? How to learn to how many categories?

**Comment by masa2146** [comment]
thank you for response. I will try.

**Comment by masa2146** [comment]
I bought VDS. Before server features is 512 mb ram, 1 cpu. so it was very slow. better than current server and it is very quick. So the problem solved.
