### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Macley-Kun** [Program-O/Program-O#477]
Is this project still maintained?
It's a great solution for many projects, i'm just worried that there isn't any development going on anymore.

**Comment by patrickschur** [comment]
Sorry to say that, but this project is not maintained anymore. We are working on a new version of Program O right now. We don't have a release date yet, so stay tuned. :)

**Comment by Macley-Kun** [comment]
Oh wow that's amazing! A sort of rewrite i assume?

Is there any article i can read trough to get more information about this?

**Comment by patrickschur** [comment]
Yes it's completly rewritten from scratch. We are now using PHP 7 and for the UI we will use Bootstrap. We have a documentation but there is not much to see, because it's not ready yet. The project itself is in a private repo. So there is nothing you can read about right now. :(

**Comment by Macley-Kun** [comment]
Sure no problem! I'm eager to see your guys work!

Just one final question. A friend of mine is looking on supporting program-o like it is now.
Would it be wiser to build support for program-o now, or wait until the new version is out?

We wanna make it a plugin for [this project](https://github.com/avaire/avaire).
Again thank you for telling this, on the internet there is no real alternative to program-o as far as my research has reached. Given the functionalities, price and support.

**Comment by patrickschur** [comment]
Because this project is already a bit outdated and we will no longer support it, it will definitely make sense to wait until the new version is out. But again, we don't now when the release will be. :)

**Comment by Macley-Kun** [comment]
No problem! Thanks for answering these few questions!
We'll refain from working on the AI part until the new version is out!

Goodluck on the project and have a great weekend!

**Comment by lucasturci** [comment]
Hello, great to hear Program-O will be renewed!
I wonder if the new project will have the same open source license of this one?
