### ISSUE TITLE
Certificate expired of program-o.com!

### ISSUE THREAD

**Issue by Macley-Kun** [Program-O/Program-O#478]
Me and a friend have decided to support the v2 of program-o. And when i wanted to show my friend the demo. We both got some wierd certification errors, even css didn't load in for us.
Now after checking the certficiate. It seems that it has expired since yesterday!
![image](https://user-images.githubusercontent.com/26381427/62891517-33724d00-bd46-11e9-854b-4df9e0abcc11.png)

Maybe you guys can use this: https://certbot.eff.org/ if you haven't used it :P 

Hope to see this resolved soon!

**Comment by Dave-Morton** [comment]
Liz is currently on holiday (her honeymoon, actually), ans as she's the person in control of the website, it's she who will have to deal with it. Once she returns to the UK, I'll make sure she's aware of the issue.

**Comment by Macley-Kun** [comment]
Thanks! Congratulations to her o/

**Comment by Program-O** [comment]
i think this is fixed now ....

**Comment by Program-O** [comment]
once confirmed i will close

**Comment by Macley-Kun** [comment]
Can confirm! Thanks for fixing it so fast!
Good luck on the v3!
