### ISSUE TITLE
bot cannot response base on current time

### ISSUE THREAD

**Issue by miowXD** [Program-O/Program-O#482]
Let's say if I type "good morning" to my bot at night, the bot will still respond to me "morning".<br>Is there any possible solution to this kind of problem?<br>what I want is if I type "good morning" to my bot at night, the bot will respond "current time is 9pm, so you shouldn't use `morning`  ".

**Comment by patrickschur** [comment]
Could you send us the AIML you used?

**Comment by miowXD** [comment]
> Could you send us the AIML you used?

At the end I found that it can't be done by AIML, so I had found another solution to it
<br/>
The solution is like this: <br/>
Before the message send to program o to check the matched aiml word, I do a checking about the message.<br>If the message is greeting like `morning`, `good afternoon` or something else, then I will check is it the greeting correct to use at current time, and pass the result to aiml for reply
