### ISSUE TITLE
Non-English accented characters not handled correctly

### ISSUE THREAD

**Issue by Dave-Morton** [Program-O/Program-O#6]
When a non-English chatbot is created, certain accented characters are being handled incorrectly. This causes a problem with some responses not being triggered when they should be. the problem lies in the functions remove_allpuncutation() and remove_puncutation() {both of those function names are not spelled properly, BTW}, where all sorts of accented characters are being replaced with a space character, rather than their non-accented counterparts.

**Comment by nikmauro** [comment]
any news or solution about this issue?

**Comment by nikmauro** [comment]
take a look in this library https://github.com/jbroadway/urlify

**Comment by Dave-Morton** [comment]
No progress has been made with this issue, as yet, mainly because life issues have prevented us from devoting any significant time to the project in this area. I've looked at the URLify project you've mentioned, but some concerns over "*Symbols it cannot transliterate it will simply omit*" prevent me from fully endorsing it's use.
