### ISSUE TITLE
upload AIML error

### ISSUE THREAD

**Issue by vanabel** [Program-O/Program-O#63]
I don't know what's the AIML used by defalut, But it seems I should upload an AIML file for the bot. 

I get one here: https://code.google.com/p/aiml-en-us-foundation-alice/downloads/list

But at the upload, it report the error:

```
Fatal Error 9: Input is not proper UTF-8, indicate encoding ! Bytes: 0x85 0x2C 0x62 0x75 on line 32
Fatal Error 4: Start tag expected, '<' not found on line 2
String could not be parsed as XML at line 168
There was a problem adding file update1.aiml to the database. Please refer to the message below to correct the problem and try again.
String could not be parsed as XML
Fatal Error 9: Input is not proper UTF-8, indicate encoding ! Bytes: 0xE9 0x63 0x69 0x6C on line 1005
Fatal Error 4: Start tag expected, '<' not found on line 2
```

How to fix this?

**Comment by maxwellmandela** [comment]
where do i upload the aiml to?

**Comment by Dave-Morton** [comment]
You upload the AIML files through the admin interface. Simply log into the admin page, and navigate to the Uploads panel, using the navigation links on the left side of the page.
