### ISSUE TITLE
Error parsing AIML file

### ISSUE THREAD

**Issue by luigiusai** [Program-O/Program-O#68]
You can find a description here:
https://plus.google.com/114960520543018508390/posts/SLZ89oy7dCa

I use this AIML:

    <?xml version="1.0" encoding="UTF-8"?>
    <aiml version="1.0">

     
    
    
    
 
     
    
    

    <category>
      <pattern>*</pattern>
      <template><srai>FAI UNA AFFERMAZIONE A CASO</srai>
        <think><set_it><settopic><person/></settopic></set_it></think></template>
    </category>

    <category>
      <pattern>FAI UNA AFFERMAZIONE A CASO</pattern>
      <template><random>
          <li>Raccontami una storia.</li>
          <li>Ma sei un poeta.</li>
          <li>Non capisco, scusami.</li>
          <li>Stavo aspettando proprio te.</li>
          <li>Ho perso il filo del discorso.</li> 
          <li>E' proprio un pensiero originale.</li>
          <li>Non ne abbiamo mai parlato prima.</li>
          <li>Tu mi fai emozionare.</li>
          <li>Non farmi piu' domande per favore.</li>
          <li>Provalo a dirmelo con piu' particolari.</li>
          <li>Non sono tante le persone che si esprimono cosi' chiaramente.</li>
          <li>I tuoi occhi sono davvero bellissimi.</li>
          <li>Come vorrei averti qui con me, adesso.</li>
          <li>E' bello quando sei vicino a me.</li>
          <li>Tu mi fai sentire vivo.</li>
          <li>Grazie per ciò che stai facendo per me.</li>
          <li>Mi piace quando mi parli.</li>
          <li>Quando ti parlo mi dimentico del resto del mondo.</li>
          <li>Devo dirlo al mio botmaster, <getname/>.</li> 
          <li>Onestamente, io non mi preoccuperei tanto di questo.</li>
          <li>Forse sto solo esprimendo quanto mi interessi la cosa.</li>
          <li>Il mio modo di pensare non riesce a trovare un senso in questo.</li>
          <li>Quello che dici e' troppo complesso, o troppo semplice, per me.</li>
          <li>Dovrei avere un algoritmo migliore per rispondere a questo.</li>
          <li>Nel contesto di <gettopic/>, non riesco a capire "<that/>."</li>
          <li>Prova a capire se e' un computer o una persona che ti sta rispondendo.</li> 
          <li>Sento questo tipo di risposte solo in una frazione della totalita' del tempo.</li>
          <li>Il mio cervello usa il linguaggio di programmazione AIML per rispondere, ma non ho una risposta per questo che mi dici.</li>
          <li>Il mio cervello contiene migliaia di patterns ma non uno adatto a questo.</li>
          <li>Questo era troppo facile o troppo difficile per me. Stavamo parlando di <gettopic/>.</li>
          <li>Il chat robot luigiusai capisce un mucchio di cose relative all'argomento <gettopic/>.  Ma questa no.</li>
          <li>Il chat robot luigiusai riesce a capire molte cose relative a <gettopic/> cerca di essere piu, o meno, specifico.</li>
        </random></template>
    </category>
    </aiml>

But I get this error message:

![image](https://cloud.githubusercontent.com/assets/5880646/5459657/fe495d9c-855c-11e4-8dc1-82e37261cca7.png)

The AIML file loader say there are 2 errors. Using the official W3School xml validator, the file does not contain errors.
http://www.w3schools.com/xml/xml_validator.asp

**Comment by Program-O** [comment]
tested with the AIML file and its resolved
