### ISSUE TITLE
Interface bug and loop on login, if logged with an other browser

### ISSUE THREAD

**Issue by luigiusai** [Program-O/Program-O#69]
First of all, the image:
![image](https://cloud.githubusercontent.com/assets/5880646/5459755/cda0c152-855d-11e4-84e9-c893433188d2.png)

I am already logged in with firefox as admin; 
I try to connect with chrome, but I have this problem:
1) the interface is not showing correctly, as you can see from the picture;
2) after I do a correct login and password, the system loops showing me again the same page, asking me again to login, even if my data were correct.

**Comment by Program-O** [comment]
resolved
