### ISSUE TITLE
New feature: connecting to wikipedia to retrieve information

### ISSUE THREAD

**Issue by luigiusai** [Program-O/Program-O#72]
Dave,

this is for you :)
You could think about adding some feature about getting answers from wikipedia in php like this, using Wikipedia API:

<?php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://en.wikipedia.org/w/api.php?action=query&titles=Your_Highness&prop=revisions&rvprop=content&rvsection=0&format=xml");
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_USERAGENT, "Testing for http://stackoverflow.com/questions/8956331/how-to-get-results-from-the-wikipedia-api-with-php");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$result = curl_exec($ch);
curl_close($ch);

echo $result;
?>

This way, for instance, if someone ask: Who is Einstein?
The tool connects to wikipedia and prints some output to the reader :santa: 
this way the tool may appear more clever, I suppose.
If you think this is not possible, please close this new feature request :)
but I think we could implement this in the future. It would be really nice!

**Comment by samynathan17** [comment]
hi ,
iam using for 
<category>
  <pattern>WIKI *</pattern>
  <template><wiki><star/></wiki></template>
</category>

but not get results..

**Comment by Dave-Morton** [comment]
@samynathan17 It would be very helpful for us to have some more information about the problem that you are experiencing. Please read [**this wiki post**](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to learn what information we need to see. The more information you provide, the more we can help you.
