### ISSUE TITLE
Admin page issue

### ISSUE THREAD

**Issue by dsoap** [Program-O/Program-O#74]
I have configured the install page and it says that you are ready to use the admin page but every time I type in the admin URL it goes directly back to the install page? Is there something I did that was wrong? Thanks.

**Comment by dsoap** [comment]
Disregard my question it is now working.

**Comment by Dave-Morton** [comment]
Thanks for letting us know. Any idea what the problem was?

**Comment by dsoap** [comment]
Not sure. Left the page to work on something else for a second and came back to try again and it worked.

**Comment by Dave-Morton** [comment]
ALright. Thanks. :)
