### ISSUE TITLE
The config folder cannot be written to, or does not exist. Please correct this before you continue.  The debug folder cannot be written to, or does not exist. Please correct this before you continue.  The logs folder cannot be written to, or does not exist. Please correct this before you continue.

### ISSUE THREAD

**Issue by saadmeman** [Program-O/Program-O#75]

**Comment by Dave-Morton** [comment]
This is generally a permissions problem. What Operating system and server software are used with your Program O install?

**Comment by saadmeman** [comment]
ubuntu with lamp

**Comment by Dave-Morton** [comment]
Check the file/folder permissions for your Program O install for not only the folders given in the error message, but also fir the admin and chatbot folders. They should all be 0755. If the permissions are correct and you're still getting the same error messages during the install, please look at logs/install.error.log and post back with it's contents.

**Comment by saadmeman** [comment]
Problem is resolved , thank you sir. :)

**Comment by Dave-Morton** [comment]
I'm glad that resolved your issue.
