### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by noonn** [Program-O/Program-O#76]
object(PDOException)#2 (8) {
  ["message":protected]=>
  string(21) "could not find driver"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(48) "D:\APM_Setup\htdocs\install\install_programo.php"
  ["line":protected]=>
  int(179)
  ["trace":"Exception":private]=>
  array(2) {
    [0]=>
    array(6) {
      ["file"]=>
      string(48) "D:\APM_Setup\htdocs\install\install_programo.php"
      ["line"]=>
      int(179)
      ["function"]=>
      string(11) "__construct"
      ["class"]=>
      string(3) "PDO"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(3) {
        [0]=>
        string(45) "mysql:host=Localhost;dbname=chat;charset=utf8"
        [1]=>
        string(4) "root"
        [2]=>
        string(6) "dkssud"
      }
    }
    [1]=>
    array(4) {
      ["file"]=>
      string(48) "D:\APM_Setup\htdocs\install\install_programo.php"
      ["line"]=>
      int(73)
      ["function"]=>
      string(4) "Save"
      ["args"]=>
      array(1) {
        [0]=>
        &string(1) "2"
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
  ["errorInfo"]=>
  NULL
}
Cannot connect to the database! could not find driver

**Comment by Dave-Morton** [comment]
It seems as though your server's PHP install does not have the MySQL driver installed. It also appears that you've put your Program O chatbot into your server's root directory. This isn't necessarily a bad thing, but it does create problems if you need to do a "clean" install of the script at some point.

Can you please tell me your server's PHP version, and whether you're using Apache or IIS for your server software?

**Comment by noonn** [comment]
Hi~
Can you give the installation DB to me?
set admin id: admin and admin password: dkssud

My email: noonn@naver.com

I can edit DB information. (localhost, db name, db id, db password)

----------------------
My Local computer information and 
And  server is APMSETUP for windows.

Server Infos: Apache
PHP-Version: 5.3.23
PHP API: apache2handler
MySQL-Client-Version: mysqlnd 5.0.8-dev - 20102224 - $Id: 731e5b87ba42146a687c29995d2dfd8b4e40b325 $
MySQL-Server-Version: 5.1.41-community
Addresse: http://127.0.0.1/
Pfad: http://127.0.0.1/index.php
JSON Verfügbar: Ja
BCMath Verfügbar: Ja
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
Problem besteht seit Installation:
Verwendeter Editor:
Screenshot:
Problembeschreibung:


Thanks.

**Comment by Dave-Morton** [comment]
Noonn, I don't understand what you mean when you ask me to "give the installation DB" to you. The database has to be set up on your system (or on a system that you can both access and control) by you (or someone that you hire to do the job for you) before you can install Program O. This usually means having something like [phpMyAdmin](http://www.phpmyadmin.net/) to manage databases locally. If this is something that you need assistance with, please let me know via my [Contact Page](http://www.geekcavecreations.com/?contactMe&subject=Help+with+Program+O+database), and we can discuss it privately.

**Comment by noonn** [comment]
Sorry. my ENGLISH is no good.^^
Mail has been sent.

**Comment by Dave-Morton** [comment]
If you prefer asking in German (I assume from earlier posts that this is your native language, though I might be wrong), I can translate it well enough in most cases.
