### ISSUE TITLE
Server error #500 after installation 

### ISSUE THREAD

**Issue by lordhari** [Program-O/Program-O#82]
Uploaded files to a new directory (Were using v1.0.4 of Program-O).
Created database.
Ran installer.
Filled out all information, both bot (new bot) and database.
Reached installation complete message.

But at admin page I am getting "Server error #500".
Using myPHPAdmin in BlueHost.

**Comment by Dave-Morton** [comment]
Hi, lordhari.

I've taken a short sabbatical from the project while I'm attending school, but I still monitor GitHub from time to time. Have you looked at the error log to see if the problem has been recorded? You'll find the error log in the logs folder.

**Comment by lordhari** [comment]
Hi Dave,

Initially there was no admin.error.log but there was a install.error.log which had warnings :

> mkdir(): No such file or directory in ../install/install_programo.php on line 161
> file_put_contents: No such file or directory in ../install/install_programo.php on line 164

so I changed 
``` mkdir(_ADMIN_PATH_ . $session_dir, 0755) ``` in line 161 to ``` mkdir(_ADMIN_PATH_ . $session_dir, 0755, true) ```

After that, with a clean installation there is no error logs in the logs directory.

However the problem persists and the error_log in admin directory and parent directory contains :
> PHP Warning:  chdir() : No such file or directory (errno 2) in ../config/global_config.php on line 16
> PHP Warning:  file_get_contents(__DIR__/version.txt): failed to open stream: No such file or directory in ../config/global_config.php on line 55

**Comment by Dave-Morton** [comment]
Ok, what code is contained in lines 16 and 55 of global_config.php? That particular config file is created during the clean install process, so will vary, depending on your setup. Please feel free to remove the first few directory levels of the file paths, if you wish, so that you're not giving away anything that might prove to be insecure.

**Comment by lordhari** [comment]
Oh, I see.
In line 16 : ``` chdir($currentFolder); ```
where ``` $currentFolder = __DIR__ . DIRECTORY_SEPARATOR; ```

should I manually set this to something else?

and in line 55 : ``` define ('VERSION', trim(file_get_contents(_BASE_PATH_ . 'version.txt'))); ```
but version.txt is already there at the parent directory.

**Comment by Dave-Morton** [comment]
We'll need to find out the values of $currentFolder and _BASE_PATH_, and check them against the file path for the script. If you know what that file path is, you can comment out those 2 lines and replace them (by adding in alternative code) with code that sets the correct values. For example, you could just open version.txt, read the value in there, and then add the following line:

    define('VERSION', {whatever the value in version.txt is});

For line 16, you'll need to know what the exact file path to your Program O install is. It may look something like /var/www/program_o for Linux systems, or C:\web\program_o for Windows Your setup will likely be different, but this will give you at least a basic idea of how it should look. My file path for my local server is P:\HTTP\git\Program-O, for example.

Out of curiosity, can you tell me the OS, server software (both type and version), and PHP version of what you're running Program O on? The version of Program O would also help.

**Comment by lordhari** [comment]
Thank you, Dave. That fixed the issue.

I'm trying this on a Bluehost linux server. Apache Version : 2.2.31. PHP Version : 5.4.24. Program-O version : 2.4.7

**Comment by Dave-Morton** [comment]
I'm glad that took care of it.
