### ISSUE TITLE
Get original phrase before normalization

### ISSUE THREAD

**Issue by manuchis** [Program-O/Program-O#92]
Hi There. I'm trying to save on my conversation_log the original input, I mean before normalization, in an extra column. This is for a research experiment that I'm working on. 
But I'm looking inside the arrays and it's seems that it is replaced in some point. That is right? it is saved in the ConvoArr anywhere? 

Thanks!

**Comment by Program-O** [comment]
Hi there.
The user input gets cleaned up before it is stored.
you could capture it in the conversation_start.php stage
e.g. just before $say = normalize_text($say);  and then store it in $convoArr to use and save in the 
function log_conversation($convoArr)

hope that helps
:)

**Comment by manuchis** [comment]
Thanks for your quick answer!

I added $convoArr['usersay_org'] = $say;  before that line. 
But it seems that the variable is not passing through the log_conversation function. 

So, finally I used the variable $rawSay. 
`$convoArr['aiml']['usersay_org'] = $rawSay;`

**Comment by Program-O** [comment]
:cake: :)
