### ISSUE TITLE
Recover user information

### ISSUE THREAD

**Issue by manuchis** [Program-O/Program-O#93]
Hi there! 
I was wondering how to make recursive conversations (from users that returns to the platform to initiate another conversation).
I assume that tags like `learnf` is not supported, but I was wondering to recover some variable from the user that is in recorded the database. 

Did you have tried something like that? I'm thinking on how to make a good point there. Maybe trying new tags, or something. 

Regards!

**Comment by Program-O** [comment]
I am not sure what you mean, do you think you could give an example conversation?

**Comment by manuchis** [comment]
Ok. I'll try. I'm assuming that we can save a PLACE, a DATE, and AGE.

> Day 1: 
> User: Hello! 
> Bot: Hey! How old are you? 
> User: 29
> Bot: Oh, I see... and what are you doing here today?
> User: I'm going to the Public Relation office. 
> Bot: Lucky with that. 

> Day 2: 
> User: Hello!
> Bot: Hey! How was your meeting in the Public Relation office? 
> User: Was good. 
> Bot: Nice. I was thinking, you told me that you are 29, right? When is it your birthday? 
> 

> Day 3:
> User: Hi!
> Bot: Hey! Yesterday was your birthday, right? 
> ...

Better? I'm thinking that I can call custom tags for each type of data or using the "inline" knowledge of the database....

**Comment by Program-O** [comment]
The convo_id is created using a cookie so you should be able to access the user information for the lifetime of the cookie
(i think!)
Then you need to write some AIML to actually return the results you want.
look for the function here ... jq_get_convo_id() 
and look at setting the expiry of the cookie,
or if you are setting it somewhere else on your site make sure you are setting it for at least 30days

**Comment by manuchis** [comment]
Thanks, actually I'm not using the cookies for the moment. I've implemented some libraries to interact with Telegram and Twilio, So I register the user ID in the convo_ID field... That way I can track each user conversation. 
The thing is, how do you think is the right way to implement that data gathering?

**Comment by Program-O** [comment]
Unless your users log in to your site, you will need something to keep a record of who they actually are. So you might need cookies.
if i was you i would just dump the user id in a cookie and use that to maintain the conversation.
unless you do actually get your users to log in which case they could be assigned the same id each time aswell.
Does that answer your question? I am not sure if i properly understood

**Comment by manuchis** [comment]
Yes, I understood that part. The way that I work with that is using each platform ID, for example Telegram has a user ID, also Twilio sends the phone number through their API. 

My issue is about how to record specific data from the user and gather in a future conversation. 
Thanks again.

**Comment by Program-O** [comment]
You will have to write AIML extract and return data from and to the user
if you write <set name="yourvalue">123</set> to save a client value
and <get name="yourvalue"/> to retrieve it

**Comment by manuchis** [comment]
Perfect, I'm on it, but how I make that value to keep alive? It is back when I open a new conversation ? or expires?

**Comment by Program-O** [comment]
each conversation is stored against a user id
that is why you need the login or the cookie to store the conversation id 
so the user id can be retrieved.

**Comment by manuchis** [comment]
ok, I see. thanks. I will let you know I could make it.

**Comment by Program-O** [comment]
:four_leaf_clover: good luck

**Comment by manuchis** [comment]
Thanks! BTW, I'm working in a spanish bot. Until now I just used AIML in spanish, but I'm thinking to translate part of the core. (parse_iml.php has a lot of constructions to change), what do you think about?

**Comment by Dave-Morton** [comment]
If you're using Program O with another service or app that uses a unique ID for a user, you can pass that same ID to Program O as a GET or POST variable in order to keep things consistent for each user. All that is needed is to set the GET or POST variable convo_id in your HTTP request to the same unique ID that the other service uses. No cookies needed. :)

**Comment by manuchis** [comment]
@Dave-Morton Indeed is what I've made. thanks

**Comment by Dave-Morton** [comment]
Glad to have helped. Please let us know how you get on with your project.
