### ISSUE TITLE
Empty response?

### ISSUE THREAD

**Issue by marktopper** [Program-O/Program-O#96]
Whenever I ask my Program-O robot a question which it does not know, I get an empty response instead of the default response.

Any ideas how to debug this in order to fix this issue?

**Comment by Program-O** [comment]
Hi there,
Has the default response been added in the admin area for that bot?

**Comment by marktopper** [comment]
Hi @Program-O, yes it have, and that is why I'm wondering what's going on.

**Comment by Program-O** [comment]
is it possible that it is actually error-ing? rather than returning blank?
if you are doing a json request and it errors it might look as if its blank when actually there is an error.
Also are you sure you don't have any rouge AIML that is a catch all e.g.` <pattern>*</pattern>`

**Comment by marktopper** [comment]
@Program-O, will check out on that and let you know later today.

**Comment by Dave-Morton** [comment]
It may also be that the AIML itself has no "catchall" response written in, such as this one:

    <category>
      <pattern>*</pattern>
      <template>I don't know what to say.</template>
    </category>

If you have the config set to capture debug events you can look through the debug file to see if anything might be going on. if you point your browser to your Program O install's debug folder (path/to/Program-O/**chatbot/debug/**) you can log in as the admin account and view the debug files. Look for any PHP errors that may have been reported, and anything else that looks odd (well, it will probably ALL look odd, but...)

**Comment by marktopper** [comment]
In the logs (`logs/error.log` and `gui.xml.error.log`) I have nothing.

Also [here](https://gist.github.com/marktopper/dfa9d5a5f5b88437aa93) is the debug if you wish to have a look.

I will try do a fresh reinstall to see if that helps it.

**Comment by marktopper** [comment]
After a fresh install, I created a catchall response as @Dave-Morton suggested and it works great.

Thanks.

**Comment by Program-O** [comment]
:)

**Comment by Dave-Morton** [comment]
I noticed the following in the debug file, probably because the chatbot's ID wasn't being processed for some reason:

> Found an error trying to identify the chatbot.

That's an error that I've not seen before, so I'm glad that a reinstall took care of the problem. :)
