### ISSUE TITLE
Something went wrong! Error = Internal Server Error

### ISSUE THREAD

**Issue by AaronZhangL** [Program-O/Program-O#97]
I installed it on docker CentOS 7 successfully. Port number is 8081.
It is ok to upload&&download aiml files.
But I got the error message [Something went wrong! Error = Internal Server Error], when I click the [say] button located the url [http://www.xxxxx.com:8081/gui/jquery/multibot_gui_with_chatlog.php]
How to get the detail error message? There were no log contents when I checked the logs feature of admin control page.

Thanks.

**Comment by Program-O** [comment]
in chrome inspect the page and see what errors are reported in the console.
did you follow the installation instructions?
https://github.com/Program-O/Program-O/wiki/Installation-Guide

**Comment by AaronZhangL** [comment]
I have installed it successfully.
And I found following error message. There isn't users table in database. 
Are there script of users table ?
--------
[11-Mar-2016 09:11:48 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.users' doesn't exist' in /var/www/html/chatbot/core/user/handle_user.php:101
Stack trace:
#0 /var/www/html/chatbot/core/user/handle_user.php(101): PDOStatement->execute()
#1 /var/www/html/chatbot/core/conversation/intialise_conversation.php(567): intisaliseUser(Array)
#2 /var/www/html/chatbot/conversation_start.php(162): check_set_user(Array)
#3 {main}
  thrown in /var/www/html/chatbot/core/user/handle_user.php on line 101
--------

**Comment by Program-O** [comment]
this is a problem that has been reported before....
i think something in the install chain is breaking preventing all the tables from being installed.
I will definitely look into a fix for this .... @Dave-Morton please keep this ticket open whilst it remains unfixed 

There is an sql dump in the installs folder or here: https://github.com/Program-O/Program-O/blob/master/install/new.sql

You will be missing more than one table so make sure you create all the tables or just run the entire sql to install everything

**Comment by AaronZhangL** [comment]
The reason is setting default value to  `last_update` timestamp column failed. 
In the script of create users table, try to set timestamp default value by '0000-00-00 00:00:00',
but TIMESTAMP has a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC.  
So this script running failed.
I update this value to '1970-01-01 00:00:01', It works fine. just like below.
```

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_name` text NOT NULL,
  `session_id` varchar(255) NOT NULL,
  `bot_id` int(11) NOT NULL,
  `chatlines` int(11) NOT NULL,
  `ip` varchar(100) NOT NULL,
  `referer` text NOT NULL,
  `browser` text NOT NULL,
  `date_logged_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01',
  `state` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

```
Thank you very much.

**Comment by Dave-Morton** [comment]
Actually, last_update would probably be best served by allowing a null value. Your fix is great, but I think the next update will just allow that value to be null.

**Comment by Program-O** [comment]
good thinking... allow nulls and thanks @AaronZhangL  for finding the point of failure.

**Comment by Program-O** [comment]
complete!
