### ISSUE TITLE
generic top-level domains (gTLDs) i.e. ".cafe" domain breaks links "/" removed

### ISSUE THREAD

**Issue by subvertio** [Program-O/Program-O#98]
...not so sure if this is an issue with program-o or my domain issue, browser issue, or my server config etc but, I have new and weird gTLD ".cafe", and each browser seems to remove the "/" for example after a submit.
I just use the default settings/install of program-o and the slash seems to get removed ... for example:
when I go to https://www.myDomain.cafe/logs/ and I login, the url after submitting username and password goes to (in Chrome, firefox, and safari):
https://www.myDomain.cafelogs/
* note the slash is being removed between .cafe"/"logs

in the meantime I'm gonna stay away from weird gTLDs. and stick with " .com" domains

**Comment by Dave-Morton** [comment]
Frankly, it sounds more to me like a bug in the code, where a forward slash is missing, but both work and school are preventing me from digging into the code to find it. Perhaps after the weekend I'll be able to give it a look. If you folks want to look for the missing slash, it's likely in the index.php file in the logs folder (I think).

**Comment by subvertio** [comment]
Program-O, my version :
Ubuntu 14.04.4 LTS

I'm no ubuntu champ, I'm gonna check our apache config, etc. Then I may check source too. I had a busy few days also. I'll be able to look more thoroughly at server config. I still am suspecting though some sort of weird browser issue, I remember when I had no ssl and just the generic default Apache "IT WORKS" page and safari on my iPhone managed to scrub the "/" also, so I'd re-enter it and it would work. Thats why my intuition was suspecting new tlds causing issues in most browsers.

**Comment by subvertio** [comment]
...I swapped out the weird  " .cafe" domain extension with a normal " .com" and it is now working fine-I don't think this a source issue doing that, I was having trouble with that domain from day 1. There is a possibility though that when I re-did the sitename.conf a2endite apache command the set up it cleared any goof ups.

**Comment by Dave-Morton** [comment]
Glad to hear it's sorted now. Please let us know if there's anything else we can do.
